### ISSUE TITLE
请教下同步中断的问题

### ISSUE THREAD

**Issue by pengchao666** [aliyun/redis-shake#126]
hi,您好：
             我在测试redis cluster的时候，使用redis shake从源端的3.0单实例往目标端4.0.14的cluster同步。全同步的时候，总是会中断卡住。但是cluster是正常的。操作系统版本为centOS7.4 
报错如下：
2019/07/16 16:29:31 [PANIC] restore command error key:¬첵content_type_564827a1a71d802acc44f0c5 err:CLUSTERDOWN The cluster is down
[error]: CLUSTERDOWN The cluster is down
[stack]: 
    1   /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:808
            redis-shake/common.RestoreRdbEntry
    0   /home/zhuzhao.cx/redis-shake/src/redis-shake/sync.go:441
            redis-shake.(*dbSyncer).syncRDBFile.func1.1

**Comment by vinllen** [comment]
这个报错 应该有个db节点是挂了的 你检查下输入的目标中的db结点状态

**Comment by vinllen** [comment]
问题暂无反馈，进行关闭。如果还有问题请再打开该问题
