### ISSUE TITLE
希望支持指定db到cluster的迁移

### ISSUE THREAD

**Issue by zhklcf** [aliyun/redis-shake#127]
例如源端是：单实例的db2,添加filter.db = 2参数后，
能同步到目的端：cluster的 db0。

**Comment by vinllen** [comment]
这个你指定target.db = 0就行，所有的都会打到db = 0中。
参考：https://github.com/alibaba/RedisShake/wiki/FAQ#q-if-i-both-set-targetdb--3-and-filterdbwhitelist--0510-what-will-happen

**Comment by zhklcf** [comment]
测试了下，好像并不行
filter.db.whitelist = 1;
target.db = 0
结果还是db0的同步到了 cluster的 db0。

看了下源码:
```
	// if the target is "cluster", only allow pass db 0
	if conf.Options.TargetType == conf.RedisTypeCluster {
		conf.Options.FilterDBWhitelist = []string{"0"} // set whitelist = 0
		conf.Options.FilterDBBlacklist = []string{}  // reset blacklist
		log.Info("the target redis type is cluster, only pass db0")
	}
```

**Comment by vinllen** [comment]
版本已经发布，请拉取v1.6.13版本

**Comment by zhklcf** [comment]
OK，好的~

**Comment by vinllen** [comment]
此问题关闭，如果还有问题请再打开
