### ISSUE TITLE
希望restore rdb done 之后，能自动退出，而不是wait forever。

### ISSUE THREAD

**Issue by zhklcf** [aliyun/redis-shake#132]
redis-shake restore 的时候，restore : rdb done了，之后为什么一直wait forever。
感觉done 之后，程序就可以结束了。而现在好像都不会自己结束，而是要自己手动kill。
话说有什么办法，让restore rdb done之后，自动退出的吗？

**Comment by vinllen** [comment]
可以设置http_profile为-1，同步完会自动退出。此功能在v1.6.14版本会release

**Comment by vinllen** [comment]
add question in FAQ:
https://github.com/alibaba/RedisShake/wiki/FAQ#q-when-i-set-type-restore-why-doesnt-redisshake-exit-when-finish-restoring-rdb-but-print-wait-forever

**Comment by vinllen** [comment]
版本已发布
