### ISSUE TITLE
集群版同步出core

### ISSUE THREAD

**Issue by vinllen** [aliyun/redis-shake#145]
报错：
![image](https://user-images.githubusercontent.com/6987398/62860763-d9688c00-bd33-11e9-80a2-452e315f0381.png)
问题定位：
Put的时候对于事务处理node没有初始化：
![image](https://user-images.githubusercontent.com/6987398/62860860-26e4f900-bd34-11e9-8b48-8301dd17511c.png)
此处return的是nil，塞入batch队列没有校验：
![image](https://user-images.githubusercontent.com/6987398/62860893-4714b800-bd34-11e9-80ff-dafbcd79b0cd.png)
导致在RunBatch的时候出core了：
![image](https://user-images.githubusercontent.com/6987398/62860926-5e53a580-bd34-11e9-8cea-8e18cbfcf62a.png)
总结：
redis-go-cluster驱动的bug。

**Comment by vinllen** [comment]
此处由于驱动更新了，导致代码行数对不上。
本地验证，是这个问题

**Comment by vinllen** [comment]
v1.6.17已修复，请等待版本发布

**Comment by tao12345666333** [comment]
:+1: 感谢
