### ISSUE TITLE
报错信息不明显

### ISSUE THREAD

**Issue by vinllen** [aliyun/redis-shake#148]
![image](https://user-images.githubusercontent.com/6987398/63167037-aa6b5680-c062-11e9-8bd9-4047838f14fd.png)
这个原因是用的redigo直接处理返回，但是在类型是redis.Error，redigo驱动应该抛出具体的错误，但是其实并没有：
```
dumps, err := redis.Strings(dre.sourceClient.Do(""))
if err != nil && err != redis.ErrNil {
	return fmt.Errorf("do dump with failed[%v]", err)
}
```
修改后的代码，抛出具体的错误类型。目前redis-shake里面还有类似的问题，由于比较多，暂时先不统一修改了。这里最好是由驱动层进行抛出错误，当type是redis.Error的时候：`redis.Strings`。
```
reply, err := dre.sourceClient.Do("")
dumps, err := redis.Strings(reply, err)
if err != nil && err != redis.ErrNil {
	return fmt.Errorf("do dump with failed[%v], reply[%v]", err, reply)
}
```
计划release在v1.6.17版本

**Comment by no-today** [comment]
我现在使用v2.0.3 还有这个问题，dbRumper 78% 时报错中断，用途是阿里云读写分离版跨区同步 (迪拜 -> 法兰克福)
