### ISSUE TITLE
rump模式下源端支持cluster

### ISSUE THREAD

**Issue by vinllen** [aliyun/redis-shake#149]
目前rump模式下源端如果是cluster是有问题的，考虑支持
![image](https://user-images.githubusercontent.com/6987398/63168137-e48a2780-c065-11e9-8175-f57b10206830.png)

**Comment by vinllen** [comment]
这个可能是用户源端发生了Move slot操作，或者节点配置不对，理论上不应该由这个报错。

**Comment by vinllen** [comment]
用户源端是6个节点（3主3从），但是source.address配置了所有6个节点，是会报这个错误。
后面加上校验，防止用户配置出错。
报错的原因是，slave本身不接受读命令，默认redirect到master上，除非配置了readonly（命令行配置的readonly只是当前连接生效的）。
1.8版本起，cluster的角色只能是master，不能为slave。
![image](https://user-images.githubusercontent.com/6987398/68464826-449aff00-024c-11ea-9f01-2b8e64b58519.png)

**Comment by suxb201** [comment]
todo：文档需要介绍具体些
