### ISSUE TITLE
“-ERR unknown command 'SYNC“ 阿里云redis不支持sync指令，如何解决？

### ISSUE THREAD

**Issue by leveysama** [aliyun/redis-shake#151]
我在同步阿里云redis数据时出现如下错误：

2019/08/20 16:48:09 [PANIC] invalid sync response, rsp = '-ERR unknown command 'sync'
'
[stack]: 
    0   /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:190
            redis-shake/common.waitRdbDump.func1
        ... ...

源端和目标端都是阿里云redis，
源端版本号：
Redis 2.8（兼容3.0特性） | 16G集群版
目标端版本号：
Redis 2.8（兼容3.0特性） | 32G集群版

**Comment by vinllen** [comment]
源端集群版暂未对外开放复制权限，可以用dts进行迁移
