### ISSUE TITLE
全量同步时对源redis的影响

### ISSUE THREAD

**Issue by bylijinnan** [aliyun/redis-shake#152]
在我测试中，RedisShake中断后重新连接，开始进行全量同步，源redis读写耗时上升。已经设置“psync = true”。源redis由于是一直在线上正在提供服务的，会对生产业务有影响。
有没有办法减少全量同步时对源redis的影响？目标redis只是一个备份（冷备），我们对同步的时效性要求不高。
```
6379: set 367138 ok, cost 11 ms
OK
6379: set 367139 ok, cost 11 ms
OK
6379: set 367140 ok, cost 12 ms
OK
6379: set 367141 ok, cost 11 ms
OK
6379: set 367142 ok, cost 11 ms
OK
6379: set 367143 ok, cost 13 ms
OK
6379: set 367144 ok, cost 11 ms
OK
6379: set 367145 ok, cost 11 ms

####RedisShake中断后重新连接，开始进行全量同步，源redis读写耗时上升

6379: set 367146 ok, cost 70 ms
OK
6379: set 367147 ok, cost 53 ms
OK
6379: set 367148 ok, cost 68 ms
OK
6379: set 367149 ok, cost 63 ms
OK
6379: set 367150 ok, cost 43 ms
OK
6379: set 367151 ok, cost 57 ms
OK
6379: set 367152 ok, cost 59 ms
OK
6379: set 367153 ok, cost 55 ms
OK
6379: set 367154 ok, cost 40 ms
OK
6379: set 367155 ok, cost 42 ms
  ```

**Comment by vinllen** [comment]
全量同步会导致变高，进入到增量阶段应该就没啥影响了，也可以从slave上拉取。也可以提高parallel提高全量同步的速率。
全量导致性能影响主要是做bgsave，有cow的操作

**Comment by bylijinnan** [comment]
> 全量同步会导致变高，进入到增量阶段应该就没啥影响了，也可以从slave上拉取。也可以提高parallel提高全量同步的速率。
> 全量导致性能影响主要是做bgsave，有cow的操作

我的测试结果跟你说的一样，进入增量阶段后就几乎没影响了，回到了正常的10ms左右。如果只是一次全量同步的话，我可以选择在业务量低谷进行同步。就怕后面riskshake因为其他原因中断了，重新连接后又进行全量同步

**Comment by vinllen** [comment]
目前这个避免不了，后面我们会考虑支持断点续传，解决这种因为网络抖动等问题造成连接的短时间中断，目前需求没进入具体排期，请关注 #18
