### ISSUE TITLE
全量增加落盘选项

### ISSUE THREAD

**Issue by vinllen** [aliyun/redis-shake#153]
为了保证全量同步时间尽可能短，以降低对源库的影响，增加落盘选项支持拉取源rdb落盘。同样的，这个时候增量也需要落盘，等全量完毕，先读取持久化的增量，再读取源端后续增量。

**Comment by tancehao** [comment]
您好，请问这个功能有了吗？

**Comment by vinllen** [comment]
这个功能目前暂时不考虑支持

**Comment by tancehao** [comment]
我觉得这个功能还有有必要的哦。目前同步rdb的策略是一边少量地下载，一边向目标集群发送数据，这样的速度是较低的，因此出现这种情况的概率很大：redisshake在同步rdb的过程中，由于源实例的写请求较多，它的积压缓冲区不再包含redisshake在同步rdb文件之前拿到的那个offset，此时会直接断开连接。因此有必要通过落盘的方式提升rdb文件的下载速度，降低失败率。

**Comment by suxb201** [comment]
有必要，但代码改动较大，短期没有计划。欢迎 PR。

**Comment by suxb201** [comment]
@tancehao 已经在 v3 上实现了：https://github.com/alibaba/RedisShake/tree/v3
