### ISSUE TITLE
RedisShake  release-v1.6.18-20190904 start.sh 脚本报错

### ISSUE THREAD

**Issue by mimowen** [aliyun/redis-shake#161]
解压工具之后有如下文件
ChangeLog   
redis-shake.conf 
redis-shake.darwin  
redis-shake.linux   
redis-shake.windows  
start.sh  
stop.sh

但是我按照教程运行，会出现错误
./start.sh redis-shake.conf restore

错误：
./start.sh: line 19: ./hypervisor: No such file or directory

**Comment by vinllen** [comment]
感谢反馈，这个版本没有打上Hypervisor在里面，我更新了一下，你重新拉一下：
`redis-shake-1.6.18-2.tar.gz`
