### ISSUE TITLE
rump模式自动循环跑

### ISSUE THREAD

**Issue by ghost** [aliyun/redis-shake#162]
源和目的Redis都为2.8版本。使用rump模式，通过输出日志可以看到不断循环跑。日志如下：
2019/09/12 15:04:58 [INFO] execute runner[*run.CmdRump] finished!
2019/09/12 15:04:58 [WARN]
                ##### | #####
Oh we finish ? # _ _ #|# _ _ #
 。。。。。。
- child process[7217] terminated .
- read zero from pipe of children.
- extra info: - normal termination, exit status = 0

- process: "./redis-shake.linux" exit, restart it
- execute: "./redis-shake.linux"
2019/09/12 15:05:03 [INFO] http_profile is disable
2019/09/12 15:05:03 [WARN]
。。。。。。
if you have any problem, please visit https://github.com/alibaba/RedisShake/wiki/FAQ

**Comment by vinllen** [comment]
用脚本启动是会有自动循环的，你手动启动redis-shake跑好了：redis-shake -conf=conf -type=rump
后面版本我修改一下脚本

**Comment by vinllen** [comment]
v1.6.19版本已发布，改善这个问题
