### ISSUE TITLE
sync方式运行一段时间中断退出

### ISSUE THREAD

**Issue by wangran101** [aliyun/redis-shake#163]
2019/09/18 20:23:24 [INFO] dbSyncer[0] sync:  +forwardCommands=5      +filterCommands=1      +writeBytes=79288
2019/09/18 20:23:25 [INFO] dbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2019/09/18 20:23:25 [DEBUG] dbSyncer[0] send command[36836]: [select [1]]
2019/09/18 20:23:25 [DEBUG] dbSyncer[0] send command[36837]: [evalsha [70a6c106c6c27de28e5b482cfbfdc14c46f04a40 3 {k7manage_oo1paxpesfgezsrzvivj30un}_Write_Lock {k7manage_oo1paxpesfgezsrzvivj30un}_Data {k7manage_oo1paxpesfgezsrzvivj30un}_Internal 637044350037726964 30]]
2019/09/18 20:23:25 [DEBUG] receive reply-id[36715]: [<nil>], error:[invalid response]
2019/09/18 20:23:25 [PANIC] dbSyncer[0] Event:ErrorReply	Id:redis-shake	Command: [unknown]	Error: invalid response
[stack]: 
    0   /home/zhuzhao.cx/redis-shake/src/redis-shake/sync.go:551
            redis-shake.(*dbSyncer).syncCommand.func2
        ... ...
![微信图片_20190919084833](https://user-images.githubusercontent.com/52906730/65200735-a2b42d00-daba-11e9-80c7-7f6bbe2cc672.jpg)

**Comment by vinllen** [comment]
拉下最新版本，报错更为详细，之前的版本由于驱动的问题报错不明显，这个是Lua跨slot访问导致。
https://github.com/alibaba/RedisShake/wiki/FAQ#q-how-to-solve-error-crossslot-keys-in-request-dont-hash-to-the-same-slot-error
