### ISSUE TITLE
2个datacenter的集群，互相sync的时候，set key可以同步，但是del的同步失败

### ISSUE THREAD

**Issue by polarbear567** [aliyun/redis-shake#166]
集群a在datacenter b，集群c在datacenter d，在b和d中都有一个redisshake
b中redisshake的设置：
source.address:集群a所有m/s节点
target.address:集群c所有m节点

d中redisshake的设置：
source.address:集群c所有m/s节点
target.address:集群a所有m节点

这样的设置对于set是可以同步的，但是当我在集群a中先set一个key，然后del的时候，集群c中依然可以get到对应key的值，并且在a集群中也可以get

**Comment by vinllen** [comment]
双向同步不能直接用，是需要依赖内核的。如果没有内核支撑，是没办法保证最终一致性的。数据会出现环形链路：A: set key -> B: set key -> A: set key -> ....。所以会出现你说的上述问题。

**Comment by polarbear567** [comment]
@vinllen 如果a默认写db0，b默认写db1，那redisshake同步的时候，从a那边同步过来的数据，b是写到db1吗？
