### ISSUE TITLE
希望将监控api，返回的JSON数组中，各个字段的含义以及对应值的枚举、单位，列一个详细的说明

### ISSUE THREAD

**Issue by lijun535535** [aliyun/redis-shake#168]
redis-shake的监控api，返回的JSON数组中，各个字段的含义以及对应值的枚举、单位，有没有一个详细的文档，我们想基于这开发一个监控服务

**Comment by vinllen** [comment]
最近会输出相应文档

**Comment by vinllen** [comment]
https://github.com/alibaba/RedisShake/wiki/restful%E7%9B%91%E6%8E%A7%E6%8C%87%E6%A0%87
