### ISSUE TITLE
3.2版本集群迁入4.0.14 版本集群报错：Error  moved 

### ISSUE THREAD

**Issue by WatchLucky** [aliyun/redis-shake#169]
redis-shake 版本 ： develop,97965ca954d526d8cc2e6cc43133e6f2fb4f02df

迁移3.2.12redis 集群 至 4.0.14 版本集群
报错如下
2019/09/27 15:06:17 [PANIC] dbSyncer[1] Event:ErrorReply    Id:redis-shake  Command: [unknown]  Error: MOVED 6289 10.0.8.121:11100
[stack]: 
    0   /root/RedisShake/src/redis-shake/sync.go:551
            redis-shake.(*dbSyncer).syncCommand.func2

**Comment by vinllen** [comment]
目的端target.type配置了cluster吗？

**Comment by WatchLucky** [comment]
配置了的

**Comment by vinllen** [comment]
贴下配置文件，密码脱敏一下

**Comment by WatchLucky** [comment]
source.address = 10.6.4.120:21100;10.6.4.121:21100;10.6.4.122:21100
source.password_raw =   xxxxxxxx
source.auth_type = auth
source.tls_enable = false
source.rdb.input = local
source.rdb.parallel = 0 
source.rdb.special_cloud = 
target.type = cluster
target.address =  10.6.3.120:21100
target.password_raw = xxxxxxxxx
target.auth_type = auth
target.db = -1
target.tls_enable = false 

其他都是默认配置，没改

**Comment by vinllen** [comment]
```
target.type = cluster
target.address = 10.6.3.120:21100
```
你这个target.address就配置了一个地址，如果需要自动发现，需要以@开头：
```
@10.6.3.120:21100 # 从master上拉取
master@10.6.3.120:21100 # 从master上拉取
slave@10.6.3.120:21100 # 从slave上拉取
```

**Comment by WatchLucky** [comment]
谢谢。
