### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by wsh-sun** [aliyun/redis-shake#176]
导入到90%左右的时候报错：
restore command response = 'ECONNTIMEOUT: dial tcp 172.xxx:36384: context deadline exceeded', should be 'OK'

从3.0.7 迁移到 3.2.12

**Comment by vinllen** [comment]
这个看起来是网络问题，重试能稳定复现吗？

**Comment by wsh-sun** [comment]
刚开始也有报这个错误，有重试报错。后面又报了一个错误：restore command response = 'ECONNTIMEOUT: dial tcp 172.xxx:36384: io timeout。网络方面没撒问题，怀疑是不是节点被阻塞了，出现了timeout，节点上的确有看到许多restore的慢查询。随后将配置文件中的并行数降低为8，还改了keep_alive这个保活参数为100s（因为看起来像是探活类的就尝试改了一下）后面看起来都是正常了，知道90%左右又报了restore command response = 'ECONNTIMEOUT: dial tcp 172.xxx:36384: context deadline exceeded', should be 'OK' 这个错误。但是对应时间点，该节点无慢查询。
另外，还要请教一个问题，如果我90%失败了，在跑的话只能全量同步吧？采用覆盖和不覆盖的效率差别大么？
另外，这个集群较大，同步90% 花了3h左右，并行数为8 。

**Comment by wsh-sun** [comment]
原端和目标端都是集群模式。

**Comment by wsh-sun** [comment]
2019/10/18 04:35:57 [PANIC] restore command response = 'ECONNTIMEOUT: dial tcp 172.xxx :36380: context deadline exceeded', should be 'OK'
[stack]: 
    1   /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:847
            redis-shake/common.RestoreRdbEntry
    0   /home/zhuzhao.cx/redis-shake/src/redis-shake/sync.go:447
            redis-shake.(*dbSyncer).syncRDBFile.func1.1
        ... ...

**Comment by wsh-sun** [comment]
又多了一步猜想，看到源集群Connection with slave client id #1760461810 lost. 主从连接断开，看到一个参数repl-timeout，会不会因为在载入rdb文件或者其他操作时候阻塞，超过了这个时间，然后主从就断开了。
所以是不是需要调整下repl-timeout？？目前是300s

**Comment by vinllen** [comment]
也可能是目的端Block了，你得看看报错的时候目的端是否写入正常。keep_alive是tcp的探活参数。
你走的是sync模式吧，主上断开一般是同步过久，backlog撑满了就断开了，一般这个是果，不是因，因还是同步久导致的。

**Comment by vinllen** [comment]
可以部署离目的集群近一些，一般慢都是写入瓶颈

**Comment by wsh-sun** [comment]
请教。目的端Block. 这个不太明白。
还有都报错了，还怎么看目的端写入正常？
走的是sync模式，因还是同步久导致的这个是什么意思？

**Comment by wsh-sun** [comment]
写入瓶颈这块有什么参数可以来调整么？

**Comment by wsh-sun** [comment]
再把并行数调低一点？

**Comment by vinllen** [comment]
得看下你写入具体是什么问题了，tcp的keepalive超时了是当前没有数据包交互了，tcp就把连接断开了，正式不可能没有数据包交互的，除非之前restore的一直hang住了。得找找为什么hang住的原因。
源端断开应该是全量同步久，增量缓存在backlog，时间长了，这个缓存撑满了，连接就断开了。

**Comment by wsh-sun** [comment]
55963:S 18 Oct 02:18:45.004 * Slave 172.xxx:<unknown-slave-port> asks for synchronization
55963:S 18 Oct 02:18:45.004 * Starting BGSAVE for SYNC with target: disk
55963:S 18 Oct 02:18:45.474 * Background saving started by pid 11191
11191:C 18 Oct 02:19:54.030 * DB saved on disk
11191:C 18 Oct 02:19:54.392 * RDB: 239 MB of memory used by copy-on-write
55963:S 18 Oct 02:19:55.016 * Background saving terminated with success
55963:S 18 Oct 04:35:58.456 # Connection with slave client id #1758262516 lost.
55963:S 18 Oct 04:38:34.984 * Slave xxx<unknown-slave-port> asks for synchronization
55963:S 18 Oct 04:38:34.984 * Starting BGSAVE for SYNC with target: disk
55963:S 18 Oct 04:38:35.524 * Background saving started by pid 70681
55963:S 18 Oct 04:39:06.849 # Connection with slavexxx:<unknown-slave-port> lost.
70681:C 18 Oct 04:39:40.697 * DB saved on disk
70681:C 18 Oct 04:39:41.069 * RDB: 206 MB of memory used by copy-on-write
55963:S 18 Oct 04:39:41.644 * Background saving terminated with success
55963:S 18 Oct 04:39:42.045 * Slavexxx:9320 asks for synchronization
55963:S 18 Oct 04:39:42.045 * Full resync requested by slave 172.xxx:9320
55963:S 18 Oct 04:39:42.045 * Starting BGSAVE for SYNC with target: disk
55963:S 18 Oct 04:39:42.563 * Background saving started by pid 72128
55963:S 18 Oct 04:39:42.567 # Connection with slave client id #1758652881 lost.
55963:S 18 Oct 04:40:10.271 * Slave 172.xxx:9320 asks for synchronization
55963:S 18 Oct 04:40:10.271 * Full resync requested by slave 172.xxx:9320
55963:S 18 Oct 04:40:10.271 * Waiting for next BGSAVE for SYNC
55963:S 18 Oct 04:40:10.318 # Connection with slave 172.xxx:9320 lost.

源集群某个节点的日志如上，（同步过程中的日志，rdb是每次生成一小个，然后生成多个么？因为这个节点实际占用内存有8G）

Replication backlog freed after 7200 seconds without connected slaves.
主库日志还发现了这个信息，是否有必要增大backlog

**Comment by dayuanyuan1989** [comment]
@wsh-sun  这个有进展吗？我也碰到同样的问题了，sync在90%左右全量时候timeout了

**Comment by vinllen** [comment]
@dayuanyuan1989 你也是集群到集群的同步？timeout之前应该是hang了一段时间把？这个打印堆栈信息看一下：
`curl http://127.0.0.1:9310/debug/pprof/goroutine?debug=2`

**Comment by blackghost-01** [comment]
这个问题还有后续吗，我也遇到了这个问题，sync在99%的时候timeout

**Comment by vinllen** [comment]
问题还在修复中

**Comment by vinllen** [comment]
谁还有问题类似的，请在钉钉上私聊我一下

**Comment by vinllen** [comment]
请试用一下1.6最新版本，问题先行关闭，如果还存在问题请重新打开该问题。
