### ISSUE TITLE
源端rdb save失败，redis-shake一直在wait source rdb状态

### ISSUE THREAD

**Issue by vinllen** [aliyun/redis-shake#179]
![image](https://user-images.githubusercontent.com/6987398/67549304-7f724280-f736-11e9-9fad-b4e42f81f672.png)
![image](https://user-images.githubusercontent.com/6987398/67549334-9022b880-f736-11e9-936d-67d715a49e25.png)
如何让shake获取到源端rdb save失败的状态

**Comment by coderw184** [comment]
一直在wait source rdb是由于什么原因造成的？有什么解决的方法么？重启还是？
我这边线上出现这个问题，只同步几个库过去，剩下库一直卡着

**Comment by vinllen** [comment]
@coderw184 看下源端，大概率源端自己bgsave失败了

**Comment by vinllen** [comment]
看redis源码，如果源端bgsave失败，是会向slave推送一条消息的，需要shake层面进行捕获：
```

    /* If we failed to BGSAVE, remove the slaves waiting for a full
     * resynchorinization from the list of salves, inform them with
     * an error about what happened, close the connection ASAP. */
    if (retval == C_ERR) {
        serverLog(LL_WARNING,"BGSAVE for replication failed");
        listRewind(server.slaves,&li);
        while((ln = listNext(&li))) {
            client *slave = ln->value;

            if (slave->replstate == SLAVE_STATE_WAIT_BGSAVE_START) {
                slave->flags &= ~CLIENT_SLAVE;
                listDelNode(server.slaves,ln);
                addReplyError(slave,
                    "BGSAVE failed, replication can't continue");
                slave->flags |= CLIENT_CLOSE_AFTER_REPLY;
            }
        }
        return retval;
    }

```

**Comment by coderw184** [comment]
好的,这个问题已经确认，

**Comment by coderw184** [comment]
目前同步又被中断，日志打印如下：
2019/12/27 07:20:10 [INFO] dbSyncer[0] total = 6.734GB -     63.999MB [  0%]  entry=540406      
2019/12/27 07:20:11 [INFO] dbSyncer[0] total = 6.734GB -     64.310MB [  0%]  entry=543037      
2019/12/27 07:20:11 [PANIC] read error
[error]: EOF
[stack]: 
    1   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/common/utils.go:860
            redis-shake/common.Iocopy
    0   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/sync.go:317
            redis-shake.(*dbSyncer).sendPSyncCmd.func1
        ... ...
2019/12/27 07:23:11 [INFO] source rdb[172.29.4.92:6379] checksum[yes]

这是什么原因，每次中断的位置并不一样，是网络抖动么还是

**Comment by coderw184** [comment]
现在同步又被卡住，日志打印如下：
2019/12/27 07:20:10 [INFO] dbSyncer[0] total = 6.734GB -     63.999MB [  0%]  entry=540406      
2019/12/27 07:20:11 [INFO] dbSyncer[0] total = 6.734GB -     64.310MB [  0%]  entry=543037      
2019/12/27 07:20:11 [PANIC] read error
[error]: EOF
[stack]: 
    1   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/common/utils.go:860
            redis-shake/common.Iocopy
    0   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/sync.go:317
            redis-shake.(*dbSyncer).sendPSyncCmd.func1
        ... ...
这可能是什么原因？每次中断的位置并不一样，网络抖动么还是?

**Comment by vinllen** [comment]
EOF是连接断开了，具体原因可以看下对应源端或者目的端redis的日志

**Comment by coderw184** [comment]
你的意思是说远端redis集群有异常么？
我觉得如果是网络抖动导致的异常，唯一能解决的方法是断点续传，
要能保证在下一次重启时继续往之前的dump.rdb写，而不是重新建一个rdb，
我觉得这是比较重要的一个问题。

**Comment by vinllen** [comment]
断点续传做的是增量的部分，全量部分不会做。这个问题得结合redis日志一起找一下问题的原因。

**Comment by vinllen** [comment]
2.0.1版本将会启用tcp keep_alive解决这个问题
