### ISSUE TITLE
CRC算法bug以及其他一些疑问

### ISSUE THREAD

**Issue by shuff1e** [aliyun/redis-shake#189]
+ CRC算法 https://github.com/alibaba/RedisShake/blob/develop/src/redis-shake/common/crc16.go
计算中文字符串时存在[bug](https://github.com/alibaba/RedisFullCheck/issues/68)
+ sync.go
```
		for {
			/*
			 * read from br(source redis) and write into pipew.
			 * Generally speaking, this function is forever run.
			 */
			n, err := ds.pSyncPipeCopy(c, br, bw, offset, pipew)
			if err != nil {
				log.PanicErrorf(err, "dbSyncer[%v] psync runid = %s, offset = %d, pipe is broken",
					ds.id, runid, offset)
			}
			// the 'c' is closed every loop

			offset += n
			ds.targetOffset.Set(offset)

			// reopen 'c' every time
			for {
				// ds.SyncStat.SetStatus("reopen")
				base.Status = "reopen"
				time.Sleep(time.Second)
				c = utils.OpenNetConnSoft(master, auth_type, passwd, tlsEnable)
				if c != nil {
					// log.PurePrintf("%s\n", NewLogItem("SourceConnReopenSuccess", "INFO", LogDetail{Info: strconv.FormatInt(offset, 10)}))
					log.Infof("dbSyncer[%v] Event:SourceConnReopenSuccess\tId: %s\toffset = %d",
						ds.id, conf.Options.Id, offset)
					// ds.SyncStat.SetStatus("incr")
					base.Status = "incr"
					break
				} else {
					// log.PurePrintf("%s\n", NewLogItem("SourceConnReopenFail", "WARN", NewErrorLogDetail("", "")))
					log.Errorf("dbSyncer[%v] Event:SourceConnReopenFail\tId: %s", ds.id, conf.Options.Id)
				}
			}
			utils.AuthPassword(c, auth_type, passwd)
			utils.SendPSyncListeningPort(c, conf.Options.HttpProfile)
			br = bufio.NewReaderSize(c, utils.ReaderBufferSize)
			bw = bufio.NewWriterSize(c, utils.WriterBufferSize)
			utils.SendPSyncContinue(br, bw, runid, offset)
		}
```
+ n, err := ds.pSyncPipeCopy(c, br, bw, offset, pipew)中  
是不是只有c这个连接断开或者出其他错误的时候，pSyncPipeCopy才会返回，然后更新targetOffset。   
更新targetOffset似乎放在pSyncPipeCopy方法中更合适。
+ c = utils.OpenNetConnSoft(master, auth_type, passwd, tlsEnable)中已经Auth过了
似乎没必要再utils.AuthPassword(c, auth_type, passwd)
+ 上面代码中，内层和外层的两个for循环是为了网络波动时可以断开重连？
那么GetFakeSlaveOffset的goroutine中是不是也可以采用这种方式，而不是utils.OpenRedisConnWithTimeout这种会panic的方式。

**Comment by vinllen** [comment]
1. 这里crc的确是漏掉了
2. 你说的targetOffset是有问题的，因为这个是个伪的offset，并不是实际意义上目的端的offset，当初也是为了全量和增量中间衔接的考虑。而源端redis info replication看到的offset其实就是shake回复的，所以如果放到pSyncPipeCopy里面的话，其实也就是这里targetOffset，这两个值基本上就是一样的，sourceOffset是1秒1更新，targetOffset是实时更新。准确的说，targetOffset这个值没有什么意义。
3. 这里外面的auth是没有必要，可以去掉
4. 这里是做部分网络问题导致的断点续传逻辑，OpenRedisConnWithTimeout这种问题也不大，相当于是一次重连，失败就Panic了，这个目前timeout时间挺长的，这个如果timeout了那panic没问题

**Comment by shuff1e** [comment]
2.更新targetOffset放在pSyncPipeCopy里面，的确是和sourceOffset基本上应该差不多……
在syncCommand中的第三个goroutine中，计算解析出来的命令占了多少字节，  
第四个goroutine中delayNode带上字节数信息   
然后在第二个goroutine中接受响应时，根据recvId更新targetOffset比较好

**Comment by vinllen** [comment]
delayNode目前是采样的机制，不是每条命令都做的。如果想做的话，你说的思路是ok的，统计一下所有的offset，然后根据回复的id更新这个offset，不过这里的offset不是实际的字节数，到这里的协程已经是解析后的命令了，统计字节数还是比较麻烦。

**Comment by vinllen** [comment]
crc问题已发布在v1.6.22版本

**Comment by shuff1e** [comment]
RedisFullCheck中\r\n的bug，啥时候发个版
