### ISSUE TITLE
导入RDB数据报错

### ISSUE THREAD

**Issue by wwwjinlong** [aliyun/redis-shake#191]
![image](https://user-images.githubusercontent.com/10222104/69131149-d3c9d180-0aec-11ea-8f54-c830f26a14c2.png)

**Comment by unixgiant** [comment]
我也碰见了这问题。type是rump
./redis-shake.linux -conf=redis-shake.conf -type=rump

**Comment by vinllen** [comment]
请更新下最新版本，1.6.21应该修复了这个问题

**Comment by wwwjinlong** [comment]
就是用的最新的1.6.21，还有问题

**Comment by vinllen** [comment]
相关问题：https://github.com/alibaba/RedisShake/issues/189
bug待修复

**Comment by vinllen** [comment]
@wwwjinlong @unixgiant 方便的话可以钉钉上私聊我下 我发你个版本试下 README上有联系方式

**Comment by wwwjinlong** [comment]
我加入群里，怎么找你？

**Comment by vinllen** [comment]
直接群里说话 或者at我，我是群主

**Comment by vinllen** [comment]
v1.6.22版本已经发布，可以试下
