### ISSUE TITLE
目标机器连接超时出错

### ISSUE THREAD

**Issue by sofire** [aliyun/redis-shake#194]
2019/11/27 14:20:07 [PANIC] restore command error key:xxx err:EOF
[error]: EOF
[stack]: 
    1 /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/common/utils.go:844
            redis-shake/common.RestoreRdbEntry
    0 /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/sync.go:447
            redis-shake.(*dbSyncer).syncRDBFile.func1.1

发现是 目标Redis 的 timeout 设置太小（30s），调大就可以了。
可能是 因为 rdb 文件比较大，需要迁移的 key 特别少。

程序 方面 是否有机制 可以保证在 从rdb 恢复的时候，不出现这个错误呢？

**Comment by vinllen** [comment]
可以试下把`big_key_threshold`参数调低，这样大key不会一直block，会进行拆分后写入目的端，预发同步时间过久连接断开的问题。另外，也可以设置`keep_alive`参数，用于tcp通道的保活。

**Comment by sofire** [comment]
keep_alive = 1 ，没用。
应该没大key，就是key比较多，一直不执行恢复命令。

**Comment by vinllen** [comment]
`keep_alive`在集群版里没生效，下个小版本我加上。`big_key_threshold `调低也没有用吗？

**Comment by sofire** [comment]
不是集群，单机到单机的。感觉 keep_alive 参数 在 rdb 恢复期间 不起作用。

需要从2000千万的key 中 迁移走 几个 Key，每个key 就几十字节。
big_key_threshold 没试过，感觉没关系。

**Comment by vinllen** [comment]
需要从2000千万的key 中 迁移走 几个 Key，每个key 就几十字节。
------------
这个看起来是过滤导致的，源端遍历进行过滤，时间过久了没有保活导致断开了。1.6.23的版本应该没这个问题。

**Comment by sofire** [comment]
好的，多谢修复
