### ISSUE TITLE
希望能支持 试运行模式和输出迁移的KEY

### ISSUE THREAD

**Issue by sofire** [aliyun/redis-shake#195]
试运行模式，加上输出 key，可以 在正式迁移前 检查 key 是不是有问题。
可以检查 目标机器是不是存在 相同的Key.

用debug 可以看到迁移的KEY，但是无用信息太多。希望有选项能单独配置。

**Comment by vinllen** [comment]
迁移的key就是所有的key，你可以在源端扫描

**Comment by sofire** [comment]
添加了过滤等 条件后 就不确定了。

**Comment by vinllen** [comment]
你需要关注过滤后的key？这个需求看起来不是大众需求，目前暂无计划支持
