### ISSUE TITLE
从原生redis同步数据到阿里云redis提示write: connection reset by peer

### ISSUE THREAD

**Issue by koolboy2016** [aliyun/redis-shake#198]
1）错误信息：[PANIC] restore command error key:hget-key100B-field100B-value128B-perftest-rdb-server-set-string-key-269511 err:write tcp write: connection reset by peer
[error]: write tcp write: connection reset by peer，提示错误信息时已经同步了20%数据
2）检查源端和目标端都正常，同时check了下报错提示的key发现并非大key

**Comment by vinllen** [comment]
与 #199 问题重复
