### ISSUE TITLE
原生redis同步数据到阿里云redis同步失败

### ISSUE THREAD

**Issue by koolboy2016** [aliyun/redis-shake#199]
2019/11/29 11:23:27 [PANIC] flush command to redis failed
[error]: read tcp 10.177.40.65:46368->39.100.185.107:6379: read: connection reset by peer
[stack]:

**Comment by vinllen** [comment]
![image](https://user-images.githubusercontent.com/6987398/69847145-41c28580-12b1-11ea-9da6-2f7baf231773.png)

**Comment by vinllen** [comment]
请试一下1.6的最新版本

**Comment by vinllen** [comment]
问题先行关闭，如还有类似问题请再打开
