### ISSUE TITLE
执行restore操作报错[PANIC] auth failed[-ERR unknown command '']

### ISSUE THREAD

**Issue by blackghost-01** [aliyun/redis-shake#202]
target端redis信息
#Server
redis_version:3.2.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:8260094123d3b78b
redis_mode:standalone
os:Linux 2.6.32-573.26.1.el6.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.4.7

配置文件：
id = redis-shake
system_profile = 9310
http_profile = 9320
ncpu = 0
source.rdb.input = /root/redis/xxx/xxx.rdb
rewrite = true
target.db = -1
filter.db =
filter.key =
extra = false
parallel = 4
target.password_raw = 
target.type = standalone
target.address = 

报错详情：
redis-shake.linux -type=restore -conf=xxx.conf
2019/12/02 12:55:29 [PANIC] auth failed[-ERR unknown command '']
[stack]:
    6   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/common/utils.go:157
            redis-shake/common.AuthPassword
    5   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/common/utils.go:78
            redis-shake/common.OpenNetConn
    4   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/common/utils.go:58
            redis-shake/common.OpenRedisConnWithTimeout
    3   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/common/utils.go:34
            redis-shake/common.OpenRedisConn
    2   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/common/utils.go:905
            redis-shake/common.GetRedisVersion
    1   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/main/main.go:422
            main.sanitizeOptions
    0   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/main/main.go:84
            main.main
        ... ...

**Comment by wangka-na** [comment]
Maybe the password contains special characters，like % ?

**Comment by wangka-na** [comment]
By the way,have you solved?how to solve this problem?thanks
