### ISSUE TITLE
[error]: bad resp CRLF end

### ISSUE THREAD

**Issue by shuff1e** [aliyun/redis-shake#204]
![image](https://user-images.githubusercontent.com/30022834/70030602-879a8900-15e4-11ea-8432-fb55429655e9.png)

**Comment by shuff1e** [comment]
redis版本
![image](https://user-images.githubusercontent.com/30022834/70030650-9f720d00-15e4-11ea-939d-ac1e22e98fe4.png)

**Comment by shuff1e** [comment]
bug应该是因为这个地方
![image](https://user-images.githubusercontent.com/30022834/70030687-b153b000-15e4-11ea-9767-63b545cca9b4.png)
稍后修复

**Comment by shuff1e** [comment]
3.2.7版本，发送 psync ? -1 之后，有时候 +FULLRESYNC响应前后有很多换行  
src/pkg/redis/decoder.go中decodeType方法有bug  
应该修改为
```
func (d *Decoder) decodeType() (respType, error) {
    ReadByte:
    if b, err := d.r.ReadByte(); err != nil {
        return 0, errors.Trace(err)
    } else if string(b) == "\n" {
        goto ReadByte
    } else {
        return respType(b), nil
    }
}
```

**Comment by shuff1e** [comment]
telnet 下应该可以比较容易复现，会有类似如下输出   
有时候是类似如下输出，有时候是正常的
```
Escape character is '^]'.
*3
$8
replconf
$14
listening-port
$4
9320
+OK
*3
$5
psync
$1
?
$2
-1











+FULLRESYNC e1cff8723be0dac09752ec3a63ac742f69bf9fb3 873812432115









```

**Comment by vinllen** [comment]
看redis源码的确是可能这种行为的，不止3.2，后面的版本也是一样的。redis收到psync命令以后，会先进行判断是否要进行bgsave，期间会向slave回复\n以进行连接保活，然后启动bgsave的线程进行操作，一旦bgsave操作完成，会回复+FULLRESYNC。
而\n会一直发送，直到RDB生成完毕。所以+FULLRESYNC之后的\n必然是存在的，代码层面已经做了判断：
```
sendPSyncCmd函数
	var nsize int64
	for nsize == 0 {
		select {
		case nsize = <-wait:
			if nsize == 0 {
				log.Infof("DbSyncer[%2d] +", ds.id)
			}
		case <-time.After(time.Second):
			log.Infof("DbSyncer[%2d] -", ds.id)
		}
	}
```
而+FULLRESYNC之前的\n是因为bgsave是独立线程做的，所以这个存在先后顺序的问题。这里的确是有问题的。
你的修改是OK的。感谢再次PR。

**Comment by vinllen** [comment]
代码会先合入develop，但是分支版本的发布会延后，着急的话可以自己先编译develop的版本。

**Comment by shuff1e** [comment]
👍

**Comment by vinllen** [comment]
v1.6.24已发布

**Comment by shuff1e** [comment]
> 看redis源码的确是可能这种行为的，不止3.2，后面的版本也是一样的。redis收到psync命令以后，会先进行判断是否要进行bgsave，期间会向slave回复\n以进行连接保活，然后启动bgsave的线程进行操作，一旦bgsave操作完成，会回复+FULLRESYNC。
> 而\n会一直发送，直到RDB生成完毕。所以+FULLRESYNC之后的\n必然是存在的，代码层面已经做了判断：
> 
> ```
> sendPSyncCmd函数
> 	var nsize int64
> 	for nsize == 0 {
> 		select {
> 		case nsize = <-wait:
> 			if nsize == 0 {
> 				log.Infof("DbSyncer[%2d] +", ds.id)
> 			}
> 		case <-time.After(time.Second):
> 			log.Infof("DbSyncer[%2d] -", ds.id)
> 		}
> 	}
> ```
> 
> 而+FULLRESYNC之前的\n是因为bgsave是独立线程做的，所以这个存在先后顺序的问题。这里的确是有问题的。
> 你的修改是OK的。感谢再次PR。

最近在学习redis源码
大佬你说的 “期间会向slave回复\n以进行连接保活”
是下面的这个地方吗？
```
-> redis.c/main 中的

initServer();

-> redis.c/initServer 中的

if(aeCreateTimeEvent(server.el, 1, serverCron, NULL, NULL) == AE_ERR) {
        redisPanic("Can't create the serverCron time event.");
        exit(1);
}

注册时间事件 serverCron 

-> redis.c/serverCron 

run_with_period(1000) replicationCron();

-> redis.c/replicationCron

if (write(slave->fd, "\n", 1) == -1) {
    /* Don't worry, it's just a ping. */
}
```

**Comment by Colstuwjx** [comment]
想问下这个 issue 确实修复了吗？我这边用 develop 分支最新的代码仍然会有这个问题：

```
2021/09/09 15:15:32 [PANIC] decode redis resp failed
[error]: bad resp CRLF end
    5   github.com/alibaba/RedisShake/pkg/redis/decoder.go:169
            github.com/alibaba/RedisShake/pkg/redis.(*Decoder).decodeBulkBytes
    4   github.com/alibaba/RedisShake/pkg/redis/decoder.go:87
            github.com/alibaba/RedisShake/pkg/redis.(*Decoder).decodeResp
    3   github.com/alibaba/RedisShake/pkg/redis/decoder.go:189
            github.com/alibaba/RedisShake/pkg/redis.(*Decoder).decodeArray
    2   github.com/alibaba/RedisShake/pkg/redis/decoder.go:91
            github.com/alibaba/RedisShake/pkg/redis.(*Decoder).decodeResp
    1   github.com/alibaba/RedisShake/pkg/redis/decoder.go:38
            github.com/alibaba/RedisShake/pkg/redis.MustDecodeOpt
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/syncIncrease.go:183
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).parseSourceCommand
        ... ...
[stack]:
    1   github.com/alibaba/RedisShake/pkg/redis/decoder.go:40
            github.com/alibaba/RedisShake/pkg/redis.MustDecodeOpt
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/syncIncrease.go:183
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).parseSourceCommand
        ... ...
```

**Comment by Colstuwjx** [comment]
@suxb201 有注意到 Q & A 部分有提到这个 [decode resp failed](https://github.com/alibaba/RedisShake/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q-decode-redis-resp-failed-error-eof) 问题，我有两个疑问，希望能帮忙解答一下：

1、 RedisShake 不应该连接到的是 master 节点吗，为什么还会遇到这个连到 slave 才可能出现的问题？

2、如果存在这个问题，那有什么推荐的解决方案吗，Q & A 只是解释了原因，并没有给出推荐的解决办法

谢谢！

**Comment by suxb201** [comment]
@Colstuwjx 
1. 这个 QA 我也迷惑... 
2. 我理解这个 bug 是修了的，你是咋触发的？

**Comment by Colstuwjx** [comment]
> 我理解这个 bug 是修了的，你是咋触发的？

放那里跑的时间长了就容易出现这个问题，我明天再多打点 log 看看是怎么触发的。

**Comment by Colstuwjx** [comment]
打了点 log，发现是一段 lua 脚本，等于 `decodeBulkBytes` 这个方法在解析这段 lua 脚本时 b[n] 或者 b[n+1] 不是预期的 \r \n，所以 panic 了。
