### ISSUE TITLE
源redis集群写入大量数据时，redis-shake增量同步报错：[PANIC] decode redis resp failed

### ISSUE THREAD

**Issue by mali0512** [aliyun/redis-shake#207]
环境：源和目标redis集群版本4.0.9，redis-shake版本：1.6.23
场景：对源redis集群中的一个节点进行压测（redis-benchmark），redis-shake同步报错：[PANIC] decode redis resp failed，停顿十几秒之后，重新从源redis集群拉取数据进行全量同步。
日志：
2019/12/06 16:06:05 [WARN] available channel size[4096] less than current returned batch size[5000]
2019/12/06 16:06:05 [INFO] dbSyncer[3] sync:  +forwardCommands=1      +filterCommands=0      +writeBytes=4
2019/12/06 16:06:05 [WARN] available channel size[4096] less than current returned batch size[5000]
2019/12/06 16:06:06 [INFO] dbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2019/12/06 16:06:06 [INFO] dbSyncer[4] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2019/12/06 16:06:06 [WARN] available channel size[4096] less than current returned batch size[5000]
2019/12/06 16:06:06 [INFO] dbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2019/12/06 16:06:06 [INFO] dbSyncer[0] sync:  +forwardCommands=15000  +filterCommands=0      +writeBytes=153885000
2019/12/06 16:06:06 [INFO] dbSyncer[3] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2019/12/06 16:06:06 [WARN] available channel size[4096] less than current returned batch size[5000]
2019/12/06 16:06:07 [INFO] dbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2019/12/06 16:06:07 [INFO] dbSyncer[4] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2019/12/06 16:06:07 [WARN] available channel size[4096] less than current returned batch size[5000]
2019/12/06 16:06:07 [PANIC] decode redis resp failed
[error]: unexpected EOF
    5   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/pkg/redis/decoder.go:146
            pkg/redis.(*Decoder).decodeBulkBytes
    4   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/pkg/redis/decoder.go:84
            pkg/redis.(*Decoder).decodeResp
    3   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/pkg/redis/decoder.go:166
            pkg/redis.(*Decoder).decodeArray
    2   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/pkg/redis/decoder.go:88
            pkg/redis.(*Decoder).decodeResp
    1   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/pkg/redis/decoder.go:36
            pkg/redis.MustDecodeOpt
    0   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/sync.go:596
            redis-shake.(*dbSyncer).syncCommand.func3
        ... ...
[stack]: 
    1   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/pkg/redis/decoder.go:38
            pkg/redis.MustDecodeOpt
    0   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/sync.go:596
            redis-shake.(*dbSyncer).syncCommand.func3
        ... ...
2019/12/06 16:06:12 [INFO] the target redis type is cluster, only pass db0
2019/12/06 16:06:12 [INFO] RecvChanSize is modified from [4096] to [5000]
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:7003] with type[].
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:7002] with type[].
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:7001] with type[].
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:6381] with type[].
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:6385] with type[].
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:6384] with type[].
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:6383] with type[].
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:6380] with type[].
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:6381] with type[].
2019/12/06 16:06:12 [INFO] source rdb[x.x.x.x:6381] checksum[yes]
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:6385] with type[].
2019/12/06 16:06:12 [INFO] source rdb[x.x.x.x:6385] checksum[yes]
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:6384] with type[].
2019/12/06 16:06:12 [INFO] source rdb[x.x.x.x:6384] checksum[yes]
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:6383] with type[].
2019/12/06 16:06:12 [INFO] source rdb[x.x.x.x:6383] checksum[yes]
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:6380] with type[].
2019/12/06 16:06:12 [INFO] source rdb[x.x.x.x:6380] checksum[yes]
2019/12/06 16:06:12 [WARN] 
______________________________
\                             \           _         ______ |
 \                             \        /   \___-=O'/|O'/__|
  \   RedisShake, here we go !! \_______\          / | /    )
  /                             /        '/-==__ _/__|/__=-|  -GM
 /        Alibaba Cloud        /         *             \ | |
/                             /                        (o)
------------------------------
if you have any problem, please visit https://github.com/alibaba/RedisShake/wiki/FAQ

2019/12/06 16:06:12 [INFO] redis-shake configuration: {"Id":"redis-shake","LogFile":"./redis-shake.log","LogLevel":"info","SystemProfile":9310,"HttpProfile":9320,"Parallel":32,"SourceType":"cluster","SourceAddress":"master@x.x.x.x:6379","SourcePasswordRaw":"","SourcePasswordEncoding":"","SourceAuthType":"","SourceTLSEnable":false,"SourceRdbInput":null,"SourceRdbParallel":5,"SourceRdbSpecialCloud":"","TargetAddress":"@x.x.x.x:7001","TargetPasswordRaw":"","TargetPasswordEncoding":"","TargetDBString":"-1","TargetAuthType":"","TargetType":"cluster","TargetTLSEnable":false,"TargetRdbOutput":"","TargetVersion":"4.0.9","FakeTime":"","Rewrite":true,"FilterDBWhitelist":["0"],"FilterDBBlacklist":[],"FilterKeyWhitelist":null,"FilterKeyBlacklist":null,"FilterSlot":null,"FilterLua":false,"BigKeyThreshold":524288000,"Psync":false,"Metric":true,"MetricPrintLog":false,"SenderSize":104857600,"SenderCount":5000,"SenderDelayChannelSize":65535,"KeepAlive":0,"PidPath":"./","ScanKeyNumber":50,"ScanSpecialCloud":"","ScanKeyFile":"","Qps":500000,"NCpu":0,"HeartbeatUrl":"","HeartbeatInterval":3,"HeartbeatExternal":"test external","HeartbeatNetworkInterface":"","ReplaceHashTag":false,"ExtraInfo":false,"SockFileName":"","SockFileSize":0,"FilterKey":null,"FilterDB":"","SourceAddressList":["x.x.x.x:6381","x.x.x.x:6385","x.x.x.x:6384","x.x.x.x:6383","x.x.x.x:6380"],"TargetAddressList":["x.x.x.x:7003","x.x.x.x:7002","x.x.x.x:7001"],"SourceVersion":"4.0.9","HeartbeatIp":"127.0.0.1","ShiftTime":0,"TargetReplace":true,"TargetDB":-1,"Version":"bugfix-1.6.23,b40bd294be9892fd9319f88b6b7e7ea978b2cb62,go1.10.1,2019-11-28_20:34:03","Type":"sync"}
2019/12/06 16:06:12 [INFO] routine[0] starts syncing data from x.x.x.x:6381 to [x.x.x.x:7003 x.x.x.x:7002 x.x.x.x:7001] with http[9325]
2019/12/06 16:06:12 [INFO] routine[4] starts syncing data from x.x.x.x:6380 to [x.x.x.x:7003 x.x.x.x:7002 x.x.x.x:7001] with http[9325]
2019/12/06 16:06:12 [INFO] routine[3] starts syncing data from x.x.x.x:6383 to [x.x.x.x:7003 x.x.x.x:7002 x.x.x.x:7001] with http[9325]
2019/12/06 16:06:12 [INFO] routine[2] starts syncing data from x.x.x.x:6384 to [x.x.x.x:7003 x.x.x.x:7002 x.x.x.x:7001] with http[9325]
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:6381] with type[].
2019/12/06 16:06:12 [INFO] routine[1] starts syncing data from x.x.x.x:6385 to [x.x.x.x:7003 x.x.x.x:7002 x.x.x.x:7001] with http[9325]
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:6380] with type[].
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:6385] with type[].
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:6384] with type[].
2019/12/06 16:06:12 [INFO] input password is empty, skip auth address[x.x.x.x:6383] with type[].
2019/12/06 16:06:12 [INFO] dbSyncer[1] rdb file size = 178
2019/12/06 16:06:12 [INFO] Aux information key:redis-ver value:4.0.9
2019/12/06 16:06:12 [INFO] Aux information key:redis-bits value:64
2019/12/06 16:06:12 [INFO] Aux information key:ctime value:1575619572
2019/12/06 16:06:12 [INFO] Aux information key:used-mem value:136036528
2019/12/06 16:06:12 [INFO] Aux information key:repl-stream-db value:0
2019/12/06 16:06:12 [INFO] Aux information key:repl-id value:4368b7c4c0cb4f827528824c27b7f24bb8646f17
2019/12/06 16:06:12 [INFO] Aux information key:repl-offset value:53216
2019/12/06 16:06:12 [INFO] Aux information key:aof-preamble value:0
2019/12/06 16:06:12 [INFO] dbSyncer[2] rdb file size = 188
2019/12/06 16:06:12 [INFO] dbSyncer[4] rdb file size = 194
2019/12/06 16:06:12 [INFO] Aux information key:redis-ver value:4.0.9
2019/12/06 16:06:12 [INFO] Aux information key:redis-bits value:64
2019/12/06 16:06:12 [INFO] Aux information key:ctime value:1575619572
2019/12/06 16:06:12 [INFO] Aux information key:used-mem value:136954504
2019/12/06 16:06:12 [INFO] Aux information key:repl-stream-db value:0
2019/12/06 16:06:12 [INFO] Aux information key:redis-ver value:4.0.9
2019/12/06 16:06:12 [INFO] Aux information key:redis-bits value:64
2019/12/06 16:06:12 [INFO] Aux information key:ctime value:1575619572
2019/12/06 16:06:12 [INFO] Aux information key:used-mem value:136010624
2019/12/06 16:06:12 [INFO] Aux information key:repl-stream-db value:0
2019/12/06 16:06:12 [INFO] Aux information key:repl-id value:d49221e9c770e47e3901b66a0171c5f40d0c8a3d
2019/12/06 16:06:12 [INFO] Aux information key:repl-id value:11bd4720d4682f44370db2bf033374a3701fd126
2019/12/06 16:06:12 [INFO] Aux information key:repl-offset value:9296809433
2019/12/06 16:06:12 [INFO] Aux information key:aof-preamble value:0
2019/12/06 16:06:12 [INFO] db_size:1 expire_size:0
2019/12/06 16:06:12 [INFO] Aux information key:repl-offset value:53178
2019/12/06 16:06:12 [INFO] Aux information key:aof-preamble value:0
2019/12/06 16:06:12 [INFO] db_size:1 expire_size:0
2019/12/06 16:06:12 [INFO] dbSyncer[3] rdb file size = 194
2019/12/06 16:06:12 [INFO] Aux information key:redis-ver value:4.0.9
2019/12/06 16:06:12 [INFO] Aux information key:redis-bits value:64
2019/12/06 16:06:12 [INFO] Aux information key:ctime value:1575619572
2019/12/06 16:06:12 [INFO] Aux information key:used-mem value:136645248
2019/12/06 16:06:12 [INFO] Aux information key:repl-stream-db value:0
2019/12/06 16:06:12 [INFO] Aux information key:repl-id value:2d6ec7ea37bb863dfdb202e865801236c7528346
2019/12/06 16:06:12 [INFO] Aux information key:repl-offset value:9373905081
2019/12/06 16:06:12 [INFO] Aux information key:aof-preamble value:0
2019/12/06 16:06:12 [INFO] db_size:1 expire_size:0
2019/12/06 16:06:12 [INFO] dbSyncer[4] total = 194B -         194B [100%]  entry=1           
2019/12/06 16:06:12 [INFO] dbSyncer[4] sync rdb done
2019/12/06 16:06:12 [INFO] dbSyncer[1] total = 178B -         178B [100%]  entry=0           
2019/12/06 16:06:12 [INFO] dbSyncer[1] sync rdb done
2019/12/06 16:06:12 [INFO] dbSyncer[2] total = 188B -         188B [100%]  entry=1           
2019/12/06 16:06:12 [INFO] dbSyncer[2] sync rdb done
......

**Comment by vinllen** [comment]
2019/12/06 16:06:05 [WARN] available channel size[4096] less than current returned batch size[5000]
------------------
这里看起来有点问题，问题待定位

**Comment by vinllen** [comment]
钉钉上私聊我一下

**Comment by vinllen** [comment]
请试一下1.6.24版本

**Comment by vinllen** [comment]
问题先关闭，如还有问题请再打开

**Comment by blueQiang** [comment]
这个问题解决了吗？怎么2.0.2上还出现？
