### ISSUE TITLE
rump 报错 BUSYKEY Target key name already exists.

### ISSUE THREAD

**Issue by dengchao123456** [aliyun/redis-shake#208]
redis-shake 版本：bugfix-1.6.23,b40bd294be9892fd9319f88b6b7e7ea978b2cb62,go1.10.1,2019-11-28_20:34:03
redis 源端：蚂蚁云2.8.19主从版
redis 目标端：阿里云4.0.11集群版
参数如下（未列出的都是默认）：
source.type = standalone
source.address = r-p2u98****.redis.rds.aliyuncs.com:6379
source.password_raw = ****
target.type = proxy
target.address = r-uf6ju****.redis.rds.aliyuncs.com:6379
target.password_raw = ****
rewrite = false
scan.key_number = 500
执行命令：
./redis-shake.linux  -type=rump -conf=redis-shake.conf
日志：
2019/12/10 07:52:11 [INFO] start dbRumper[0]
2019/12/10 07:52:11 [INFO] dbRumper[0] get node count: 1
2019/12/10 07:52:11 [INFO] dbRumper[0] executor[0] start fetcher with special-cloud[]
2019/12/10 07:52:11 [INFO] dbRumper[0] executor[0] fetch db list: [0]
2019/12/10 07:52:11 [INFO] dbRumper[0] executor[0] fetch logical db: 0
2019/12/10 07:52:11 [INFO] dbRumper[0] executor[0] start fetching node db[0]
2019/12/10 07:52:12 [INFO] dbRumper[0] total = 17179508(keys) -          0(keys) [  0%]  entry=0           
2019/12/10 07:52:12 [PANIC] dbRumper[0] executor[0] restore key[IOT:BDC:CAB_BAT_ID_ORDER:6d6efbb000010001005e45a75c10cfa7] error[BUSYKEY Target key name already exists.]: pttl[0], value length[374], rdb version[6], checksum[126888905205
44332816], check error[<nil>]
[stack]: 
    0   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/rump.go:446
            redis-shake.(*dbRumperExecutor).receiver
        ... ...

**Comment by mali0512** [comment]
rewrite = false 改为 rewrite = ture

**Comment by mali0512** [comment]
rewrite = false 改为 rewrite = ture

**Comment by vinllen** [comment]
https://github.com/alibaba/RedisShake/wiki/FAQ#q-how-to-solve-the-target-key-name-is-busy-error

**Comment by dengchao123456** [comment]
> rewrite = false改写reture = ture

如果这样，目标端的同名key会被覆盖掉。而我想要的是：源端和目标端有同名key，不覆盖，以目标端为准；源端和目标端key不同名，写入到目标端。有办法可以实现吗。

**Comment by vinllen** [comment]
目前没有
