### ISSUE TITLE
Error:read tcp hostname1:port1 ->hostname2:port2 i/o timeout

### ISSUE THREAD

**Issue by coderw184** [aliyun/redis-shake#210]
现象：redis-shake同步模式为sync，type为sentinel,大概每过12分钟会有一次io超时，使连接中断，
hypervisor然后将其重启。
1.重启会重复同步数据吗？设置rewrite为false是不是可以解决？
2.io超时应该是既定的机制？12分钟在哪可以设置？
3.另外断点续传大概在哪个版本会引入？

**Comment by vinllen** [comment]
1. 会重复同步全量数据。rewrite可以覆盖掉目的端有的，源端也有的数据，但是如果中断期间源端发生了删除，目的端无法感知。
2. io超时你需要看看redis的日志，可能是redis本身的超时，同步hang住导致
3. 下个大版本，1.8或者2.0

**Comment by coderw184** [comment]
我同步测试的是单库，数据量不大，同步数据完成之后，每过大概12分钟会io超时，这是其实合理的情况，
所以根据你说的，rewrite无法让它停止重复同步？
另外线上使用时，上面那种io超时应该不会发生，如果网络中断导致连接重置，鉴于现在没有断点续传，它一定会重复同步一遍？
所以我得出的结论是：当前连接只要重置，redis-shake一定会重新同步。这个结论正确吗？

**Comment by vinllen** [comment]
12分钟io timeout，这个很奇怪，你说的是增量吗？目的端是集群版还是主从单节点？
rewrite重新同步是可以覆盖目的端数据的，只是如果在断开的gap时间，如果源端发生了删除，目的端会多出某些key。
没有断点续传支持，一旦断开，是会进行重新的全量同步。

**Comment by coderw184** [comment]
和最上面说的是一样的，sync+sentinel，我这边观察的情况是同步进行完成后，没有数据写入，大概就是12分钟

**Comment by vinllen** [comment]
你说的同步完成是全量同步完成后吧？可以钉钉上私聊我下

**Comment by flykingmz** [comment]
> 你说的同步完成是全量同步完成后吧？可以钉钉上私聊我下

请问下你说的断点续传是说在网络抖动或者主从切换迁移情况下无法续传会重新发起psync会进行全量同步吗？我看代码里面有基于psync的offset的保存和续传逻辑呢？在sync的sendPSyncCmd方法里面

**Comment by coderw184** [comment]
对，是全量同步完成后，具体日志如下：
2019/12/11 11:14:15 [PANIC] dbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:read tcp 10.210.200.160:39784->10.210.163.13:6379: i/o timeout
2019/12/11 11:26:27 [PANIC] dbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:read tcp 10.210.200.160:39884->10.210.163.13:6379: i/o timeout
2019/12/11 11:38:38 [PANIC] dbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:read tcp 10.210.200.160:39976->10.210.163.13:6379: i/o timeout
2019/12/11 11:51:04 [PANIC] dbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:read tcp 10.210.200.160:40068->10.210.163.13:6379: i/o timeout
2019/12/11 12:03:47 [PANIC] dbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:read tcp 10.210.200.160:40166->10.210.163.13:6379: i/o timeout
2019/12/11 12:17:09 [PANIC] dbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:read tcp 10.210.200.160:40262->10.210.163.13:6379: i/o timeout
2019/12/11 12:29:24 [PANIC] dbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:read tcp 10.210.200.160:40360->10.210.163.13:6379: i/o timeout
2019/12/11 12:41:38 [PANIC] dbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:read tcp 10.210.200.160:40454->10.210.163.13:6379: i/o timeout
2019/12/11 12:54:03 [PANIC] dbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:read tcp 10.210.200.160:40546->10.210.163.13:6379: i/o timeout
2019/12/11 13:06:45 [PANIC] dbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:read tcp 10.210.200.160:40644->10.210.163.13:6379: i/o timeout
2019/12/11 13:20:19 [PANIC] dbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:read tcp 10.210.200.160:40740->10.210.163.13:6379: i/o timeout
2019/12/11 13:32:28 [PANIC] dbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:read tcp 10.210.200.160:40838->10.210.163.13:6379: i/o timeout
2019/12/11 13:44:37 [PANIC] dbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:read tcp 10.210.200.160:40932->10.210.163.13:6379: i/o timeout
2019/12/11 13:56:56 [PANIC] dbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:read tcp 10.210.200.160:41024->10.210.163.13:6379: i/o timeout
2019/12/11 14:09:40 [PANIC] dbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:read tcp 10.210.200.160:41122->10.210.163.13:6379: i/o timeout


另外这是我的钉钉号：1hi-2vh588dzbv
方便的话给我，我私敲你也可以。

**Comment by vinllen** [comment]
这个问题还在定位中

**Comment by vinllen** [comment]
@coderw184 私聊一下吧

**Comment by vinllen** [comment]
请试一下1.6.24版本

**Comment by vinllen** [comment]
1.6的最新版本已修复，如果还有类似的问题请重新打开该问题
