### ISSUE TITLE
源端是sentinel，运行迁移任务提示配置出错

### ISSUE THREAD

**Issue by koolboy2016** [aliyun/redis-shake#212]
Conf.Options check failed: mode[sync] parse address failed[redis type[sentinel] address[Migr6301:master@*.*.*.*:26000;*.*.*.*:26001;*.*.*.*:26000;
Migr6302:master@*.*.*.*:26000;*.*.*.*:26001;*.*.*.*:26000;Migr6303:master@*.*.*.*:26000;*.*.*.*:26001;*.*.*.*:26000;
Migr6304:master@*.*.*.*:26000;*.*.*.*:26001;*.*.*.*:26000] 
must begin with or has '@': e.g., "master@ip1:port1;ip2:port2", "@ip1:port1,ip2:port2"]

**Comment by vinllen** [comment]
这里有多个`Migr6301:master@`，对于单个shake来说，sentinel模式只能拉取单个。
