### ISSUE TITLE
多db如何处理呢

### ISSUE THREAD

**Issue by david6522** [aliyun/redis-shake#221]
比如源端8个db，目标端4个db，这时候同步会报错
![image](https://user-images.githubusercontent.com/33677926/71444229-a0f9a580-274a-11ea-910a-c1c758bc0adc.png)

**Comment by vinllen** [comment]
目的端只能支持4个逻辑db？开源的标准应该有16个。可以增加filter去掉某些db

**Comment by vinllen** [comment]
问题如果还有疑问，请重新打开该问题
