### ISSUE TITLE
能否提供命令行传参提供配置而不是走配置文件

### ISSUE THREAD

**Issue by CSNight** [aliyun/redis-shake#225]
因为redis 的配置会经常变，能否提供命令行的方式传入配置项，而不是每次去改配置文件？不知道是否已经有这个功能？

**Comment by vinllen** [comment]
目前由于参数过多，不支持命令行传入。你这个需求我们会进行考虑，开放部分参数在命令行传入。对你们来说，哪些是比较频繁更改的？还是说都比较需要？

**Comment by CSNight** [comment]
主要是 源端和目的端参数，source/target 地址能够支持根据地址格式，自动识别是哪种连接方式，减少参数量

**Comment by CSNight** [comment]
另外就是需要input/output 参数支持命令行

**Comment by vinllen** [comment]
关于自动识别你有什么想法？你觉得目前哪些参数比较无用可以去掉？

**Comment by CSNight** [comment]
我的建议是
1.根据五种功能对配置文件进行划分 分不同的配置文件 因为例如restore dump和decode 的input output参数就是冲突的  用了dump 再用decode output和input参数就需要调换 而日志文件分开后 可以做到配置一次长期使用的效果 
2.一些基础配置 如是否使用metric 并发数 日志级别，端口号等几乎不会变的参数，完全可以改成默认参数 用户需要的时候在命令行里对个别项目进行特别指定就好

**Comment by vinllen** [comment]
这个建议我们可以后面考虑一下

**Comment by zh-wen** [comment]
有个建议，关于密码部分能不能做成配置项？ 这样我们可以封装脚本交互式输入密码，避免密码记录到bash history以及配置文件中

**Comment by suxb201** [comment]
@zh-wen @CSNight 
1. 没有必要命令行参数，会增加复杂度，如果有批量处理的需求建议使用脚本生成配置文件
2. 关于配置文件配置项冗余的情况，v3 已有改善 https://github.com/alibaba/RedisShake/tree/v3
3. 密码已经是配置项，事后删除即可。其实不管是在磁盘还是内存在宿主机不安全的情况下都不是安全的，你们需要保证宿主机是安全的。
