### ISSUE TITLE
从3.2.9的单点redis无法同步数据到5.0.5的集群

### ISSUE THREAD

**Issue by zhouyongqiang1975** [aliyun/redis-shake#226]
同步执行的命令方式：
redis-shake -type=sync -conf=redis-shake.conf

执行后出现下面错误
- execute: "./redis-shake"
2020/01/13 13:46:56 [INFO] the target redis type is cluster, only pass db0
2020/01/13 13:46:56 [INFO] source rdb[127.0.0.1:7070] checksum[yes]
2020/01/13 13:46:56 [WARN] 
______________________________
\                             \           _         ______ |
 \                             \        /   \___-=O'/|O'/__|
  \   RedisShake, here we go !! \_______\          / | /    )
  /                             /        '/-==__ _/__|/__=-|  -GM
 /        Alibaba Cloud        /         *             \ | |
/                             /                        (o)
------------------------------
if you have any problem, please visit https://github.com/alibaba/RedisShake/wiki/FAQ

2020/01/13 13:46:56 [INFO] redis-shake configuration: {"Id":"redis-shake","LogFile":"","LogLevel":"info","SystemProfile":9310,"HttpProfile":9320,"Parallel":32,"SourceType":"standalone","SourceAddress":"127.0.0.1:7070","SourcePasswordRaw":"r515f2114669tv1f98b0b5330ec0e2sd","SourcePasswordEncoding":"","SourceAuthType":"auth","SourceTLSEnable":false,"SourceRdbInput":["local"],"SourceRdbParallel":1,"SourceRdbSpecialCloud":"","TargetAddress":"10.199.99.40:7000;10.199.99.133:7000;10.199.99.132:7000","TargetPasswordRaw":"r515f2114669tv1f98b0b5330ec0e2sd","TargetPasswordEncoding":"","TargetDBString":"-1","TargetAuthType":"auth","TargetType":"cluster","TargetTLSEnable":false,"TargetRdbOutput":"local_dump","TargetVersion":"5.0.5","FakeTime":"","Rewrite":true,"FilterDBWhitelist":["0"],"FilterDBBlacklist":[],"FilterKeyWhitelist":[],"FilterKeyBlacklist":[],"FilterSlot":[],"FilterLua":false,"BigKeyThreshold":524288000,"Metric":true,"MetricPrintLog":false,"SenderSize":104857600,"SenderCount":4095,"SenderDelayChannelSize":65535,"KeepAlive":0,"PidPath":"./","ScanKeyNumber":50,"ScanSpecialCloud":"","ScanKeyFile":"","Qps":200000,"ResumeFromBreakPoint":false,"Psync":true,"NCpu":0,"HeartbeatUrl":"","HeartbeatInterval":10,"HeartbeatExternal":"","HeartbeatNetworkInterface":"","ReplaceHashTag":false,"ExtraInfo":false,"SockFileName":"","SockFileSize":0,"FilterKey":null,"FilterDB":"","SourceAddressList":["127.0.0.1:7070"],"TargetAddressList":["10.199.99.40:7000","10.199.99.133:7000","10.199.99.132:7000"],"SourceVersion":"5.0.5","HeartbeatIp":"127.0.0.1","ShiftTime":0,"TargetReplace":true,"TargetDB":-1,"Version":"feature-1.7-unstable,d3edad22d3ed7ee17d0fddb81afad8d13bbe958e,go1.10.1,2019-12-31_15:54:33","Type":"sync"}
2020/01/13 13:46:56 [INFO] DbSyncer[0] starts syncing data from 127.0.0.1:7070 to [10.199.99.40:7000 10.199.99.133:7000 10.199.99.132:7000] with http[9321]
2020/01/13 13:46:56 [PANIC] DbSyncer[0] load checkpoint from [10.199.99.40:7000 10.199.99.133:7000 10.199.99.132:7000] failed[Do failed[invalid response]]
[stack]: 
    0   /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/dbSyncer.go:82
            redis-shake/dbSync.(*DbSyncer).Sync
        ... ...
- child process[35934] terminated .
- child process killed in 0 seconds , may wrong ! exit !

**Comment by zhouyongqiang1975** [comment]
请问对于源节点存在特定的配置要求

**Comment by shuff1e** [comment]
应该是在[10.199.99.40:7000 10.199.99.133:7000 10.199.99.132:7000]这个集群上     
+ info keyspace   
+ select db  
+ exists redis-shake-checkpoint  
+ hgetall redis-shake-checkpoint  
中的某个命令执行失败

**Comment by zhouyongqiang1975** [comment]
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
10.199.99.40:7000> info keyspace
# Keyspace
db0:keys=9450443,expires=165806,avg_ttl=1430064509
10.199.99.40:7000> select db
(error) ERR invalid DB index
10.199.99.40:7000> select db0
(error) ERR invalid DB index
10.199.99.40:7000> select 1
(error) ERR SELECT is not allowed in cluster mode
10.199.99.40:7000> exists redis-shake-checkpoint
(integer) 0
10.199.99.40:7000> 
10.199.99.40:7000> hgetall redis-shake-checkpoint
(empty list or set)
10.199.99.40:7000> 
10.199.99.40:7000> quit
[kc@station40 ~]$ ls
已经根据你的提示进行验证，我该如何去判断哪个存在问题。。

**Comment by shuff1e** [comment]
select 0试下……
那我就不知道什么原因了……

**Comment by zhouyongqiang1975** [comment]
请问这个redis-shake支持无盘化的数据同步么？

**Comment by zhouyongqiang1975** [comment]
试了select 0没有问题

**Comment by shuff1e** [comment]
无盘化是什么意思

**Comment by zhouyongqiang1975** [comment]
就是那个repl-deskless-sync模式，尽量少操作硬盘形成rdb文件。。

**Comment by zhouyongqiang1975** [comment]
请问有没有直接从redis缓存中进行数据同步的模式。。

**Comment by vinllen** [comment]
@zhouyongqiang1975 
1. 目前的1.7版本目的端不支持集群版，所以现在是有问题的。集群版的支持还在开发中。这里面有说明：https://github.com/alibaba/RedisShake/wiki/%E6%96%AD%E7%82%B9%E7%BB%AD%E4%BC%A0
2. 关于无盘化，后面shake会发送capa给源端，但是具体是否落盘还是由源端redis决定的。

**Comment by vinllen** [comment]
@zhouyongqiang1975 1.7版本是非稳定版本，如果想要同步可以用1.6版本，1.7版本功能还在继续迭代中。
无盘化功能进入开发。
