### ISSUE TITLE
sync but rewrite fail

### ISSUE THREAD

**Issue by HaiquanHe** [aliyun/redis-shake#227]
command:
./redis-shake.linux -type=sync -conf=./redis-shake.conf
failed log:

2020/01/16 18:08:30 [INFO] redis-shake configuration: {"Id":"redis-shake","LogFile":"","LogLevel":"info","SystemProfile":9310,"HttpProfile":9320,"Parallel":1,"SourceType":"standalone","SourceAddress":"127.0.0.1:6379","SourcePasswordRaw":"","SourcePasswordEncoding":"","SourceAuthType":"auth","SourceTLSEnable":false,"SourceRdbInput":["local"],"SourceRdbParallel":1,"SourceRdbSpecialCloud":"","TargetAddress":"127.0.0.1:6777","TargetPasswordRaw":"","TargetPasswordEncoding":"","TargetDBString":"4","TargetAuthType":"auth","TargetType":"standalone","TargetTLSEnable":false,"TargetRdbOutput":"local_dump","TargetVersion":"2.8.24","FakeTime":"","Rewrite":true,"FilterDBWhitelist":["0"],"FilterDBBlacklist":[],"FilterKeyWhitelist":[],"FilterKeyBlacklist":[],"FilterSlot":[],"FilterLua":false,"BigKeyThreshold":524288000,"Psync":true,"Metric":true,"MetricPrintLog":false,"SenderSize":104857600,"SenderCount":4095,"SenderDelayChannelSize":65535,"KeepAlive":0,"PidPath":"","ScanKeyNumber":50,"ScanSpecialCloud":"","ScanKeyFile":"","Qps":2000,"NCpu":0,"HeartbeatUrl":"","HeartbeatInterval":10,"HeartbeatExternal":"","HeartbeatNetworkInterface":"","ReplaceHashTag":false,"ExtraInfo":false,"SockFileName":"","SockFileSize":0,"FilterKey":null,"FilterDB":"","SourceAddressList":["127.0.0.1:6379"],"TargetAddressList":["127.0.0.1:6777"],"SourceVersion":"2.8.24","HeartbeatIp":"127.0.0.1","ShiftTime":0,"TargetReplace":false,"TargetDB":4,"Version":"bugfix-1.6.24,6d6cc3a8d3e07d4544eead2a218a80b5ca897ceb,go1.10.1,2019-12-20_17:27:56","Type":"sync"}
2020/01/16 18:08:30 [INFO] routine[0] starts syncing data from 127.0.0.1:6379 to [127.0.0.1:6777] with http[9321]
2020/01/16 18:08:30 [INFO] input password is empty, skip auth address[127.0.0.1:6379] with type[auth].
2020/01/16 18:08:30 [INFO] dbSyncer[0] psync connect '127.0.0.1:6379' with auth type[auth] OK!
2020/01/16 18:08:30 [INFO] dbSyncer[0] psync send listening port[9320] OK!
2020/01/16 18:08:30 [INFO] dbSyncer[0] try to send 'psync' command
2020/01/16 18:08:30 [INFO] Event:FullSyncStart  Id:redis-shake
2020/01/16 18:08:30 [INFO] dbSyncer[0] psync runid = d60f8e1b79e3de8157f41b65a0fe9628623314f7 offset = 4750626322, fullsync
2020/01/16 18:08:31 [INFO] dbSyncer[0] rdb file size = 6645329
2020/01/16 18:08:31 [INFO] input password is empty, skip auth address[127.0.0.1:6777] with type[auth].
2020/01/16 18:08:31 [PANIC] delete key[OPEN_PLATFORM_WECHAT_UNIQUE_V2_20191013125604_4200000403201910139400158549_1860000.00] failed[redigo: unexpected type for String, got type int64]
[stack]: 
    1   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/common/utils.go:845
            redis-shake/common.RestoreRdbEntry
    0   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/sync.go:447
            redis-shake.(*dbSyncer).syncRDBFile.func1.1

./redis-shake.linux -version
bugfix-1.6.24,6d6cc3a8d3e07d4544eead2a218a80b5ca897ceb,go1.10.1,2019-12-20_17:27:56
 
redis version: 2.8.24

 key's type: 
127.0.0.1:6379> type OPEN_PLATFORM_WECHAT_UNIQUE_V2_20191013125604_4200000403201910139400158549_1860000.00
string

**Comment by vinllen** [comment]
在配置文件里面启用rewrite选项，这个是删除目的端key出错了，但是目前报错不太明显，这个地方需要优化一下让报错更加直观。

**Comment by HaiquanHe** [comment]
> 在配置文件里面启用rewrite选项，这个是删除目的端key出错了，但是目前报错不太明显，这个地方需要优化一下让报错更加直观。

---可是我配置文件里已经是true了
[root@test1 redis-shake-1.6.24]# grep rew redis-shake.conf
# force rewrite when destination restore has the key
rewrite = true

**Comment by HaiquanHe** [comment]
> 在配置文件里面启用rewrite选项，这个是删除目的端key出错了，但是目前报错不太明显，这个地方需要优化一下让报错更加直观。

---可是我的配置文件里已经是true了
[root@test1 redis-shake-1.6.24]# grep rew redis-shake.conf
rewrite = true

**Comment by vinllen** [comment]
哦，你这个目的端版本是2.8的，是不会自动rewrite，执行逻辑是需要先删除再写入，3.x以上是直接rewrite的。
看了下，这里的确是bug，我会进行修复。

**Comment by vinllen** [comment]
1.6.25版本已修复并发布，请再试一下

**Comment by HaiquanHe** [comment]
> 1.6.25版本已修复并发布，请再试一下

---谢谢，该版本测试没问题，不报错。功能正常。
