### ISSUE TITLE
这个redis-shake能否在同步完全量后一直保持数据同步

### ISSUE THREAD

**Issue by zhouyongqiang1975** [aliyun/redis-shake#228]
这个redis-shake能否在同步完全量后一直保持数据同步，我使用了sync和rump模式都是在同步完后就整个应用退出了，就无法做到数据想主从那样进行同步更新最新的修改数据。

**Comment by vinllen** [comment]
sync模式正常全量同步是会进入增量，增量如果不出错是一个长期的同步过程，也就是你说的更新的数据都是能同步。如果退出了肯定是有报错了。可以看下具体的报错日志，对照wiki的faq看看，或者抛在下面的回复。
rump模式仅仅是一个全量的同步，同步完全量以后会自己退出。

**Comment by vinllen** [comment]
@zhouyongqiang1975 问题暂无反馈，先行关闭了，后面有问题可以加我们的钉钉群，交流更加方便了。

**Comment by igozhang** [comment]
[root@igo_redis-shake-191 ~]# /opt/redis-shake/redis-shake.linux -conf=/opt/redis-shake/redis-shake.conf -type=sync
2022/03/06 18:49:58 [INFO] input password is empty, skip auth address[192.168.3.171:7001] with type[].
2022/03/06 18:49:58 [INFO] input password is empty, skip auth address[192.168.3.183:8005] with type[].
[root@igo_redis-shake-191 ~]#

**Comment by igozhang** [comment]
就是自己退出，没有报错，加个&，就能正常工作，感觉有点low

**Comment by igozhang** [comment]
是最新版本  release-v2.1.1-20210903
