### ISSUE TITLE
这个是不是BUG？

### ISSUE THREAD

**Issue by jiuker** [aliyun/redis-shake#233]
你好，我深入看一下逻辑代码，发现有一个点没想通：A为源redis，B为target redis，type=sync
阶段：增量更新
当每次A监听指令发送，都会执行一次 ds.addDelayChan(sendId.Get())，但是如果没有触发Flush的话，命令还是在Send层面。
监听B的响应处，有一个去拉去这个Channel，但是如果上述命令执行5000次，也就是有5000个delay chan，但是监听B的响应只拉一个，delay是不是会迟早塞满。
特别是qps特别高的时候1S内有100个操作，这个情况就会出现。
不应该是执行Flush的时候再去写这个ds.addDelayChan(sendId.Get())，并且
used := cap(ds.delayChannel) - len(ds.delayChannel)这种命名很容易产生混淆，我都不知道used对应的是余量还是使用了多少

**Comment by jiuker** [comment]
我好像明白了，即便是批量操作也是会有多个返回结果的，不可能就只有一个，但是
used := cap(ds.delayChannel) - len(ds.delayChannel) 仍然很疑惑，符合你自己的意愿不呢

**Comment by vinllen** [comment]
这里used命名是有问题的，应该是available，表示channel里面可用的大小。
下个版本我会进行修改。

**Comment by vinllen** [comment]
已在1.7版本修改为available，后面会正式发布在v2.0里面。1.7之前的版本不做修改。
