### ISSUE TITLE
go mod迁移？

### ISSUE THREAD

**Issue by jiuker** [aliyun/redis-shake#234]
require (
	github.com/BurntSushi/toml v0.3.1 // indirect
	github.com/FZambia/go-sentinel v0.0.0-20171204085413-76bd05e8e22f
	github.com/cupcake/rdb v0.0.0-20161107195141-43ba34106c76
	github.com/garyburd/redigo v1.6.0
	github.com/gugemichael/nimo4go v0.0.0-20190904073057-32795d80f83a
	github.com/kr/pretty v0.2.0 // indirect
	github.com/nightlyone/lockfile v0.0.0-20180618180623-0ad87eef1443
	github.com/prometheus/client_golang v1.3.0
	github.com/stretchr/testify v1.4.0
	github.com/vinllen/redis-go-cluster v0.0.0-20191216031721-ceb83e88e9fa
	gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15
	gopkg.in/natefinch/lumberjack.v2 v2.0.0
)
就可以完成 go mod的迁移
重点是 github.com/vinllen/redis-go-cluster v0.0.0-20191216031721-ceb83e88e9fa
这样就可以享受go mod的好处啦

**Comment by jiuker** [comment]
当然还是推荐用其他的go-redis-cluster来替换一下，比如官方的

**Comment by CaoZB** [comment]
请问github.com/vinllen/redis-go-cluster v0.0.0-20191216031721-ceb83e88e9fa到哪里可以找到

**Comment by jiuker** [comment]
> 请问github.com/vinllen/redis-go-cluster v0.0.0-20191216031721-ceb83e88e9fa到哪里可以找到

你把上述go.mod的内容复制到你项目里面go.mod即可，然后设置代理 GOPATOXY=https://goproxy.cn   ，在你go.mod的目录下，执行go mod tidy即可完成下载依赖

**Comment by CaoZB** [comment]
> > 请问github.com/vinllen/redis-go-cluster v0.0.0-20191216031721-ceb83e88e9fa到哪里可以找到
> 
> 你把上述go.mod的内容复制到你项目里面go.mod即可，然后设置代理 GOPATOXY=https://goproxy.cn ，在你go.mod的目录下，执行go mod tidy即可完成下载依赖

感谢感谢🙏🙏，解决了，谢谢大佬。

**Comment by suxb201** [comment]
感谢，已改用 go mod 管理依赖。
