### ISSUE TITLE
redis哨兵同步

### ISSUE THREAD

**Issue by zzzxx** [aliyun/redis-shake#235]
![图片](https://user-images.githubusercontent.com/22747106/73717637-5873d580-4755-11ea-846d-9465558eb096.png)
以下是我的配置的哨兵同步，在同步期间，我的源地址的  哨兵集群的数据master节点挂了，  数据同步就断开了，重启 RedisShake后 ，又继续同步，这个是正常的吗？

**Comment by vinllen** [comment]
你用的是1.6的版本吧，目前版本如果节点挂了导致数据拉取不到是会直接退出的。这个时候如果重启RedisShake，是会从**新的master**上进行重新拉取，会重新进行全量+增量的同步。
