### ISSUE TITLE
[PANIC] invalid sync response, rsp = '-ERR unknown command 'sync'

### ISSUE THREAD

**Issue by liangkun16** [aliyun/redis-shake#240]
./redis-shake -conf=redis-shake.conf -type=sync
我这么执行命令 这个是什么报错啊，为什么会要sync命令不可用。

**Comment by vinllen** [comment]
你这个是阿里云上的实例吧，源端被禁用了sync，可以在控制台开启复制权限的账号

**Comment by wenzhucjy** [comment]
腾讯云的实例，提示  [PANIC] invalid psync response, continue, ERR unknown command ' psync '
[stack]: 
    2   github.com/alibaba/RedisShake/redis-shake/common/utils.go:251
