### ISSUE TITLE
RedisShake不支持Qihoo360/pika进行数据迁移

### ISSUE THREAD

**Issue by giantchou** [aliyun/redis-shake#241]
当从把pika作为数据源节点时，会报如下错误：
Conf.Options check failed: get source redis version failed
我主要测试的版本有1.6.24和1.6.26及1.7版本。
但不知从哪个版本开始，source.version 参数已经不被支持了。

**Comment by vinllen** [comment]
pika的协议跟redis有所差异，他们有一个pika-port的工具可以进行使用。
source.version这个变量是shake通过发送info server自动获取的，不支持是pika不支持`info server`命令导致的。

**Comment by giantchou** [comment]
当pika作为目的端的时候是没问题的，是因为targer.version参数在起作用吗？当在配置文件中不指定targer.version参数时默认是6的时候会报错，该参数配置为7的时候，可以把pika作为目的端进行数据的备份。

**Comment by giantchou** [comment]
<img width="400" alt="图片" src="https://user-images.githubusercontent.com/13905371/74130086-39c18300-4c1c-11ea-9b34-f9fef284a5dc.png">
<img width="382" alt="图片" src="https://user-images.githubusercontent.com/13905371/74130123-4cd45300-4c1c-11ea-9aff-b21740486986.png">
通过实际测试，pika支持info server命令的呀。

**Comment by vinllen** [comment]
完整的报错你帖我看下，看起来Info server是可以拿到的。
不过pika同步的协议是不一样的，而且我记得全量结束是断开再增量的，这块即使没问题，后面可能也有问题。

**Comment by giantchou** [comment]
我大概知道哪里的问题了，因为pika是不支持psync协议的，我估计这才是根本原因所在。
