### ISSUE TITLE
RedisShake的/metric状态信息输出格式可否支持prometheus数据格式？

### ISSUE THREAD

**Issue by giantchou** [aliyun/redis-shake#242]
当前RedisShake的状态信息输出格式如下:
[
{
StartTime: "2020-02-11T17:05:02Z",
PullCmdCount: 0,
PullCmdCountTotal: 15064,
BypassCmdCount: 0,
BypassCmdCountTotal: 0,
PushCmdCount: 0,
PushCmdCountTotal: 15064,
SuccessCmdCount: 0,
SuccessCmdCountTotal: 15064,
FailCmdCount: 0,
FailCmdCountTotal: 0,
Delay: "null ms",
AvgDelay: "null ms",
NetworkSpeed: 0,
NetworkFlowTotal: 60289,
FullSyncProgress: 100,
Status: "incr",
SenderBufCount: 0,
ProcessingCmdCount: 15061,
TargetDBOffset: 1,
SourceDBOffset: 210978,
SourceAddress: "192.168.30.72:6379",
TargetAddress: [
"192.168.13.10:3072"
],
Details: null
}
]
我看到源码中已经有prometheus_metrics.go的模块，请问如何才能获取prometheus需要的数据类型么？

**Comment by vinllen** [comment]
pr: https://github.com/alibaba/RedisShake/pull/103/files
通过/metrics进行访问

**Comment by giantchou** [comment]
收到、非常感谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Vinllen Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月14日(星期五) 上午10:14
收件人:&nbsp;"alibaba/RedisShake"<RedisShake@noreply.github.com&gt;;
抄送:&nbsp;"shoring"<505972916@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/RedisShake] RedisShake的/metric状态信息输出格式可否支持prometheus数据格式？ (#242)




pr: https://github.com/alibaba/RedisShake/pull/103/files
 通过/metrics进行访问
