### ISSUE TITLE
同步出现lack_target的问题

### ISSUE THREAD

**Issue by surfingPro** [aliyun/redis-shake#244]
发现redis-shake同步完成后，用fullcheck工具检查出有4个key没有同步，重试多次都一样
同步数据量：1.2G
同步时间：90s左右
出问题的key的tll大多数为几十秒，而且会不定时更新ttl。

**Comment by vinllen** [comment]
这个问题出在全量同步的gap，举个例子，假如10:00开始同步，10:10完成全量同步并进入增量同步，然后shake会拉取10:00-10:10积累的增量并发送。对于正常没有问题，对于ttl恰好在10:00-10:10期间过期并提前续租的可能就有问题了：

1. 10:00 源redis set a = 1，ttl = 3分钟（10:03过期）
2. 全量同步开始，save rdb并发送
3. 10:02分，源redis续租ttl a = 20分钟（10:22过期）
4. 10:08分rdb中的a被写入到目的端，立刻触发了删除，因为之前的ttl（10:03）已经到期了
5. 10:10开始增量，收到了之前的续租ttl命令，发送给目的端，但是没有生效。因为目的端a已经被删除不存在了。

这个问题对于所有全量+增量模式的外部同步工具**都会存在**，因为全量同步是有时间差的，这个时间差就会导致这个key被删除。除非依赖redis内核，正常slave不发生过期淘汰，由master发送delete命令触发删除。
解决办法：增大ttl的过期时间（大于rdb传输的时间），或者提高rdb的传输效率也可以一定意义上进行缓解，但不是根本方法。
修复方法可以是：采用full-check校验，找出不一致的key，然后**手动**或者**用shake的rump+过滤模式**再导入一遍这些不一致的key。
