### ISSUE TITLE
redis cluster之间同步报错

### ISSUE THREAD

**Issue by IT-xiaoge** [aliyun/redis-shake#247]
2020/03/09 19:02:20 [INFO] dbSyncer[0] sync rdb done
2020/03/09 19:02:20 [INFO] dbSyncer[0] FlushEvent:IncrSyncStart Id:redis-shake
2020/03/09 19:02:20 [INFO] input password is empty, skip auth address[] with type[auth].
2020/03/09 19:02:20 [PANIC] dbSyncer[0] Event:SendToTargetFail  Id:redis-shake  Error:run ChooseNodeWithCmd failed[Put: mset not supported]
[stack]:
    0   /home/dba_dev/godev/gopath/src/RedisShake/src/redis-shake/sync.go:675
            redis-shake.(*dbSyncer).syncCommand.func4
        ... ...

**Comment by vinllen** [comment]
`Put: mset not supported`驱动层面还不支持mset和msetex命令。这个后面可以加上

**Comment by vinllen** [comment]
1.6.27版本将会支持
