### ISSUE TITLE
shake on k8s

### ISSUE THREAD

**Issue by shuff1e** [aliyun/redis-shake#249]
shake作为long run的同步服务，部署在k8s上，由k8s提供调度，以及保证HA。

**Comment by vinllen** [comment]
这里有什么建议，shake需要提供什么能力，断点续传？以及HA切换保证的数据持续同步。还有master-salve选主的模式？

**Comment by shuff1e** [comment]
HA切换和master-slave选主具体指的是什么？和MongoShake本身的高可用一样吗？    
高可用，可以由k8s来保证的吧。    
目前需要加一个断点续传，应该就可以了

**Comment by vinllen** [comment]
断点续传会慢慢完善，人力问题 排期延后

**Comment by vinllen** [comment]
2.0对断点续传已经支持，具体请查看wiki文档
