### ISSUE TITLE
[PANIC] repl listening-port failed[-ERR command replconf not support for normal user]

### ISSUE THREAD

**Issue by langse059** [aliyun/redis-shake#252]
执行命令
./start.sh redis-shake.conf sync

报错
2020/03/12 13:40:59 [PANIC] repl listening-port failed[-ERR command replconf not support for normal user]
[stack]:
    2   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/common/utils.go:137
            redis-shake/common.SendPSyncListeningPort
    1   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/sync.go:281
            redis-shake.(*dbSyncer).sendPSyncCmd
    0   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/sync.go:219
            redis-shake.(*dbSyncer).sync

**Comment by mind9blowing** [comment]
我刚遇到这个问题，请问您如何解决的呢？

**Comment by vinllen** [comment]
云上的吧，不支持sync权限导致的

**Comment by mind9blowing** [comment]
通过rump模式已经解决了

**Comment by smileMrLee** [comment]
> 云上的吧，不支持sync权限导致的

你好，请问这个情况怎么解决？

**Comment by mind9blowing** [comment]
@smileMrLee  使用rump模式就可以了

**Comment by smileMrLee** [comment]
> rump

./redis-shake.linux -conf=redis-shake.conf -type=rump 1>>redis-shake.output 2>&1
执行这个命令吗？

**Comment by mind9blowing** [comment]
@smileMrLee 最好是完整输出信息，直接展示出来 ./redis-shake -type=rump -conf=redis-shake.conf

**Comment by smileMrLee** [comment]
@mind9blowing 已经搞定了。厉害啊。

**Comment by mind9blowing** [comment]
@smileMrLee 之前云上迁移遇到过这个问题
