### ISSUE TITLE
common/utils.go疑问

### ISSUE THREAD

**Issue by veblenzhang** [aliyun/redis-shake#253]
redis-shake/common/utils.go疑问，
func RestoreRdbEntry(c redigo.Conn, e *rdb.BinEntry) {
	if e.Type == rdb.RdbTypeQuicklist {
                ....
                return
	}
       
        s, err := redigoCluster.String(c.Do("restore", params...))
｝

会为什么对QuickList单独做处理呢，而不采用restore的方式呢？是为了兼容某些厂商的redis版本么？

**Comment by vinllen** [comment]
这部分逻辑跟下面的big key处理是可以合并的。直接restore是出于大Key的考虑
