### ISSUE TITLE
单机模式迁移至RDS redis集群版ERR 'EVAL' command keys must in same slot问题

### ISSUE THREAD

**Issue by gaoqiang-0327** [aliyun/redis-shake#254]
单机模式3.2迁移至RDS redis集群版4.0，因为有使用lua脚本，迁移过程中会出现	Error: ERR 'EVAL' command keys must in same slot
错误。这个该如何处理？如果调整script_check_enable参数 是否会有影响。

**Comment by vinllen** [comment]
redis集群有约束，事务和lua脚本是不能跨slot的
