### ISSUE TITLE
单机版迁移到集群 redis 4.0.10报错

### ISSUE THREAD

**Issue by wavelet123** [aliyun/redis-shake#256]
Hi Team,
我们迁移的时候有如下报错，麻烦帮忙看下。
谢谢

2020/03/24 19:48:59 [PANIC] read error
[error]: EOF
[stack]: 
    1   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/common/utils.go:878
            redis-shake/common.Iocopy
    0   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/sync.go:317
            redis-shake.(*dbSyncer).sendPSyncCmd.func1
        ... ...

**Comment by wavelet123** [comment]
config set client-output-buffer-limit 'slave 1073741824 268435456 300'
设置之后问题解决

**Comment by vinllen** [comment]
后续需要对打印添加更明显的日志，引导用户查看源端redis

**Comment by vinllen** [comment]
1.6.27已进行修改
