### ISSUE TITLE
无线循环，怎么处理，数据还有一部分没有过来。

### ISSUE THREAD

**Issue by Jugol7** [aliyun/redis-shake#261]
![image](https://user-images.githubusercontent.com/48045783/78112872-6da57180-7431-11ea-9e00-99037b273906.png)

![image](https://user-images.githubusercontent.com/48045783/78112795-523a6680-7431-11ea-855f-ec145d2ab632.png)

**Comment by vinllen** [comment]
增量本身就是无限循环的，不会停下来，这里显示没数据同步就是没有了。你可以用redis-full-check校验看下差异。
