### ISSUE TITLE
不停机迁移后热切服务的问题，有没有可能出现下述这种情况

### ISSUE THREAD

**Issue by hzux** [aliyun/redis-shake#262]
源redis迁移至目标redis。
全量同步完成，进入增量同步阶段，此时热切实例连接的redis地址。
一个服务有实例A和B，已经热切了实例A，此时实例A连接的是目标redis，在还未热切实例B之前的这段时间里，服务的实例A被调用数据写入了目标redis，很快实例B也被调用读相同的数据，可此时实例B读取的是源redis，自然是读不到的。
请问有没有一个最佳实践呢？

**Comment by vinllen** [comment]
看的不太理解，能用图画一下吗？还有热切是说的不停机？你这个场景需要短暂的停业务，比如源端读源端的业务，数据同步需要切到目的端，那么源端先停写，然后终止一段时间（通常1秒就够了），等通道中的数据都同步到目的端（可以通过log或者restful接口），再连接目的端。

**Comment by suxb201** [comment]
要停机的。或者有切域名的服务，可以流量暂停短暂时间，确保数据同步，然后域名切过去，恢复流量。
