### ISSUE TITLE
redis 4.0.10 cluster 同步到单点报错

### ISSUE THREAD

**Issue by wavelet123** [aliyun/redis-shake#263]
[stack]: 
    1   /home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:253
            redis-shake/common.SendPSyncContinue
    0   /home/zhuzhao.cx/RedisShake/src/redis-shake/sync.go:357
            redis-shake.(*dbSyncer).sendPSyncCmd.func1
        ... ...
2020/04/03 00:35:58 [PANIC] invalid psync response = 'FULLRESYNC cc863673f668dce9fecb8c6db042d93bc5d6e001 48232054424', should be continue
[stack]: 
    1   /home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:255
            redis-shake/common.SendPSyncContinue
    0   /home/zhuzhao.cx/RedisShake/src/redis-shake/sync.go:357
            redis-shake.(*dbSyncer).sendPSyncCmd.func1

**Comment by vinllen** [comment]
重试一下，看起来是中断过

**Comment by zh-wen** [comment]
@vinllen 我同步到集群也遇到类似的问题。请教一下，在什么的情况下会出现这样的报错？

**Comment by suxb201** [comment]
问题太久，难以排查。先关闭了，有问题可以另开 issue。
