### ISSUE TITLE
集群到集群同步报错

### ISSUE THREAD

**Issue by lijun535535** [aliyun/redis-shake#266]
![image](https://user-images.githubusercontent.com/31472166/79707646-cf018780-82ef-11ea-9242-1178969fe8dc.png)

**Comment by vinllen** [comment]
redis和shake的版本是多少？

**Comment by lijun535535** [comment]
source是3.2.8
target是5.0.3
shake是1.6.18

**Comment by vinllen** [comment]
shake升级到1.6的最新版，看看报错应该更加详细一点

**Comment by lijun535535** [comment]
![image](https://user-images.githubusercontent.com/31472166/79725259-88298700-831b-11ea-86f3-c4cdb1991772.png)
这个是shake升级到1.6.27的报错，好像没啥变化

**Comment by vinllen** [comment]
钉钉私聊我一下，一起看下

**Comment by vinllen** [comment]
问题是cluster nodes显示的地址是私网地址，跟shake机器无法相通，后续需要评估修改driver层面对这种场景的支持。

**Comment by vinllen** [comment]
关于log的打印已经发布v1.6.28版本进行优化。
