### ISSUE TITLE
高ops的时候，redis-shake占用CPU比较高，13M/s,3W ops+

### ISSUE THREAD

**Issue by jiuker** [aliyun/redis-shake#269]
pprof查出，是net.Read调用太频繁，可以适当延迟，目前发现2ms比较合适，我不知道最佳是多少，1的话，效果不理想。
原来我们的cpu占用为125%，pprof出来，net.Read为71%，当我们加上time.Sleep之后，直接将为50%左右，并且不影响同步
然后openConnet可以 net.DialTCP,可以设置ReadBuffer和WriteBuffer，然后当做net.Conn传出去即可。

**Comment by vinllen** [comment]
感谢反馈，方便发一下pprof火焰图或者调用链吗？

**Comment by jiuker** [comment]
如图，这个是核心地方
ds.sendPSyncCmd -> ds.pSyncPipeCopy->bufio.Read->图

**Comment by jiuker** [comment]
放不了图。。。  图那里是  net(conn).Read->net(netFD).Read->poll(FD).Read->syscall(read),一整个流程标红，并且cpu 71一直没降低

**Comment by vinllen** [comment]
看看可否方便发我邮箱吧：cvinllen@gmail.com

**Comment by jiuker** [comment]
已发

**Comment by vinllen** [comment]
可能墙的问题，没收到，你看看方便加钉钉沟通吗？首页能找到群，加群后找到我

**Comment by jiuker** [comment]
投递成功了

**Comment by vinllen** [comment]
收到了

**Comment by vinllen** [comment]
这个net.Read消耗高的问题是网络收包多，导致网卡中断送包就多，这个跟你目前的qps是符合预期的，所以你看到的cpu高应该都是cpu.sys，而不是cpu.user。你sleep的话相当于降低网络IO次数，而增大一次读取的量，这个cpu.sys来说消耗就少了，但是收包就有延迟了。相当于原来是一次中断一次收取，现在是多次来包，一次收取。
你要是觉得对自己业务场景合适可以这么修改，但shake目前不会考虑这个修改。

**Comment by jiuker** [comment]
所以我们在端口那里加了readBuf，所以减少了读取次数，但是读取量是不会变的

**Comment by jiuker** [comment]
具体体现为 
        ```
targetAddr, err = net.ResolveTCPAddr("tcp", target)
		if err == nil {
			c1, err := net.DialTCP("tcp", nil, targetAddr)
			if err == nil {
				c1.SetKeepAlive(true)
				c1.SetKeepAlivePeriod(d.KeepAlive)
				c1.SetNoDelay(false)
				c1.SetReadBuffer(10 * 1024 * 1024)
				c1.SetWriteBuffer(10 * 1024 * 1024)
			}
			c = c1
		}
```

**Comment by vinllen** [comment]
这个地方可以提个pull request，我后面评估看看要不要合入。加buffer方式相对于sleep来说，目前看来是可取的。

**Comment by jiuker** [comment]
加了buffer的话，如果不用sleep，对于降低cpu占用率没啥用处，但是我提一个没有sleep的pull request吧

**Comment by jiuker** [comment]
`d := &net.Dialer{
		KeepAlive: time.Duration(60) * time.Second,
		Control: func(network, address string, c syscall.RawConn) error {
			var operr error
			var fn func(uintptr)
			switch network {
			case "tcp", "udp", "ip":
				return errors.New("ambiguous network: " + network)
			case "unix", "unixpacket", "unixgram":
				fn = func(s uintptr) {
					_, operr = syscall.GetsockoptInt(int(s), syscall.SOL_SOCKET, syscall.SO_ERROR)
				}
			default:
				switch network[len(network)-1] {
				case '4':
					fn = func(s uintptr) {
						// readBuffer
						operr = syscall.SetsockoptInt(int(s), syscall.SOL_SOCKET, syscall.SO_RCVBUF, 10*1024)
						// writeBuffer
						operr = syscall.SetsockoptInt(int(s), syscall.SOL_SOCKET, syscall.SO_SNDBUF, 10*1024)
					}
				case '6':
					fn = func(s uintptr) {
						// readBuffer
						operr = syscall.SetsockoptInt(int(s), syscall.SOL_SOCKET, syscall.SO_RCVBUF, 10*1024)
						// writeBuffer
						operr = syscall.SetsockoptInt(int(s), syscall.SOL_SOCKET, syscall.SO_SNDBUF, 10*1024)
					}
				default:
					return errors.New("unknown network: " + network)
				}
			}
			if err := c.Control(fn); err != nil {
				return err
			}
			if operr != nil {
				return operr
			}
			return nil
		},
	}`

**Comment by jiuker** [comment]
d := &net.Dialer{
		KeepAlive: time.Duration(60) * time.Second,
		Control: func(network, address string, c syscall.RawConn) error {
			var operr error
			var fn func(uintptr)
			switch network {
			case "tcp", "udp", "ip":
				return errors.New("ambiguous network: " + network)
			case "unix", "unixpacket", "unixgram":
				fn = func(s uintptr) {
					_, operr = syscall.GetsockoptInt(int(s), syscall.SOL_SOCKET, syscall.SO_ERROR)
				}
			default:
				switch network[len(network)-1] {
				case '4':
					fn = func(s uintptr) {
						// readBuffer
						operr = syscall.SetsockoptInt(int(s), syscall.SOL_SOCKET, syscall.SO_RCVBUF, 10*1024)
						// writeBuffer
						operr = syscall.SetsockoptInt(int(s), syscall.SOL_SOCKET, syscall.SO_SNDBUF, 10*1024)
					}
				case '6':
					fn = func(s uintptr) {
						// readBuffer
						operr = syscall.SetsockoptInt(int(s), syscall.SOL_SOCKET, syscall.SO_RCVBUF, 10*1024)
						// writeBuffer
						operr = syscall.SetsockoptInt(int(s), syscall.SOL_SOCKET, syscall.SO_SNDBUF, 10*1024)
					}
				default:
					return errors.New("unknown network: " + network)
				}
			}
			if err := c.Control(fn); err != nil {
				return err
			}
			if operr != nil {
				return operr
			}
			return nil
		},
	}

**Comment by jiuker** [comment]
声明dailer的时候，可以加上control
