### ISSUE TITLE
lastdb的问题

### ISSUE THREAD

**Issue by jiuker** [aliyun/redis-shake#270]
我们有一个库，数据全在db1，但是db0上有sub/pub
我们执行了全量，但是增量阶段第一条数据并不是Select 1，由于程序是断开连接，所以默认select db默认是0，造成了数据不一致的问题。

**Comment by vinllen** [comment]
这个不应该的，新连接逻辑db源端会发送select命令，你确定是db1的数据跑到了db0？

**Comment by jiuker** [comment]
极其肯定的，第一条并不是select ,我们线上执行 psync ？-1 很多增量第一条并不是select
version 5.0.5

**Comment by vinllen** [comment]
不可能会出现这种情况，全量同步完毕源端肯定会推送last dbid的，你可以源码层面确认下。

**Comment by jiuker** [comment]
我们直接client执行 psync ？ -1第一条都不是select db，具体看钉钉

**Comment by vinllen** [comment]
你看下redis源码吧replicationFeedSlaves，这种情况不会出现，除非你们自己代码改过了

**Comment by jiuker** [comment]
我们没有改过源码，但是确实出现了，群里有截图，肯定不是ps的，我们线上数据库，出现了这个问题

**Comment by vinllen** [comment]
redis-cli本身不应该支持psync命令，因为这个不只是单条命令，而且还有协议报文的交互，源端会回复FULLRESYNC或者CONTINUE，然后才是后面的数据同步，而你这里截图都没有。

**Comment by jiuker** [comment]
redis-cli  是支持的psync的，只是client会丢掉，不处理，会不会是被缓冲冲掉了，因为我们收到的第一条和client的表现确实一致，用的sync.Once ,发现第一条不是select

**Comment by jiuker** [comment]
但是大多数确实是select ，这个是可以肯定的

**Comment by vinllen** [comment]
这个问题很简单，你抓包分析一下就能看到

**Comment by suxb201** [comment]
看样子问题好像已经解决了。如果还有问题，请另开 issue。
