### ISSUE TITLE
replconf ack postion 建议上一个读写锁

### ISSUE THREAD

**Issue by jiuker** [aliyun/redis-shake#271]
根据官方文档，replconf ack上报位置小于当前的位置，服务器会在积压区再次发送该丢失区间的命令，有这个隐患，因为我是批量读取已经出现此问题，但是我还是建议上一个读写锁，更加严谨
ds.pSyncPipeCopy -> nread

**Comment by baronwangr** [comment]
PR is welcomed!

**Comment by suxb201** [comment]
没看到 Redis 有这个逻辑
