### ISSUE TITLE
建议支持按照一定规则重写key名称

### ISSUE THREAD

**Issue by BlackWatchuser** [aliyun/redis-shake#272]
使用场景：如果从多个redis集群，迁移至同一个集群，可能会面临key重名覆盖的问题，如果可以按照一定规则（比如给所有满足迁移条件的key，添加前缀后写入到目标集群），就可以规避掉key覆盖的问题。

**Comment by vinllen** [comment]
方案不可行，全量阶段如果重命名，会导致增量同步找不到key存在问题。目前2.0版本针对key存在的情况，key_exists提供了rewrite和ignore2个参数。
