### ISSUE TITLE
全量同步失败，报错 panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by linyunnew** [aliyun/redis-shake#279]
goroutine 4121 [running]:
bufio.(*Reader).Read(0xc5c548cd20, 0xc5d69f6a99, 0x1, 0x1, 0x1, 0xc69cdcebd0, 0x2c)
        /home/zhuzhao.cx/go/src/bufio/bufio.go:227 +0x3bf
redis-shake/common.waitRdbDump.func1(0x97d8e0, 0xc5c548cd20, 0xc5a7432240)
        /home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:179 +0x9f
created by redis-shake/common.waitRdbDump
        /home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:175 +0x71

**Comment by linyunnew** [comment]
使用版本 redis-shake-v2.0.0

**Comment by vinllen** [comment]
感谢反馈，能否贴一下完整的日志信息，最后报错这一部分的。

**Comment by linyunnew** [comment]
panic: runtime error: slice bounds out of range
goroutine 4121 [running]:
bufio.(*Reader).Read(0xc5c548cd20, 0xc5d69f6a99, 0x1, 0x1, 0x1, 0xc69cdcebd0, 0x2c)
/home/zhuzhao.cx/go/src/bufio/bufio.go:227 +0x3bf
redis-shake/common.waitRdbDump.func1(0x97d8e0, 0xc5c548cd20, 0xc5a7432240)
/home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:179 +0x9f
created by redis-shake/common.waitRdbDump
/home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:175 +0x71

最后报错部分的信息。

**Comment by linyunnew** [comment]
现在多次执行后错误必现。

**Comment by dwf3201** [comment]
使用版本redis-shake 2.0.0， redis 3.2.12  同步 本地cluster 到本地cluster 也报如下错误

# panic: runtime error: index out of range
goroutine 47 [running]:
vendor/github.com/vinllen/redis-go-cluster.(*Cluster).ChooseNodeWithCmd(0xc420e32000, 0x91cf15, 0x6, 0xc420160270, 0x1, 0x1, 0xc420d4b7e0, 0x0, 0x0)
        /home/zhuzhao.cx/RedisShake/src/vendor/github.com/vinllen/redis-go-cluster/cluster.go:193 +0x133c
vendor/github.com/vinllen/redis-go-cluster.(*Cluster).Do(0xc420e32000, 0x91cf15, 0x6, 0xc420160270, 0x1, 0x1, 0x10, 0x86ace0, 0x42bc01, 0xc420160270)
        /home/zhuzhao.cx/RedisShake/src/vendor/github.com/vinllen/redis-go-cluster/cluster.go:128 +0x81
redis-shake/common.(*ClusterConn).Do(0xc420da61e0, 0x91cf15, 0x6, 0xc420160270, 0x1, 0x1, 0x6fbdec, 0xc42015b020, 0x3, 0xc42002c210)
        /home/zhuzhao.cx/RedisShake/src/redis-shake/common/cluster.go:51 +0x6a
redis-shake/checkpoint.fetchCheckpoint(0xc420d81670, 0xf, 0x984460, 0xc420da61e0, 0x0, 0xc420156800, 0x1b, 0xc42012e280, 0x0, 0x0, ...)
        /home/zhuzhao.cx/RedisShake/src/redis-shake/checkpoint/checkpoint.go:75 +0x10b
redis-shake/checkpoint.LoadCheckpoint(0x0, 0xc420d81670, 0xf, 0xc42015aff0, 0x3, 0x3, 0xc4201833d3, 0x4, 0xc4201845d6, 0x20, ...)
        /home/zhuzhao.cx/RedisShake/src/redis-shake/checkpoint/checkpoint.go:35 +0x3c6
redis-shake/dbSync.(*DbSyncer).Sync(0xc420e24100)
        /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/dbSyncer.go:97 +0x39a
created by redis-shake.(*CmdSync).Main.func1
        /home/zhuzhao.cx/RedisShake/src/redis-shake/sync.go:99 +0x56

**Comment by dwf3201** [comment]
> goroutine 4121 [running]:
> bufio.(*Reader).Read(0xc5c548cd20, 0xc5d69f6a99, 0x1, 0x1, 0x1, 0xc69cdcebd0, 0x2c)
> /home/zhuzhao.cx/go/src/bufio/bufio.go:227 +0x3bf
> redis-shake/common.waitRdbDump.func1(0x97d8e0, 0xc5c548cd20, 0xc5a7432240)
> /home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:179 +0x9f
> created by redis-shake/common.waitRdbDump
> /home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:175 +0x71

升级到2.0.2我的问题就解决了，不知道你的会不会升级后解决

**Comment by tancehao** [comment]
我也遇到了这个问题，详细看了一下，是由于对bufio.Reader的并发读引起的。在sendPsyncCmd中创建的br同时在runIncrementalSync函数和waitRdbDump函数中被读取，导致的这个panic。

**Comment by ruanjl** [comment]
I have the same problem，my redis-shake version is 2.0.2 and there is stack:
panic: runtime error: slice bounds out of range
goroutine 358 [running]:
bufio.(*Reader).Read(0xc439e4f1a0, 0xc43a7fdfb7, 0x1, 0x1, 0x1, 0xc43d235b00, 0x80a)
        /home/zhuzhao.cx/go/src/bufio/bufio.go:227 +0x3bf
redis-shake/common.waitRdbDump.func1(0x97d9a0, 0xc439e4f1a0, 0xc4354262a0)
        /home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:179 +0x9f
created by redis-shake/common.waitRdbDump
        /home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:175 +0x71
panic: runtime error: slice bounds out of range
goroutine 207 [running]:
bufio.(*Reader).Read(0xc439e4f1a0, 0xc43d2ee000, 0x2000, 0x2000, 0x1865, 0x0, 0x0)
        /home/zhuzhao.cx/go/src/bufio/bufio.go:227 +0x3bf
redis-shake/dbSync.(*DbSyncer).pSyncPipeCopy(0xc420e9e200, 0x985360, 0xc420d76190, 0xc439e4f1a0, 0xc42006e480, 0x2303d29e272, 0x7f293259d4c0, 0xc420d76040, 0xc4354262a0, 0x0, ...)
        /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncBegin.go:159 +0x116
redis-shake/dbSync.(*DbSyncer).runIncrementalSync(0xc420e9e200, 0x985360, 0xc420d76190, 0xc439e4f1a0, 0xc42006e480, 0x1577, 0xc420dfe0fb, 0x28, 0x2303d29e272, 0xc420d8225f, ...)
        /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncBegin.go:101 +0x5c9
created by redis-shake/dbSync.(*DbSyncer).sendPSyncCmd
        /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncBegin.go:77 +0xa16

**Comment by ruanjl** [comment]
I have the same problem，my redis-shake version is 2.0.2 and there is stack:
`panic: runtime error: slice bounds out of range
goroutine 358 [running]:
bufio.(*Reader).Read(0xc439e4f1a0, 0xc43a7fdfb7, 0x1, 0x1, 0x1, 0xc43d235b00, 0x80a)
/home/zhuzhao.cx/go/src/bufio/bufio.go:227 +0x3bf
redis-shake/common.waitRdbDump.func1(0x97d9a0, 0xc439e4f1a0, 0xc4354262a0)
/home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:179 +0x9f
created by redis-shake/common.waitRdbDump
/home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:175 +0x71
panic: runtime error: slice bounds out of range
goroutine 207 [running]:
bufio.(*Reader).Read(0xc439e4f1a0, 0xc43d2ee000, 0x2000, 0x2000, 0x1865, 0x0, 0x0)
/home/zhuzhao.cx/go/src/bufio/bufio.go:227 +0x3bf
redis-shake/dbSync.(*DbSyncer).pSyncPipeCopy(0xc420e9e200, 0x985360, 0xc420d76190, 0xc439e4f1a0, 0xc42006e480, 0x2303d29e272, 0x7f293259d4c0, 0xc420d76040, 0xc4354262a0, 0x0, ...)
/home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncBegin.go:159 +0x116
redis-shake/dbSync.(*DbSyncer).runIncrementalSync(0xc420e9e200, 0x985360, 0xc420d76190, 0xc439e4f1a0, 0xc42006e480, 0x1577, 0xc420dfe0fb, 0x28, 0x2303d29e272, 0xc420d8225f, ...)
/home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncBegin.go:101 +0x5c9
created by redis-shake/dbSync.(*DbSyncer).sendPSyncCmd
/home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncBegin.go:77 +0xa16`

**Comment by ruanjl** [comment]
I have the same problem, my redis-shake veresion is 2.0.2 and there is error detail:
`panic: runtime error: slice bounds out of range`
`goroutine 358 [running]:`
`bufio.(*Reader).Read(0xc439e4f1a0, 0xc43a7fdfb7, 0x1, 0x1, 0x1, 0xc43d235b00, 0x80a)`
`/home/zhuzhao.cx/go/src/bufio/bufio.go:227 +0x3bf`
`redis-shake/common.waitRdbDump.func1(0x97d9a0, 0xc439e4f1a0, 0xc4354262a0)`
`/home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:179 +0x9f`
`created by redis-shake/common.waitRdbDump`
`/home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:175 +0x71`
`panic: runtime error: slice bounds out of range`
`goroutine 207 [running]:`
`bufio.(*Reader).Read(0xc439e4f1a0, 0xc43d2ee000, 0x2000, 0x2000, 0x1865, 0x0, 0x0)`
`/home/zhuzhao.cx/go/src/bufio/bufio.go:227 +0x3bf`
`redis-shake/dbSync.(*DbSyncer).pSyncPipeCopy(0xc420e9e200, 0x985360, 0xc420d76190, 0xc439e4f1a0, 0xc42006e480, `0x2303d29e272, 0x7f293259d4c0, 0xc420d76040, 0xc4354262a0, 0x0, ...)`
`/home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncBegin.go:159 +0x116`
`redis-shake/dbSync.(*DbSyncer).runIncrementalSync(0xc420e9e200, 0x985360, 0xc420d76190, 0xc439e4f1a0, 0xc42006e480, `0x1577, 0xc420dfe0fb, 0x28, 0x2303d29e272, 0xc420d8225f, ...)`
`/home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncBegin.go:101 +0x5c9`
`created by redis-shake/dbSync.(*DbSyncer).sendPSyncCmd`
`/home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncBegin.go:77 +0xa16`

**Comment by ruanjl** [comment]
I have the same problem, my redis-shake version is 2.0.2 and there is error detail:
>panic: runtime error: slice bounds out of range
 goroutine 358 [running]:
 bufio.(*Reader).Read(0xc439e4f1a0, 0xc43a7fdfb7, 0x1, 0x1, 0x1, 0xc43d235b00, 0x80a)
         /home/zhuzhao.cx/go/src/bufio/bufio.go:227 +0x3bf
 redis-shake/common.waitRdbDump.func1(0x97d9a0, 0xc439e4f1a0, 0xc4354262a0)
         /home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:179 +0x9f
 created by redis-shake/common.waitRdbDump
         /home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:175 +0x71
 panic: runtime error: slice bounds out of range
 goroutine 207 [running]:
 bufio.(*Reader).Read(0xc439e4f1a0, 0xc43d2ee000, 0x2000, 0x2000, 0x1865, 0x0, 0x0)
         /home/zhuzhao.cx/go/src/bufio/bufio.go:227 +0x3bf
 redis-shake/dbSync.(*DbSyncer).pSyncPipeCopy(0xc420e9e200, 0x985360, 0xc420d76190, 0xc439e4f1a0, 0xc42006e480, 0x2303d29e272, 0x7f293259d4c0, 0xc420d76040, 0xc4354262a0, 0x0, ...)
         /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncBegin.go:159 +0x116
 redis-shake/dbSync.(*DbSyncer).runIncrementalSync(0xc420e9e200, 0x985360, 0xc420d76190, 0xc439e4f1a0, 0xc42006e480, 0x1577, 0xc420dfe0fb, 0x28, 0x2303d29e272, 0xc420d8225f, ...)
         /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncBegin.go:101 +0x5c9
 created by redis-shake/dbSync.(*DbSyncer).sendPSyncCmd
         /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncBegin.go:77 +0xa16

**Comment by suxb201** [comment]
测试未遇到此类错误。
此问题较久远，可能已经修复，如果使用中仍有问题可以另开 issue。

**Comment by HeyInnf** [comment]
> 我也遇到了这个问题，详细看了一下，是由于对bufio.Reader的并发读引起的。在sendPsyncCmd中创建的br同时在runIncrementalSync函数和waitRdbDump函数中被读取，导致的这个panic。

请问最后解决了吗。怎么解决的
