### ISSUE TITLE
[PANIC] select command error

### ISSUE THREAD

**Issue by qiyihu** [aliyun/redis-shake#280]
From `Standalone` redis to `Twemproxy`

### ERROR
[PANIC] select command error
[error]: EOF
[stack]:
    1   /Users/qiyi.hu/development/projects/RedisShake/src/redis-shake/common/utils.go:297
            redis-shake/common.SelectDB
    0   /Users/qiyi.hu/development/projects/RedisShake/src/redis-shake/dbSync/syncRDB.go:49
            redis-shake/dbSync.(*DbSyncer).syncRDBFile.func1.1
        ... ...

### conf file：

conf.version = 1

id = redis-shake

log.file = /tmp/shake.log

log.level = info

pid_path =

system_profile = 9310

http_profile = 9320

parallel = 32

source.type = standalone

source.address = 192.168.X.X:30060

source.auth_type = auth

source.tls_enable = false

source.rdb.input = 

source.rdb.parallel = 0

source.rdb.special_cloud =

target.type = proxy

target.address = 192.168.X.X:30070

target.auth_type = auth
target.db = -1

target.tls_enable = false

target.rdb.output = local_dump

target.version = 0.4.1

fake_time =
key_exists = none

filter.db.whitelist =
filter.db.blacklist =

filter.key.whitelist =
filter.key.blacklist =

filter.slot =

filter.lua = true

big_key_threshold = 1

metric = true

metric.print_log = false

sender.size = 104857600

sender.count = 4095

sender.delay_channel_size = 65535

keep_alive = 0

scan.key_number = 50

scan.special_cloud =

scan.key_file =

qps = 200000

resume_from_break_point = false

replace_hash_tag = false

**Comment by qiyihu** [comment]
look like I found the issue. 
The `target.db = 0` for twemproxy. LOL

**Comment by vinllen** [comment]
这个原因是：twemproxy没办法接受select命令，而对于driver来说，没办法识别目的端到底是twemproxy还是仅仅普通的一个standalone，所以对于源端发送过来的select命令转发到目的端就出问题了。

**Comment by qiyihu** [comment]
是的， 所以如果是twemproxy的话 target.db  要设置成0。
