### ISSUE TITLE
get source redis version failed[ERR invalid node]

### ISSUE THREAD

**Issue by motoband** [aliyun/redis-shake#281]
get source redis version failed[ERR invalid node]
![image](https://user-images.githubusercontent.com/36153790/81281105-feecb100-908b-11ea-94ba-f95ce53c2418.png)

**Comment by vinllen** [comment]
For some redis proxy version, like codis, twemproxy, huawei cloud, we can't fetch the version information by `info server` command.
I'll consider supporting this by adding `source.version` field on the configuration later. Maybe on next version: 2.0.3.
