### ISSUE TITLE
阿里云redis全量同步报错

### ISSUE THREAD

**Issue by kevinWuqisheng** [aliyun/redis-shake#282]
阿里云Redis 4.0 社区版  同步到  阿里云Redis 4.0 社区版，全量同步的过程中，始终报如下错误：

2020/05/12 15:36:51 [INFO] DbSyncer[0] total = 285.68MB -     127.33MB [ 44%]  entry=500359
2020/05/12 15:36:52 [INFO] DbSyncer[0] total = 285.68MB -     127.86MB [ 44%]  entry=502458
2020/05/12 15:36:53 [PANIC] read error, please check source redis log or network
[error]: EOF
[stack]:
    1   /home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:915
            redis-shake/common.Iocopy
    0   /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncBegin.go:92
            redis-shake/dbSync.(*DbSyncer).runIncrementalSync

阿里云redis 无法设置参数  output-buffer-limit

版本：redis-shake-v2.0.0

**Comment by kevinWuqisheng** [comment]
调整并发线程，大概跑几分钟，或者10来分钟，全量同步就会中断
parallel = 64
parallel = 10

**Comment by kevinWuqisheng** [comment]
全量同步的问题已解决
阿里云Redis 无法设置参数output-buffer-limit
调高parallel 以及 在业务低峰期进行全量同步

**Comment by blueQiang** [comment]
我也出现了这个问题，特别是在源redis写高峰期的时候，很容易就报错。请问你是怎么解决的？
