### ISSUE TITLE
进行redis集群数据迁移时报错[error]:  Do failed[unknow type uint8]

### ISSUE THREAD

**Issue by angelleexy** [aliyun/redis-shake#284]
源redis集群及目标redis集群均为4主4从结构。版本均为5.0.3。执行数据迁移操作时报错。报错信息参见截图。
![image](https://user-images.githubusercontent.com/13584880/82308375-45c79880-99f4-11ea-8b74-839829c85722.png)

**Comment by Rockycc** [comment]
2.0.3版本对这个问题做了解决，更新一下
