### ISSUE TITLE
redis3.0.5 迁移到redis5.0CLUSTER 不成功

### ISSUE THREAD

**Issue by liuzanhub** [aliyun/redis-shake#287]
2020/06/12 23:27:10 [INFO] restore big hash key uInfo:5781 field count 9
2020/06/12 23:27:10 [PANIC] target key name is busy: lCode:14
[stack]:
    1   /home/zhuzhao.cx/RedisShake/src/redis-shake/common/utils.go:804
            redis-shake/common.RestoreRdbEntry
    0   /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncRDB.go:68
            redis-shake/dbSync.(*DbSyncer).syncRDBFile.func1.1

**Comment by jiuker** [comment]
rewrite = true
