### ISSUE TITLE
集群之间增量同步数据出错：

### ISSUE THREAD

**Issue by level077** [aliyun/redis-shake#290]
当前有A集群12主12从，版本3.2.6。单节点4100W+的key，rdb文件1.6G上下。
现在新建集群B，12主12从，版本5.0.8，数据从集群A实时同步到集群B中。
当某个(重试几次，不固定)Dbsyncer完成全量同步开始增量同步时，报下图错误，同时进程退出：
<img width="1117" alt="redis-shake-error" src="https://user-images.githubusercontent.com/1182409/86199076-baf9c200-bb8b-11ea-9292-76ed2b515508.png">

cluster keyslot 查了一下，错误中的key都是分布在节点边界slot上，比如节点的第一个或者最后一个slot。

没有用到事务，没有lua，没有bigkey，只是最简单的操作。可以往什么方向排查？

**Comment by baronwangr** [comment]
在迁移中，有过HA切换发生么？
