### ISSUE TITLE
大量数据写到源redis的时候出现这种情况，版本2.0.2。

### ISSUE THREAD

**Issue by blueQiang** [aliyun/redis-shake#291]
2020/07/11 01:02:38 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/07/11 01:02:39 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/07/11 01:02:39 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/07/11 01:02:39 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/07/11 01:02:39 [PANIC] decode redis resp failed
[error]: bad resp CRLF end
    5   /home/zhuzhao.cx/RedisShake/src/pkg/redis/decoder.go:169
            pkg/redis.(*Decoder).decodeBulkBytes
    4   /home/zhuzhao.cx/RedisShake/src/pkg/redis/decoder.go:87
            pkg/redis.(*Decoder).decodeResp
    3   /home/zhuzhao.cx/RedisShake/src/pkg/redis/decoder.go:189
            pkg/redis.(*Decoder).decodeArray
    2   /home/zhuzhao.cx/RedisShake/src/pkg/redis/decoder.go:91
            pkg/redis.(*Decoder).decodeResp
    1   /home/zhuzhao.cx/RedisShake/src/pkg/redis/decoder.go:38
            pkg/redis.MustDecodeOpt
    0   /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncIncrease.go:192
            redis-shake/dbSync.(*DbSyncer).parseSourceCommand
        ... ...
[stack]: 
    1   /home/zhuzhao.cx/RedisShake/src/pkg/redis/decoder.go:40
            pkg/redis.MustDecodeOpt
    0   /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncIncrease.go:192
            redis-shake/dbSync.(*DbSyncer).parseSourceCommand
        ... ...
[root@ycmspptsvr00

**Comment by blueQiang** [comment]
另外一台服务器日志是这样。
2020/07/11 04:04:41 [INFO] DbSyncer[2] sync:  +forwardCommands=2002   +filterCommands=4      +writeBytes=68208
2020/07/11 04:04:41 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/07/11 04:04:42 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/07/11 04:04:42 [ERROR] dbSyncer[2] send offset to source redis failed[write tcp 10.91.109.19:55732->10.86.16.144:6380: write: broken pipe]
[stack]: 
    0   /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncBegin.go:145
            redis-shake/dbSync.(*DbSyncer).pSyncPipeCopy.func1
        ... ...
2020/07/11 04:04:42 [INFO] input password is empty, skip auth address[10.86.16.144:6380] with type[auth].
2020/07/11 04:04:42 [INFO] DbSyncer[2] Event:SourceConnReopenSuccess	Id: redis-shake	offset = 17865402210
2020/07/11 04:04:42 [INFO] input password is empty, skip auth address[10.86.16.144:6380] with type[auth].
2020/07/11 04:04:42 [INFO] Event:FullSyncStart	Id:redis-shake	
2020/07/11 04:04:42 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/07/11 04:04:42 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/07/11 04:04:42 [ERROR] dbSyncer[0] send offset to source redis failed[write tcp 10.91.109.19:59832->10.86.16.142:6380: write: broken pipe]
[stack]: 
    0   /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncBegin.go:145
            redis-shake/dbSync.(*DbSyncer).pSyncPipeCopy.func1
        ... ...
2020/07/11 04:04:43 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/07/11 04:04:43 [INFO] input password is empty, skip auth address[10.86.16.142:6380] with type[auth].
2020/07/11 04:04:43 [INFO] DbSyncer[0] Event:SourceConnReopenSuccess	Id: redis-shake	offset = 17565606550
2020/07/11 04:04:43 [INFO] input password is empty, skip auth address[10.86.16.142:6380] with type[auth].
2020/07/11 04:04:43 [INFO] Event:FullSyncStart	Id:redis-shake	
2020/07/11 04:04:43 [WARN] DbSyncer[1] Event:GetFakeSlaveOffsetFail	Id:redis-shake	Warn:OffsetNotFoundInInfo
2020/07/11 04:04:43 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/07/11 04:04:43 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/07/11 04:04:44 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/07/11 04:04:44 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/07/11 04:04:44 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/07/11 04:04:44 [PANIC] decode redis resp failed
[error]: bad resp CRLF end
    5   /home/zhuzhao.cx/RedisShake/src/pkg/redis/decoder.go:169
            pkg/redis.(*Decoder).decodeBulkBytes
    4   /home/zhuzhao.cx/RedisShake/src/pkg/redis/decoder.go:87
            pkg/redis.(*Decoder).decodeResp
    3   /home/zhuzhao.cx/RedisShake/src/pkg/redis/decoder.go:189
            pkg/redis.(*Decoder).decodeArray
    2   /home/zhuzhao.cx/RedisShake/src/pkg/redis/decoder.go:91
            pkg/redis.(*Decoder).decodeResp
    1   /home/zhuzhao.cx/RedisShake/src/pkg/redis/decoder.go:38
            pkg/redis.MustDecodeOpt
    0   /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncIncrease.go:192
            redis-shake/dbSync.(*DbSyncer).parseSourceCommand
        ... ...
[stack]: 
    1   /home/zhuzhao.cx/RedisShake/src/pkg/redis/decoder.go:40
            pkg/redis.MustDecodeOpt
    0   /home/zhuzhao.cx/RedisShake/src/redis-shake/dbSync/syncIncrease.go:192
            redis-shake/dbSync.(*DbSyncer).parseSourceCommand
        ... ...

**Comment by BestQu** [comment]
有结果吗？然后服务重启了

**Comment by suxb201** [comment]
hi @BestQu @blueQiang 此 issue 时间有些久远了，还可以复现吗，能提供更多细节吗？

**Comment by Colstuwjx** [comment]
我也遇到这个问题，很是困扰。是否和 send psync ack 这里报错有关系？

```
send offset to source redis failed[write tcp 10.91.109.19:59832->10.86.16.142:6380: write: broken pipe]
```

**Comment by suxb201** [comment]
新版应该没这个问题了。
