### ISSUE TITLE
迁移时，出现EOF错误，read  error

### ISSUE THREAD

**Issue by jxqiuhan** [aliyun/redis-shake#293]

**Comment by vinllen** [comment]
@Rockycc 这个问题后面关注一下，出现过几次了，看看到底是不是网络层面的问题

**Comment by UsamiRenko97** [comment]
`[PANIC] read error, please check source redis log or network`
`[error]: EOF`
`[stack]: `
`    1   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/common/utils.go:930
            redis-shake/common.Iocopy`
`    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/syncBegin.go:92
            redis-shake/dbSync.(*DbSyncer).runIncrementalSync`
`        ... ...`

**Comment by suxb201** [comment]
@UsamiRenko97 hi 可以提供更多信息吗？源端 Redis log，redis-shake 运行时间，配置等。

**Comment by UsamiRenko97** [comment]
#redis-shake配置，版本v2.0.3，参考了issue里提的keep_alive参数由10改为了1，还是报错，source redis集群日志没有配找不到了，第一次22:11启动的redis-shake，22:16报错，第二次是23:15开始同步，23:22报错

conf.version = 1

id = redis-shake

log.file = /data/logs/redis-shake/redis-shake.log
log.level = info
pid_path = 
system_profile = 9310
http_profile = 9320

parallel = 32

source.type = cluster

source.address = slave@172.24.9.223:8101
source.password_raw =
source.auth_type = auth
source.tls_enable = false
source.rdb.input = local
source.rdb.parallel = 0
source.rdb.special_cloud = 

target.type = cluster
target.address = @172.29.0.47:8001
target.password_raw =
target.auth_type = auth
target.db = -1
target.tls_enable = false
target.rdb.output = local_dump
target.version =

fake_time =
key_exists = rewrite
filter.key.whitelist = mid_30000069__;mid30000052__;

filter.key.blacklist =
filter.slot =
filter.lua = false

big_key_threshold = 524288000


metric = true
metric.print_log = false

sender.size = 104857600
sender.count = 4095
sender.delay_channel_size = 65535

keep_alive = 1

scan.key_number = 100
scan.special_cloud =
scan.key_file =

qps = 100000

resume_from_break_point = false

replace_hash_tag = false

**Comment by UsamiRenko97** [comment]
redis-shake服务器配置是4C8G的，同步开启时，内存逐渐占满，占满之后，有时会报上述错然后redis-shake进程变为killed，有时不报错，redis-shake日志刷的逐渐变慢，然后停止，进程变为killed。有开启swap分区。

**Comment by UsamiRenko97** [comment]
#source redis配置
daemonize yes
pidfile "/var/run/redis.pid"

port 8001

tcp-backlog 511

timeout 300
tcp-keepalive 0


loglevel notice
logfile ""

databases 16
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes


dbfilename "dump.rdb"

dir "/data/redis/8001"


replica-serve-stale-data yes
replica-read-only yes
repl-diskless-sync no
repl-diskless-sync-delay 5
repl-disable-tcp-nodelay no
replica-priority 100

appendonly no
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no

auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes

lua-time-limit 5000

cluster-enabled yes

cluster-node-timeout 15000
slowlog-log-slower-than 10000
slowlog-max-len 1024

latency-monitor-threshold 0

notify-keyspace-events ""

hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-entries 512
list-max-ziplist-value 64
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
hll-sparse-max-bytes 3000
activerehashing yes


client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60

hz 10
aof-rewrite-incremental-fsync yes
repl-timeout 300
repl-backlog-size 128mb
repl-backlog-ttl 0
maxmemory 10gb
maxmemory-policy allkeys-lru

protected-mode no
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
replica-lazy-flush yes

**Comment by suxb201** [comment]
@UsamiRenko97 感谢提供的日志，我在本地没复现出类似问题，看代码也没看出问题。请问方便再提供下在 redis-shake 报 EOF 错误时 source redis 的 log 吗？

**Comment by suxb201** [comment]
@UsamiRenko97 此外，redis-shake 日志有全一些的版本吗？比如在EOF picnic 之前，redis-shake 的日志是什么样子的？

**Comment by suxb201** [comment]
源端写入流量大吗？源端数据量有多大？一个可能的原因是 output-buffer 太小了，被打满后 kill，推荐设置为 512mb 0 0
```
client-output-buffer-limit replica 256mb 64mb 60
```

**Comment by UsamiRenko97** [comment]
报EOF panic之前都是正常的同步日志，现在怀疑是source redis的client-output-buffer-limit slave默认设的256MB 64MB 60缓冲区不够了，打算今晚调大了再试试。
2021/09/02 22:15:58 [INFO] DbSyncer[15] total = 2.86GB -     613.49MB [ 20%]  entry=4278339       filter=3717159     
2021/09/02 22:15:58 [INFO] DbSyncer[1] total = 1.53GB -     847.50MB [ 54%]  entry=6673067       filter=5796419     
2021/09/02 22:15:58 [INFO] DbSyncer[13] total = 1.53GB -     695.82MB [ 44%]  entry=5467902       filter=4750574     
2021/09/02 22:15:58 [INFO] DbSyncer[5] total = 1.53GB -     641.16MB [ 40%]  entry=5005016       filter=4347789     
2021/09/02 22:15:58 [INFO] DbSyncer[9] total = 1.55GB -     637.93MB [ 40%]  entry=4989990       filter=4335911     
2021/09/02 22:15:58 [INFO] DbSyncer[6] total = 1.53GB -     657.10MB [ 41%]  entry=5130541       filter=4456658     
2021/09/02 22:15:58 [INFO] DbSyncer[14] total = 1.55GB -     717.84MB [ 45%]  entry=5497861       filter=4776811     
2021/09/02 22:15:58 [INFO] DbSyncer[12] total = 1.60GB -     643.41MB [ 39%]  entry=5011052       filter=4353397     
2021/09/02 22:15:58 [INFO] DbSyncer[8] total = 1.53GB -     632.93MB [ 40%]  entry=4952230       filter=4301186     
2021/09/02 22:15:58 [INFO] DbSyncer[7] total = 1.55GB -     710.40MB [ 44%]  entry=5537804       filter=4811999     
2021/09/02 22:15:58 [INFO] DbSyncer[11] total = 1.53GB -     698.69MB [ 44%]  entry=5456412       filter=4742128     
2021/09/02 22:15:58 [INFO] DbSyncer[3] total = 1.53GB -     654.45MB [ 41%]  entry=5121980       filter=4450871     
2021/09/02 22:15:58 [INFO] DbSyncer[2] total = 1.53GB -     622.00MB [ 39%]  entry=4890178       filter=4248152     
2021/09/02 22:15:58 [INFO] DbSyncer[4] total = 1.55GB -     609.62MB [ 38%]  entry=4717119       filter=4097201     
2021/09/02 22:15:59 [INFO] DbSyncer[0] total = 1.60GB -     782.40MB [ 47%]  entry=5594915       filter=4861415     
2021/09/02 22:15:59 [INFO] DbSyncer[15] total = 2.86GB -     616.79MB [ 21%]  entry=4303611       filter=3739123     
2021/09/02 22:15:59 [INFO] DbSyncer[10] total = 2.86GB -       1.77GB [ 62%]  entry=4087377       filter=3550319     
2021/09/02 22:15:59 [INFO] DbSyncer[1] total = 1.53GB -     850.53MB [ 54%]  entry=6697356       filter=5817504     
2021/09/02 22:15:59 [INFO] DbSyncer[13] total = 1.53GB -     698.86MB [ 44%]  entry=5492463       filter=4771968     
2021/09/02 22:15:59 [INFO] DbSyncer[5] total = 1.53GB -     644.12MB [ 40%]  entry=5028586       filter=4368349     
2021/09/02 22:15:59 [INFO] DbSyncer[9] total = 1.55GB -     640.90MB [ 40%]  entry=5013384       filter=4356216     
2021/09/02 22:15:59 [INFO] DbSyncer[6] total = 1.53GB -     659.92MB [ 42%]  entry=5153478       filter=4476515     
2021/09/02 22:15:59 [INFO] DbSyncer[14] total = 1.55GB -     720.89MB [ 45%]  entry=5521327       filter=4797157     
2021/09/02 22:15:59 [INFO] DbSyncer[12] total = 1.60GB -     646.42MB [ 39%]  entry=5035648       filter=4374898     
2021/09/02 22:15:59 [INFO] DbSyncer[8] total = 1.53GB -     635.91MB [ 40%]  entry=4975517       filter=4321410     
2021/09/02 22:15:59 [INFO] DbSyncer[7] total = 1.55GB -     713.39MB [ 45%]  entry=5561380       filter=4832425     
2021/09/02 22:15:59 [INFO] DbSyncer[11] total = 1.53GB -     701.58MB [ 44%]  entry=5479766       filter=4762342     
2021/09/02 22:15:59 [INFO] DbSyncer[3] total = 1.53GB -     657.69MB [ 41%]  entry=5145756       filter=4471590     
2021/09/02 22:15:59 [INFO] DbSyncer[4] total = 1.55GB -     612.50MB [ 38%]  entry=4740192       filter=4117285     
2021/09/02 22:15:59 [INFO] DbSyncer[2] total = 1.53GB -     624.71MB [ 39%]  entry=4912522       filter=4267568     
2021/09/02 22:16:00 [INFO] DbSyncer[0] total = 1.60GB -     785.63MB [ 47%]  entry=5620892       filter=4884005     
2021/09/02 22:16:00 [PANIC] read error, please check source redis log or network
[error]: EOF
[stack]: 
    1   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/common/utils.go:930
            redis-shake/common.Iocopy
    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/syncBegin.go:92
            redis-shake/dbSync.(*DbSyncer).runIncrementalSync
        ... ...

**Comment by UsamiRenko97** [comment]
非常感谢您的指导，现在问题已解决。使用过程中遇到的两个问题：
1.报PANIC EOF的问题。原因是client-output-buffer-limit太小了，改成512mb 0 0之后问题解决。
2.redis-shake进程被kill，日志中没有异常。原因是redis-shake进程占用内存过多，被OOM Killer干掉了。
最后再次感谢您的指导，对我帮助很大。
