### ISSUE TITLE
sync 同步报错

### ISSUE THREAD

**Issue by Sugar-coated-bullet** [aliyun/redis-shake#297]
源redis版本：阿里云redis 5.0主从版
目标redis版本：IDC自建redis4.0单点

全量同步后未保持增量同步，日志报错如下：
![图片](https://user-images.githubusercontent.com/35293253/89867779-45e6c700-dbe4-11ea-8c1c-01c288453305.png)

2020/08/11 14:16:47 [INFO] DbSyncer[0] total = 277.87MB -     277.87MB [100%]  entry=2009551     
2020/08/11 14:16:47 [INFO] DbSyncer[0] sync rdb done
2020/08/11 14:16:47 [INFO] DbSyncer[0] FlushEvent:IncrSyncStart Id:redis-shake
2020/08/11 14:16:47 [PANIC] DbSyncer[0] Event:ErrorReply        Id:redis-shake  Command: [unknown]      Error: ERR unknown command `ars`, with args beginning with: `B`, `UNLINK`, `ms/room/room_lc109517882-LCOMDP_16990110419234`, 
[stack]: 
    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/syncIncrease.go:120
            redis-shake/dbSync.(*DbSyncer).receiveTargetReply
        ... ...

配置文件修改项（未贴出的都是默认配置）：
parallel = 64
source.type = standalone
source.address = ***.redis.rds.aliyuncs.com:6379
source.password_raw = sync_test:***passwd***
target.type = standalone
target.address = ***ip***:6379
target.password_raw = ***passwd***
target.db = -1
rewrite = true

**Comment by Rockycc** [comment]
你这里源端是redis企业版目的端是社区版吧，redis企业版和社区版的Binlog不一样，所以不支持增量同步。如果源端和目的端都是企业版redis，可以使用内部的redis-shake进行全量和增量同步

**Comment by qD6HrDvBtUuE9nH** [comment]
这个问题解决了嘛，我这边两边都是社区版，增量同步的时候还是报这个错
