### ISSUE TITLE
使用restore恢复，无报错卡死

### ISSUE THREAD

**Issue by KakuCicada** [aliyun/redis-shake#300]
版本：2.0.3
使用restore模式恢复下载到本地的rdb文件(来源自阿里云集群版redis实例)，rdb文件1.5G的总量
在运行restore后，大概10分钟显示数据已经恢复完成，redis-cli连redis服务器后，key的数量基本一致
但是redis-shake进程依旧在运行中，日志最后一条显示`[INFO] Enabled http stats, set status (incr), and wait forever.`
持续十几个小时，依旧没有停掉进程

**Comment by Rockycc** [comment]
restore模式下，[INFO] Enabled http stats, set status (incr), and wait forever.该条日志表示RDB文件已经同步完成，在同步完成之后需要手动停掉进程，这里一直block是因为metric的原因。如果希望RDB同步完成后程序直接退出，可以配置http_profile=-1
