### ISSUE TITLE
sync同步出错

### ISSUE THREAD

**Issue by rayi27** [aliyun/redis-shake#301]
两端都是阿里云redis 

版本： Redis 5.0 企业版
--

实例规格： 1G主从性能增强版
--
同步报错：
2020/09/04 10:37:29 [INFO] Aux information key:lua value:local tokens_key = KEYS[1]
local timestamp_key = KEYS[2]
--redis.log(redis.LOG_WARNING, "tokens_key " .. tokens_key)

local rate = tonumber(ARGV[1])
local capacity = tonumber(ARGV[2])
local now = tonumber(ARGV[3])
local requested = tonumber(ARGV[4])

local fill_time = capacity/rate
local ttl = math.floor(fill_time*2)

--redis.log(redis.LOG_WARNING, "rate " .. ARGV[1])
--redis.log(redis.LOG_WARNING, "capacity " .. ARGV[2])
--redis.log(redis.LOG_WARNING, "now " .. ARGV[3])
--redis.log(redis.LOG_WARNING, "requested " .. ARGV[4])
--redis.log(redis.LOG_WARNING, "filltime " .. fill_time)
--redis.log(redis.LOG_WARNING, "ttl " .. ttl)

local last_tokens = tonumber(redis.call("get", tokens_key))
if last_tokens == nil then
  last_tokens = capacity
end
--redis.log(redis.LOG_WARNING, "last_tokens " .. last_tokens)

local last_refreshed = tonumber(redis.call("get", timestamp_key))
if last_refreshed == nil then
  last_refreshed = 0
end
--redis.log(redis.LOG_WARNING, "last_refreshed " .. last_refreshed)

local delta = math.max(0, now-last_refreshed)
local filled_tokens = math.min(capacity, last_tokens+(delta*rate))
local allowed = filled_tokens >= requested
local new_tokens = filled_tokens
local allowed_num = 0
if allowed then
  new_tokens = filled_tokens - requested
  allowed_num = 1
end

--redis.log(redis.LOG_WARNING, "delta " .. delta)
--redis.log(redis.LOG_WARNING, "filled_tokens " .. filled_tokens)
--redis.log(redis.LOG_WARNING, "allowed_num " .. allowed_num)
--redis.log(redis.LOG_WARNING, "new_tokens " .. new_tokens)

redis.call("setex", tokens_key, ttl, new_tokens)
redis.call("setex", timestamp_key, ttl, now)

return { allowed_num, new_tokens }
2020/09/04 10:37:29 [INFO] DbSyncer[0] total = 48.71MB -      48.71MB [100%]  entry=116548
2020/09/04 10:37:29 [INFO] DbSyncer[0] sync rdb done
2020/09/04 10:37:29 [INFO] DbSyncer[0] FlushEvent:IncrSyncStart	Id:redis-shake
2020/09/04 10:37:30 [PANIC] DbSyncer[0] Event:ErrorReply	Id:redis-shake	Command: [unknown]	Error: ERR BLOG ERROR Yellow to master
[stack]:
    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/syncIncrease.go:120
            redis-shake/dbSync.(*DbSyncer).receiveTargetReply
        ... ...

**Comment by Rockycc** [comment]
开源redis-shake不能用于企业版redis同步，请联系相关技术人员或者使用DTS。
