### ISSUE TITLE
dump 提示checksum failed

### ISSUE THREAD

**Issue by byronjxb** [aliyun/redis-shake#303]
源redis：AWS ElastiCache 5.0.6
redis-shake-v2.0.3

背景：执行dump备份ElastiCache提示“[WARN] fetch source rdb[xxxxx.amazonaws.com:6379] checksum failed[ERR unknown command `config`, with args beginning with: `get`, `rdbchecksum`, ], ignore”
![image](https://user-images.githubusercontent.com/21222280/92377089-2fc21d00-f136-11ea-8eca-279379058eb3.png)

通过在redis里执行 CONFIG GET rdbchecksun 提示一些错误信息，估计aws把这些命令阉割掉了，在FAQ里查看需要设置参数为YES，但目前没有设置。如果不开启rdbchecksun 是否无法使用redis-shake所有功能？？

**Comment by byronjxb** [comment]
aws那边提示rdbchecksun 是关闭的，也无法开启。发现使用rump方式是可以的，但也会提示checksum failed ，这个会影响同步吗？？
![image](https://user-images.githubusercontent.com/21222280/92561423-c6155080-f2a6-11ea-9646-4323e9f37474.png)

**Comment by Rockycc** [comment]
不影响同步，忽略好了
