### ISSUE TITLE
[WARN] available channel size[1520] less than current returned batch size[1729]

### ISSUE THREAD

**Issue by iushas** [aliyun/redis-shake#304]
请问下这个是什么错，线上同步时，好像导致了数据同步丢失

**Comment by Rockycc** [comment]
确定数据丢失了吗？ warn警告不是出错，正常同步完成应该不会造成数据丢失

**Comment by iushas** [comment]
确实丢失了， 日志里面没看到报错信息，只有这些warning。 现在这个问题不确定，我们都不敢再生产环境用了，还请帮忙能确认下

**Comment by iushas** [comment]
源redis和目的redis都是15个分片的cluster， 我们怀疑是源节点qps高，导致同步数据丢失

**Comment by Rockycc** [comment]
你好，在发送命令接收回复都使用的是通道机制，即使available channel size < batch size，可能会阻塞一下，但是不会丢数据。您可以再尝试一下。

**Comment by suxb201** [comment]
@Rockycc 但是通道会阻塞，导致程序卡死在这里。好像没有异步消费的逻辑？
