### ISSUE TITLE
迁移过程中出现target key name is busy: SHOW_OPER_1120011639

### ISSUE THREAD

**Issue by spirit-unpredictable** [aliyun/redis-shake#307]
![image](https://user-images.githubusercontent.com/43667484/94335124-efa2db80-000b-11eb-8a4d-2b527de7f724.png)

**Comment by yy951352631** [comment]
check the file redis-shake.conf,change parameter key_exists from none to rewrite or ignore ,it will rewrite the repeat keys or just skip them.

**Comment by Salt-Baked-Chicken-wings** [comment]
good
