### ISSUE TITLE
在集群模式下同步数据是否根本就不支持断点续传？

### ISSUE THREAD

**Issue by tancehao** [aliyun/redis-shake#310]
经抓包查看，在开启了断点续传选项时，redis-shake发往目标节点的批量命令并未被包裹在redis事务中。

![47FFFB89-E1B5-4096-83A3-B8FCE3DA074E](https://user-images.githubusercontent.com/20390579/95870161-c5d50d00-0d9e-11eb-80b4-a71035763d7d.png)

查看源代码，发现在src/redis-shake/common/cluster.go文件中，ClusterConn对象的Send方法中，调用了cc.batcher.Put方法，在put方法内，首先在第一行调用了batch.cluster.ChooseNodeWithCmd方法，在其内部，当发现命令是MULTI或者EXEC时，不会为node赋值，因此ChooseNodeWithCmd函数返回的node为nil，继而回到Batch.Put方法后第5行判定结果为真，直接返回了，未将命令push到batch.batches中，因此最后flush的命令未被包裹在事务内。

![1602597130125](https://user-images.githubusercontent.com/20390579/95869991-8efef700-0d9e-11eb-8edd-27ee5fac02cc.jpg)

![1602597265528](https://user-images.githubusercontent.com/20390579/95870098-b35ad380-0d9e-11eb-92b0-4b858d146c1c.jpg)

**Comment by suxb201** [comment]
Redis Cluster 不支持事务（虽然 go-redis- cluster 里面简单处理了下事务）：https://github.com/wuxibin89/redis-go-cluster/blob/222d81891f1d3fa7cf8b5655020352c3e5b4ec0f/README.md

**Comment by suxb201** [comment]
此外明确下此 bug 与断点续传没有关系。 @tancehao
