### ISSUE TITLE
redis4.0主从同步到5.0cluster报错无效命令？

### ISSUE THREAD

**Issue by zhengbucuo** [aliyun/redis-shake#311]
2020/10/14 11:33:45 [INFO] DbSyncer[0] starts syncing data from 10.107.48.51:6379 to [10.207.0.5:6379 10.207.0.15:6379 10.207.0.14:6379] with http[9321], enableResumeFromBreakPoint[false], slot boundary[-1, -1]
2020/10/14 11:33:45 [INFO] DbSyncer[0] psync connect '10.107.48.51:6379' with auth type[auth] OK!
2020/10/14 11:33:45 [INFO] DbSyncer[0] psync send listening port[9320] OK!
2020/10/14 11:33:45 [INFO] DbSyncer[0] try to send 'psync' command: run-id[?], offset[-1]
2020/10/14 11:33:45 [PANIC] invalid psync response, continue, ERR unknown command ' psync '
[stack]: 
    2   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/common/utils.go:250
            redis-shake/common.SendPSyncContinue
    1   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/syncBegin.go:50
            redis-shake/dbSync.(*DbSyncer).sendPSyncCmd
    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/dbSyncer.go:111
            redis-shake/dbSync.(*DbSyncer).Sync
        ... ...

**Comment by bangbangzheng** [comment]
配置如下
root@xx:/opt/redis-shake-v2.0.3# grep -v "#" redis-shake.conf

conf.version = 1
id = redis-shake

log.file =
log.level = info
pid_path = 

system_profile = 9310
http_profile = 9320

parallel = 64

source.type = standalone
source.address = 10.107.48.51:6379
source.password_raw = passwd
source.auth_type = auth
source.tls_enable = false
source.rdb.input = local
source.rdb.parallel = 0
source.rdb.special_cloud = 

target.type = cluster
target.address = 10.207.0.5:6379;10.207.0.15:6379;10.207.0.14:6379
target.password_raw = passwd
target.auth_type = auth
target.db = -1
target.tls_enable = false
target.rdb.output = local_dump
target.version = 5.0

fake_time =

key_exists = rewrite

filter.db.whitelist =
filter.db.blacklist =
filter.key.whitelist =
filter.key.blacklist =
filter.slot =
filter.lua = false

big_key_threshold = 524288000

metric = true
metric.print_log = false

sender.size = 104857600
sender.count = 4095
sender.delay_channel_size = 65535

keep_alive = 0

scan.key_number = 50
scan.special_cloud =
scan.key_file =

qps = 200000

resume_from_break_point = false


replace_hash_tag = false
