### ISSUE TITLE
codis集群迁移到codis集群，只能同一个分组

### ISSUE THREAD

**Issue by wenminglei** [aliyun/redis-shake#312]
您好，以下是我的问题
源端是codis集群，目的端也是codis集群。codis版本elease3.2
source.type = cluster
source.address = xxx:xx;xxx:xx   两个分组的从节点地址

target.type = proxy
target.address = xxx:19000
最终显示，只同步了一个分组。

**Comment by baronwangr** [comment]
source.type 不要配cluster，把standalone的一个一个地址配上就好了。
