### ISSUE TITLE
增量同步报错[error]: expect Array, but got <*redis.Error>

### ISSUE THREAD

**Issue by zhengbucuo** [aliyun/redis-shake#313]
2020/10/14 17:11:05 [WARN] DbSyncer[0] Event:GetFakeSlaveOffsetFail     Id:redis-shake  Warn:OffsetNotFoundInInfo
2020/10/14 17:11:06 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/10/14 17:11:07 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/10/14 17:11:08 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/10/14 17:11:09 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/10/14 17:11:10 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/10/14 17:11:11 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/10/14 17:11:12 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/10/14 17:11:13 [INFO] DbSyncer[0] sync:  +forwardCommands=1      +filterCommands=0      +writeBytes=4
2020/10/14 17:11:14 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/10/14 17:11:15 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/10/14 17:11:15 [WARN] DbSyncer[0] Event:GetFakeSlaveOffsetFail     Id:redis-shake  Warn:OffsetNotFoundInInfo
2020/10/14 17:11:16 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/10/14 17:11:17 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/10/14 17:11:18 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/10/14 17:11:19 [PANIC] DbSyncer[0] parse command arguments failed[expect Array, but got <*redis.Error>]
[error]: expect Array, but got <*redis.Error>
    2   /Users/tongyao.lty/Work/RedisShake/src/pkg/redis/resp.go:165
            pkg/redis.AsArray
    1   /Users/tongyao.lty/Work/RedisShake/src/pkg/redis/handler.go:88
            pkg/redis.ParseArgs
    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/syncIncrease.go:184
            redis-shake/dbSync.(*DbSyncer).parseSourceCommand
        ... ...
[stack]: 
    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/syncIncrease.go:185
            redis-shake/dbSync.(*DbSyncer).parseSourceCommand
        ... ...

**Comment by isoleo** [comment]
怎么解决的呢？

**Comment by suxb201** [comment]
hi @isoleo @bangbangzheng 看样子是 master 向 slave 发送了奇怪格式的数据。你们后续还遇到过此类错误吗？有无办法复现？或者是否了解发生错误时 master 上执行的命令？
