### ISSUE TITLE
I try used sync to migrate，but it failed，rump is ok.

### ISSUE THREAD

**Issue by yangshuming0** [aliyun/redis-shake#314]
2020/10/28 08:43:47 [INFO] DbSyncer[0] try to send 'psync' command: run-id[?], offset[-1]
2020/10/28 08:43:47 [INFO] DbSyncer[1] try to send 'psync' command: run-id[?], offset[-1]
2020/10/28 08:43:47 [PANIC] invalid psync response, continue, ERR unknown command `psync`, with args beginning with: `?`, `-1`,

**Comment by baronwangr** [comment]
Problem is that the source redis(or other cloud based redis system) is not supporting the PSYNC protocol.
There're two solutions.
1. check if the PSYNC protocol can be enabled at the source redis
2. or else you can use the 'rump' mode of redisshake; please note that 'rump' mode can't gives you a stable replication stream, so the source should be keep readonly if everything need copied.
