### ISSUE TITLE
哨兵同步问题

### ISSUE THREAD

**Issue by tianyangyang427** [aliyun/redis-shake#316]
配置如下:
conf.version = 1

id = redis-shake-sentinel

log.file =/data/redis/redis-shake/redis-shake-sentinel.log

pid_path =/data/redis/redis-shake

source.type = sentinel
source.address = shopmaster:slave@192.168.10.109:26359;192.168.10.109:26369;192.168.10.109:26379
source.password_raw = shop@leadeon.cn
source.auth_type = auth

target.type = sentinel
target.address = mymaster:master@192.168.10.110:26359;192.168.10.110:26369;192.168.10.110:26379
target.password_raw = dbbasic@leadeon.cn
target.auth_type = auth

当源端选择从slave拉去数据，在源端主从切换过程中，同步进程会断开，查看日志显示无法获取从节点；

**Comment by jacobeYang** [comment]
同问，哨兵模式，主从切换后，redis-shake会退出

**Comment by baronwangr** [comment]
目前不支持sentinel模式和切换。
