### ISSUE TITLE
增量同步时run ChooseNodeWithCmd failed出错

### ISSUE THREAD

**Issue by level077** [aliyun/redis-shake#320]
两组正常长时间同步中的redis集群同步出错，重启后，都在开始增量同步时run ChooseNodeWithCmd failed，应该都是和replconf [GETACK *]相关，后面的key的slot和前面的replconf GETACK * 这条cmd不在同一个node上。

集群之间的slots分布一致，业务没有用到事务。shake 2.0.2，2.0.3版本都一样的报错，有什么排查方向？

**Comment by suxb201** [comment]
有更详细的错误信息吗？

**Comment by 3tem** [comment]
我也遇到同样问题：
Id:redis-shake  Error:run ChooseNodeWithCmd failed[transaction command[replconf] key[GETACK] not hashed in the same node: current[10.100.64.142:6379], previous[10.102.77.4:6379]]
[stack]:
    1   github.com/alibaba/RedisShake/redis-shake/dbSync/syncIncrease.go:321
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).sendTargetCommand.func1
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/syncIncrease.go:391
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).sendTargetCommand

**Comment by level077** [comment]
我遇到的问题是因为用到了redisson分布式锁的功能导致的。当时解决的办法是在shake中增加了忽略replconf相关的操作

**Comment by suxb201** [comment]
@level077 感谢反馈。
可以过滤掉 replconf 命令，使用此 pr 中的新增选项：https://github.com/alibaba/RedisShake/pull/385
