### ISSUE TITLE
源端有数据不会同步到目标

### ISSUE THREAD

**Issue by Brightest08** [aliyun/redis-shake#324]
正常情况下源和目标数据同步是一致的，当人为或发生意外导致目标数据丢失，但是源的数据还存在，当再次执行sadd或hset时不会同步数据到目标。

举个例子：
1、在源端添加一个set类型的key，成员是11,22
192.168.1.1:6379> sadd test 11 22
(integer) 2
192.168.1.1:6379> SMEMBERS test
1) "11"
2) "22"
检查目标数据正常
127.0.0.1:6379> SMEMBERS test
1) "11"
2) "22"

2、在目标端执行删除成员操作
127.0.0.1:6379> SREM test 11
(integer) 1

3、再在源执行添加成员操作
172.31.7.123:6380> sadd test 11
(integer) 0  返回值为0

4、检查源端数据未同步过来
127.0.0.1:6379> SMEMBERS test
1) "22"

**Comment by dbabao** [comment]
检查下配置文件中key_exists模式设置的值

**Comment by suxb201** [comment]
https://github.com/redis/redis/blob/1221f7cd5eea8877a3df766f5c0a67255a894295/src/server.c#L3805

在源端 `sadd test 11` 不会修改数据，所以不会向 slave 传播。
