### ISSUE TITLE
send offset to source redis failed

### ISSUE THREAD

**Issue by BestQu** [aliyun/redis-shake#328]
./redis-benchmark -h x -p x -t set -r 1000000 -n 1000000 -d 3000
使用redis-benchmark测试 当-d超过2000时报错了

2021/01/07 17:27:06 [ERROR] dbSyncer[2] send offset to source redis failed[write tcp x.xx.x.xx:12419->x.x.x.x:7000: write: broken pipe]
[stack]: 
    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/syncBegin.go:145
            redis-shake/dbSync.(*DbSyncer).pSyncPipeCopy.func1
        ... ...
2021/01/07 17:27:07 [PANIC] decode redis resp failed
[error]: bad resp CRLF end
    5   /Users/tongyao.lty/Work/RedisShake/src/pkg/redis/decoder.go:169
            pkg/redis.(*Decoder).decodeBulkBytes
    4   /Users/tongyao.lty/Work/RedisShake/src/pkg/redis/decoder.go:87
            pkg/redis.(*Decoder).decodeResp
    3   /Users/tongyao.lty/Work/RedisShake/src/pkg/redis/decoder.go:189
            pkg/redis.(*Decoder).decodeArray
    2   /Users/tongyao.lty/Work/RedisShake/src/pkg/redis/decoder.go:91
            pkg/redis.(*Decoder).decodeResp
    1   /Users/tongyao.lty/Work/RedisShake/src/pkg/redis/decoder.go:38
            pkg/redis.MustDecodeOpt
    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/syncIncrease.go:182
            redis-shake/dbSync.(*DbSyncer).parseSourceCommand
        ... ...
[stack]: 
    1   /Users/tongyao.lty/Work/RedisShake/src/pkg/redis/decoder.go:40
            pkg/redis.MustDecodeOpt
    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/syncIncrease.go:182
            redis-shake/dbSync.(*DbSyncer).parseSourceCommand
        ... ...

**Comment by baronwangr** [comment]
检查源端负载情况。检查redis.log是否有断链接的logging
