### ISSUE TITLE
集群到集群的同步，全量阶段出现invalid sync response

### ISSUE THREAD

**Issue by Emma-uestc** [aliyun/redis-shake#331]
全量同步最后出现无效的响应字符，日志信息的开始和结束部分如下
` [PANIC] invalid sync response, rsp = '
XXX:XXXX-NULL�@�@��`  

`[stack]: 
    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/common/utils.go:192
            redis-shake/common.waitRdbDump.func1`  
乱码部分是key的一部分

**Comment by mansoncui** [comment]
集群到集群同步，你这边解决了吗？我报下面错误：
2021/03/30 13:39:48 [INFO] dbSyncer[5] Event:IncrSyncStart      Id:redis-shake
2021/03/30 13:39:48 [PANIC] dbSyncer[2] Event:SendToTargetFail  Id:redis-shake  Error:Put: no key found in args
[stack]: 
    0   /home/zhuzhao.cx/redis-shake/src/redis-shake/sync.go:675
            redis-shake.(*dbSyncer).syncCommand.func4
        ... ...

**Comment by baronwangr** [comment]
请使用最新版本的shake
