### ISSUE TITLE
单机同步到集群报错read sync response=''

### ISSUE THREAD

**Issue by caoxingsheng** [aliyun/redis-shake#332]
1、单机版本：redis_version:3.2.12
2、集群版本：redis_version:5.0.10
3、配置文件：
source.type = standalone
source.address = 192.168.221.111:6679
source.password_raw = 123456

target.type = cluster
target.address = 10.3.4.1:6666;10.3.4.2:6667;10.3.4.3:6668
target.password_raw = 123456
4、报错信息：
![image](https://user-images.githubusercontent.com/27294643/105929146-ec832f00-6081-11eb-894b-1c416edb7939.png)

**Comment by baronwangr** [comment]
看下源上的log，大概率是把复制链接给close了

**Comment by 1342843039** [comment]
我也是，该咋解决啊

**Comment by suxb201** [comment]
@1342843039  看下源 Redis 上的 log，是不是爆 buffer 了

**Comment by suxb201** [comment]
可以试试 v3 了，没有这些问题：https://github.com/alibaba/RedisShake/tree/v3
