### ISSUE TITLE
[-ERR unknown command 'REPLCONF'] 错误

### ISSUE THREAD

**Issue by samwitiwiki** [aliyun/redis-shake#333]
redis的版本源和目的机器都是4.0.11，在windows环境下报如下错误：
2021/01/28 09:41:25 [PANIC] repl listening-port failed[-ERR unknown command 'REPLCONF']
[stack]: 
    2   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/common/utils.go:139
            redis-shake/common.SendPSyncListeningPort
    1   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/syncBegin.go:40
            redis-shake/dbSync.(*DbSyncer).sendPSyncCmd
    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/dbSyncer.go:111
            redis-shake/dbSync.(*DbSyncer).Sync

**Comment by baronwangr** [comment]
源端不支持psync协议
