### ISSUE TITLE
redis-shake 目前支持redis6.0吗？

### ISSUE THREAD

**Issue by 454622535** [aliyun/redis-shake#335]

**Comment by 454622535** [comment]
当前redis-shake 版本v2.0.3

**Comment by jiaminxia** [comment]
同问，支持6.0以上吗

**Comment by yuddpky** [comment]
同问，支持6.0以上吗

**Comment by zkfopen** [comment]
请问，现在支持6.2.4吗

**Comment by baronwangr** [comment]
支持的。

**Comment by jiaminxia** [comment]
> 支持的。

那为什么readme里写着Redis version from 2.x to 5.0 ？是因为还有bug吗？

**Comment by ReasonDuan** [comment]
> > 支持的。
> 
> 那为什么readme里写着Redis version from 2.x to 5.0 ？是因为还有bug吗？

那估计是没有更新的原因

**Comment by baronwangr** [comment]
没有更新。sorry啊。最近会更新下

**Comment by suxb201** [comment]
文档已更新。 #353
