### ISSUE TITLE
怎么在目标端加上key前缀

### ISSUE THREAD

**Issue by fulldog** [aliyun/redis-shake#338]

**Comment by michael-liumh** [comment]
不是有filter.key.whitelist参数吗

**Comment by fulldog** [comment]
这个不是过滤白名单吗？
我的场景是：从A库同步key，同步后的key被重命名为：prefix:key  这样

**Comment by chengkala** [comment]
可能需要改代码了  redis-shake写入目标库的时候  可以把key修改

**Comment by michael-liumh** [comment]
> 可能需要改代码了 redis-shake写入目标库的时候 可以把key修改

确实，一般改key前缀这种，普遍为定制化需求

**Comment by suxb201** [comment]
暂不考虑类似需求，但欢迎 PR。
