### ISSUE TITLE
主备站点场景

### ISSUE THREAD

**Issue by andyyuano** [aliyun/redis-shake#340]
主备站点希望通过redisshake做同步，当前是在主备站点各部署一个redisshake，对对端做为目标端，主站点正常时，备站点的redisshake不启动；主备切换时，才启动备站点的redisshake。但若主站点的网络恢复，或者主站点的redis及redisshake并没有故障，会产生双向同步的情况。不知道针对此种场景，有没有好的解决方案？

**Comment by baronwangr** [comment]
redisshake这个工具，其实定义为一次搬迁工具。
1. 不适合做长时间单向同步，这不是shake的原因，而是redis本身的psync协议不能提供稳定的复制流
2. 不能做双向复制。redis的psync协议不能解回环

需要引入支持断点，支持双向同步的协议。（阿里的tair是redis的企业版，支持的是binlog协议而非psync协议，所以可以做多活）
