### ISSUE TITLE
同步日志出现delayChannel is full

### ISSUE THREAD

**Issue by tina-shi** [aliyun/redis-shake#343]
redis-shake 开启了集群间同步，同步日志有报[WARN] DbSyncer[1] delayChannel is full
同步日志也没有更新，这个WARN是什么意思

**Comment by liuqy95** [comment]
同问

**Comment by suxb201** [comment]
hi @liuqy95 @tina-shi，我在本地没有复现这个 WARN，可以提供更多信息吗？比如：
1. 有哪些非默认配置
2. 开启时源端，目的端数据情况
3. 开启后多久出现此 WARN
