### ISSUE TITLE
源端16进制数据迁移后成乱码

### ISSUE THREAD

**Issue by redgreat** [aliyun/redis-shake#344]
![c2512094-4443-4f1e-8315-9fd3f582f0db](https://user-images.githubusercontent.com/1754926/123230926-4b9e8000-d50a-11eb-8f39-b643173983f9.png)
源端为自建Redis，迁移到RDS-Redis后Value值乱码。shake怎么指定连接后的格式是 -raw呢

**Comment by baronwangr** [comment]
shake导入都是二进制导入。并不确认这个问题。要不然hex dump下？

**Comment by chenyang8094** [comment]
这个是redis-cli自己转换的，你用redis-cli连目的端看到的也会是一样的（和源端）
