### ISSUE TITLE
缓存场景优化，将增量同步操作改为删除操作

### ISSUE THREAD

**Issue by yinghonghui** [aliyun/redis-shake#345]
增量的时候对批量操作支持不够

**Comment by baronwangr** [comment]
请问能详细描述下需求？

**Comment by yinghonghui** [comment]
之前做集群增量思考不够，增量的数据是针对一个slot，就不存在这个问题了。
1.在你们sync的基础上改造了一种方式，全量的是数据放到新集群，增量的时候进行对新集群的数据删除。（这种方式对有数据有兜底的应用服务，可以进行平滑的数据迁移）
2.另外shake 方式多节点shake 运行，在cluster模式的时候对源集群进行校验的时候，可以部分节点迁移。（因为我这边发现在集群模式比较大的时候，迁移数据会有异常失败的情况，但是节点数少了这个问题可以避开）。
3.另外新增了一种迁移方式，全量和增量，匹配数据都会的目标集群进行数据删除。这样设置目标节点和源节点是一样的情况下，可以支持匹配进行数据删除功能

**Comment by suxb201** [comment]
hi @yinghonghui ，没有听懂你的描述，不知道所谓“删除”是什么意思。但根据描述和你 fork 的仓库能看出做了不少工作。可否具体描述下？我们也欢迎 pr。

**Comment by yinghonghui** [comment]
> hi @yinghonghui ，没有听懂你的描述，不知道所谓“删除”是什么意思。但根据描述和你 fork 的仓库能看出做了不少工作。可否具体描述下？我们也欢迎 pr。

因为在迁移的增量数据有延迟的原因，可能导致部分数据正确性不能得到保证。
比如key A old 集群修改time1 迁移到新集群 time2  另外客户端有对新集群操作time3
如果在time1< time3< time2 的情况，导致key 2的数据有误
这是话采用对增量的数据，在new 集群继续删除操作，能保证新集群的数据最终是正确的。

**Comment by suxb201** [comment]
还是不懂
> 这是话采用对增量的数据，在new 集群继续删除操作，能保证新集群的数据最终是正确的。


看起来还是在讨论新老集群一致性，我们建议是停机短暂时间。和这个问题比较像，可以看一下： https://github.com/alibaba/RedisShake/issues/262

**Comment by yinghonghui** [comment]
redis 因为有其特殊性，某些数据应用可以不停机切换，我的方式就是为了这些场景。
你可以看一下我的场景分析的原理基础。
![image](https://user-images.githubusercontent.com/18246565/129889649-7a4b07d1-03a5-4a05-9916-19ea52fd002e.png)
![image](https://user-images.githubusercontent.com/18246565/129889683-473e8400-a987-4dad-ad10-e51607793c79.png)
![image](https://user-images.githubusercontent.com/18246565/129889738-ac204d84-c6ba-4e0c-80cb-61ea308a0a15.png)

**Comment by suxb201** [comment]
谢谢，懂了。
sync 模式有两个阶段，`全量同步 rdb 文件阶段`和`增量同步阶段`。你是把`增量同步阶段`中所有命令都改成删除操作了吗？

**Comment by yinghonghui** [comment]
嗯，因为缓存有他自身的特殊性，利用他的特殊性，有些场景可以做到平滑不宕机的自动迁移。
1.仿照sync 新增了syncPdel模式。全量同步 rdb 文件阶段和增量同步阶段，增量同步阶段中所有命令都改成删除操作
2.另外还有一种del模式，用来匹配删除数据。

**Comment by suxb201** [comment]
是可以的，有兴趣可以提个 PR，我会接受的。

**Comment by yinghonghui** [comment]
好的

**Comment by suxb201** [comment]
这个场景是不是所有操作都是 string 类（比如 set k v）或者说是幂等的。

---
time1 time2 time3 都是发生在增量同步阶段？
那就不能保证 new db 查询的时候没有数据了，因为 key 可能再 rdb 中被传过来。
![image](https://user-images.githubusercontent.com/16659368/130003156-6dbc4a67-2306-4964-89b4-87304c415423.png)

**Comment by yinghonghui** [comment]
其他数据类型也可以的，
time1 time2 time3 都是发生在增量同步阶段，
这个可以通过shake restful 服务接口来查询状态，只有都进入增量情况下，才进行数据迁移。

**Comment by yinghonghui** [comment]
其他数据类型也可以的，
time1 time2 time3 都是发生在增量同步阶段，
这个可以通过shake restful 服务接口来查询状态，只有都进入增量情况下，才进行服务切换集群操作。

**Comment by suxb201** [comment]
过程中的数据错误可以容忍，但要求最终的数据正确？

**Comment by suxb201** [comment]
> 过程中的数据错误可以容忍，但要求最终的数据正确？

蓝框中的数据错误可以认为是客户端延迟导致的，也可以认为是数据正确。比如客户端 A 延迟比 客户端 B 大些就会有这种情况。
![image](https://user-images.githubusercontent.com/16659368/130003991-c6581e1d-2052-4767-ac24-0315229414bb.png)

**Comment by yinghonghui** [comment]
嗯，过程阶段是没办法避免的。
不过切换操作我们这边是用zk通知客户端服务，是一个比较快的响应。另外本质上错误数据其实概率很低。迁移延迟也很低。
我这边一般是在切换之后，通知客户端服务再重启一下服务。来保证服务的正确性。

**Comment by yinghonghui** [comment]
因为涉及到两个数据源的多个客户端服务，其实类似于分布式事务。我选择最终的数据正确性，然后尽量保证切换时间短。
这样对大部分业务的缓存是可以容忍不宕机切换集群。

**Comment by suxb201** [comment]
了解了。

**Comment by baronwangr** [comment]
请问下，这种使用方式，是做一次性的数据迁移，还是做长时间的数据同步使用？

**Comment by yinghonghui** [comment]
一次性的数据迁移。
我这边设计是把迁移工具，界面服务化，自动生成配置，然后通过restful 来监控状态，配合客户端SDK 来数据迁移。

syncPdel是一种可以应付大部分的业务迁移，
也有sync 来应付迁移过程中不会有数据变动。
其他的类型还在考虑中。
思路其实就是把迁移数据根据不同场景划分，然后针对性走对应迁移策略。

**Comment by dbabao** [comment]
> redis 因为有其特殊性，某些数据应用可以不停机切换，我的方式就是为了这些场景。
> 你可以看一下我的场景分析的原理基础。
> ![image](https://user-images.githubusercontent.com/18246565/129889649-7a4b07d1-03a5-4a05-9916-19ea52fd002e.png)
> ![image](https://user-images.githubusercontent.com/18246565/129889683-473e8400-a987-4dad-ad10-e51607793c79.png)
> ![image](https://user-images.githubusercontent.com/18246565/129889738-ac204d84-c6ba-4e0c-80cb-61ea308a0a15.png)

不论redis是用于缓存或是持久化存储，这个现象都是会存在的吧？
之前在应对这种情况的一种解决思路是在上层应用上做路由绑定功能，即一个key的请求要么落在源集群上，要么落在新集群上，不让其出现既可能访问源集群又可能访问新集群的情况。

**Comment by suxb201** [comment]
> 之前在应对这种情况的一种解决思路是在上层应用上做路由绑定功能，即一个 key 的请求要么落在源集群上，要么落在新集群上，不让其出现既可能访问源集群又可能访问新集群的情况。

是这样的，这样就没问题了。

**Comment by baronwangr** [comment]
目前redis无法区分是del，还是expire del，还是evict del

**Comment by baronwangr** [comment]
可实施性并不高。如果是复杂数据结构，那么整个缓存的命中率会非常低。
BTW，我们无法区分是内存数据库场景，还是缓存场景。另外提到的，由于redis不支持稳定的复制流，那么全量同步发生会怎么办？
ETL的能力希望后面用户能自己去实施
