### ISSUE TITLE
sync模式同步非db0库，增量数据默认全部同步到了db0

### ISSUE THREAD

**Issue by luxiangyulinux** [aliyun/redis-shake#346]
redis-shake版本： v2.0.3
目标： 从阿里云同步到ecs自建redis，版本相同，均为5.0
过程： 只配置了阿里云db1 同步到自建db1，使用sync模式；
结果： 全量同步正常，日志显示到达了增量阶段，但是目标db0（源端和目的端db0均为空的）出现了部分key，后经验证是db1的增量数据，且该数据db1中没有。判断是非db0的增量数据同步到了db0

**Comment by chenyang8094** [comment]
已经修复，谢谢反馈
