### ISSUE TITLE
能否动态设置filter.key.whitelist

### ISSUE THREAD

**Issue by neo0591** [aliyun/redis-shake#347]
请问使用filter.key.whitelist过滤同步key，能否支持运行中更新whitelist，不用重启shke

**Comment by baronwangr** [comment]
sorry 目前shake没有计划做动态配置。它仍是一个工具，做一次性数据导入

**Comment by yinghonghui** [comment]
可以通过对应稍微改造一下对应restful，来动态更新配置

**Comment by neo0591** [comment]
> 可以通过对应稍微改造一下对应restful，来动态更新配置

感谢回复，请问如何修改restful，我未找到shake有开放接口

**Comment by yinghonghui** [comment]
![image](https://user-images.githubusercontent.com/18246565/129149925-a4484333-85a6-487c-90e6-f5799d136027.png)
 入口这里，然后自己添加一下动态修改配置的接口就行

**Comment by neo0591** [comment]
> ![image](https://user-images.githubusercontent.com/18246565/129149925-a4484333-85a6-487c-90e6-f5799d136027.png)
> 入口这里，然后自己添加一下动态修改配置的接口就行

谢谢指点
