### ISSUE TITLE
希望能增加自定义将源redis中哪个db同步到目标redis中哪个db功能，比如 db0-> db 5, db1->bd3

### ISSUE THREAD

**Issue by zhangqi-ulua** [aliyun/redis-shake#348]
希望能增加自定义将源redis中哪个db同步到目标redis中哪个db功能，比如 db0-> db 5, db1->bd3

**Comment by zhangqi-ulua** [comment]
补充，我说的是多个db的映射。比如json参数配置

**Comment by chenyang8094** [comment]
谢谢，可以看看这个[https://github.com/alibaba/RedisShake/pull/352](PR)
