### ISSUE TITLE
start.sh脚本的问题（由于下载的二进制包缺少hypervisor可执行文件）造成启动不了

### ISSUE THREAD

**Issue by ewsq** [aliyun/redis-shake#350]
使用以下语句启动时：
./start.sh redis-shake.conf sync

显示start.sh脚本的问题（由于下载的二进制包缺少hypervisor可执行文件）造成启动不了

解决办法是（https://blog.csdn.net/xlh1991/article/details/113130136）：
在运行RedisShake 二进制包自带的start.sh 会出现以下报错：、

problem：

./start.sh: line 20: ./hypervisor: No such file or directory

solution：

去github官网下载这个文件，再手工进行编译即可。

wget https://github.com/alibaba/RedisShake/blob/develop/scripts/hypervisor.c

gcc -Wall -O3 hypervisor.c -o hypervisor

能否在二进制包中直接加入呀，否则第一次用会有些莫名其妙。

**Comment by suxb201** [comment]
```
./redis-shake -conf redis.conf -type sync
```
感谢反馈，使用此命令来运行 redis-shake。start.sh 与 stop.sh 会从 release 包中去除，保留 supervisor.c 给可能用到此功能的人。
