### ISSUE TITLE
parallel 参数的理解

### ISSUE THREAD

**Issue by ReasonDuan** [aliyun/redis-shake#351]
**parallel** 参数是不是指启动多少线程来负责将源同步过来的数据写入到目标redis中？
SourceRedis -> RedisShake 是一个任务，并行数量由**source.rdb.parallel**决定
RedisShake -> TargetRedis 是一个任务，并行数量由**parallel**决定

我这么理解是否正确？

**Comment by chenyang8094** [comment]
source.rdb.parallel 是针对源端的，表示会同时起多少个goroutine 来拉取/解析rdb，以及后续的增量。
parallel是针对目的端/发送端而言，表示解析后的rdb采用多少个goroutine发送，因为rdb的restore有可能是乱序的（多携程情况下）。
