### ISSUE TITLE
 read: connection reset by peer

### ISSUE THREAD

**Issue by oneday2442** [aliyun/redis-shake#360]
两次redis同步遇到相同问题
![Snipaste_2021-08-19_10-58-02](https://user-images.githubusercontent.com/89174961/130001070-b005bfc7-cdb1-4a70-95cb-eaf857b07426.png)

redis的相关配置为：
```
repl-timeout 60
client-output-buffer-limit slave 0 0 0 
```

源端日志显示为
```
* Background saving terminated with success
# Connection with slave client id #2894126 lost.
```

已尝试参照 https://github.com/alibaba/RedisShake/issues/282 修改 parallel = 64，但并未成功
尝试过修改repl-timeout为300，也试过修改client-output-buffer-limit slave 为256m 64m 60，也没有成功。
所以请教一下作者，是否有什么好的调整建议。

**Comment by suxb201** [comment]
此时源 Redis 写入很高吗？

**Comment by baronwangr** [comment]
reset by peer是server close，查一下相应源redis.log的记录

**Comment by oneday2442** [comment]
案例一qps约为7000，使用内存约700M
RDB文件落地的瞬间磁盘io写从100上升至60000sec/s,但util和await值很低，均低于5。
具体日志如下：
>60018:M 18 Aug 14:28:02.834 * Slave 10.1.137.136:9320 asks for synchronization
>60018:M 18 Aug 14:28:02.841 * Full resync requested by slave 10.1.137.136:9320
>60018:M 18 Aug 14:28:02.841 * Starting BGSAVE for SYNC with target: disk
>60018:M 18 Aug 14:28:02.855 * Background saving started by pid 19124
>19124:C 18 Aug 14:28:06.478 * DB saved on disk
>19124:C 18 Aug 14:28:06.479 * RDB: 494 MB of memory used by copy-on-write
>60018:M 18 Aug 14:28:06.516 * Background saving terminated with success
>60018:M 18 Aug 14:29:42.431 # Connection with slave client id #1311976 lost.

案例二qps约为2000，使用内存约2.5G，已排除无大key问题
RDB文件落地的瞬间磁盘io也是从100上升至60000sec/s, util约20%和await值约40ms(今早的一次重试中,awati值短暂上升至120ms)
具体日志如下

>2470:M 18 Aug 14:19:37.247 * Slave 10.1.138.36:9320 asks for synchronization
>2470:M 18 Aug 14:19:37.266 * Full resync requested by slave 10.1.138.36:9320
>2470:M 18 Aug 14:19:37.266 * Starting BGSAVE for SYNC with target: disk
>2470:M 18 Aug 14:19:37.269 * Background saving started by pid 17645
>17645:C 18 Aug 14:19:52.828 * DB saved on disk
>17645:C 18 Aug 14:19:52.829 * RDB: 3168 MB of memory used by copy-on-write
>2470:M 18 Aug 14:19:52.933 * Background saving terminated with success
>2470:M 18 Aug 14:23:38.453 # Connection with slave client id #2887307 lost.

**Comment by suxb201** [comment]
@oneday2442 RedisShake 与源 Redis 不是直连的？改用直连试试。

**Comment by oneday2442** [comment]
> @oneday2442 RedisShake 与源 Redis 不是直连的？改用直连试试。

不好意思，没有理解到这句话的意思？两次案例中redisshake都是与源redis的master节点在同一服务器上（10.1.137.136，10.1.138.36）运行的，是直连的，中间没有代理。

**Comment by suxb201** [comment]
@oneday2442 因为 RedisShake log 中 port 与 Redis log 中的 port 对应不上，所有我猜测你是不是使用了 proxy 之类的代理层？

**Comment by baronwangr** [comment]
redislog里，shake是10.1.137.136:9320；shake的log里，是50404，第二个log也不是136.

**Comment by suxb201** [comment]
尝试修改配置文件 redis-shake.conf
```
keep_live = 1
```

**Comment by oneday2442** [comment]
> 尝试修改配置文件 redis-shake.conf
> 
> ```
> keep_live = 1
> ```

将参数中的keep_alive设置为1确实 **有效解决** 了案例中的情况，非常感谢您的建议和耐心指导！

**Comment by suxb201** [comment]
@oneday2442 请问你是自己编译的 redis-shake 还是用的 release 中的 redis-shake？
如果是自己编译的话，那么编译机上的 golang 版本是多少？

**Comment by oneday2442** [comment]
> @oneday2442 请问你是自己编译的 redis-shake 还是用的 release 中的 redis-shake？
> 如果是自己编译的话，那么编译机上的 golang 版本是多少？

未编译，使用的是release的redis-shake : redis-shake-v2.0.3.tar.gz。

**Comment by suxb201** [comment]
了解了，问题已解决，此 issue 关闭了。
