### ISSUE TITLE
可以自动实现获取集群的主节点吗

### ISSUE THREAD

**Issue by jiaminxia** [aliyun/redis-shake#361]
如题，如果在同步过程中，集群的主节点发生变更，同步还会进行吗？

**Comment by suxb201** [comment]
我认为是可以的，但没有测试过。

**Comment by jiaminxia** [comment]
> 我认为是可以的，但没有测试过。

我测试了，主集群中主从切换一次是可以的，但是两次或多次以上就会报错，这个可以解决吗
