### ISSUE TITLE
metric 中的延迟信息为 null

### ISSUE THREAD

**Issue by jiaminxia** [aliyun/redis-shake#363]
在集群与集群同步过程中，从http://IP:9320/metric中查看的Delay和AvgDelay永远是null
请问这个是正常的吗

**Comment by jiaminxia** [comment]
还有除了这一种方式查看延迟，还有没有其他方法查看两个集群间的延迟

**Comment by suxb201** [comment]
不正常，是 bug。

**Comment by jiaminxia** [comment]
> 不正常，是 bug。

后续会更新这个功能吗，因为想在界面上体现出两个集群之间的延迟时间

**Comment by suxb201** [comment]
@jiaminxia 会，但近期没有时间。欢迎 PR。

**Comment by Colstuwjx** [comment]
这个我也关注到了，貌似是事务这块没想好怎么处理？这块后续有确定解决办法吗？

然后还有个问题是，是否可以用 RedisShake 这个 fake 的 slave 和 source master 的 offset 来作为另外一个维度的 metric？我目前就是根据这个 offset 知道大概的延迟情况。
