### ISSUE TITLE
集群重启后，shake进程报错

### ISSUE THREAD

**Issue by jiaminxia** [aliyun/redis-shake#365]
我在重启三主三从的集群后，再次起shake进程日志报错

2021/08/30 17:06:43 [PANIC] del %!(EXTRA string=qq:406191, *errors.errorString=redigo: unexpected type for Int64, got type redis.redisError, value: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.)
[stack]: 
    1   github.com/alibaba/RedisShake/redis-shake/common/utils.go:845
            github.com/alibaba/RedisShake/redis-shake/common.RestoreRdbEntry
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/syncRDB.go:71
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).syncRDBFile.func1.1
        ... ...

**Comment by suxb201** [comment]
> MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). 

Redis 在 save rdb 的时候出了问题。

**Comment by jiaminxia** [comment]
> > MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option).
> 
> Redis 在 save rdb 的时候出了问题。

我后来把目标端的集群的主节点rdb文件删除后，同步正常
