### ISSUE TITLE
同步的延迟时间怎么看

### ISSUE THREAD

**Issue by Val-zhang-147** [aliyun/redis-shake#366]
发送了一条set命令，但是源端和目标端都不能立马查到，过几秒钟，再执行set，再查 发现可以了，观察日志，第一次好像没有把命令同步过去

**Comment by Val-zhang-147** [comment]
2021/08/30 20:20:25 [DEBUG] DbSyncer[0] receive reply-id[348524]: [OK], error:[<nil>]
2021/08/30 20:20:25 [DEBUG] DbSyncer[0] receive reply-id[348525]: [QUEUED], error:[<nil>]
2021/08/30 20:20:25 [DEBUG] DbSyncer[0] receive reply-id[348526]: [QUEUED], error:[<nil>]
2021/08/30 20:20:25 [DEBUG] DbSyncer[0] receive reply-id[348527]: [QUEUED], error:[<nil>]
2021/08/30 20:20:25 [DEBUG] DbSyncer[0] receive reply-id[348528]: [QUEUED], error:[<nil>]
2021/08/30 20:20:25 [DEBUG] DbSyncer[0] receive reply-id[348529]: [QUEUED], error:[<nil>]
2021/08/30 20:20:25 [DEBUG] DbSyncer[0] receive reply-id[348530]: [QUEUED], error:[<nil>]
2021/08/30 20:20:25 [DEBUG] DbSyncer[0] receive reply-id[348531]: [QUEUED], error:[<nil>]

**Comment by Val-zhang-147** [comment]
日志里会有这样的信息

**Comment by Val-zhang-147** [comment]
部署了2套shake，想测试双向同步是什么效果，发现有这样的问题
![image](https://user-images.githubusercontent.com/67937883/131345723-e8ee2426-7fc6-4862-9ee2-3d6be5fc284a.png)

![image](https://user-images.githubusercontent.com/67937883/131345526-af1bb0d9-6905-4383-9fd8-ebfedd7432ab.png)

**Comment by suxb201** [comment]
不支持双向同步

**Comment by suxb201** [comment]
可以看一下这里：https://github.com/alibaba/RedisShake/issues/367
