### ISSUE TITLE
支持双向同步

### ISSUE THREAD

**Issue by jiuker** [aliyun/redis-shake#367]
思路：
1.全量就不说了，肯定会以某一段为主
2.增量，当出现一个需要同步的命令就pipeline 去执行，用事务包裹，第一条命令，永远是 SETEX node-{ip}-sync 0 {time},这样就实现了命令的打标。

**Comment by silencer001** [comment]
> 思路：
> 1.全量就不说了，肯定会以某一段为主
> 2.增量，当出现一个需要同步的命令就pipeline 去执行，用事务包裹，第一条命令，永远是 SETEX node-{ip}-sync 0 {time},这样就实现了命令的打标。

我理解redis没办法防环，所有对端和自身收到的增量数据都要需要传递到shake，由shake来拦截过滤；
如果这样的话，有两个开销增长，第一redis给shake的增量同步数据仍然会放大一倍，第二shake增加事务和setex命令，公网带宽也增加了好多；这样就不太实用了

**Comment by suxb201** [comment]
阿里云有一个类似的实现：https://help.aliyun.com/document_detail/71881.html 

但如果保证可用的话，需要考虑的点很多很多，RedisShake 不会做的。

**Comment by jiuker** [comment]
> > 思路：
> > 1.全量就不说了，肯定会以某一段为主
> > 2.增量，当出现一个需要同步的命令就pipeline 去执行，用事务包裹，第一条命令，永远是 SETEX node-{ip}-sync 0 {time},这样就实现了命令的打标。
> 
> 我理解redis没办法防环，所有对端和自身收到的增量数据都要需要传递到shake，由shake来拦截过滤；
> 如果这样的话，有两个开销增长，第一redis给shake的增量同步数据仍然会放大一倍，第二shake增加事务和setex命令，公网带宽也增加了好多；这样就不太实用了

可以一次性发送多点，比如一次性发送100条，你中途加一个3条也就很小了

**Comment by jiuker** [comment]
> 阿里云有一个类似的实现：https://help.aliyun.com/document_detail/71881.html
> 
> 但如果保证可用的话，需要考虑的点很多很多，RedisShake 不会做的。

就简单做呗，不需要保证可用，一般来说，双写的场景我理解是不需要处理可用问题的，因为全量这个事情就无法保证谁对谁错

**Comment by suxb201** [comment]
@jiuker 没办法处理环

**Comment by baronwangr** [comment]
psync协议不支持稳定的复制流（repl buffer满了会引发全量复制）；另外redis不支持数据解回环。
目前只有阿里云Tair（企业版redis）和redislabs的企业版（redis-enterprise）支持双向同步。Tair支持的更多，支持多地多活。

**Comment by jiuker** [comment]
> @jiuker 没办法处理环

事务封装打标，是可以处理回环得，没仔细看思路？

**Comment by jiuker** [comment]
> psync协议不支持稳定的复制流（repl buffer满了会引发全量复制）；另外redis不支持数据解回环。
> 目前只有阿里云Tair（企业版redis）和redislabs的企业版（redis-enterprise）支持双向同步。Tair支持的更多，支持多地多活。

我知道你推阿里得服务是好事，是可以解回环得，用事务机制打标

**Comment by suxb201** [comment]
@jiuker 想了下，确实可以实现。

**Comment by baronwangr** [comment]
> > @jiuker 没办法处理环
> 
> 事务封装打标，是可以处理回环得，没仔细看思路？

这种是在使用上做“假定”，谁来保障这个假定？这个假定有什么价值？具备多少的通用性？假定失效会导致什么后果？
shake就是个工具，它的主要定位是提供一个通用的数据同步和一个框架，具体实在没法去实施这种假定。
请理解。

**Comment by baronwangr** [comment]
> > @jiuker 没办法处理环
> 
> 事务封装打标，是可以处理回环得，没仔细看思路？

这种是在使用上做“假定”，谁来保障这个假定？这个假定有什么价值？具备多少的通用性？假定失效会导致什么后果？
shake就是个工具，它的主要定位是提供一个通用的数据同步和一个框架，具体实在没法去实施这种假定。
请理解。

另外提一句，redis的pipeline，过去，现在，未来都不是原子的。

**Comment by jiuker** [comment]
> > > @jiuker 没办法处理环
> > 
> > 
> > 事务封装打标，是可以处理回环得，没仔细看思路？
> 
> 这种是在使用上做“假定”，谁来保障这个假定？这个假定有什么价值？具备多少的通用性？假定失效会导致什么后果？
> shake就是个工具，它的主要定位是提供一个通用的数据同步和一个框架，具体实在没法去实施这种假定。
> 请理解。
> 
> 另外提一句，redis的pipeline，过去，现在，未来都不是原子的。

提供一个打标功能，不做双向的总可以撒，比如有一个汇总redis，我要知道这批命令来源

**Comment by cheney-plus** [comment]
> > > 思路：
> > > 1.全量就不说了，肯定会以某一段为主
> > > 2.增量，当出现一个需要同步的命令就pipeline 去执行，用事务包裹，第一条命令，永远是 SETEX node-{ip}-sync 0 {time},这样就实现了命令的打标。
> > 
> > 
> > 我理解redis没办法防环，所有对端和自身收到的增量数据都要需要传递到shake，由shake来拦截过滤；
> > 如果这样的话，有两个开销增长，第一redis给shake的增量同步数据仍然会放大一倍，第二shake增加事务和setex命令，公网带宽也增加了好多；这样就不太实用了
> 
> 可以一次性发送多点，比如一次性发送100条，你中途加一个3条也就很小了



没用的，redis的事物命令同步不是同步 整个 multi 命令，而是同步被包裹的命令，也就意味着你的第一个标记无法标记后面跟着的命令。

**Comment by cheney-plus** [comment]
> [@jiuker](https://github.com/jiuker) 想了下，确实可以实现。

没用的，redis的事物命令同步不是同步 整个 multi 命令
