### ISSUE TITLE
2.1.0版本，sync模式同步非db0库，增量数据默认全部同步到了db0

### ISSUE THREAD

**Issue by peigonga** [aliyun/redis-shake#369]
与 https://github.com/alibaba/RedisShake/issues/346 的现象完全一样
请问2.1.0版本包含修复该问题的代码吗

**Comment by peigongpeigong** [comment]
https://github.com/alibaba/RedisShake/issues/346

**Comment by chenyang8094** [comment]
已经在v2.1.1版本中修复。
