### ISSUE TITLE
使用redisshake进行同步的时候出现以下错误

### ISSUE THREAD

**Issue by 3tem** [aliyun/redis-shake#371]
版本：2.1.0
Error:run ChooseNodeWithCmd failed[transaction command[replconf] key[GETACK] not hashed in the same node: current[10.100.64.142:6379], previous[10.102.77.4:6379]]
出现这个报错之后就会导致一直重启不起来，这个应该怎么解决？

**Comment by suxb201** [comment]
目的端是集群，且用了 multi 命令，且事务中的命令有 slot 不在一个分片的情况。
