### ISSUE TITLE
源端为rdb文件同步到目的端报OOM

### ISSUE THREAD

**Issue by 3tem** [aliyun/redis-shake#372]
源端为rdb文件同步到目的端为集群，也会报oom ，看了下QA并没有相关说明，这个是怎么处理的？

2021/09/06 16:19:13 [PANIC] parse rdb entry error, if the err is :EOF, please check that if the src db log has client outout buffer oom, if so set output buffer larger.
[error]: decompress exception: runtime error: index out of range [-1528]
    0   github.com/alibaba/RedisShake/pkg/rdb/reader.go:501
            github.com/alibaba/RedisShake/pkg/rdb.lzfDecompress.func1
        ... ...
[stack]:
    0   github.com/alibaba/RedisShake/redis-shake/common/utils.go:953
            github.com/alibaba/RedisShake/redis-shake/common.NewRDBLoader.func1
        ... ...

**Comment by suxb201** [comment]
这 log 表述有问题，本意是解析 rdb 文件时出错了。麻烦先确认下 rdb 文件时完好无损的。如果还是有问题，方便提供 rdb 文件供我 debug 下吗？

**Comment by 3tem** [comment]
不好意思，rdb文件为客户文件，不方便提供哈，我描述一下我现在遇到的问题：
该rdb文件生成的是在一次服务宕机之后生成的，重启redis 读取该rdb文件之后，redis报错为：
--- RDB ERROR DETECTED ---
[offset 57934084] Invalid LZF compressed string
[additional info] While doing: read-object-value
[additional info] Reading key 'cd:ph:dev:86151212'
[additional info] Reading type 0 (string)
[info] 171083 keys read
[info] 26 expires
[info] 3 already expired
我怀疑是rdb文件损坏。所以就尝试了下使用redisshake 来进行同步该文件或者解析成json文件，看是否能够帮助我解决问题，操作的过程中出现了该问题。同时我想请教一下，如果rdb文件损坏的话我应该使用什么来分析该rdb文件损坏的数据或者有什么方式来矫正它，有一些思路可以提供吗，多谢。

**Comment by suxb201** [comment]
试试这个：https://github.com/sripathikrishnan/redis-rdb-tools
如果没有其他数据备份，且数据真的很重要的话，可以考虑魔改 RedisShake 或者 redis-rdb-tools，然后恢复部分数据。

**Comment by 3tem** [comment]
好的，多谢，我看一下
