### ISSUE TITLE
checkpoint testcase 需要调整

### ISSUE THREAD

**Issue by Colstuwjx** [aliyun/redis-shake#374]
如题，切换到 checkpoint 目录之后尝试执行 `go test -v *.go` 会报如下错误：

```
# command-line-arguments
checkpoint_test.go:7:2: package redis-shake/common is not in GOROOT (/usr/local/go/src/redis-shake/common)
FAIL	command-line-arguments [setup failed]
FAIL
```

import 的包路径可能需要调整下。

然后我们 testcase 好像是没有和 CI 联动起来？是否可以参考 k8s 的做法，后续和 [e2e test](https://github.com/alibaba/RedisShake/tree/develop/test) 一起做到 CI 里，每次 PR 都可以触发 CI Test 。

**Comment by suxb201** [comment]
是的，没要加 ci 呢，而且测试也没有覆盖完全。

**Comment by Colstuwjx** [comment]
修复了部分 testcase 无法运行的问题，见 #388，但是有两个遗留的 issue 可能还需要你们帮忙填充修复下。
