### ISSUE TITLE
使用 source cluster -> target cluster 同步方式发现源集群已删除的 key 仍然存在于目标集群

### ISSUE THREAD

**Issue by Colstuwjx** [aliyun/redis-shake#376]
如下，delete 不会被同步到目标集群吗：

```
<Source_Cluster>> del hellowjxtest
(integer) 1
<Source_Cluster>> get hellowjxtest
(nil)

<Target_Cluster> > get hellowjxtest
"test1"
```

**Comment by Colstuwjx** [comment]
经过实验，大概了解了，是不是这么一个情况：如果 del 事件没被 RedisShake 捕获到，那么后面再启动 RedisShake，它是不会做源和目标的完全对等覆盖同步？比如 target 有 1300 个 key，而 source 只有一个 key，开启 RedisShake `key_exists = rewrite` 配置的话，也无法让 target 经过同步之后变成和 source 一样，只有一个 key，它这 1300 个 key 仍然会存在？

这好像不太符合预期，如果是主备集群场景的话，我们是希望主备集群的数据是完全一致的。

**Comment by suxb201** [comment]
自己手动执行下 flushall 就符合预期了

**Comment by Colstuwjx** [comment]
好吧
