### ISSUE TITLE
redis安装了bloom插件，有数据类型为bloom类型，同步无法识别

### ISSUE THREAD

**Issue by LonersBoy** [aliyun/redis-shake#382]
从单点redis往一个新的redis中同步数据，同步类型选择的sync，很快就报错了

> 2021/09/17 00:26:52 [INFO] db_size:93006 expire_size:62691
2021/09/17 00:26:52 [PANIC] parse rdb entry error, if the err is :EOF, please check that if the src db log has client outout buffer oom, if so set output buffer larger.
[error]: unknown object-type 07
    2   github.com/alibaba/RedisShake/pkg/rdb/reader.go:109
            github.com/alibaba/RedisShake/pkg/rdb.(*rdbReader).readObjectValue
    1   github.com/alibaba/RedisShake/pkg/rdb/loader.go:202
            github.com/alibaba/RedisShake/pkg/rdb.(*Loader).NextBinEntry
    0   github.com/alibaba/RedisShake/redis-shake/common/utils.go:952
            github.com/alibaba/RedisShake/redis-shake/common.NewRDBLoader.func1
        ... ...
[stack]:
    0   github.com/alibaba/RedisShake/redis-shake/common/utils.go:953
            github.com/alibaba/RedisShake/redis-shake/common.NewRDBLoader.func1
        ... ...

源redis中安装了bloom插件，有数据类型为bloom类型

**Comment by suxb201** [comment]
是的，现在只支持 Redis 原生数据结构的 rdb 解析。
