### ISSUE TITLE
transaction command[replconf]   这种情况导致退出

### ISSUE THREAD

**Issue by 3tem** [aliyun/redis-shake#386]
版本：2.1.1
redis :docker 部署。版本5.0.5
Event:SendToTargetFail  Id:redis-shake  Error:run ChooseNodeWithCmd failed[transaction command[replconf] key[GETACK] not hashed in the same node: current[10.100.64.142:6379], previous[10.97.117.9:6379]]
重启之后依旧无法启动，这种问题怎么解决

**Comment by 3tem** [comment]
有回答该问题： https://github.com/alibaba/RedisShake/issues/371
但是我查找了下项目中并没有使用事务相关

**Comment by suxb201** [comment]
使用最新分支编译，然后过滤掉 replconf 命令即可。
参照：https://github.com/alibaba/RedisShake/issues/320#issuecomment-922265671
