### ISSUE TITLE
华为云分布式缓存redis服务，使用redis-shake同步失败

### ISSUE THREAD

**Issue by bhljay** [aliyun/redis-shake#387]
[PANIC] invalid psync response, continue, ERR Unsupported command: psync ? -1

[stack]: 
    2   github.com/alibaba/RedisShake/redis-shake/common/utils.go:251
            github.com/alibaba/RedisShake/redis-shake/common.SendPSyncContinue
    1   github.com/alibaba/RedisShake/redis-shake/dbSync/syncBegin.go:50
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).sendPSyncCmd
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/dbSyncer.go:111
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).Sync
        ... ...

**Comment by chengkala** [comment]
psync 没有开 可以试一下huawei云的在线迁移

**Comment by bhljay** [comment]
> psync 没有开可以试一下华为
