### ISSUE TITLE
Sync模式增量同步时Status一直是waitfull

### ISSUE THREAD

**Issue by hkp2008** [aliyun/redis-shake#390]
源（redis_version:3.2.6）和目的（redis_version:5.0.13）都是哨兵模式，通过redis-shake（release-v2.1.1-20210903）的Sync模式迁移数据，redis-shake有开启断点续传功能；数据量有4个多G，修改源端的client-output-buffer-limit参数可以正常迁移数据，但是发现源端的内存到了增量同步阶段还在不断上涨，然后就手动更改了源端的client-output-buffer-limit，发现redis-shake打印的metric日志如下：（重启redis-shake也一样）
2021/10/15 10:36:24 [INFO] [{"StartTime":"2021-10-14T14:08:24Z","PullCmdCount":0,"PullCmdCountTotal":0,"BypassCmdCount":0,"BypassCmdCountTotal":0,"PushCmdCount":0,"PushCmdCountTotal":0,"SuccessCmdCount":0,"SuccessCmdCountTotal":0,"FailCmdCount":0,"FailCmdCountTotal":0,"Delay":"null ms","AvgDelay":"null ms","NetworkSpeed":0,"NetworkFlowTotal":0,"FullSyncProgress":0,"Status":"waitfull","SenderBufCount":0,"ProcessingCmdCount":0,"TargetDBOffset":0,"SourceDBOffset":0,"SourceAddress":"192.168.1.12:6379","TargetAddress":["192.168.100.12:6379"],"Details":null}]

**Comment by suxb201** [comment]
看起来是没到增量同步阶段呢。
源端内存上涨可能是 output-buffer 的内存使用。
