### ISSUE TITLE
客户端分片模式的集群能同步吗？

### ISSUE THREAD

**Issue by viciousstar** [aliyun/redis-shake#392]
比如原来我们使用2个客户端分片模式的源，因数据增长，现在需要同步到三个目标上。
这样源就是2个实例，目标是3个实例，而且要统一进行重新hash计算路由。

**Comment by suxb201** [comment]
第一次遇到这种需求，默认是不支持，但我认为你可以先把三个目标实例设置成集群，然后迁移，这样来实现

**Comment by viciousstar** [comment]
老系统了，动不了。而且也不支持集群模式。是不是可以在三个目标实例上起一个代理负责分片，然后源到代理？但是这时源和目标要用什么模式呢？都是standalone模式么？standalone支持多个源？

**Comment by suxb201** [comment]
sync 模式，开两个 redis-shake 就行。

**Comment by viciousstar** [comment]
嗯嗯 感谢
