### ISSUE TITLE
是否支持手工指定源端版本？

### ISSUE THREAD

**Issue by dddd529** [aliyun/redis-shake#394]
源端实例是华为云redis 执行info server没有信息返回，导致redis-shake报错Conf.Options check failed: get source redis version failed[MissingRedisVersionInInfo]； 该如何解决？
![image](https://user-images.githubusercontent.com/39817811/141882178-4a9d7d21-e794-46fe-afb1-e57daf37832f.png)

**Comment by suxb201** [comment]
直接把判断 version 的代码注释掉好了

**Comment by dddd529** [comment]
具体判断version的代码能帮忙圈一下么，另外如何编译

**Comment by suxb201** [comment]
https://github.com/alibaba/RedisShake/blob/0d72f6e6687d28f4b2218609d12f3a5bbf2ad0f0/src/redis-shake/main/sanitize.go#L351-L361

**Comment by dddd529** [comment]
编译的时候卡在这里了，为啥？
![image](https://user-images.githubusercontent.com/39817811/142130108-ffaf6ad6-3ce7-47c3-a66b-fb1110eff1d7.png)
![image](https://user-images.githubusercontent.com/39817811/142130124-2bf4367f-6a64-4881-969a-2b7fc9c359f0.png)

**Comment by suxb201** [comment]
sh build.sh 编译就好

**Comment by dddd529** [comment]
是sh build.sh 编译，不过一直卡在go build这步了
![image](https://user-images.githubusercontent.com/39817811/142130904-b4199979-608d-41a7-834f-c56e0d38b783.png)

**Comment by dddd529** [comment]
unknow revision
![image](https://user-images.githubusercontent.com/39817811/142143677-f7a067c8-f607-4742-aef3-37f9c216d6eb.png)

**Comment by suxb201** [comment]
试试：https://goproxy.cn/

**Comment by dddd529** [comment]
改用go1.16版本就好了；不过使用redis-shake有报错
![image](https://user-images.githubusercontent.com/39817811/142147503-17fa3c73-a397-4ca3-b162-a9777cff302c.png)

**Comment by dddd529** [comment]
用go 1.16版本就行；不过现在有报错，invalid info Keyspace；
![image](https://user-images.githubusercontent.com/39817811/142148492-09adf2d8-8898-4bdc-9721-f8eb1cbc42c9.png)

**Comment by dddd529** [comment]
源库执行info Keyspace没有信息返回，可以对应修改代码屏蔽掉这个检测吗

**Comment by suxb201** [comment]
你这是最新的代码吗？stack 信息对不上
info keyspace 你可以试着删除，我没试过

**Comment by dddd529** [comment]
是最新的，info keyspace的代码帮忙圈一下呢，我试试；

**Comment by suxb201** [comment]
搜报错就能搜到
