### ISSUE TITLE
从一个阿里云的redis实例中迁移至另一个阿里云redis实例，出现异常：repl listening-port failed[-ERR command replconf not support for your account]

### ISSUE THREAD

**Issue by scaler-hu** [aliyun/redis-shake#395]

**Comment by scaler-hu** [comment]
![image](https://user-images.githubusercontent.com/69282306/142576712-bf88c4f5-35b0-4487-ad17-0cd237007c7a.png)

**Comment by suxb201** [comment]
迁移的话走控制台就能搞吧，不用 shake 的。

**Comment by scaler-hu** [comment]
> 迁移的话走控制台就能搞吧，不用 shake 的。

运维沟通过，没有从redis迁移至redis中的工具。

**Comment by suxb201** [comment]
具体点你们是想怎么迁？
阿里云 Redis 数据库迁移到阿里云 Redis 数据库？
还是阿里云 Redis 数据库迁移到 ECS 自建数据库？

**Comment by scaler-hu** [comment]
> 具体点你们是想怎么迁？ 阿里云 Redis 数据库迁移到阿里云 Redis 数据库？ 还是阿里云 Redis 数据库迁移到 ECS 自建数据库？

阿里云的redis库迁移到另一个阿里云redis库，因为之前和别的项目共用一个redis库，现在想分开，重新购买了一个redis，想把老的redis的数据迁移到重新购买的redis中。本来想用DTS来同步，但是DTS同步会占用源库的资源，怕影响源库的业务。

**Comment by suxb201** [comment]
用 DTS 吧，redis-shake 和 DTS 对源端影响差不多的。建议在写入低的时候迁移。

**Comment by albertZhang2013** [comment]
请问当前版本支持从一个阿里云2.8的单点redis迁移到另一个阿里云2.8的单点redis吗？
询问阿里客服，答案是不能。但是从原理上来说应该是行得通的。DTS不支持阿里云2.8版本的redis，目前只能通过redis-shake进行迁移。

**Comment by suxb201** [comment]
> 请问当前版本支持从一个阿里云2.8的单点redis迁移到另一个阿里云2.8的单点redis吗？ 询问阿里客服，答案是不能。但是从原理上来说应该是行得通的。DTS不支持阿里云2.8版本的redis，目前只能通过redis-shake进行迁移。

1. 升级 Redis 版本
2. 试试 redis-shake 的 rump 模式

**Comment by albertZhang2013** [comment]
> > 请问当前版本支持从一个阿里云2.8的单点redis迁移到另一个阿里云2.8的单点redis吗？ 询问阿里客服，答案是不能。但是从原理上来说应该是行得通的。DTS不支持阿里云2.8版本的redis，目前只能通过redis-shake进行迁移。
> 
> 1. 升级 Redis 版本
> 2. 试试 redis-shake 的 rump 模式

好的，感谢。最终选择升级 redis 版本，然后再通过DTS解决。

**Comment by azbox2014** [comment]
> > > 请问当前版本支持从一个阿里云2.8的单点redis迁移到另一个阿里云2.8的单点redis吗？ 询问阿里客服，答案是不能。但是从原理上来说应该是行得通的。DTS不支持阿里云2.8版本的redis，目前只能通过redis-shake进行迁移。
> > 
> > 
> > 
> > 1. 升级 Redis 版本
> > 2. 试试 redis-shake 的 rump 模式
> 
> 好的，感谢。最终选择升级 redis 版本，然后再通过DTS解决。

我是用DTS也报了：ERR unknown command REPLCONF

![image](https://user-images.githubusercontent.com/9022651/143157849-3eeb428c-a0e9-4f36-a452-99d1733d85fc.png)

**Comment by suxb201** [comment]
@azbox2014 DTS 源库不支持 2.8 的 Redis，确认下你的 Redis 版本。
https://help.aliyun.com/document_detail/97027.html

**Comment by azbox2014** [comment]
> @azbox2014 DTS 源库不支持 2.8 的 Redis，确认下你的 Redis 版本。 https://help.aliyun.com/document_detail/97027.html

版本是5.0，问题已经解决了。需要在源库中创建一个复制权限的账号就可以同步了。

![image](https://user-images.githubusercontent.com/9022651/143163910-e51aaf3b-ff0a-40e7-ad4e-34a59cbc2df8.png)

新创建的账号：密码格式为<user>:<password>，默认账号也支持此认证方式。
例如自定义账号为testaccount，密码为Rp829dlwa，密码需填写为testaccount:Rp829dlwa

**Comment by azbox2014** [comment]
![image](https://user-images.githubusercontent.com/9022651/143164236-84f389c2-ddff-4ca6-b28f-430588c28a8f.png)

**Comment by chenyig001** [comment]
@scaler-hu 我也遇到了相同的问题，请问怎么解决的？

**Comment by suxb201** [comment]
@chenyig001 创建复制账号：https://help.aliyun.com/document_detail/92665.html
