### ISSUE TITLE
redis-shake存量同步RDB慢

### ISSUE THREAD

**Issue by jxqiuhan** [aliyun/redis-shake#396]
你好:

   我使用redis-shake迁移redis集群(3 master+3slave)，源端rdb一个是970MB左右

  redis-shake下载rdb非常慢，需要接近30分钟，网络带宽只使用了30%~40%

  这种一般是什么原因

**Comment by suxb201** [comment]
代码逻辑问题，现在是在下载 rdb 的同时解析 rdb 文件并发往 slave。
所以可能是 slave 执行 `restore` 命令过慢

**Comment by suxb201** [comment]
可以试试新版 shake 会有改善：https://github.com/alibaba/RedisShake/tree/v3
