### ISSUE TITLE
增量同步报错Aux information key:lua

### ISSUE THREAD

**Issue by hcc285964227** [aliyun/redis-shake#397]
2021/11/24 10:14:33 [INFO] DbSyncer[0] total = 147.95MB -     127.30MB [ 86%]  entry=1400680     
2021/11/24 10:14:34 [INFO] DbSyncer[0] total = 147.95MB -     131.02MB [ 88%]  entry=1441572     
2021/11/24 10:14:35 [INFO] DbSyncer[0] total = 147.95MB -     134.85MB [ 91%]  entry=1483805     
2021/11/24 10:14:36 [INFO] DbSyncer[0] total = 147.95MB -     138.64MB [ 93%]  entry=1525718     
2021/11/24 10:14:37 [INFO] DbSyncer[0] total = 147.95MB -     142.39MB [ 96%]  entry=1566927     
2021/11/24 10:14:38 [INFO] DbSyncer[0] total = 147.95MB -     146.15MB [ 98%]  entry=1608507     
2021/11/24 10:14:39 [INFO] Aux information key:lua value:local gva = redis.call('GET', KEYS[1])
if gva == ARGV[1] then
  redis.call('DEL', KEYS[1])
  return 1
end
return 0
2021/11/24 10:14:39 [PANIC] parse rdb checksum error
[error]: checksum validation failed
    1   github.com/alibaba/RedisShake/pkg/rdb/loader.go:53
            github.com/alibaba/RedisShake/pkg/rdb.(*Loader).Footer
    0   github.com/alibaba/RedisShake/redis-shake/common/utils.go:959
            github.com/alibaba/RedisShake/redis-shake/common.NewRDBLoader.func1
        ... ...
[stack]: 
    0   github.com/alibaba/RedisShake/redis-shake/common/utils.go:960
            github.com/alibaba/RedisShake/redis-shake/common.NewRDBLoader.func1
        ... ...

**Comment by suxb201** [comment]
重跑试试

**Comment by hcc285964227** [comment]
> 重跑试试
多次重跑都是这样

**Comment by suxb201** [comment]
@hcc285964227 这个报错是 rdb 文件的校验失败。还是怀疑源端 rdb 有问题，你可以采取几种方式验证下源端 rdb 是否正确，比如：
1. 复制出 rdb 使用 redis load 下，看看有没有报错
2. redis slaveof 上试试有没有报错
