### ISSUE TITLE
单机To单机linux版本只同步部分数据

### ISSUE THREAD

**Issue by ezy2021** [aliyun/redis-shake#398]
在单实例同步到单实例的情况，linux有部分redis目录数据没办法同步成功。类似xxx.yyy.zzz(3)实际只同步了xxx.yyy.zzz(1)。在windows下同一个版本的redis-shake没这个问题。测试的redis实例都安装在linux上，以docker方式安装部署。redis版本为6.2.6。redisshake版本为release-v2.1.1-20210903

**Comment by chenyang8094** [comment]
我没太看懂你的问题，能描述的详细点吗，或者贴点图或者log之类的

**Comment by ezy2021** [comment]
您好，问题应该找到了，是因为target和source的redis版本不一致有这个问题，版本一致的话，在linux下是正常的。
