### ISSUE TITLE
单机 to cluster报错（invalid psync response, continue）

### ISSUE THREAD

**Issue by haiwen1** [aliyun/redis-shake#399]
**命令：**
./redis-shake.linux -conf=redis-shake.conf -type=sync

**日志：**
tail -f /var/log/redis-shake.log 
 /        Alibaba Cloud        /         *             \ | |
/                             /                        (o)
#------------------------------
if you have any problem, please visit https://github.com/alibaba/RedisShake/wiki/FAQ

2021/12/01 14:02:24 [INFO] redis-shake configuration: {"ConfVersion":1,"Id":"redis-shake","LogFile":"/var/log/redis-shake.log","LogLevel":"info","SystemProfile":9310,"HttpProfile":9320,"Parallel":32,"SourceType":"standalone","SourceAddress":"192.168.1.163:6379","SourcePasswordRaw":"***","SourcePasswordEncoding":"***","SourceAuthType":"auth","SourceTLSEnable":false,"SourceRdbInput":["local"],"SourceRdbParallel":1,"SourceRdbSpecialCloud":"","TargetAddress":"192.168.1.164:7000;192.168.1.164:7001;192.168.1.164:7002","TargetPasswordRaw":"***","TargetPasswordEncoding":"***","TargetDBString":"-1","TargetAuthType":"auth","TargetType":"cluster","TargetTLSEnable":false,"TargetRdbOutput":"local_dump","TargetVersion":"3.2.8","FakeTime":"","KeyExists":"none","FilterDBWhitelist":["0"],"FilterDBBlacklist":[],"FilterKeyWhitelist":[],"FilterKeyBlacklist":[],"FilterSlot":[],"FilterLua":false,"BigKeyThreshold":524288000,"Metric":true,"MetricPrintLog":false,"SenderSize":104857600,"SenderCount":4095,"SenderDelayChannelSize":65535,"KeepAlive":0,"PidPath":"","ScanKeyNumber":50,"ScanSpecialCloud":"","ScanKeyFile":"","Qps":200000,"ResumeFromBreakPoint":false,"Psync":true,"NCpu":0,"HeartbeatUrl":"","HeartbeatInterval":10,"HeartbeatExternal":"","HeartbeatNetworkInterface":"","ReplaceHashTag":false,"ExtraInfo":false,"SockFileName":"","SockFileSize":0,"FilterKey":null,"FilterDB":"","Rewrite":false,"SourceAddressList":["192.168.1.163:6379"],"TargetAddressList":["192.168.1.164:7000","192.168.1.164:7001","192.168.1.164:7002"],"SourceVersion":"3.2.8","HeartbeatIp":"127.0.0.1","ShiftTime":0,"TargetReplace":true,"TargetDB":-1,"Version":"develop,d7cb0297f121e2f441d3636ef363871aa2ab5e25,go1.14.4,2020-07-24_17:19:07","Type":"sync"}
2021/12/01 14:02:24 [INFO] DbSyncer[0] starts syncing data from 192.168.1.163:6379 to [192.168.1.164:7000 192.168.1.164:7001 192.168.1.164:7002] with http[9321], enableResumeFromBreakPoint[false], slot boundary[-1, -1]
2021/12/01 14:02:24 [INFO] DbSyncer[0] psync connect '192.168.1.163:6379' with auth type[auth] OK!
2021/12/01 14:02:24 [INFO] DbSyncer[0] psync send listening port[9320] OK!
2021/12/01 14:02:24 [INFO] DbSyncer[0] try to send 'psync' command: run-id[?], offset[-1]
2021/12/01 15:02:25 [PANIC] invalid psync response, continue
[error]: EOF
    5   /Users/tongyao.lty/Work/RedisShake/src/pkg/redis/decoder.go:108
            pkg/redis.(*Decoder).decodeType
    4   /Users/tongyao.lty/Work/RedisShake/src/pkg/redis/decoder.go:67
            pkg/redis.(*Decoder).decodeResp
    3   /Users/tongyao.lty/Work/RedisShake/src/pkg/redis/decoder.go:33
            pkg/redis.Decode
    2   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/common/utils.go:243
            redis-shake/common.SendPSyncContinue
    1   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/syncBegin.go:50
            redis-shake/dbSync.(*DbSyncer).sendPSyncCmd
    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/dbSyncer.go:111
            redis-shake/dbSync.(*DbSyncer).Sync
        ... ...
[stack]: 
    2   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/common/utils.go:245
            redis-shake/common.SendPSyncContinue
    1   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/syncBegin.go:50
            redis-shake/dbSync.(*DbSyncer).sendPSyncCmd
    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/dbSyncer.go:111
            redis-shake/dbSync.(*DbSyncer).Sync
        ... ...

**redis版本：3.2.8**

**redis-shake-v2.0.3**

**centos7.9**

**Comment by haiwen1** [comment]
![1638352447598_62C939E5-F29A-41ee-9618-BD8007EF80AC](https://user-images.githubusercontent.com/87536676/144212475-29171e1f-41a0-4d76-8d81-18f48ea62a10.png)

**Comment by haiwen1** [comment]
汇总了测试结果。。

**Comment by haiwen1** [comment]
补充，数据量少(就几个key)的时候是可以的
![image](https://user-images.githubusercontent.com/87536676/144364858-8cf240b8-1e2b-4941-9667-be69c33c4187.png)

**Comment by haiwen1** [comment]
感觉跟数据量大小有关，rdb文件1G可迁移，rdb文件1.4G就不行了。。。

**Comment by haiwen1** [comment]
实锤了，跟内存大小有关，源redis不够内存......

![`~L_{W8M(JU6DA B32()KIR](https://user-images.githubusercontent.com/87536676/144374349-6dcc34c2-a2c8-47fe-9047-1e340d3d67c1.png)

**Comment by haiwen1** [comment]
自问自答结束，有老哥遇到可以借鉴

**Comment by chenyang8094** [comment]
> 自问自答结束，有老哥遇到可以借鉴

👍
