### ISSUE TITLE
Event:ErrorReply

### ISSUE THREAD

**Issue by githubwangxiaorui2019** [aliyun/redis-shake#401]
I got a problem when I did a increase sync!The error is below:

[INFO] Aux information key:lua value:local key = KEYS[1] 
local field = KEYS[2] 
local amount = tonumber(ARGV[1]) 
local limit = tonumber(ARGV[2]) 
local curlimit = tonumber(redis.call('HINCRBY',key,field,amount)) 
if (curlimit > limit) then 
redis.call('HINCRBY',key,field,-amount) 
return -1 
else 
return 1 
end
2021/12/07 10:51:30 [INFO] DbSyncer[0] total = 951.01MB -     951.01MB [100%]  entry=14294034      filter=33          
2021/12/07 10:51:30 [INFO] DbSyncer[0] sync rdb done
2021/12/07 10:51:30 [INFO] DbSyncer[0] FlushEvent:IncrSyncStart Id:redis-shake2
2021/12/07 10:51:30 [PANIC] DbSyncer[0] Event:ErrorReply        Id:redis-shake2 Command: [unknown]      Error: NOSCRIPT No matching script. Please use EVAL.
[stack]: 
    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/syncIncrease.go:120
            redis-shake/dbSync.(*DbSyncer).receiveTargetReply
        ... ...

**Comment by githubwangxiaorui2019** [comment]
I tried a few times,but they all failed!

**Comment by suxb201** [comment]
你的源端实例应该是 Redis4.0 或者更老的版本？

> starting with Redis 5, scripts are always replicated as effects and not sending the script verbatim. So the following section is mostly applicable to Redis version 4 or older.

https://redis.io/commands/eval#scripts-with-deterministic-writes

一种解决方案：在确认过数据安全的前提下，你可以更改 redis-shake 配置文件过滤掉 evalsha 命令
另一种方案：使用 Reids5.0 及以上版本

**Comment by githubwangxiaorui2019** [comment]
我的源实例是redis4.0，目的实例也是redis4.0
但是我redis2.8的实例，同步至redis4.0是可以的
为什么呢？

**Comment by suxb201** [comment]
可能运气好，aof 中还有 lua。

**Comment by githubwangxiaorui2019** [comment]
老师，请教一个问题

我从2.8直接通过从到主到从的方式进行数据同步升级至5.0版本，会出现不兼容的问题吗？

**Comment by githubwangxiaorui2019** [comment]
实际上我源端版本包含了2.8，3.2和4.0，当前主版本用的是3.2和4.0，不知道这些版本通过数据同步的方式升级至5.0，会不会有不兼容风险？

**Comment by suxb201** [comment]
> 

没问题的
