### ISSUE TITLE
redis-shake增量同步时，master推给redis-shake的命令很卡

### ISSUE THREAD

**Issue by jxqiuhan** [aliyun/redis-shake#402]
你好:

    redis-shake本身是作为伪装slave，接入到matser上的
    我们这边源matser下有两个slave节点：  业务slave0，slave1(redis-shake)

我们发现slave0的offset可以跟上源matser
但是slave1的offset跟不上master

麻烦帮忙确认下一般是什么原因

**Comment by suxb201** [comment]
Redis 收到命令后直接执行，速度很快
redis-shake 收到命令后需要转发，会慢些。有爆 buffer 风险

这一块 shake 其实可以搞个磁盘 buffer，能解决一大部分问题，但一直没时间搞。

**Comment by jxqiuhan** [comment]
redis-shake处理增量命令的时候，是一次拉取一批，

执行步骤应该是   从源端读一批增量命令--->解析命令----->写入pipeline------>批量flush------>等到目的端回复reply id------->上一次命令回复完后------>再从源端读一批增量命令。。。。。

你好，请问我描述的增量处理流程有没有问题

**Comment by suxb201** [comment]
没问题

**Comment by jxqiuhan** [comment]
你好：

我这边进行了一些其他的测试，也查看了redis-shake的源码

发现主要的瓶颈还是在网络传输速率上的瓶颈
源redis和目标redis的时间延迟是40ms
导致传输时，传输速率大概是4.9Mbps
而源redis的写入速率是10MB/s

redis-shake对源命令的拉去，命令的解析，批量的flush；目标redis执行命令、返回成功的reply id性能都相对很快，量不大的话不会产生性能问题

 我这边主要性能瓶颈还是在跨区网络慢上，与redis-shake无关
