### ISSUE TITLE
是否支持aarch64环境运行，如何编译？

### ISSUE THREAD

**Issue by lynn447742** [aliyun/redis-shake#405]

**Comment by chenyang8094** [comment]
我所知的我们内部版本是支持的，你可以在你的arm环境中执行build.sh看看

**Comment by lynn447742** [comment]
> 我所知的我们内部版本是支持的，你可以在你的arm环境中执行build.sh看看

你好：

下载源码执行编译后，报`reading github.com/BurntSushi/toml/go.mod at revision v0.3.1: unknown revision v0.3.1`.
```
[root@localhost RedisShake-release-v2.1.1-20210903]# bash build.sh 
[ BUILD RELEASE ]
try build GOOS=linux
go: github.com/BurntSushi/toml@v0.3.1: reading github.com/BurntSushi/toml/go.mod at revision v0.3.1: unknown revision v0.3.1
```

**Comment by suxb201** [comment]
我没有 arm 环境，你试试这个：https://github.com/alibaba/RedisShake/releases/tag/Experimental-release-for-arm

**Comment by chenyang8094** [comment]
你这个错误看着像go版本太低的原因。可以试一下我们提供的包或者升级go版本再试一下。

**Comment by lynn447742** [comment]
> 我没有 arm 环境，你试试这个：https://github.com/alibaba/RedisShake/releases/tag/Experimental-release-for-arm

完美运行，感谢！
