### ISSUE TITLE
cluster type address check equal

### ISSUE THREAD

**Issue by nichoalsliu** [aliyun/redis-shake#406]
common/command.go

func CheckSlotDistributionEqual(src, dst []SlotOwner) bool {
	if len(src) != len(dst) {
		return false
	}

	for i := 0; i < len(src); i++ {
		if src[i].SlotLeftBoundary != src[i].SlotLeftBoundary ||
			src[i].SlotRightBoundary != src[i].SlotRightBoundary {
			return false
		}
	}
	return true
}

should src compare with dst

**Comment by suxb201** [comment]
是的，有 bug。
