### ISSUE TITLE
从集群同步到单机，只同步过去部分数据

### ISSUE THREAD

**Issue by v587xpt** [aliyun/redis-shake#407]
源redis集群是三主三从架构，目的redis是一个单机；
配置：
`
key_exists = rewrite
source.type = cluster
source.address = master@192.168.1.121:6379
source.password_raw =

target.type = standalone
target.address = 192.168.2.12:6379
target.password_raw =
`
当执行  ./redis-shake.linux -conf=redis-shake.conf -type=sync  并增量同步之后，目标redis中的数据并不是全完的，只有集群数据的一部分；

**Comment by suxb201** [comment]
更详细的信息有吗？比如什么数据丢了，比如同步完成后只有某一分片的数据。

**Comment by v587xpt** [comment]
在三主三从中，
```
       主                                  从
192.168.1.121:6379                192.168.1.122:6379
192.168.1.121:7379                192.168.1.122:7379
192.168.1.121:8379                192.168.1.122:8379
```
192.168.1.121:6379 的数量为 5933
192.168.1.121:7379 的数量为 33
192.168.1.121:8379 的数量为 5967
而sync到单机后，单机redis中的数据量为6000；
手动抽查了部分数据，在单机redis中并没有找到 192.168.1.121:6379 的数据，貌似是它并并有导入成功；

**Comment by suxb201** [comment]
source.address = master@192.168.1.121:6379
改成
source.address = 192.168.1.121:6379;192.168.1.121:7379;192.168.1.121:8379

**Comment by v587xpt** [comment]
这两种配置都试了一试，同步得到的结果是相同的；

**Comment by suxb201** [comment]
@v587xpt 
麻烦检查下日志
1. 启动 redis-shake 后日志中有没有 warn 或 error ？
2. 启动 redis-shake 后的时刻，192.168.1.121:6379 端的日志中有没有报错？
