### ISSUE TITLE
从单机迁移到集群，迁移时候未提示报错 但是目标redis没有数据

### ISSUE THREAD

**Issue by zhuchaowei24** [aliyun/redis-shake#408]
源redis版本：4.0.2 （数据量大概2G左右）
目标redis集群版本：5.0.14
![image](https://user-images.githubusercontent.com/29916440/147810369-71f05de4-8c7e-4b4c-8e39-9ad594e93775.png)
已经显示rdb同步完成,但是目标集群数据数据仍然为空
![image](https://user-images.githubusercontent.com/29916440/147810404-2db5bbff-e216-4331-8d84-d003842cea5a.png)

配置如下：
conf.version = 1

id = redis-shake

log.file =

log.level = info

pid_path =

system_profile = 9310

http_profile = 9320

parallel = 32

source.type = standalone

source.address = 10.230.1.181:6379

source.password_raw = 123456

source.auth_type = auth

source.tls_enable = false

source.rdb.input =

source.rdb.parallel = 0

source.rdb.special_cloud =

target.type = cluster

target.address = 10.230.1.153:6371;10.230.1.153:6372;10.230.1.153:6373

target.password_raw = 123456

target.auth_type = auth

target.db = -1

target.dbmap =

target.tls_enable = false

target.rdb.output = local_dump

target.version = 5.0.14

fake_time =

key_exists = none

filter.db.whitelist =

filter.db.blacklist =

filter.key.whitelist =

filter.key.blacklist =

filter.slot =

filter.lua = false

big_key_threshold = 1

metric = true

metric.print_log = false

sender.size = 1048576

sender.count = 40950

sender.delay_channel_size = 65535
。
keep_alive = 0

scan.key_number = 100

scan.special_cloud =

scan.key_file =

qps = 20000000

resume_from_break_point = false

replace_hash_tag = false

**Comment by chenyang8094** [comment]
确认下是否源端的数据是否设置了过期时间并且都已经过期了

**Comment by zhuchaowei24** [comment]
> 确认下是否源端的数据是否设置了过期时间并且都已经过期了

可以了 ，要设置 target.db = 0 默认值-1 就不能导入成功
