### ISSUE TITLE
数据一点没同步，直接报错退出了

### ISSUE THREAD

**Issue by 1342843039** [aliyun/redis-shake#409]
2022/01/15 11:33:54 [INFO] DbSyncer[0] -
2022/01/15 11:33:55 [INFO] DbSyncer[0] -
2022/01/15 11:33:56 [INFO] DbSyncer[0] -
2022/01/15 11:33:57 [INFO] DbSyncer[0] -
2022/01/15 11:33:58 [INFO] DbSyncer[0] -
2022/01/15 11:33:59 [INFO] DbSyncer[0] -
2022/01/15 11:34:00 [INFO] DbSyncer[0] -
2022/01/15 11:34:01 [INFO] DbSyncer[0] -
2022/01/15 11:34:02 [INFO] DbSyncer[0] -
2022/01/15 11:34:03 [INFO] DbSyncer[0] -
2022/01/15 11:34:04 [INFO] DbSyncer[0] -
2022/01/15 11:34:05 [INFO] DbSyncer[0] -
2022/01/15 11:34:06 [INFO] DbSyncer[0] -
2022/01/15 11:34:07 [INFO] DbSyncer[0] -
2022/01/15 11:34:08 [INFO] DbSyncer[0] -
2022/01/15 11:34:09 [INFO] DbSyncer[0] -
2022/01/15 11:34:10 [INFO] DbSyncer[0] -
2022/01/15 11:34:11 [INFO] DbSyncer[0] -
2022/01/15 11:34:12 [INFO] DbSyncer[0] -
2022/01/15 11:34:13 [PANIC] read sync response = ''
[error]: EOF
[stack]: 
    0   github.com/alibaba/RedisShake/redis-shake/common/utils.go:181
            github.com/alibaba/RedisShake/redis-shake/common.waitRdbDump.func1
        ... ...
^C
[1]+  退出 1                nohup ./redis-shake.linux -conf=./redis-shake.conf -type=sync

**Comment by suxb201** [comment]
看下源 Redis 上的 log，是不是爆 buffer 了

**Comment by 1342843039** [comment]
确实是，请教大佬该咋解决呢

**Comment by suxb201** [comment]
buffer 调大，或者等写入流量小的时候再搞。
