### ISSUE TITLE
tls支持情况咨询

### ISSUE THREAD

**Issue by lsw21** [aliyun/redis-shake#410]
目前redis 6版本已支持tls，看到redis-shake配置文件中有如下参数：
#tls enable, true or false. Currently, only support standalone.
#open source redis does NOT support tls so far, but some cloud versions do.
source.tls_enable = false

未看到文档明确说明，咨询如下内容，谢谢！
1、是否支持tls方式同步数据，如果支持，只需设置 source.tls_enable = true？是否需要加载CA证书
2、只支持单机方式传输？（only support standalone）

**Comment by suxb201** [comment]
1. 设置成 true 即可，不需要 ca，原理是跳过证书校验
2. 是的

**Comment by lsw21** [comment]
按以上的配置，redis-shake访问源redis报错：
[error]: x509: cannot validate certificate for X.X.X.X because it doesn't contain any IP SANs [stack]:
但通过redis-cli命令行方式可以（redis-cli -h IP -p PORT --tls --cacert ./ca.crt）

软件版本：
redis 6.0.8 启用TLS
redis-shake-1.6.26
使用的自签名证书

不知哪里的问题，谢谢！

**Comment by suxb201** [comment]
两个都设置成 true
```
source.tls_enable = true
source.tls_skip_verify = true
```

**Comment by lsw21** [comment]
已下载最新develop分支进行编译，测试通过，谢谢！
是需要最新develop分支才可以用这个参数吧（source.tls_skip_verify），看其他版本没有该参数。

**Comment by suxb201** [comment]
哦，是的，还没发包。
