### ISSUE TITLE
[error]: unknown object-type 07

### ISSUE THREAD

**Issue by glyslxq** [aliyun/redis-shake#413]
是不是不支持redis json呀？

2022/01/21 09:49:27 [INFO] DbSyncer[0] -
2022/01/21 09:49:27 [INFO] DbSyncer[0] +
2022/01/21 09:49:27 [INFO] DbSyncer[0] rdb file size = 12906149297
2022/01/21 09:49:27 [INFO] Aux information key:redis-ver value:6.2.5
2022/01/21 09:49:27 [INFO] Aux information key:redis-bits value:64
2022/01/21 09:49:27 [INFO] Aux information key:ctime value:1642729446
2022/01/21 09:49:27 [INFO] Aux information key:used-mem value:50827507200
2022/01/21 09:49:27 [INFO] Aux information key:repl-stream-db value:0
2022/01/21 09:49:27 [INFO] Aux information key:repl-id value:79439d4c1e777409e57b2b37efe4818e8aa242b3
2022/01/21 09:49:27 [INFO] Aux information key:repl-offset value:0
2022/01/21 09:49:27 [INFO] Aux information key:aof-preamble value:0
2022/01/21 09:49:27 [INFO] db_size:8548481 expire_size:0
2022/01/21 09:49:27 [PANIC] parse rdb entry error, if the err is :EOF, please check that if the src db log has client outout buffer oom, if so set output buffer larger.
[error]: unknown object-type 07
    2   github.com/alibaba/RedisShake/pkg/rdb/reader.go:109
            github.com/alibaba/RedisShake/pkg/rdb.(*rdbReader).readObjectValue
    1   github.com/alibaba/RedisShake/pkg/rdb/loader.go:202
            github.com/alibaba/RedisShake/pkg/rdb.(*Loader).NextBinEntry
    0   github.com/alibaba/RedisShake/redis-shake/common/utils.go:952
            github.com/alibaba/RedisShake/redis-shake/common.NewRDBLoader.func1
        ... ...
[stack]: 
    0   github.com/alibaba/RedisShake/redis-shake/common/utils.go:953
            github.com/alibaba/RedisShake/redis-shake/common.NewRDBLoader.func1
        ... ...

**Comment by suxb201** [comment]
不支持
