### ISSUE TITLE
[BUG]同步完后报错退出

### ISSUE THREAD

**Issue by Leadrive** [aliyun/redis-shake#415]
2022/02/09 22:21:58 [PANIC] DbSyncer[0] Event:NetErrorWhileReceive      Id:redis-shake  Error:EOF
[stack]:
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/syncIncrease.go:117
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).receiveTargetReply
        ... ...

**Comment by suxb201** [comment]
应该是误报，确认下数据没问题吧

**Comment by suxb201** [comment]
试试新版，应该不会有这种问题了：https://github.com/alibaba/RedisShake/tree/v3
