### ISSUE TITLE
[BUG] 三主三从架构，增量同步失败

### ISSUE THREAD

**Issue by Charles1007** [aliyun/redis-shake#416]
2022/02/10 15:04:26 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:27 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:27 [ERROR] dbSyncer[0] send offset to source redis failed[write tcp  xx.xx.xx.34:42527-> xx.xx.xx.34:6379: write: connection reset by peer]
[stack]: 
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/syncBegin.go:145
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).pSyncPipeCopy.func1
        ... ...
2022/02/10 15:04:27 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:27 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:28 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:28 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:28 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:29 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:29 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:29 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:30 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:30 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:30 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:31 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:31 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:31 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:32 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:32 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
--
2022/02/10 15:04:39 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:39 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:39 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:40 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:40 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:40 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:41 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:41 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:41 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:42 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:42 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:42 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:43 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:43 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:43 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:44 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:44 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:44 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:45 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:45 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:45 [ERROR] dbSyncer[2] send offset to source redis failed[write tcp  xx.xx.xx.34:45407-> xx.xx.xx.37:6379: write: connection reset by peer]
[stack]: 
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/syncBegin.go:145
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).pSyncPipeCopy.func1
        ... ...
2022/02/10 15:04:45 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:46 [WARN] DbSyncer[0] Event:GetFakeSlaveOffsetFail     Id:redis-shake  Warn:OffsetNotFoundInInfo
2022/02/10 15:04:46 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:46 [WARN] DbSyncer[2] Event:GetFakeSlaveOffsetFail     Id:redis-shake  Warn:OffsetNotFoundInInfo
2022/02/10 15:04:46 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:46 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:47 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:47 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:47 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:48 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:48 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:48 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:49 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:49 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:49 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/02/10 15:04:49 [ERROR] dbSyncer[1] send offset to source redis failed[write tcp xx.xx.xx.34:54523->xx.xx.xx.35:6379: write: connection reset by peer]
[stack]: 
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/syncBegin.go:145
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).pSyncPipeCopy.func1
        ... ...
2022/02/10 15:04:50 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0

**Comment by suxb201** [comment]
看看源端日志，可能是源端主动断连了
```
2022/02/10 15:04:49 [ERROR] dbSyncer[1] send offset to source redis failed[write tcp xx.xx.xx.34:54523->xx.xx.xx.35:6379: write: connection reset by peer]
```

**Comment by Charles1007** [comment]
源端日志
 Client id=15577747 addr=xx.xx.xx.34:43960 fd=1832 name= age=820 idle=1 flags=S db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=16383 oll=3788 omem=77669152 events=rw cmd=replconf scheduled to be closed ASAP for overcoming of output buffer limits.

client-output-buffer-limit的默认配置'slave 256mb 64mb 60'，我扩大了4倍，还是不行，为什么会断开呀？

（ps:增量同步的情况）

**Comment by suxb201** [comment]
再调大些，512mb 0 0 试试。

**Comment by Charles1007** [comment]
> 再调大些，512mb 0 0 试试。

我用1024mb 256mb 240试的，报错只会迟到~~~并没有消失。我们有2套相同配置源端和目的redis，数据量不一样，另外一套数据量只有几十m，工具挺好用，全量和增量都没问题。报错的这套rdb每个节点大概600m，难道跟数据量有关系？

我先试试你发的配置

**Comment by suxb201** [comment]
写入流量是不是挺大的

**Comment by Charles1007** [comment]
> 写入流量是不是挺大的

config set client-output-buffer-limit 'slave 0 0 0'

改成无限制，还是不可以，增量同步不过去

**Comment by Charles1007** [comment]
[redis-shake日志.txt](https://github.com/alibaba/RedisShake/files/8076485/redis-shake.txt)

**Comment by suxb201** [comment]
> [redis-shake日志.txt](https://github.com/alibaba/RedisShake/files/8076485/redis-shake.txt)

这个日志看着没问题

**Comment by Charles1007** [comment]
> > [redis-shake日志.txt](https://github.com/alibaba/RedisShake/files/8076485/redis-shake.txt)
> 
> 这个日志看着没问题

大佬 还有解决思路么？

**Comment by suxb201** [comment]
你发的日志里面都是正常的，也没有 ERROR。是不是发错日志了？

**Comment by Charles1007** [comment]
> 你发的日志里面都是正常的，也没有 ERROR。是不是发错日志了？

我在源端redis上set个值，大概等几分钟，日志就会出现帖子最上面的error了，error都是同一个，没变

**Comment by Charles1007** [comment]
config set repl-timeout 3600
config set repl-backlog-size 2199023255552  --(2个T)
config set client-output-buffer-limit "normal 0 0 0 slave 0 0 0 pubsub 33554432 8388608 60"

我在主从6个节点 配置都调大了，不报错了，但是没增量

**Comment by suxb201** [comment]
看下同步时源端的 info replication

**Comment by Charles1007** [comment]
> 看下同步时源端的 info replication

主：
127.0.0.1:6379> info replication
# Replication
role:master
connected_slaves:1
slave0:ip=xx.xx.xx.38,port=6379,state=online,offset=1370710267402,lag=0
master_replid:77ad011afff3eb585297b26773e5622776ca2a73
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:1370710268713
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:2199023255552
repl_backlog_first_byte_offset:1370518290811
repl_backlog_histlen:191977903


从：
127.0.0.1:6379> info replication
# Replication
role:slave
master_host:xx.xx.xx.34
master_port:6379
master_link_status:up
master_last_io_seconds_ago:0
master_sync_in_progress:0
slave_repl_offset:1370866351740
slave_priority:100
slave_read_only:1
connected_slaves:1
slave0:ip=xx.xx.xx.34,port=9320,state=send_bulk,offset=0,lag=0
master_replid:77ad011afff3eb585297b26773e5622776ca2a73
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:1370866351740
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:2199023255552
repl_backlog_first_byte_offset:1370847714469
repl_backlog_histlen:18637272

**Comment by suxb201** [comment]
你 redis-shake 的配置文件我看下吧，你的源端配置的是三主吗？

**Comment by Charles1007** [comment]
> 你 redis-shake 的配置文件我看下吧，你的源端配置的是三主吗？

我配置的三从  源端不是可以配置成三从嘛
[redis-shake配置文件.txt](https://github.com/alibaba/RedisShake/files/8113432/redis-shake.txt)

另外  源端redis 没开启aof ，不影响吧

**Comment by kunCharles** [comment]
>

**Comment by suxb201** [comment]
slave 上显示 state 为 send_bulk，没问题，还在传输 rdb。等 slave state online 后看看同步状态

**Comment by Charles1007** [comment]
> slave 上显示 state 为 send_bulk，没问题，还在传输 rdb。等 slave state online 后看看同步状态

主：
127.0.0.1:6379> info replication
# Replication
role:master
connected_slaves:1
slave0:ip=xx.xx.xx.38,port=6379,state=online,offset=1373373016472,lag=0
master_replid:77ad011afff3eb585297b26773e5622776ca2a73
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:1373373016509
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:2199023255552
repl_backlog_first_byte_offset:1370518290811
repl_backlog_histlen:2854725699

从：
127.0.0.1:6379> info replication
# Replication
role:slave
master_host:xx.xx.xx.34
master_port:6379
master_link_status:up
master_last_io_seconds_ago:0
master_sync_in_progress:0
slave_repl_offset:1373376405088
slave_priority:100
slave_read_only:1
connected_slaves:1
slave0:ip=xx.xx.xx.34,port=9320,state=online,offset=1373219321549,lag=1
master_replid:77ad011afff3eb585297b26773e5622776ca2a73
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:1373376405088
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:2199023255552
repl_backlog_first_byte_offset:1370847714469
repl_backlog_histlen:2528690620

**Comment by suxb201** [comment]
看着正常，数据还有问题吗？

**Comment by Charles1007** [comment]
> 看着正常，数据还有问题吗？

有问题 ，日志一直是 sync: +forwardCommands=0 +filterCommands=0 +writeBytes=0，没增量，大概每个master有30w个key，其中10w个是有有效期的，增量过程中，目的端的key一直在减少，如果增量能过去的话，日志会一直刷数据吧

**Comment by suxb201** [comment]
“30w个key，其中10w个是有有效期的” 是指 10w 个是带过期时间的吗？
增量期间源端没有新的写入吗，你是通过过期来判断增量的？

你可以 monitor 到目的端看看有没有写入。

**Comment by Charles1007** [comment]
> “30w个key，其中10w个是有有效期的” 是指 10w 个是带过期时间的吗？ 增量期间源端没有新的写入吗，你是通过过期来判断增量的？
> 
> 你可以 monitor 到目的端看看有没有写入。

不是哈，我是在源端set值，判断有没有同步到目的端的。30w个key写入了

**Comment by suxb201** [comment]
试试这个版本：https://github.com/alibaba/RedisShake/tree/v3
