### ISSUE TITLE
redis-shake多数据中心双向部分key同步

### ISSUE THREAD

**Issue by xiehai** [aliyun/redis-shake#417]
redis-shake两个数据中心双向同步，两个数据中心各自部署redis-shake，相互配置为源端、目标端，通过filter.key.blacklist、filter.key.whitelist来协议需要同步的键，但是在redis-shake.log 中会不断打印DbSyncer[0] delayChannel is full，导致文件不断增加，请问有什么办法让文件不增加

**Comment by suxb201** [comment]
你怎么解决回环问题的？

**Comment by your-boy** [comment]
所以回环问题怎么解决

**Comment by cheney-plus** [comment]
在判断源端是否存在命令的 md5，如果没有在目标端存一份，解决回环问题
