### ISSUE TITLE
dump 数据失败

### ISSUE THREAD

**Issue by zvzo** [aliyun/redis-shake#418]
[PANIC] invalid sync response = '$CKP:23541
', n = 0
[error]: strconv.Atoi: parsing "CKP:23541": invalid syntax
[stack]: 
    0   github.com/alibaba/RedisShake/redis-shake/common/utils.go:197
            github.com/alibaba/RedisShake/redis-shake/common.waitRdbDump.func1
        ... ...

redis_version:4.0.11

dump 数据数据报错

**Comment by suxb201** [comment]
你的源数据库是在哪的？阿里云售卖的 redis 吗？

**Comment by zvzo** [comment]
> 你的源数据库是在哪的？阿里云售卖的 redis 吗？

是阿里云的, 混合存储型

**Comment by suxb201** [comment]
@mabloc 阿里云的协议是定制过的，没法解析。
