### ISSUE TITLE
增量同步过程切换写操作是否会导致数据错乱

### ISSUE THREAD

**Issue by 234424169** [aliyun/redis-shake#419]
目前我们的方案是做同步+增量同步，待一致后把写操作切到新的缓存，但我担心有这么个问题：
在切换写操作过程中，还有数据在同步，若刚好同步的数据中的KEY和切换后新写的KEY是一样，但值不同，会不会导致数据不一致？

例如先写旧缓存A=1，同步中，此时切换写，并往新缓存写A=2，那此时不确定是A=1还是A=2先到达新的缓存，会不会导致数据有问题？

**Comment by suxb201** [comment]
先停业务流量，等一致后再切

**Comment by 234424169** [comment]
> 先停业务流量，等一致后再切

如果停的话时间肯定不能长，同步的延迟目前有经验值是大概多长时间吗？另外怎么在停业务的时候判断增量同步已经一致呢？

**Comment by chenyang8094** [comment]
可以看源端主备之间的offset差值，如果两者差异在一定阈值（比如在10MB以内），可以源端停写，然后等主备offset一致时再写新实例。
