### ISSUE TITLE
[PANIC] invalid psync response, continue, ERR unknown command ' psync ' 

### ISSUE THREAD

**Issue by wenzhucjy** [aliyun/redis-shake#423]
源redis腾讯云，目标是自建redis
[PANIC] invalid psync response, continue, ERR unknown command ' psync '
[stack]: 
    2   github.com/alibaba/RedisShake/redis-shake/common/utils.go:251
            github.com/alibaba/RedisShake/redis-shake/common.SendPSyncContinue
    1   github.com/alibaba/RedisShake/redis-shake/dbSync/syncBegin.go:50
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).sendPSyncCmd
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/dbSyncer.go:111
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).Sync

**Comment by suxb201** [comment]
找客服，腾讯云不支持 psync 命令，不想让你下云。

**Comment by wenzhucjy** [comment]
已经开通了，但是导入到最后100%，提示
  [INFO] DbSyncer[0] sync rdb done
  [INFO] DbSyncer[0] FlushEvent:IncrSyncStart Id:redis-shake
 [PANIC] DbSyncer[0] parse command arguments failed[expect Array, but got <*redis.Error>]
[error]: expect Array, but got <*redis.Error>
    2   github.com/alibaba/RedisShake/pkg/redis/resp.go:165
            github.com/alibaba/RedisShake/pkg/redis.AsArray
    1   github.com/alibaba/RedisShake/pkg/redis/handler.go:88
            github.com/alibaba/RedisShake/pkg/redis.ParseArgs
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/syncIncrease.go:185
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).parseSourceCommand
        ... ...
[stack]: 
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/syncIncrease.go:186
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).parseSourceCommand

**Comment by suxb201** [comment]
怀疑 tx 有一些非标命令

**Comment by brendandebeasi** [comment]
This has been addressed in the [docs here](https://tair-opensource.github.io/RedisShake/en/guide/mode.html#aws-elasticache-and-memorydb)
