### ISSUE TITLE
[BUG] Support for module types in RedisShake

### ISSUE THREAD

**Issue by filipecosta90** [aliyun/redis-shake#427]
**Describe the bug**

Given modules are allowed to define datatypes, the tool should be able to issue restores for that specific type. ( that will enable agnostic datatype loads )

**To reproduce**

Use any of the modules that adds new datatype and issue:
```
./bin/redis-shake.linux -type restore -conf ./conf/redis-shake.conf
```

**Additional information**

Error log:
```
2022/03/28 12:19:53 [INFO] input password is empty, skip auth address[127.0.0.1:6379] with type[auth].
2022/03/28 12:19:53 [PANIC] parse rdb entry error, if the err is :EOF, please check that if the src db log has client output buffer oom, if so set output buffer larger.
[error]: unknown module name[TSDB-TYPE] with module id[5557655216273166340]
[stack]: 
    0   github.com/alibaba/RedisShake/redis-shake/common/utils.go:958
            github.com/alibaba/RedisShake/redis-shake/common.NewRDBLoader.func1

```

**Comment by suxb201** [comment]
Now that we have refactored a new version of redis-shake, it is relatively easy to add module support.
https://github.com/alibaba/RedisShake/tree/v3#redis-module-support

**Comment by Kalone-Lin** [comment]
Is there currently no support for modules?
Error "unknown module type:" will be reported when running

**Comment by suxb201** [comment]
@Kalone-Lin Yes, which module are you using? You can add module support yourself by submitting a PR.
