### ISSUE TITLE
支持主从切换

### ISSUE THREAD

**Issue by blue0sky123** [aliyun/redis-shake#428]
同步过程中发生主从切换，因连接不上之前配置的主节点，同步异常终止

**Comment by 15280402260** [comment]
相同问题：在集群同步过程中，发生主从切换，造成因链接断开，redis-shake异常退出。是否有解决方案，保证redis-shake不会退出且自动已新切换的主节点建立链接

**Comment by xiaoMG-X** [comment]
相同问题：在集群同步过程中，发生主从切换，造成因链接断开，redis-shake异常退出。是否有解决方案，保证redis-shake不会退出且自动已新切换的主节点建立链接

**Comment by suxb201** [comment]
现在不支持。
请问你们的场景是什么？理论上数据迁移期间发生 ha 的概率不大，可以接受。

**Comment by xiaoMG-X** [comment]
场景：在增量同步阶段，源或目的集群节点1主节点宕机，节点1从节点升为主节点，此时redis-shake会退出。希望保证不会退出，redis-shake可自动与新主节点建立链接

**Comment by xiaoMG-X** [comment]
> 现在不支持。 请问你们的场景是什么？理论上数据迁移期间发生 ha 的概率不大，可以接受。

场景：在增量同步阶段，源或目的集群节点1主节点宕机，节点1从节点升为主节点，此时redis-shake会退出。希望保证不会退出，redis-shake可自动与新主节点建立链接

**Comment by suxb201** [comment]
不会支持，也没有好的办法支持。
因为同步时间不会很长，所以发生概率较低。目前不建议长时间拿 redis-shake 保持同步。
