### ISSUE TITLE
is the faq for question "How to check if the migration is finished" not updated?

### ISSUE THREAD

**Issue by echo-of-wind** [aliyun/redis-shake#431]
for version develop, "cc226f841e2e244c48246ebfcfd5a50396b59710,go1.15.7,2021-09-03_10:06:55", no metrics called "PullCommandTotal, BypassCommandTotal, PushCommandTotal" exist, and should it be "PullCmdCountTotal, BypassCmdCountTotal, PushCmdCountTotal" instead?

**Comment by suxb201** [comment]
Yes, the old wiki is not used anymore, please use the new version of redis-shake: https://github.com/alibaba/RedisShake/tree/v3
