### ISSUE TITLE
[BUG]全量同步完成后，增量同步数据一直同步不过来，10分钟左右后redis-shake报错退出

### ISSUE THREAD

**Issue by xuyapei123** [aliyun/redis-shake#436]
2022/05/18 19:46:16 [INFO] [{"StartTime":"2022-05-18T19:35:56Z","PullCmdCount":0,"PullCmdCountTotal":4100,"BypassCmdCount":0,"BypassCmdC
ountTotal":0,"PushCmdCount":0,"PushCmdCountTotal":4,"SuccessCmdCount":0,"SuccessCmdCountTotal":2,"FailCmdCount":0,"FailCmdCountTotal":0,
"Delay":"null ms","AvgDelay":"null ms","NetworkSpeed":0,"NetworkFlowTotal":646,"FullSyncProgress":100,"Status":"incr","SenderBufCount":4
095,"ProcessingCmdCount":1,"TargetDBOffset":718406627822,"SourceDBOffset":718419417387,"SourceAddress":"XXXXXX:6379","TargetAddres
s":["XXXXXX:6379","XXXXXX:6379","XXXXXX:6379"],"Details":null},{"StartTime":"2022-05-18T19:35:56Z","PullCmdCount":0
,"PullCmdCountTotal":4193,"BypassCmdCount":0,"BypassCmdCountTotal":0,"PushCmdCount":0,"PushCmdCountTotal":97,"SuccessCmdCount":0,"Succes
sCmdCountTotal":95,"FailCmdCount":0,"FailCmdCountTotal":0,"Delay":"null ms","AvgDelay":"null ms","NetworkSpeed":0,"NetworkFlowTotal":888
8,"FullSyncProgress":100,"Status":"incr","SenderBufCount":4095,"ProcessingCmdCount":48,"TargetDBOffset":846670013217,"SourceDBOffset":84
6680707112,"SourceAddress":"10.18.51.193:6379","TargetAddress":["XXXXXX:6379","XXXXXX:6379","XXXXXX:6379"],"Details
":null},{"StartTime":"2022-05-18T19:35:56Z","PullCmdCount":0,"PullCmdCountTotal":4196,"BypassCmdCount":0,"BypassCmdCountTotal":0,"PushCm
dCount":0,"PushCmdCountTotal":100,"SuccessCmdCount":0,"SuccessCmdCountTotal":98,"FailCmdCount":0,"FailCmdCountTotal":0,"Delay":"null ms"
,"AvgDelay":"null ms","NetworkSpeed":0,"NetworkFlowTotal":8688,"FullSyncProgress":100,"Status":"incr","SenderBufCount":4095,"ProcessingC
mdCount":49,"TargetDBOffset":729493026345,"SourceDBOffset":729506187142,"SourceAddress":"XXXXXX:6379","TargetAddress":["XXXXXX:6379","XXXXXX:6379","XXXXXX:6379"],"Details":null}]
2022/05/18 19:46:16 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:17 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:17 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:17 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:18 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:18 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:18 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:19 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:19 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:19 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:20 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:20 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:20 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:21 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:21 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:21 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2022/05/18 19:46:22 [PANIC] DbSyncer[1] Event:FlushFail Id:GIS-rds-shake        Error:EOF
[stack]: 
    1   github.com/alibaba/RedisShake/redis-shake/dbSync/syncIncrease.go:369
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).sendTargetCommand.func1
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/syncIncrease.go:423
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).sendTargetCommand
        ... ...

**Comment by xuyapei123** [comment]
redis-shake版本：2.1.2
源集群：3主3从  版本：4.0.12
目标集群：3主3从  版本：5.0.5

全量同步能正常完成，增量同步数据不过来（我手动执行set 和del 命令不会同步过来），麻烦源码大神看下，报错信息太少了，不知道啥原因。

**Comment by qieting-fengyin** [comment]
我这边也遇到了：源端是aws elasticache集群（5.0.6），目标端是自建redis单实例或者cluster（5.0.6），rump方式同步；全量同步能完成，然后redis-shake进程就退出了，无法增量同步，日志也没有报错信息；目标端info replication也没看到有slave连接。

**Comment by suxb201** [comment]
这个信息确实不够，可以看看目的端，源端 log 有没有什么异常

**Comment by boboboboboli** [comment]
我们也遇到类似的问题，架构如下：

**Comment by boboboboboli** [comment]
我们也遇到类似问题（版本4.0.12），架构如下：
（主集群）3主3从  ---redis-shake---> （备集群）3主3从
可以正常全量同步，在增量同步的时候，发现redis-shake往备集群写入速度很慢，导致主集群的内存使用率较高，
具体体现主集群在client list 中的会话输出缓冲区，比如：
...  obl=0 oll=43057 omem=685932746 events=rw cmd=replconf

**Comment by suxb201** [comment]
了解，后续会更新一个版本，请问：主的 qps 大概是多少？常用什么命令？

**Comment by suxb201** [comment]
有增量数据同步过去吗？
如果没有增量数据同步过去可以解释，是同步全量数据太慢，导致增量数据打爆了 client-output-buffer。目前版本无解，只能扩大 client-output-buffer，或者等流量低峰期再同步。

**Comment by suxb201** [comment]
v3 可以解决，但还不稳定，欢迎尝试：https://github.com/alibaba/RedisShake/tree/v3
