### ISSUE TITLE
[BUG] key_exists = rewrite 问题

### ISSUE THREAD

**Issue by wuchencm** [aliyun/redis-shake#437]
环境信息：
redis-shake version：v2.1.2
redis version: 6.2.6
source.type = standalone
target.type = standalone
key_exists = rewrite

场景：
setp1：在target上添加key_5 : key_5_from_target
setp2:  在source上添加key_5 : key_5_from_source

问题：发现target上相同的key（key_5）的值（key_5_from_target）并没有修改成source端的值
操作1：重启redis-shake之后，key_5的值均变为相同（key_5_from_source）
操作2：在source端修改key_5的value为key_5_from_source_new之后，target端key_5同步成功（key_5_from_source_new）

**Comment by suxb201** [comment]
未能复现，你可以复现吗？
