### ISSUE TITLE
[BUG]Error:run ChooseNodeWithCmd failed[Put: no key found in args

### ISSUE THREAD

**Issue by xcjing** [aliyun/redis-shake#438]
**Describe the bug**
**the log is below:**

2022/05/22 06:36:38 [INFO] DbSyncer[2] total = 528.34MB -      14.83MB [  2%]  entry=484137
2022/05/22 06:36:38 [INFO] DbSyncer[0] sync:  +forwardCommands=9597   +filterCommands=0      +writeBytes=1142043
2022/05/22 06:36:39 [INFO] DbSyncer[1] sync:  +forwardCommands=35178  +filterCommands=0      +writeBytes=4186182
2022/05/22 06:36:39 [INFO] DbSyncer[2] total = 528.34MB -      14.88MB [  2%]  entry=485871
2022/05/22 06:36:39 [PANIC] DbSyncer[1] Event:SendToTargetFail  Id:redis-shake  Error:run ChooseNodeWithCmd failed[Put: no key found in args]
[stack]:
    1   github.com/alibaba/RedisShake/redis-shake/dbSync/syncIncrease.go:343
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).sendTargetCommand.func1
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/syncIncrease.go:444
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).sendTargetCommand
        ... ...

**To reproduce**
when run redis-shake.linux -type=sync -conf=redis-shake.conf，I will get above error.

**Expected behavior**

A description of what you expected to happen.

**Additional information**

Any additional information that is relevant to the problem.

**Comment by suxb201** [comment]
用到 lua 了吗，lua 脚本要指定 key 的
