### ISSUE TITLE
集群模式下不支持断点续传

### ISSUE THREAD

**Issue by xcjing** [aliyun/redis-shake#440]
在source和TARGET都是CLUSTER模式下，
把断点续传开关设为TRUE, 重启redis-shake, 还是从头开始传，没有做断点续传
resume_from_break_point = true

**Comment by tianyangyang427** [comment]
遇到同样情况redis版本5.0.5开启断点续传后还是从头开始，以下为配置信息
# this is the configuration of redis-shake.
conf.version = 1

id = redis-shake-login-cache

# log file，日志文件，不配置将打印到stdout (e.g. /var/log/redis-shake.log )
log.file =/data/redis/redis-shake/login-cache-3-5.log

pid_path =/data/redis/redis-shake


system_profile = 19410

http_profile = 19420

source.type = cluster
source.address = 192.168.10.102:7002;192.168.10.108:7002;192.168.10.112:7002
source.password_raw = Q4N$WOU25RyKSz9sL@f9
source.auth_type = auth

target.type = cluster
target.address = 192.168.10.102:7002;192.168.10.108:7002;192.168.10.112:7201
target.password_raw = Q4N$WOU25RyKSz9sL@f9
target.auth_type = auth

rewrite = true

metric =true

resume_from_break_point = true

下面为两个集群分片信息
**【目标集群分片信息】**
192.168.10.112:7201> cluster slots
1) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "192.168.10.108"
      2) (integer) 7201
      3) "dd764f08fa21657bd1b04118a45db369efeafb42"
   4) 1) "192.168.10.112"
      2) (integer) 7202
      3) "b08b9b3bec658bcf0a94b5ee1c9a29a7e1903f97"
2) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "192.168.10.112"
      2) (integer) 7201
      3) "8a407793cebc32f6d5c5a4559fc5d666bdc6d286"
   4) 1) "192.168.10.102"
      2) (integer) 7202
      3) "68afa5f081be92f8fac4ee6a193b993c60ca8cc9"
3) 1) (integer) 0
   2) (integer) 5460
   3) 1) "192.168.10.102"
      2) (integer) 7201
      3) "dfae33668a53b4f9f26d0f06190631c246b8fbdf"
   4) 1) "192.168.10.108"
      2) (integer) 7202
      3) "24983dfb842e5ab831c004686af914ee8ec9ae51"
192.168.10.112:7201> 
**【源集群分片信息】**
192.168.10.102:7001> cluster slots
1) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "192.168.10.112"
      2) (integer) 7001
      3) "57766d07b2f0135992fa3e7b8a9d88e70aaef7b9"
   4) 1) "192.168.10.102"
      2) (integer) 7002
      3) "94bc731f7cde345794435f4e1d2669477460e005"
2) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "192.168.10.108"
      2) (integer) 7001
      3) "f883bd28ee55dee7af93cb498ee8c07c42e6b019"
   4) 1) "192.168.10.112"
      2) (integer) 7002
      3) "5582e9198256fb0cf13058c22dbcb46367179612"
3) 1) (integer) 0
   2) (integer) 5460
   3) 1) "192.168.10.102"
      2) (integer) 7001
      3) "0b09e4bf8b4c138a6e8c62f5964b605248ae00ec"
   4) 1) "192.168.10.108"
      2) (integer) 7002
      3) "9f6fb1f0055f1b88a2c39ddb1a704c4adfa3af0a"
192.168.10.102:7001>

**Comment by suxb201** [comment]
断点续传这个功能这个版本不支持了，设计的不好，问题太多。
