### ISSUE TITLE
[CRASH]codis server 3.2同步到rediscluster 5.0在rdb同步阶段报错

### ISSUE THREAD

**Issue by congshenV** [aliyun/redis-shake#443]
**Crash report**

2022/05/31 17:27:08 [PANIC] set command error
[error]: Do failed[write tcp *********->*********: write: broken pipe]
[stack]:
    3   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/common/utils.go:346
            redis-shake/common.set
    2   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/common/utils.go:604
            redis-shake/common.restoreBigRdbEntry
    1   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/common/utils.go:846
            redis-shake/common.RestoreRdbEntry
    0   /Users/tongyao.lty/Work/RedisShake/src/redis-shake/dbSync/syncRDB.go:68
            redis-shake/dbSync.(*DbSyncer).syncRDBFile.func1.1
        ... ...

```
```

**Additional information**
源端分析有一个500M左右的string大key
1. OS distribution and version
2. Steps to reproduce (if any)

**Comment by suxb201** [comment]
看看目的端日志

**Comment by congshenV** [comment]
> 

目标端没有相关日志，这个错误我看是因为server连接已经断开，而客户端还在写入导致的··
目标端的timeout设置的是0，连接数也健康，所以暂时无法判断是什么原因断开的

**Comment by suxb201** [comment]
先升级下版本试试吧
