### ISSUE TITLE
[NEW]redis-shake能否只做增量同步？

### ISSUE THREAD

**Issue by xcjing** [aliyun/redis-shake#444]
**The problem/use-case that the feature addresses**

A description of the problem that the feature will solve, or the use-case with which the feature will be used.

**Description of the feature**
redis-shake启动后，能否不做全量同步，只做增量同步，

A description of what you want to happen.

**Alternatives you've considered**

Any alternative solutions or features you've considered, including references to existing open and closed feature requests in this repository.

**Additional information**

Any additional information that is relevant to the feature request.

**Comment by suxb201** [comment]
这个可以实现：https://github.com/alibaba/RedisShake/tree/v3
