### ISSUE TITLE
[BUG] restore big hash key 出错

### ISSUE THREAD

**Issue by xcjing** [aliyun/redis-shake#448]
**在同步过程中，经常报下面的错误，但实际上 big key并不大。这是源端：redis-cli --bigkeys 找出来的big key**
0 lists with 0 items (00.00% of keys, avg size 0.00)
127668 hashs with 780940 fields (40.92% of keys, avg size 6.12)
95283 strings with 900279 bytes (30.54% of keys, avg size 9.45)
0 streams with 0 entries (00.00% of keys, avg size 0.00)
0 sets with 0 members (00.00% of keys, avg size 0.00)
6 MBbloom--s with 0 ? (00.00% of keys, avg size 0.00)
89039 zsets with 196361 members (28.54% of keys, avg size 2.21)

**并且源端和目标端的 client-output-buffer-limit 的slave都已经设置成0 0 0,  有什么方法可以避免出现这个错误？**

2022/06/09 04:25:43 [INFO] restore big hash key 111368218|1|SVK||0|320x50|{103} field count 7
2022/06/09 04:25:43 [PANIC] parse rdb entry error, if the err is :EOF, please check that if the src db log has client output buffer oom, if so set output buffer larger.
[error]: unknown module name[MBbloom--] with module id[3465209449566631940]
[stack]: 
    0   github.com/alibaba/RedisShake/redis-shake/common/utils.go:958
            github.com/alibaba/RedisShake/redis-shake/common.NewRDBLoader.func1
        ... ...

**Comment by suxb201** [comment]
不支持这个 MBbloom--

**Comment by xcjing** [comment]
有没有方法忽略掉，我在src/pkg/rdb/module.go 中加一句，想让他直接返回，但好像不行
case "MBbloom--":
                fmt.Printf("**module is [%v]\n",moduleName)
                return  b.Bytes(),nil
