### ISSUE TITLE
能否忽略掉布隆过滤器生成的KEY

### ISSUE THREAD

**Issue by xcjing** [aliyun/redis-shake#449]
如果源端REDIS有用到MBboom布隆过滤器，同步过程中会报：
unknow module name MBboom-- with module id ..错
能否忽略掉布隆过滤器生成的KEY

**Comment by wujunwei** [comment]
我理解是不是你迁移的source和destination都要有这个module。

**Comment by suxb201** [comment]
@wujunwei @xcjing 是 redis-shake 需要认识 module 的命令，目前不认识。
需要改 shake 代码...

**Comment by suxb201** [comment]
数据不重要的话可以先删除，完成数据同步。
