### ISSUE TITLE
[BUG] filter slot在增量同步阶段失效

### ISSUE THREAD

**Issue by vlaualv** [aliyun/redis-shake#450]
启动两个redis主从，开启slot filter设置为3300，键b的slot为此值。在原目标写入多个键 a,b ,c。开启迁移之后，之后b键能够迁移到目标节点。然后在迁移成功后，再写入ee,ff等键值，不属于slot 3300，也能够同步到目标节点
redis-shake版本： release-v2.1.2-20220329.tar.gz

**Comment by suxb201** [comment]
ee 与 ff 是通过什么命令写入的？

**Comment by vlaualv** [comment]
> ee 与 ff 是通过什么命令写入的？

通过基本的set命令

**Comment by suxb201** [comment]
理不清原因了，你可以试试新版：https://github.com/alibaba/RedisShake/tree/v3，应该能解决问题。
