### ISSUE TITLE
模拟断点续传，故意将redisshake服务停止，在启动脚本时候报错

### ISSUE THREAD

**Issue by linorwang** [aliyun/redis-shake#451]
配置：
# 断点续传开关
resume_from_break_point = true

模拟单机redis 5 -> 单机redis 7 同步时，故意将redisshake服务停止，停止方式为kill pid，再次运行脚本是报错，如下所示，请教一下是什么原因导致的呢？
![微信截图_20220616172501](https://user-images.githubusercontent.com/23013733/174039623-dd17d212-f98a-40f7-bc6d-16f1afff9679.png)

**Comment by suxb201** [comment]
目前版本断点续传功能存在问题，后续会换成更好的实现。
