### ISSUE TITLE
请问单机到cluster的数据同步怎么做？

### ISSUE THREAD

**Issue by cstongwei** [aliyun/redis-shake#453]
我想把单机版的redis的数据同步到redis集群，在配置文件里配置了三个slave的ip和port。启动redis-shake后，控制台一直不停的重复输出
2022/06/27 15:16:17 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0这一行内容，但redis集群并没看到任何的数据。
![image](https://user-images.githubusercontent.com/15072550/175884301-f0b5ec64-6e64-47c0-ad0a-1be0808bd618.png)

我的配置文件如下：
[redis-shake.conf.txt](https://github.com/alibaba/RedisShake/files/8989561/redis-shake.conf.txt)

redis集群用的是redis7. 单机版的redis用的是redis4

我的redis的实际数据情况如图:
![image](https://user-images.githubusercontent.com/15072550/175885162-6d31c9b2-1845-4409-96e2-4a9efba98792.png)

**Comment by suxb201** [comment]
看不出原因。可以试试 https://github.com/alibaba/RedisShake/tree/v3 说不定有用。
