### ISSUE TITLE
同步重启失败

### ISSUE THREAD

**Issue by fg1813042793** [aliyun/redis-shake#455]
![图片](https://user-images.githubusercontent.com/42597625/176580089-be245edf-3bfe-4f6e-8b1f-6dde4f92b850.png)

redis版本都为4.0.14，且redis-shake版本为最新版本

**Comment by suxb201** [comment]
不要继续使用断点续传功能，存在问题。

**Comment by fg1813042793** [comment]
服务已经重新启动了，多谢指导，非常感谢！
