### ISSUE TITLE
[BUG] redis7.0 -> redis5.0 error

### ISSUE THREAD

**Issue by rleecn** [aliyun/redis-shake#458]
Source Redis Version:7.0
Target Redis Version:5.0
ERROR：
2022/06/30 20:19:47 [PANIC] parse rdb header error
[error]: verify version, invalid RDB version number 10, 9
    1   github.com/alibaba/RedisShake/pkg/rdb/loader.go:43
            github.com/alibaba/RedisShake/pkg/rdb.(*Loader).Header
    0   github.com/alibaba/RedisShake/redis-shake/common/utils.go:953
            github.com/alibaba/RedisShake/redis-shake/common.NewRDBLoader.func1
        ... ...
[stack]:
    0   github.com/alibaba/RedisShake/redis-shake/common/utils.go:954
            github.com/alibaba/RedisShake/redis-shake/common.NewRDBLoader.func1

**Comment by suxb201** [comment]
Have a try with redis-shake v3:
code: https://github.com/alibaba/RedisShake/tree/v3
release: https://github.com/alibaba/RedisShake/releases
