### ISSUE TITLE
[BUG] redisWriter received error. error=[MOVED 4075 10.28.64.18:13502], 

### ISSUE THREAD

**Issue by xcjing** [aliyun/redis-shake#461]
**最新的v3.0.0-beta.6** 还是会报下面的错，只是比以前的少而已
{"level":"info","time":"2022-07-05T05:59:59Z","message":"syncing aof. allowOps=[69.40], disallowOps=[0.00], entryId=[12170353], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[757525953272], aofAppliedOffset=[757525953272]"}
{"level":"panic","time":"2022-07-05T06:00:00Z","message":**"redisWriter received error. error=[MOVED 4075 10.28.64.18:13502], argv=[SETEX eauk_8c08f31d-27f1-4ea2-bc49-5757028b4dac_com.gpn.azs**_?胁?芯?懈蟹邪?懈? 锌芯 蟹胁芯薪泻? 5 ], reply=[%!s(<nil>)]"}

**Comment by suxb201** [comment]
这次未能复现，新加 log，可以帮助确认下原因，你可以试试：https://github.com/alibaba/RedisShake/releases/tag/v3.0.0-beta.7

**Comment by suxb201** [comment]
@xcjing hi 请问后续又出现过类似问题吗？

**Comment by xcjing** [comment]
没有了，但现在又出现read: connection reset by peer的错误

**Comment by suxb201** [comment]
@xcjing 请问：
1. 是什么时候出现的这个错误，可以的话麻烦贴下上下文日志
2. 可以看一下对应时刻 Redis 节点上的日志
