### ISSUE TITLE
[CRASH] 

### ISSUE THREAD

**Issue by wwwbjqcom** [aliyun/redis-shake#465]
2022/07/27 08:54:04 [INFO] DbSyncer[18] total = 16.70GB -       3.83MB [  0%]  entry=0           
2022/07/27 08:54:04 [INFO] DbSyncer[14] total = 16.70GB -     899.34KB [  0%]  entry=0           
2022/07/27 08:54:04 [INFO] DbSyncer[3] total = 16.61GB -      35.91MB [  0%]  entry=1536        
2022/07/27 08:54:04 [INFO] DbSyncer[23] total = 16.62GB -       5.75MB [  0%]  entry=8           
2022/07/27 08:54:04 [INFO] DbSyncer[5] total = 16.70GB -       2.53MB [  0%]  entry=0           
2022/07/27 08:54:05 [INFO] DbSyncer[13] total = 16.58GB -      14.22MB [  0%]  entry=0           
2022/07/27 08:54:05 [INFO] DbSyncer[11] total = 16.72GB -       6.42MB [  0%]  entry=0           
2022/07/27 08:54:05 [INFO] DbSyncer[9] total = 16.74GB -       4.24MB [  0%]  entry=0           
2022/07/27 08:54:05 [INFO] DbSyncer[2] total = 16.64GB -       9.88MB [  0%]  entry=326         
2022/07/27 08:54:05 [INFO] DbSyncer[12] total = 16.67GB -       3.20MB [  0%]  entry=0           
2022/07/27 08:54:05 [INFO] DbSyncer[21] total = 16.73GB -       8.28MB [  0%]  entry=0           
2022/07/27 08:54:05 [INFO] DbSyncer[10] total = 16.49GB -      11.85MB [  0%]  entry=383         
2022/07/27 08:54:05 [INFO] DbSyncer[15] total = 16.61GB -       5.04MB [  0%]  entry=0           
2022/07/27 08:54:05 [INFO] DbSyncer[0] total = 16.70GB -       5.69MB [  0%]  entry=0           
2022/07/27 08:54:05 [INFO] DbSyncer[19] total = 16.72GB -       7.58MB [  0%]  entry=0           
2022/07/27 08:54:05 [INFO] DbSyncer[8] total = 16.83GB -       4.64MB [  0%]  entry=0           
2022/07/27 08:54:05 [INFO] DbSyncer[16] total = 16.73GB -       2.65MB [  0%]  entry=0           
2022/07/27 08:54:05 [INFO] DbSyncer[4] total = 16.71GB -       3.27MB [  0%]  entry=0           
2022/07/27 08:54:05 [INFO] DbSyncer[6] total = 16.80GB -       2.07MB [  0%]  entry=0           
2022/07/27 08:54:05 [INFO] DbSyncer[1] total = 16.73GB -       3.38MB [  0%]  entry=0           
2022/07/27 08:54:05 [PANIC] restore command response = 'ECONNTIMEOUT: dial tcp 172.26.0.35:7000: i/o timeout', should be 'OK'
[stack]: 
    1   github.com/alibaba/RedisShake/redis-shake/common/utils.go:920
            github.com/alibaba/RedisShake/redis-shake/common.RestoreRdbEntry
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/syncRDB.go:71
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).syncRDBFile.func1.1
        ... ...

我在使用2.1.2版本对redis cluster进行迁移， 源时24个节点的redis cluster， 每个节点使用内存大概24G左右， 这上面报的是目的节点，设置了keep_alive = 1也不管用

**Comment by suxb201** [comment]
试一下：https://github.com/alibaba/RedisShake/releases/tag/v3.0.0-beta.9

**Comment by wwwbjqcom** [comment]
> 试一下：https://github.com/alibaba/RedisShake/releases/tag/v3.0.0-beta.9

我看3.0版本配置， 好像不支持源是redis cluster啊， 24个节点相当于我要起24个程序才行

**Comment by suxb201** [comment]
@wwwbjqcom 目前是的，但是资源占用并不会多
