### ISSUE TITLE
redis3.2 cluster 到redis6.2使用redis-shake数据同步报错：redisWriter received error；

### ISSUE THREAD

**Issue by wwang113** [aliyun/redis-shake#467]
报错日志如下：
2022-07-29 13:23:55 PNC redisWriter received error. error=[redis: nil], argv=[EVAL if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; return redis.call('pttl', KEYS[1]); 1 method.A2022042100000022.S2022051700000028.lock 5000 0130a735-0e5a-4059-8d5f-66f68fa18552:173], slots=[16005], reply=[<nil>]
panic: redisWriter received error. error=[redis: nil], argv=[EVAL if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; return redis.call('pttl', KEYS[1]); 1 method.A2022042100000022.S2022051700000028.lock 5000 0130a735-0e5a-4059-8d5f-66f68fa18552:173], slots=[16005], reply=[<nil>]

goroutine 25 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc000946240, 0x0})
	github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc00020f440, {0xc000946240, 0x20a})
	github.com/rs/zerolog@v1.27.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
	github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc00020f440, {0x7bef4d, 0x410e6a}, {0xc00024ff78, 0x74b980, 0x1})
	github.com/alibaba/RedisShake/internal/log/func.go:71 +0x53
github.com/alibaba/RedisShake/internal/log.Panicf({0x7bef4d, 0x45}, {0xc00024ff78, 0x4, 0x4})
	github.com/alibaba/RedisShake/internal/log/func.go:27 +0x57
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc00009bef0)
	github.com/alibaba/RedisShake/internal/writer/redis.go:71 +0x2b7
created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter
	github.com/alibaba/RedisShake/internal/writer/redis.go:31 +0x18f

**Comment by suxb201** [comment]
See go-redis issue: https://github.com/go-redis/redis/issues/1593.
I will fix it in the next version.
