### ISSUE TITLE
是否支持哨兵模式迁移到cluster模式呢？

### ISSUE THREAD

**Issue by mawenbin666** [aliyun/redis-shake#469]

**Comment by suxb201** [comment]
理论上没问题，source 写主节点就可以

**Comment by mawenbin666** [comment]
哨兵模式有16个db，但是实际上只需要迁移其中一个DB，问 db10同步迁移到cluster模式该怎么配置呢？
有redis-shake.conf 配置的参考例子吗？

**Comment by suxb201** [comment]
看这里：https://github.com/alibaba/RedisShake/blob/v3/redis-shake.toml

**Comment by tearstainss** [comment]
哨兵模式同步到集群模式，配置里面source可以写1主2从吗，你的推荐是什么呢？
target是不是需要写3个master地址呢

**Comment by suxb201** [comment]
哨兵和单实例一样，source 只写一个，写主写从都可以。targe 写随便一个节点就行。
参照：https://github.com/alibaba/RedisShake/blob/v3/docs/quick_start.md

**Comment by tearstainss** [comment]
> 哨兵和单实例一样，source 只写一个，写主写从都可以。targe 写随便一个节点就行。 参照：https://github.com/alibaba/RedisShake/blob/v3/docs/quick_start.md

我用3.0版本的跑不起来，最后报一大堆乱码和xshell什么的
后来换成2.0版本，source写了主、从节点的哨兵端口，targe写了集群内所有主的ip，跑起来了。但是跑了一天了，还没跑完。。  请问这种正常吗，writeBytes始终不等于0，源redis的rdb文件大小=1.7G，且是测试环境，并不会往源redis里面写数据。
这种预计大概啥时候能终止呢

**Comment by suxb201** [comment]
@tearstainss 
1. 3.0 报错是什么，麻烦贴一下
2. 不正常，再慢也不会一天搞不完的

**Comment by tearstainss** [comment]
message":"redisWriter received error. error=[ERR syntax error], argv=[restore WECHAT:VIEW:USER:DESIGN:oK-4o46VTOEv-UlTZkxtaisYaPfA:3FO44N2WN5DA 3793441162735 \u0000\ufffd\u0001\u0006\u0000\ufffd\ufffd\ufffd6$T-o replace absttl], slots=[7746], reply=[<nil>]"}

**Comment by suxb201** [comment]
目的端和源端 redis 是多少？

**Comment by tearstainss** [comment]
> 目的端和源端 redis 是多少？

都是4.0.8

**Comment by suxb201** [comment]
@tearstainss 4.0 不支持 restore 的附加子段。非常建议升级 redis 版本，或者注释 redis-shake 对应代码并重编译。redis-shake 没有在 5.0 一下版本测试。

**Comment by tearstainss** [comment]
> @tearstainss 4.0 不支持 restore 的附加子段。非常建议升级 redis 版本，或者注释 redis-shake 对应代码并重编译。redis-shake 没有在 5.0 一下版本测试。

您建议的redis版本是？

**Comment by suxb201** [comment]
5.0、6.0、7.0 都可以

**Comment by tearstainss** [comment]
源端和目的端redis版本必须都是5.0以上吗

**Comment by suxb201** [comment]
只升级目的端就可以

**Comment by tearstainss** [comment]
> 只升级目的端就可以

一般数据迁移的话，源端和目的端是怎么区分的呢，比如我要哨兵迁移到集群，源=哨兵，目的=集群？

**Comment by suxb201** [comment]
@tearstainss 是的

**Comment by tearstainss** [comment]
> @tearstainss 是的

thanks 我试一下
