### ISSUE TITLE
如何指定不发pipeline？

### ISSUE THREAD

**Issue by holmes1412** [aliyun/redis-shake#470]
想请教下是否有办法指定不发pipeline请求呢？

我目前想把restore改成正常的setex请求，发到redis协议的proxy上，由于我的proxy只能一来一回，因此我尝试了下把PipelineCountLimit改成0，但是抓包发现若干个set请求依然连续发送，chWaitReply仿佛没有生效？

请问如何能做到不发pipeline、等待回复之后再发下一个请求呢？

P.S. 另外就是编译执行sh build.sh报错。

执行：
~~~
sh build.sh
~~~
会有如下报错：
~~~
[ BUILD RELEASE ]
try build for current platform
runtime/cgo
net
build success
try build GOOS=linux GOARCH=amd64
build success
try build GOOS=linux GOARCH=arm64
build success
try build GOOS=darwin GOARCH=amd64
build success
try build GOOS=darwin GOARCH=arm64
# github.com/alibaba/RedisShake/cmd/redis-shake
/usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-880244499/go.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
~~~
不过看了下`bin/`下可以编译出`redis-shake`。

**Comment by suxb201** [comment]
@holmes1412 fix 了，PipelineCountLimit 写 1 或者 0 试试，推荐 1。

**Comment by suxb201** [comment]
@holmes1412 编译只是 darwin/arm64 的失败了，需要较高的 golang 版本 https://github.com/golang/go/issues/44115
> Go 1.16 is required for darwin/arm64

**Comment by holmes1412** [comment]
可以用了~~~赞效率~~~
