### ISSUE TITLE
[NEW] 请问数据同步期间如果网络错误是否会重试呢？

### ISSUE THREAD

**Issue by holmes1412** [aliyun/redis-shake#471]
如题~

**Comment by suxb201** [comment]
这个功能不好写。
shake 不知道目的端已经应用了哪条命令，shake 是流式向目的端发命令的，然后异步处理返回值。所以如果遇到目的端宕机的情况，宕机时刻，可能有一部分命令还在 tcp buffer 中，可能有一部分命令目的端 Redis 已经 apply，shake 不知道从哪条命令开始。

**Comment by holmes1412** [comment]
明白了～感谢～
