### ISSUE TITLE
is it support resume from break point

### ISSUE THREAD

**Issue by javaKhan** [aliyun/redis-shake#474]
resume from break point  feature in v3？

**Comment by suxb201** [comment]
现在还不支持，短期内也没有支持的计划。
1. 断点续传很难实现，在不侵入用户 keyspace 的前提下，shake 无法知道哪些命令目的端已经成功执行了。所以断点续传可能会存在重复执行或者漏执行的情况。 
2. redis PSync 的设置，导致断了之后短时间内源端 repl buffer 就会被冲刷掉，所以一般没办法重连。

**Comment by Lee-CQ** [comment]
我参看了RedisShake的wiki，看见其从2.0 开始支持断点续传，您这里指的的3.0不支持吗？
RedisRhake wiki 中亦有完备的实现细节，这些实现目前能够参考吗？

**Comment by lee-cq** [comment]
我参看了RedisShake的wiki，看见其从2.0 开始支持断点续传，您这里指的的3.0不支持吗？
RedisRhake wiki 中亦有完备的实现细节，这些实现目前能够参考吗？

[RedisShake断点续传使用介绍](https://github.com/alibaba/RedisShake/wiki/%E6%96%AD%E7%82%B9%E7%BB%AD%E4%BC%A0%E4%BD%BF%E7%94%A8%E4%BB%8B%E7%BB%8D#0-%E4%B8%BA%E4%BB%80%E4%B9%88%E8%A6%81%E5%81%9A%E6%96%AD%E7%82%B9%E7%BB%AD%E4%BC%A0)

**Comment by suxb201** [comment]
@Lee-CQ 
这套方案有想过，感觉不是很必要
1. 带来较高的代码复杂度
2. 对用户 keyspace 有侵入
3. 影响同步效率
4. 实际效果没有想象中那么理想，归根到底还是 redis 重连能力较弱。只能解决因网络问题导致的极短时间断连（发生概率很小）

请问你是会经常断连吗？断连的话是源端到 shake 断，还是 shake 到目的端断了。

**Comment by suxb201** [comment]
见讨论：https://github.com/alibaba/RedisShake/discussions/494
