### ISSUE TITLE
ERR syntax error

### ISSUE THREAD

**Issue by fotan123456** [aliyun/redis-shake#477]
2022-08-24 16:38:07 PNC redisWriter received error. error=[ERR syntax error], argv=[restore *********_hyq 1661770218384

source&target redis version:4.0  How can i solve this problem？

**Comment by suxb201** [comment]
Please give the complete log.

Redis 4.0 not support ABSTTL,IDLETIME and FREQ. https://redis.io/commands/restore/
```
Starting with Redis version 3.0.0: Added the REPLACE modifier.
Starting with Redis version 5.0.0: Added the ABSTTL modifier.
Starting with Redis version 5.0.0: Added the IDLETIME and FREQ options.
```
Maybe you can modify the source code to remove the corresponding fields

**Comment by fotan123456** [comment]
the complete log：
2022-08-24 16:38:07 PNC redisWriter received error. error=[ERR syntax error], argv=[restore ********_hyq 16617********* �@�@�"account_type":1,"login_tim "2022-08-22 18:4 0",�3o** #71c072c9ab54**********9b5caa 0sub_�h�4� E �!
                                                                                                  hyq key
                                                                                                          98aacb67d5673fad********8248e9e3 i373342"}��x4m��4 replace absttl], slots=[10839], reply=[<nil>]
panic: redisWriter received error. error=[ERR syntax error], argv=[restore **********_hyq 1661770*******4 �@�@�"account_type":1,"login_tim "2022-08-22 18:4 0",�3o** #71c072c9ab54460daa4*******b5caa 0sub_�h�4� E �!
                                                                                 hyq key
                                                                                         98aacb67d5673fadbcc3**********e3 i373342"}��x4m��4 replace absttl], slots=[10839], reply=[<nil>]

goroutine 33 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1(0xc0026c0000, 0x14f)
        github.com/rs/zerolog@v1.27.0/log.go:359 +0x4f
github.com/rs/zerolog.(*Event).msg(0xc000182300, 0xc0026c0000, 0x14f)
        github.com/rs/zerolog@v1.27.0/event.go:156 +0x30c
github.com/rs/zerolog.(*Event).Msg(...)
        github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc000182300, 0x82d5f2, 0x45, 0xc00016df88, 0x4, 0x4)
        github.com/alibaba/RedisShake/internal/log/func.go:71 +0x85
github.com/alibaba/RedisShake/internal/log.Panicf(0x82d5f2, 0x45, 0xc00016df88, 0x4, 0x4)
        github.com/alibaba/RedisShake/internal/log/func.go:27 +0x6d
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc0000a1a10)
        github.com/alibaba/RedisShake/internal/writer/redis.go:74 +0x267
created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter
        github.com/alibaba/RedisShake/internal/writer/redis.go:32 +0x199

**Comment by fotan123456** [comment]
感谢，target升级5.0后解决了
