### ISSUE TITLE
Can support redis cluster with pure memory w/o persistent storage

### ISSUE THREAD

**Issue by hobbytp** [aliyun/redis-shake#478]
Dear experts, 
My company uses Redis Cluster with pure memory without persistent storage, 
can we still use RedisShake to do the data migration task from Redis cluster to Redis cluster? Thanks,

**Comment by suxb201** [comment]
Yes, you can.
It should be noted that the source redis will generate a dump.rdb file in the work directory (if you open [diskleess replication](https://redis.io/docs/manual/replication/#diskless-replication), this file will not be generated).

**Comment by hobbytp** [comment]
@suxb201 thanks, do you mean after I enable diskless replication (yes, we use it now), I still can use RedisShake to do the data migration task, right?
And for redis cluster to cluster migration, it is recommended in the [comments ](https://github.com/alibaba/RedisShake/issues/480#issuecomment-1229649066)in #480 ?

**Comment by suxb201** [comment]
@hobbytp Yes.
