### ISSUE TITLE
[CRASH] error=[ERR Bad data format]

### ISSUE THREAD

**Issue by plus1998** [aliyun/redis-shake#479]
**Crash report**
source = 7.0.3
target = 5.0.13

全量同步时发生错误。error=[ERR Bad data format]，伴随一些乱码出现。这个问题似乎发生在任意一个zset身上。

```
panic: redisWriter received error. error=[ERR Bad data format], argv=[restore REPLY_GROUP:829 0 ''�24133029049@chatroom�d�Z��   ��u;���ō replace], slots=[12210], reply=[<nil>
```

**Comment by suxb201** [comment]
原因是 7.0 引入了新的 zset 编码结构，5.0 不能识别。解决方法：
- 目的端也使用 7.0（推荐）
- 或者修改配置项 `target_redis_proto_max_bulk_len` 为 0，会降低同步速度，但应该能正常工作

**Comment by plus1998** [comment]
> * target_redis_proto_max_bulk_len

我试了target_redis_proto_max_bulk_len = 0 配置，发生同样的报错。
我可以舍弃zset数据，可以用filters实现过滤zset吗
如果可以的话，有lua参考示例吗

**Comment by suxb201** [comment]
@plusl894860970 请问解决了吗

**Comment by thdwldud** [comment]
@suxb201 你好。
我在搜索同样的问题时，用相应的方法解决了。

我有一个疑问。
将"target_redis_proto_max_bulk_len"更改为零，可以知道为什么它运行吗？
