### ISSUE TITLE
[NEW] 请问是否支持集群到集群迁移？

### ISSUE THREAD

**Issue by xr** [aliyun/redis-shake#480]
https://github.com/alibaba/RedisShake/blob/v3/docs/quick_start.md
根据这个文档，目前只支持standalone -> cluster？

请问是否支持cluster -> cluster?

谢谢

**Comment by suxb201** [comment]
比如说 3 节点集群到 3 节点集群，目前建议启动三个 redis-shake，源端分别是源集群中的每个节点，目的端为目的集群的任意一个节点。

**Comment by opt-m** [comment]
请问shake-v3有计划支持源端为cluster吗？

**Comment by suxb201** [comment]
未来可能写个 Python 脚本，可以方便起多个 redis-shake 同步集群。但是依旧不会在 redis-shake 内原生支持源端为集群。因为对于大规模集群，资源消耗会很多，可能需要多台机器部署 redis-shake。而且多个同步逻辑在一个进程内，不容易控制与观测。

**Comment by Emma-uestc** [comment]
> 比如说 3 节点集群到 3 节点集群，目前建议启动三个 redis-shake，源端分别是源集群中的每个节点，目的端为目的集群的任意一个节点。

参考了这里的文档，https://github.com/alibaba/RedisShake/blob/v3/docs/quick_start.md
目前是不支持 cluster -> cluster 吗
使用redisShake v3 做 cluster -> cluster 之间的同步，源端必须在.toml文件中配置集群中的每个节点，是吗？
那对于大规模的集群，还是使用v2 方便吧，v2支持只配置集群中的一个节点

**Comment by Emma-uestc** [comment]
> 比如说 3 节点集群到 3 节点集群，目前建议启动三个 redis-shake，源端分别是源集群中的每个节点，目的端为目的集群的任意一个节点。

如果开启多个redis-shake 进程，源端是否只需要集群中的mater节点即可还是必须是所有节点

**Comment by mmweiyin** [comment]
> 

请问3个redis-shake要同时启动吗

**Comment by mmweiyin** [comment]
> 比如说 3 节点集群到 3 节点集群，目前建议启动三个 redis-shake，源端分别是源集群中的每个节点，目的端为目的集群的任意一个节点。

请问三个redis-shake要同时启动吗？我要把3节点集群迁移到单节点。

**Comment by suxb201** [comment]
@Emma-uestc master 节点。 
@mmweiyin 不需要同时启动。

**Comment by suxb201** [comment]
@xr @opt-m @Emma-uestc @mmweiyin 最新版 shake 新加了一个脚本方便集群迁移时快速启动多个 shake：[快速开始：数据迁移](https://github.com/alibaba/RedisShake/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B%EF%BC%9A%E6%95%B0%E6%8D%AE%E8%BF%81%E7%A7%BB#%E9%9B%86%E7%BE%A4%E5%88%B0%E9%9B%86%E7%BE%A4c-d)

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/16659368/192260396-30e03303-03fa-42cc-a92a-fde7768bd8be.png">
