### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by lizewen-shenzhen** [aliyun/redis-shake#481]
When the synchronization is complete，it starts incremental synchronization.After 10 minutes, it starts to report the network timeout and exit the process, and this phenomenon is inevitable.The log is as follows:
2022/08/26 20:40:19 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=1      +writeBytes=0
2022/08/26 20:40:19 [PANIC] DbSyncer[0] Event:NetErrorWhileReceive      Id:redis-api    Error:read tcp 192.168.8.20:37732->192.168.8.31:6379: i/o timeout
[stack]:
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/syncIncrease.go:138
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).receiveTargetReply
        ... ...

**Comment by suxb201** [comment]
已有 issue：https://github.com/alibaba/RedisShake/issues/466
