### ISSUE TITLE
业务量很活跃，任何的时间点缓冲区被打满几率很大，reddis-shake 目前的同步机制来说是不是对于这种情况无解了

### ISSUE THREAD

**Issue by HelonLee135** [aliyun/redis-shake#483]
背景：
实列配置都是社区版  集群版  5.0  64G
同地域、跨账号redis数据迁移
源端这边使用量：71.49%   45.76GB/64.00GB
目标端： 清空数据
./redis-shake.linux -type=sync -conf=redis-shake.conf

前言：之前使用过这个redis-shake 工具，当时的源端实列只有7个G的数据，直接就迁移过去了。现在来了一个大家伙。45个G，这个工具的一些局限性我是后知后觉呀。在这里我提一个问题，看看git 主能否有余力可以优化什么的。当然先感谢git主的工具奉献。谢谢你的付出~

问题描述：
目前我正在迁移的这个案列，配置还有具体的数据大小如上所述。由于我们这边业务量还挺活跃的，看这个使用量都用到了70%+（非标了，没办法了。上面也不给提升规格了）。目前我们使用这个工具，我一直在找我们业务的最低峰时间，去跑。24小时，能够跑的时间我都试过了，几乎都是全量数据还没有同步完毕，增量数据就把缓冲区给打满了。当然我们也尝试过调整这个参数parallel  调到64甚至128.。。力求在缓冲区打满之前完成全量同步。最低峰时间迁移，结果都一样还是缓冲区被打满。我去看了一下目标端的那个实列同步过来的数据跟源端就差那么的一点点，0.13%的数据。就差0.13%的数据，就断了。
而且这个工具不管差多少，哪怕是0.00001%，主要全量的数据还没有完全过来，缓冲区打满后就报错退出了。整个过程（1.5-2小时）全白搭，每次执行迁移命令：./redis-shake.linux -type=sync -conf=redis-shake.conf。它都是重新迁移一篇的，我想提的是这个关键点，这个重新迁移的操作逻辑能不能别这么粗暴。迁移过来的数据就迁移过来了，可以在这个基础上面去做对源端的数据检测，但是对于迁移过来的数据就不要重新迁移一遍了。当然了，我不太了解这个工具它是处于数据的完整性还是其他原因而做这个重新迁移的操作。如果能够解决这个问题的话，那么缓存区被打满这种问题就不会存在了，只要打满了就断开重视，校验目标端已经有的数据就好勒，不需要重新又迁移一遍。导致整个过程下来的那个结果这么难受。缓冲区该打满的它百分百给你打满。我不知道我的表达是否清晰，git主看到的话谅解。我当然希望这个工具越做越好，祝好

**Comment by HelonLee135** [comment]
也就是说实列越大，业务活跃的情况下（几乎没有低峰的空窗期）。这个工具几乎实现不了sync的迁移的

**Comment by HelonLee135** [comment]
![Uploading JQ(FA~0UDV}MSNU[5H]A0MT.png…]()
![Uploading JQ(FA~0UDV}MSNU[5H]A0MT.png…]()

**Comment by suxb201** [comment]
@HelonLee135 试试 3.0 版本，会有改善

**Comment by nankemeng690** [comment]
> 



> 也就是说实列越大，业务活跃的情况下（几乎没有低峰的空窗期）。这个工具几乎实现不了sync的迁移的

缓冲区调大了嘛？把同步的节点数调小一点呢？就差0.13感觉没问题的
