### ISSUE TITLE
开始同步aof时日志打印异常[BUG] 

### ISSUE THREAD

**Issue by liuguoshun** [aliyun/redis-shake#485]
{"level":"info","time":"2022-09-08T14:41:47+08:00","message":"syncing rdb. percent=[86.95]%, allowOps=[25119.40], disallowOps=[0.00], entryId=[3637690], unansweredBytesCount=[24215]bytes,
 rdbFileSize=[3.421]G, rdbSendSize=[2.974]G"}
{"level":"info","time":"2022-09-08T14:41:52+08:00","message":"syncing rdb. percent=[90.02]%, allowOps=[25422.20], disallowOps=[0.00], entryId=[3764835], unansweredBytesCount=[24517]bytes,
 rdbFileSize=[3.421]G, rdbSendSize=[3.079]G"}
{"level":"info","time":"2022-09-08T14:41:57+08:00","message":"syncing rdb. percent=[93.11]%, allowOps=[25932.60], disallowOps=[0.00], entryId=[3894522], unansweredBytesCount=[32925]bytes,
 rdbFileSize=[3.421]G, rdbSendSize=[3.185]G"}
{"level":"info","time":"2022-09-08T14:42:02+08:00","message":"syncing rdb. percent=[96.17]%, allowOps=[25465.00], disallowOps=[0.00], entryId=[4021845], unansweredBytesCount=[36838]bytes,
 rdbFileSize=[3.421]G, rdbSendSize=[3.290]G"}
{"level":"info","time":"2022-09-08T14:42:07+08:00","message":"syncing rdb. percent=[99.25]%, allowOps=[25224.40], disallowOps=[0.00], entryId=[4148009], unansweredBytesCount=[85608]bytes,
 rdbFileSize=[3.421]G, rdbSendSize=[3.395]G"}
{"level":"info","time":"2022-09-08T14:42:08+08:00","message":"send RDB finished. address=[10.144.122.106:6389], repl-stream-db=[0]"}
{"level":"info","time":"2022-09-08T14:42:09+08:00","message":"AOFReader open file. aof_filename=[36099464499.aof]"}
{"level":"info","time":"2022-09-08T14:42:12+08:00","message":"syncing rdb. percent=[100.00]%, allowOps=[2442.00], disallowOps=[0.00], entryId=[4160229], unansweredBytesCount=[0]bytes, rdb
FileSize=[3.421]G, rdbSendSize=[3.421]G"}
{"level":"info","time":"2022-09-08T14:42:17+08:00","message":"syncing rdb. percent=[100.00]%, allowOps=[4.00], disallowOps=[0.00], entryId=[4160249], unansweredBytesCount=[0]bytes, rdbFil
eSize=[3.421]G, rdbSendSize=[3.421]G"}
{"level":"info","time":"2022-09-08T14:42:22+08:00","message":"syncing rdb. percent=[100.00]%, allowOps=[5.00], disallowOps=[0.00], entryId=[4160274], unansweredBytesCount=[0]bytes, rdbFil
eSize=[3.421]G, rdbSendSize=[3.421]G"}
{"level":"info","time":"2022-09-08T14:42:27+08:00","message":"syncing rdb. percent=[100.00]%, allowOps=[5.40], disallowOps=[0.00], entryId=[4160301], unansweredBytesCount=[0]bytes, rdbFil
eSize=[3.421]G, rdbSendSize=[3.421]G"}

**Comment by suxb201** [comment]
未能复现这个 case，请问源端版本是多少？
或者可以利用 metrics_port 来看一下具体监控信息
