### ISSUE TITLE
是否可用于主备集群间实时数据同步

### ISSUE THREAD

**Issue by myl1024** [aliyun/redis-shake#486]
您好，我想问几个问题（v3版本）：
1. 请问是否可用于主备集群间实时数据同步
2. 测试了一下目前发生切主操作shake就会退出
    2.1 shake退出重启后又重新开始全量同步？是否考虑target节点不变的情况下通过保存复制位移之类的方式进行增量同步呢

**Comment by suxb201** [comment]
1. 只建议做数据导出、清洗使用，不建议做长期同步通道
2. 点位很难做到准确，shake 知道自己接受到的点位不假，但是 shake 无法精确知道目的端已经执行的点位（可能在网络栈中，可能在 Redis 引擎中，可能正在回包）。

**Comment by suxb201** [comment]
见讨论：https://github.com/alibaba/RedisShake/discussions/494
