### ISSUE TITLE
[CRASH] ERR syntax error 感谢感谢！

### ISSUE THREAD

**Issue by Aurel1ano** [aliyun/redis-shake#490]
**Crash report**
最新版本同步后提示ERR syntax error

```
![image](https://user-images.githubusercontent.com/17338442/191021565-927d9d28-86f0-4f1b-ba2c-e6679a337d62.png)


```
2022-09-19 20:48:54 INF AOFWriter open file. filename=[43833980818.aof]
?� replace absttl], slots=[7064], reply=[<nil>]ror. error=[ERR syntax error], argv=[restore CP_PRY_PDN_UPLOAD_RECORD_FAILED_xxxx 1663646157487 ����
?� replace absttl], slots=[7064], reply=[<nil>]yntax error], argv=[restore CP_PRY_PDN_UPLOAD_RECORD_FAILED_xxxx 1663646157487 ����

goroutine 35 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1(0xc0000c2900, 0xbd)
	github.com/rs/zerolog@v1.27.0/log.go:359 +0x4f
github.com/rs/zerolog.(*Event).msg(0xc000056120, 0xc0000c2900, 0xbd)
	github.com/rs/zerolog@v1.27.0/event.go:156 +0x30c
github.com/rs/zerolog.(*Event).Msg(...)
	github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc000056120, 0x82e612, 0x45, 0xc0001d3f88, 0x4, 0x4)
	github.com/alibaba/RedisShake/internal/log/func.go:71 +0x85
github.com/alibaba/RedisShake/internal/log.Panicf(0x82e612, 0x45, 0xc0001d3f88, 0x4, 0x4)
	github.com/alibaba/RedisShake/internal/log/func.go:27 +0x6d
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc000098270)
	github.com/alibaba/RedisShake/internal/writer/redis.go:74 +0x267
created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter
	github.com/alibaba/RedisShake/internal/writer/redis.go:32 +0x199

**Comment by suxb201** [comment]
源端与目的端版本是多少？

**Comment by Aurel1ano** [comment]
> 源端与目的端版本是多少？
都是3.2.8

**Comment by suxb201** [comment]
@Aurel1ano 换新版，3.2.8 不支持一些字段

**Comment by Aurel1ano** [comment]
> @Aurel1ano 换新版，3.2.8 不支持一些字段

好的 谢谢
