### ISSUE TITLE
多DB到单节点到集群报错，ERR SELECT is not allowed in cluster mode],

### ISSUE THREAD

**Issue by 339131041** [aliyun/redis-shake#499]
ed error. error=[ERR SELECT is not allowed in cluster mode], argv=[restore access_2529B9D7EBF56013D3B2620B37DF26BE 1664033196444 \r@@@\u0000\u0000\u0000\u000e\u0000\u0000\u0000\u0002\u0000\u0000\u0002ak\u0004/MTY2NDAMTAwMU1UWTJOREF4TWpFeE16UXhNaU16TURBPQ__\ufffd\u0006\u0000\ufffd\ufffd\ufffdQ釟乛 replace absttl], slots=[14675], reply=[<nil>]"}
redisshake3的版本

**Comment by suxb201** [comment]
Redis 的集群是不支持多 DB 的

**Comment by 339131041** [comment]
嗯谢谢，后来改了改swap_db.lua合到一个DB去了

**Comment by 135zyf** [comment]
> 嗯，谢谢，后来改了改swap_db.lua合到一个DB去了

可否提供下是如何修改的swap_db.lua

**Comment by suxb201** [comment]
@135zyf 确认 key 没有冲突的话，无脑 return 0 好了：
```lua
function filter(id, is_base, group, cmd_name, keys, slots, db_id, timestamp_ms)
    return 0,0
end
```

**Comment by 135zyf** [comment]
> @135zyf确认key 没有什么事情，无脑返回0 好：
> 
> ```lua
> function filter(id, is_base, group, cmd_name, keys, slots, db_id, timestamp_ms)
>     return 0,0
> end
> ```

收到，谢谢
