### ISSUE TITLE
哨兵模式

### ISSUE THREAD

**Issue by OctPeng** [aliyun/redis-shake#500]
**问题描述**

请问现在V3支持哨兵模式吗？如果支持的话，应该如何配置？我想的是哨兵到哨兵迁移。

**Comment by suxb201** [comment]
参考：https://github.com/alibaba/RedisShake/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B%EF%BC%9A%E6%95%B0%E6%8D%AE%E8%BF%81%E7%A7%BB#redis-%E5%93%A8%E5%85%B5%E6%A8%A1%E5%BC%8F
