### ISSUE TITLE
实时同步时出现[WARN] DbSyncer[1] delayChannel is full

### ISSUE THREAD

**Issue by planefeiji** [aliyun/redis-shake#501]
集群模式下在完成全量同步后，大概几小时后日志打印
 [WARN] DbSyncer[1] delayChannel is full
[WARN] DbSyncer[4] delayChannel is full
 [WARN] DbSyncer[1] delayChannel is full
 [WARN] DbSyncer[2] delayChannel is full
 [WARN] DbSyncer[2] delayChannel is ful

除了修改源和端的地址，以及版本6.0外，其它的设置都为默认。redis版本号为6.0.9；keys的总数大概在1亿左右。请问这warn告警是什么意思？

**Comment by suxb201** [comment]
使用新版 shake 试试：
https://github.com/alibaba/RedisShake/releases/tag/v3.1.1
https://github.com/alibaba/RedisShake/wiki

**Comment by planefeiji** [comment]
V3.1.1是否支持集群对集群？

**Comment by suxb201** [comment]
@planefeiji 现在建议每个 db 开一个节点，预计明晚会放出一个脚本，可以帮助起多个 shake。

**Comment by planefeiji** [comment]
[WARN] DbSyncer[2] Event:GetFakeSlaveOffsetFail     Id:redis-shake  Warn:OffsetNotFoundInInfo目前又出现这样的告警，redis-shake的版本是release-v2.1.2-20220329。能否解释一下这两个告警是什么意思吗？

**Comment by planefeiji** [comment]
redis-shake是通过同步rdb的吗？

**Comment by suxb201** [comment]
是同步 rdb，疑问请参考这里：https://github.com/alibaba/RedisShake/wiki

**Comment by planefeiji** [comment]
> 是同步 rdb，疑问请参考这里：https://github.com/alibaba/RedisShake/wiki

第一次做全量同步，会先保存为dump.rdb文件的是吗

**Comment by suxb201** [comment]
@planefeiji 是的

**Comment by planefeiji** [comment]
那在增量同步时是什么原理？是从rdb文件读取，还是直接在缓存读取？还有个问题就是，同步过程中出现过期的keys会有怎样的影响？

**Comment by suxb201** [comment]
和 redis 主从复制一样，看看其他介绍 redis 主从复制的文章吧。
