### ISSUE TITLE
同步超时之后进程还一直存在，需要手动kill

### ISSUE THREAD

**Issue by yjiu1990** [aliyun/redis-shake#502]
**问题描述**
同步超时之后进程一直存在变成僵尸进程

![image](https://user-images.githubusercontent.com/41354304/192191428-598bfb1e-2fc9-4995-aab8-99e9cd69b563.png)

**Comment by suxb201** [comment]
麻烦多贴些日志

**Comment by baoziaichiyu** [comment]
怎么kill 我不知道是怎么进程名称
