### ISSUE TITLE
请问下这个3.1.5版本启动支持scan了吗

### ISSUE THREAD

**Issue by Thswty** [aliyun/redis-shake#512]
**问题描述**

redis-shake v3.1.5版本启动报错，scan不支持

redis-shake 的日志：

![1665363740949](https://user-images.githubusercontent.com/45663223/194787753-56bbc019-f223-45d7-9dc3-d31ff28c9268.png)

---

**源端 Redis**
版本：阿里云的redis云实例，版本v5

---

**目的端 Redis**
版本：是自建不是集群，版本v5

**Comment by suxb201** [comment]
发 Release 了：https://github.com/alibaba/RedisShake/releases/tag/v3.1.6
