### ISSUE TITLE
redis cluster作为源，使用redis-shake进行持续的数据同步，redis cluster如果进行扩缩容，如何保证redis-shake同步的平滑性

### ISSUE THREAD

**Issue by wwloo2018** [aliyun/redis-shake#514]
**问题描述**

源：redis cluster集群
目标： 另一个redis cluster集群
现状：从源到目标使用redis-shake持续进行数据同步
需求：redis cluster如果进行扩缩容，redis-shake如何保证同步的平滑性

**Comment by suxb201** [comment]
不建议用做长期的数据同步，只建议用于一次性的数据迁移。

**Comment by wwloo2018** [comment]
好的
