### ISSUE TITLE
redisWriter received error. error=[ERR SELECT is not allowed in cluster mode]

### ISSUE THREAD

**Issue by 135zyf** [aliyun/redis-shake#517]
我在使用这个工具进行单机到集群数据迁移时，迁移过程中出现错误：日志内容"redisWriter received error. error=[ERR SELECT is not allowed in cluster mode]'' , 请问这是什么原因，如何解决？

**Comment by suxb201** [comment]
集群不支持 select 命令

**Comment by suxb201** [comment]
https://github.com/alibaba/RedisShake/wiki/%E5%B8%B8%E8%A7%81%E6%8A%A5%E9%94%99#errorerr-select-is-not-allowed-in-cluster-mode
