### ISSUE TITLE
3.0 版本不支持断点续传？

### ISSUE THREAD

**Issue by forachange** [aliyun/redis-shake#519]
**问题描述**

redisshake2 有断点续传的功能，redisshake3 没有，同步程序一重启就进行全量的数据同步

---

**源端 Redis**
版本：6.2.7

---

**目的端 Redis**
版本：7.0.4

**Comment by suxb201** [comment]
不提供，见：https://github.com/alibaba/RedisShake/discussions/494

**Comment by jianbiao11** [comment]
https://github.com/alibaba/RedisShake/discussions/494  这个网址 404 了，能提供一个新地址吗

**Comment by jianbiao11** [comment]
> 不提供，见：https://github.com/alibaba/RedisShake/discussions/494

https://github.com/alibaba/RedisShake/discussions/494 这个网址 404 了，能提供一个新地址吗

**Comment by suxb201** [comment]
因为技术原因很难实现断点续传。

**Comment by jianbiao11** [comment]
> 因为技术原因很难实现断点续传。

能简单说几点吗？ 省的我们走弯路了，万分感谢

**Comment by suxb201** [comment]
@jianbiao11 
1. 源端断线，重连成功概率极低。因为 Redis 缓冲区大小有限。Tair 例外。
2. 目的端断线，不知道是否该重试。

**Comment by jianbiao11** [comment]
> @jianbiao11
> 
> 1. 源端断线，重连成功概率极低。因为 Redis 缓冲区大小有限。Tair 例外。
> 2. 目的端断线，不知道是否该重试。

感谢
