### ISSUE TITLE
监控的含义是什么啊

### ISSUE THREAD

**Issue by jkx1206** [aliyun/redis-shake#521]
**问题描述**

1.可以解释下监控的含义是什么吗
2.使用python启动的redisshake，metrics_port会是从11008开始，到11008+num_cluster_node，而不是sync.toml里面定义的

**Comment by suxb201** [comment]
1. 这里：https://github.com/alibaba/RedisShake/wiki/%E8%BF%90%E8%A1%8C%E6%97%A5%E5%BF%97
2. 是的，你可以改脚本
