### ISSUE TITLE
单向同步如何保证redis-shake本身高可用呢

### ISSUE THREAD

**Issue by blackysy** [aliyun/redis-shake#527]
**问题描述**

我想问下，单向同步，做读写分离的场景，怎么能保证redis-shake本身高可用呢，有这么方面使用指导参考吗。

**Comment by suxb201** [comment]
1. 读写分离场景建议直接依赖 Redis 自身的同步链路，可用性会高很多
2. 正常情况下 redis-shake 自身不会挂掉，对延迟有较高耐受。网络中断或宿主机宕机会导致 shake 停止服务，这种情况只能清除目的节点数据重新启动 shake，发生概率很低。

**Comment by blackysy** [comment]
好的，明白了。
