### ISSUE TITLE
RedisShake是否支持源端实例为阿里云集群版Redis呢

### ISSUE THREAD

**Issue by callmedba** [aliyun/redis-shake#539]
**问题描述**

源端实例为阿里云集群版Redis ，但阿里云对于集群版的实例， 只提供一个proxy地址，并没有提供集群每个node节点的地址。

那么RedisShake是不是就没有办法对集群的每个node节点地址进行连接和配置呢

---

**源端 Redis**
版本：阿里云 5.0 集群版

**目的端 Redis**
版本：阿里云 2.8 集群版

另一个问题： 文档中有提到配置 big_key_threshold = 1  。 这个配置项是RedisShake 2.0 中的配置吗 ？ 我在RedisShake 3.0里使用这个配置报错，如下 。3.0里面类似的参数是哪个呢 ，谢谢 ～

[advanced]
dir = "data2"
big_key_threshold = 1
~~~~~~~~~~~~~~~~~ missing field

# runtime.GOMAXPROCS, 0 means use runtime.NumCPU() cpu cores

goroutine 1 [running]:
github.com/alibaba/RedisShake/internal/config.LoadFromFile({0x7ffe9b0012d7, 0x6})
	github.com/alibaba/RedisShake/internal/config/config.go:113 +0x145
main.main()
	github.com/alibaba/RedisShake/cmd/redis-shake/main.go:33 +0x11c

**Comment by suxb201** [comment]
阿里云可以开启直连地址的。
是的，3.0 中有对应配置，名字不一样。

**Comment by callmedba** [comment]
> 阿里云可以开启直连地址的。 是的，3.0 中有对应配置，名字不一样。

比如集群是4个分片节点组成，那么申请到的直连地址其实还是一个slb地址 ，不能给4个节点各申请一个直接访问的地址 ，应该是这样的情况吧 。而RedisShake里配置源实例为集群的话 ，那么就要求每个节点都要有一个直接可访问的地址吧 

[阿里云直连地址](https://help.aliyun.com/document_detail/146901.html)

是target_redis_proto_max_bulk_len这个参数吗 ？ 配置值为多少呢， 是 0 吗 ？

谢谢

**Comment by suxb201** [comment]
是 `target_redis_proto_max_bulk_len `，保持默认就好
