### ISSUE TITLE
redis-shake 发起同步后 target 端的哨兵会发现 souces 端的哨兵

### ISSUE THREAD

**Issue by NightmareKurumi** [aliyun/redis-shake#542]
**问题描述**

redis-shake 发起同步后，target 端的哨兵会发现 source 端的哨兵。在某些场景下 target 端的哨兵会发起主从切换将 target 端的实例降级为 slave 导致 redis-shake 同步失败，请问如何避免此类情况（ sources 和 target 的哨兵都不能关闭）。

同步前 source 主从状态
![8 BYPHY9PZ5DSTO%Z~9Y4IS](https://user-images.githubusercontent.com/26181459/206454996-15e9274b-6b31-4d25-b01a-1f6eac3a282c.png)

同步前 target 主从状态
![QI%726EZ@7UUZ$V8{_3G}CC](https://user-images.githubusercontent.com/26181459/206455047-6ac08e4e-2854-48c4-b6a0-a8dcc9c7487c.png)

同步前 target 哨兵的情况
![image](https://user-images.githubusercontent.com/26181459/206456623-e428e358-1cf6-4554-ad88-68d849ac3a24.png)

同步后的 target 哨兵的情况
![image](https://user-images.githubusercontent.com/26181459/206456491-154b3944-6ee3-4908-86e6-9d10c120e15f.png)

发起 redis-shake 同步后的状态

redis-shake 的日志：
```
shake 的日志贴在这里
```

---

**源端 Redis**
版本：3.0，自建 redis，使用 standalone 模式

---

**目的端 Redis**
版本：7.0，自建 redis，使用 standalone 模式

**Comment by NightmareKurumi** [comment]
测试后发现，由于源端与 target 端的网络不通，当 target 端发现哨兵的数量未满足重新选举的条件时不会将 target 设置为 slave。（redis-shake 是部署在能同时通 source 和 target 的机器上）。想请问下这种情况如何才能避免 target 的哨兵发现 source 的哨兵

**Comment by NightmareKurumi** [comment]
![image](https://user-images.githubusercontent.com/26181459/206459474-fcfb8b03-09fa-4254-a982-902ce7a9e5c0.png)

**Comment by suxb201** [comment]
没看懂，不是 shake 的问题吧，如果是哨兵模式用法问题可以去检索更多资料。一个想法：源端 shake 挂 slave 试试。

**Comment by wHoareYouY** [comment]
我这边也是一样的问题，可能是把sentinel互相通信的__sentinel__:hello也同步过去了，我这边把PUBLISH过滤掉就正常了

**Comment by NightmareKurumi** [comment]
> 

这个我已经解决了，排查后发现是 redis-shake 把哨兵相关的命令也一起同步了，我的做法是改 target 端哨兵的 sentinel monitor 的值，保证 sources 那边和 target 那边的哨兵这个配置不一样就行了。感谢回复！
