### ISSUE TITLE
持续增量同步及特定key特殊操作的问题

### ISSUE THREAD

**Issue by listman828** [aliyun/redis-shake#543]
1、如果源redis和目的redis，都正常运行的话，做好进程的监控和异常的条件下，能否用redisshake一直做增量同步？

2、源redis一些特定的key，没有过期时间，用redisshake对这些加上过期时间，能否做到呢？如果能的话需要在哪里做些调整？

**Comment by suxb201** [comment]
1. 不出问题是可以的。出问题 shake 没有自恢复逻辑，因为自动恢复无法保证数据一致性
2. 手动改代码吧，比较简单，直接在 main 函数地方处理 argv，加上过期参数就好。

**Comment by listman828** [comment]
已解决，感谢大神的提示
