### ISSUE TITLE
using redis-shake when source is ElastiCache

### ISSUE THREAD

**Issue by kimdubi** [aliyun/redis-shake#545]
fisrt of all, thanks for this great tool RedisShake.

I have a question while using redisshake. 
I am using elasticache as the source redis, 
so I want to put a value in the "elasticache_psync=" column of sync.toml, 
what should I put?

**Comment by suxb201** [comment]
You need to submit a ticket to AWS to request the psync command.
- https://github.com/alibaba/RedisShake/wiki/%E4%BB%8E%E5%B8%B8%E8%A7%81%E4%BA%91%E5%8E%82%E5%95%86%E8%BF%81%E5%87%BA%E6%95%B0%E6%8D%AE
- https://github.com/alibaba/RedisShake/issues/373

**Comment by kimdubi** [comment]
@suxb201 ah i understand thanks!
Then, using scan.toml instead of sync.toml is also a way.
right?

**Comment by suxb201** [comment]
@kimdubi yes
