### ISSUE TITLE
can I keep the syncing mode(scan.toml) until i finishi it manually?

### ISSUE THREAD

**Issue by kimdubi** [aliyun/redis-shake#546]
The redis-shake must be maintained 
until the connection is moved to the new redis for non-downtime transfer of the redis, 
but the redis-shake is terminated when all data transfers are completed.
like this (i used scan.toml)
```
2022-12-13 04:01:32 INF syncing. dbId=[0], percent=[97.07]%, allowOps=[38145.40], disallowOps=[0.00], entryId=[3639959], InQueueEntriesCount=[0], unansweredBytesCount=[120800]bytes
2022-12-13 04:01:34 INF scanReader fetch finished. address=[testserver:6379]
2022-12-13 04:01:34 INF finished.
```

I hope the redis-shake will continue to be maintained while transferring incremental data until I finish redis-shake.

Is there any way to solve this problem?
Thank you for your help.

**Comment by suxb201** [comment]
Please use scan mode.

**Comment by kimdubi** [comment]
yes i used scan.toml
my command was   ./redis-shake scan.toml  
and configs were all default setting except source ,target endpoint.

it works well. all keys are migrated.but It ends automatically after migrating all keys.

**Comment by suxb201** [comment]
Sorry, I made a mistake. Please use `sync` mode, `scan` mode does not support running for a long time.

**Comment by kimdubi** [comment]
Oh, then is it normal for scan.toml to automatically end after completing key migration?

**Comment by suxb201** [comment]
@kimdubi Yes.

**Comment by kimdubi** [comment]
ok thanks!
