### ISSUE TITLE
redis 4.0 cluster 同步到redis 6.0 报错

### ISSUE THREAD

**Issue by wavelet123** [aliyun/redis-shake#548]
**问题描述**

redis 4.0同步到redis 6.0 期间报错，redis shake退出

redis-shake 的日志：
```
panic: write tcp 192.168.xxx.2:53364->192.168.xxx.50:6690: write: broken pipe

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc00009ecd0, 0x0})
        github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc000092300, {0xc00009ecd0, 0x46})
        github.com/rs/zerolog@v1.27.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
        github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc000092300, {0xc00009ec30, 0xc0002ee720}, {0x0, 0x32, 0xc000355a40})
        github.com/alibaba/RedisShake/internal/log/func.go:77 +0x53
github.com/alibaba/RedisShake/internal/log.Panicf({0xc00009ec30, 0x46}, {0x0, 0x0, 0x0})
        github.com/alibaba/RedisShake/internal/log/func.go:27 +0x57
github.com/alibaba/RedisShake/internal/log.PanicError({0x81bc20, 0xc000351310})
        github.com/alibaba/RedisShake/internal/log/func.go:31 +0x33
github.com/alibaba/RedisShake/internal/client.(*Redis).flush(0xc00009c180)
        github.com/alibaba/RedisShake/internal/client/redis.go:100 +0x2a
github.com/alibaba/RedisShake/internal/client.(*Redis).SendBytes(0xc0000126c0, {0xc00008de00, 0xa82738, 0xc0000a0870})
        github.com/alibaba/RedisShake/internal/client/redis.go:94 +0x45
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).Write(0xc00005ca40, 0xc0003fb400)
        github.com/alibaba/RedisShake/internal/writer/redis.go:54 +0x12d
github.com/alibaba/RedisShake/internal/writer.(*RedisClusterWriter).Write(0x0, 0xc0003fb400)
        github.com/alibaba/RedisShake/internal/writer/redis_cluster.go:100 +0x92
main.main()
        github.com/alibaba/RedisShake/cmd/redis-shake/main.go:109 +0x7fa
panic: redisWriter received error. error=[EOF], argv=[script load local val = 0 if redis.call('GET', KEYS[1]) == ARGV[1] then val = redis.call('DEL', KEYS[1]) end return tostring(val)], slots=[], reply=[<nil>]

goroutine 20 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc0004c00d0, 0x0})
        github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc00038eae0, {0xc0004c00d0, 0xca})
        github.com/rs/zerolog@v1.27.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
        github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc00038eae0, {0x7b742a, 0x40c0ca}, {0xc000313f78, 0x745ea0, 0x407001})
        github.com/alibaba/RedisShake/internal/log/func.go:77 +0x53
github.com/alibaba/RedisShake/internal/log.Panicf({0x7b742a, 0x45}, {0xc000313f78, 0x4, 0x4})
        github.com/alibaba/RedisShake/internal/log/func.go:27 +0x57
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc00005ca40)
        github.com/alibaba/RedisShake/internal/writer/redis.go:75 +0x3bd
created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter
        github.com/alibaba/RedisShake/internal/writer/redis.go:35 +0x19c
shake 的日志贴在这里
```

---

**源端 Redis**
版本：版本号，自建还是云厂商？
redis-cli 4.0.10 自建 ，集群
日志：
```
22337:M 16 Dec 10:08:32.420 * Full resync requested by slave 192.168.xxx.2:10007
22337:M 16 Dec 10:08:32.420 * Starting BGSAVE for SYNC with target: disk
22337:M 16 Dec 10:08:32.693 * Background saving started by pid 9366
22337:M 16 Dec 10:08:47.381 # Connection with slave 192.168.xxx.2:10007 lost.
22337:M 16 Dec 10:09:28.406 * Slave 192.168.xxx.2:10007 asks for synchronization
22337:M 16 Dec 10:09:28.406 * Full resync requested by slave 192.168.xxx.2:10007
22337:M 16 Dec 10:09:28.406 * Can't attach the slave to the current BGSAVE. Waiting for next BGSAVE for SYNC
```

---

**目的端 Redis**
版本：版本号，是否是集群？自建还是云厂商？
redis 6.2.6 是集群，自建
日志：
```
24861:M 16 Dec 2022 10:55:23.038 * 1 changes in 3600 seconds. Saving...
24861:M 16 Dec 2022 10:55:23.038 * Background saving started by pid 45524
45524:C 16 Dec 2022 10:55:23.040 * DB saved on disk
45524:C 16 Dec 2022 10:55:23.040 * RDB: 0 MB of memory used by copy-on-write
24861:M 16 Dec 2022 10:55:23.058 * Background saving terminated with success
24861:M 16 Dec 2022 10:55:45.750 * Starting automatic rewriting of AOF on 6715309000% growth
24861:M 16 Dec 2022 10:55:45.752 * Background append only file rewriting started by pid 45529
24861:M 16 Dec 2022 10:55:47.435 * AOF rewrite child asks to stop sending diffs.
45529:C 16 Dec 2022 10:55:47.435 * Parent agreed to stop sending diffs. Finalizing AOF...
45529:C 16 Dec 2022 10:55:47.435 * Concatenating 4.19 MB of AOF diff received from parent.
45529:C 16 Dec 2022 10:55:47.447 * SYNC append only file rewrite performed
日志贴在这里
```

**Comment by suxb201** [comment]
请按照 issue 模板提示，提供更多的信息。比如目的端的运行日志。

**Comment by wavelet123** [comment]
> 请按照 issue 模板提示，提供更多的信息。比如目的端的运行日志。

已提供日志，麻烦看下

**Comment by suxb201** [comment]
请提供发生问题时刻的日志，这个节点：192.168.xxx.50

**Comment by wavelet123** [comment]
> 请提供发生问题时刻的日志，这个节点：192.168.xxx.50
没有异常

24905:M 14 Dec 2022 14:53:49.842 # configEpoch set to 2 via CLUSTER SET-CONFIG-EPOCH
24905:M 14 Dec 2022 14:53:49.889 # IP address for this node updated to 192.168.154.50
24905:M 14 Dec 2022 14:53:55.200 # Cluster state changed: ok
24905:M 14 Dec 2022 14:53:59.895 * Replica 192.168.254.4:6690 asks for synchronization
24905:M 14 Dec 2022 14:53:59.895 * Partial resynchronization not accepted: Replication ID mismatch (Replica asked for 'd56357842510d8aecc653cde3e752fe994068612', my replication IDs are '7f2a0a729bef5e70f4688266428f5d9c0052ee5c' and '0000000000000000000000000000000000000000')
24905:M 14 Dec 2022 14:53:59.895 * Replication backlog created, my new replication IDs are '3a994ed97c82a08bd3ac59a21ecea3b8ed5bd4c4' and '0000000000000000000000000000000000000000'
24905:M 14 Dec 2022 14:53:59.895 * Starting BGSAVE for SYNC with target: disk
24905:M 14 Dec 2022 14:53:59.895 * Background saving started by pid 25113
25113:C 14 Dec 2022 14:53:59.896 * DB saved on disk
25113:C 14 Dec 2022 14:53:59.897 * RDB: 0 MB of memory used by copy-on-write
24905:M 14 Dec 2022 14:53:59.901 * Background saving terminated with success
24905:M 14 Dec 2022 14:53:59.901 * Synchronization with replica 192.168.254.4:6690 succeeded
24905:M 14 Dec 2022 15:00:25.358 # CONFIG REWRITE executed with success.
24905:M 16 Dec 2022 10:55:08.269 * 1 changes in 3600 seconds. Saving...
24905:M 16 Dec 2022 10:55:08.269 * Background saving started by pid 44767
44767:C 16 Dec 2022 10:55:08.271 * DB saved on disk
44767:C 16 Dec 2022 10:55:08.272 * RDB: 0 MB of memory used by copy-on-write
24905:M 16 Dec 2022 10:55:08.289 * Background saving terminated with success
24905:M 16 Dec 2022 10:55:26.383 * Starting automatic rewriting of AOF on 6715917900% growth
24905:M 16 Dec 2022 10:55:26.385 * Background append only file rewriting started by pid 44769
24905:M 16 Dec 2022 10:55:28.079 * AOF rewrite child asks to stop sending diffs.
44769:C 16 Dec 2022 10:55:28.079 * Parent agreed to stop sending diffs. Finalizing AOF...
44769:C 16 Dec 2022 10:55:28.079 * Concatenating 5.05 MB of AOF diff received from parent.
44769:C 16 Dec 2022 10:55:28.096 * SYNC append only file rewrite performed
44769:C 16 Dec 2022 10:55:28.098 * AOF rewrite: 71 MB of memory used by copy-on-write
24905:M 16 Dec 2022 10:55:28.112 * Background AOF rewrite terminated with success
24905:M 16 Dec 2022 10:55:28.112 * Residual parent diff successfully flushed to the rewritten AOF (0.11 MB)
24905:M 16 Dec 2022 10:55:28.112 * Background AOF rewrite finished successfully
24905:M 16 Dec 2022 10:55:59.264 * Starting automatic rewriting of AOF on 100% growth
24905:M 16 Dec 2022 10:55:59.269 * Background append only file rewriting started by pid 44776
24905:M 16 Dec 2022 10:56:01.993 * AOF rewrite child asks to stop sending diffs.
44776:C 16 Dec 2022 10:56:01.993 * Parent agreed to stop sending diffs. Finalizing AOF...
44776:C 16 Dec 2022 10:56:01.993 * Concatenating 7.99 MB of AOF diff received from parent.
44776:C 16 Dec 2022 10:56:02.015 * SYNC append only file rewrite performed
44776:C 16 Dec 2022 10:56:02.021 * AOF rewrite: 148 MB of memory used by copy-on-write
24905:M 16 Dec 2022 10:56:02.042 * Background AOF rewrite terminated with success
24905:M 16 Dec 2022 10:56:02.042 * Residual parent diff successfully flushed to the rewritten AOF (0.13 MB)
24905:M 16 Dec 2022 10:56:02.042 * Background AOF rewrite finished successfully
24905:M 16 Dec 2022 10:56:09.016 * 10000 changes in 60 seconds. Saving...
24905:M 16 Dec 2022 10:56:09.021 * Background saving started by pid 44780

**Comment by wavelet123** [comment]
hi,能通过钉钉交流吗

**Comment by wavelet123** [comment]
目标端是redis 6.2.6,配置成了6.0，这个有影响吗

**Comment by suxb201** [comment]
看不出问题，可以自己排查下是不是网络问题。重试看看能复现吗。

**Comment by wavelet123** [comment]
get metrics from [192.168.xxx.249:6690] failed: HTTPConnectionPool(host='localhost', port=11010): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4110d73c18>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by suxb201** [comment]
shake 没启动的话会有这个报错

**Comment by wavelet123** [comment]
我不用python,单用shake的话，还是失败
2022-12-16 17:28:29 PNC write tcp 192.168.254.2:33740->192.168.154.48:6690: write: broken pipe
2022-12-16 17:28:29 PNC redisWriter received error. error=[EOF], argv=[script load local val = 0 if redis.call('GET', KEYS[1]) == ARGV[1] then val = redis.call('DEL', KEYS[1]) end return tostring(val)], slots=[], reply=[<nil>]
panic: write tcp 192.168.254.2:33740->192.168.154.48:6690: write: broken pipe

**Comment by suxb201** [comment]
你使用 redis-cli 连接上目的端，执行这条命令看看结果：
```
script load "local val = 0 if redis.call('GET', KEYS[1]) == ARGV[1] then val = redis.call('DEL', KEYS[1]) end return tostring(val)"
```

**Comment by wavelet123** [comment]
> script load "local val = 0 if redis.call('GET', KEYS[1]) == ARGV[1] then val = redis.call('DEL', KEYS[1]) end return tostring(val)"

127.0.0.1:6690> script load "local val = 0 if redis.call('GET', KEYS[1]) == ARGV[1] then val = redis.call('DEL', KEYS[1]) end return tostring(val)"
"c08d5d0a1de9f735722cda1a2f457cd0293c49aa"

**Comment by wavelet123** [comment]
> 你使用 redis-cli 连接上目的端，执行这条命令看看结果：
> 
> ```
> script load "local val = 0 if redis.call('GET', KEYS[1]) == ARGV[1] then val = redis.call('DEL', KEYS[1]) end return tostring(val)"
> ```

比较紧急，能尽快看下吗

{"level":"info","time":"2022-12-16T17:28:29+08:00","message":"LUA script: [local val = 0 if redis.call('GET', KEYS[1]) == ARGV[1] then val = redis.call('DEL', KEYS[1]) end return tostring(val)]"}
{"level":"info","time":"2022-12-16T17:28:29+08:00","message":"LUA script: [local gva = redis.call('GET', KEYS[1])\r\nif gva == ARGV[1] then\r\n  redis.call('DEL', KEYS[1])\r\n  return 1\r\nend\r\nreturn 0]"}
{"level":"info","time":"2022-12-16T17:28:29+08:00","message":"LUA script: [return redis.call('HMGET', KEYS[1], unpack(ARGV))]"}
{"level":"info","time":"2022-12-16T17:28:29+08:00","message":"LUA script: [if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('hincrby', KEYS[1], ARGV[3], -1); if (counter > 0) then redis.call('pexpire', KEYS[1], ARGV[2]); return 0; else redis.call('del', KEYS[1]); redis.call('publish', KEYS[2], ARGV[1]); return 1; end; return nil;]"}
{"level":"info","time":"2022-12-16T17:28:29+08:00","message":"LUA script: [\r\n                redis.call('HMSET', KEYS[1], 'absexp', ARGV[1], 'sldexp', ARGV[2], 'data', ARGV[4])\r\n                if ARGV[3] ~= '-1' then\r\n                  redis.call('EXPIRE', KEYS[1], ARGV[3])\r\n                end\r\n                return 1]"}
{"level":"info","time":"2022-12-16T17:28:29+08:00","message":"LUA script: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; return redis.call('pttl', KEYS[1]);]"}
{"level":"info","time":"2022-12-16T17:28:29+08:00","message":"send RDB finished. address=[192.168.xxx.1:6690], repl-stream-db=[0]"}
{"level":"panic","time":"2022-12-16T17:28:29+08:00","message":"write tcp 192.168.254.2:33740->192.168.xxx.48:6690: write: broken pipe"}
{"level":"panic","time":"2022-12-16T17:28:29+08:00","message":"redisWriter received error. error=[EOF], argv=[script load local val = 0 if redis.call('GET', KEYS[1]) == ARGV[1] then val = redis.call('DEL', KEYS[1]) end return tostring(val)], slots=[], reply=[<nil>]"}

**Comment by wavelet123** [comment]
用redisshake 2,报错信息如下：

2022/12/17 17:19:14 [DEBUG] DbSyncer[1] try restore key[task_Arrive_xxx_1] with value length[33]
2022/12/17 17:19:14 [PANIC] read error, please check source redis log or network
[error]: EOF
[stack]: 
    1   github.com/alibaba/RedisShake/redis-shake/common/utils.go:932
            github.com/alibaba/RedisShake/redis-shake/common.Iocopy
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/syncBegin.go:93
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).runIncrementalSync
        ... ...
2022/12/17 17:19:14 [DEBUG] DbSyncer[5] start restoring key[SEGRANK_GROUPMEM_xxx_222_1_1] with value length[60]

**Comment by suxb201** [comment]
是否存在类似 proxy 之类的组件

**Comment by wavelet123** [comment]
> 是否存在类似 proxy 之类的组件

没有，我怀疑还是client_output_buffer的问题，已经设置为4G了，我们再测一下

**Comment by wavelet123** [comment]
19872:S 20 Dec 14:29:24.509 # Connection with slave client id #1048576686 lost.
按单点到集群的模式，还是报错

        github.com/alibaba/RedisShake/cmd/redis-shake/main.go:109 +0x7fa
panic: redisWriter received error. error=[EOF], argv=[script load if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('hincrby', KEYS[1], ARGV[3], -1); if (counter > 0) then redis.call('pexpire', KEYS[1], ARGV[2]); return 0; else redis.call('del', KEYS[1]); redis.call('publish', KEYS[2], ARGV[1]); return 1; end; return nil;], slots=[], reply=[<nil>]

goroutine 34 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc000182000, 0x0})
        github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc000244c60, {0xc000182000, 0x186})
        github.com/rs/zerolog@v1.27.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
        github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc000244c60, {0x7b742a, 0x40c0ca}, {0xc000046f78, 0x745ea0, 0x407001})
        github.com/alibaba/RedisShake/internal/log/func.go:77 +0x53
github.com/alibaba/RedisShake/internal/log.Panicf({0x7b742a, 0x45}, {0xc000046f78, 0x4, 0x4})
        github.com/alibaba/RedisShake/internal/log/func.go:27 +0x57
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc000098100)
        github.com/alibaba/RedisShake/internal/writer/redis.go:75 +0x3bd
created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter
        github.com/alibaba/RedisShake/internal/writer/redis.go:35 +0x19c

**Comment by suxb201** [comment]
你再重试一次，启动单个 shake 就好。然后 shake 日志发全量的 redis-shake.log，源端和目的端 redis 日志发启动 shake 这一时刻之后的。

**Comment by wavelet123** [comment]
我就是启动的单个shake

**Comment by suxb201** [comment]
@wavelet123 然后 shake 日志发全量的 redis-shake.log，源端和目的端 redis 日志发启动 shake 这一时刻之后的。

**Comment by wavelet123** [comment]
[shakek1new.log](https://github.com/alibaba/RedisShake/files/10266754/shakek1new.log)
source:
19872:S 20 Dec 16:16:34.238 * Slave 192.168.254.2:10007 asks for synchronization
19872:S 20 Dec 16:16:34.238 * Full resync requested by slave 192.168.254.2:10007
19872:S 20 Dec 16:16:34.238 * Starting BGSAVE for SYNC with target: disk
19872:S 20 Dec 16:16:34.521 * Background saving started by pid 15402
15402:C 20 Dec 16:17:45.693 * DB saved on disk
15402:C 20 Dec 16:17:45.932 * RDB: 2539 MB of memory used by copy-on-write
19872:S 20 Dec 16:17:46.520 * Background saving terminated with success
19872:S 20 Dec 16:17:50.883 * Synchronization with slave 192.168.254.2:10007 succeeded
19872:S 20 Dec 16:21:13.308 # Connection with slave client id #1048706656 lost.
19872:S 20 Dec 16:22:44.575 * Slave 192.168.254.2:10007 asks for synchronization
19872:S 20 Dec 16:22:44.575 * Full resync requested by slave 192.168.254.2:10007
19872:S 20 Dec 16:22:44.575 * Starting BGSAVE for SYNC with target: disk
19872:S 20 Dec 16:22:44.849 * Background saving started by pid 15787
15787:C 20 Dec 16:23:55.891 * DB saved on disk
15787:C 20 Dec 16:23:56.124 * RDB: 2441 MB of memory used by copy-on-write
19872:S 20 Dec 16:23:56.693 * Background saving terminated with success
19872:S 20 Dec 16:24:01.208 * Synchronization with slave 192.168.254.2:10007 succeeded
19872:S 20 Dec 16:27:13.489 # Connection with slave client id #1048713837 lost.
target:
无

shake.log
[redis-shake1.log](https://github.com/alibaba/RedisShake/files/10266670/redis-shake1.log)

2022-12-20 16:27:13 INF LUA script: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; return redis.call('pttl', KEYS[1]);]
2022-12-20 16:27:13 INF LUA script: [local gva = redis.call('GET', KEYS[1])
if gva == ARGV[1] then
  cal ttlva = redis.call('PTTL', KEYS[1])
  dis.call('PEXPIRE', KEYS[1], ARGV[2] + ttlva)
return 1
end
return 0]
2022-12-20 16:27:13 INF send RDB finished. address=[192.168.254.245:6690], repl-stream-db=[0]
2022-12-20 16:27:13 PNC redisWriter received error. error=[EOF], argv=[script load if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('hincrby', KEYS[1], ARGV[3], -1); if (counter > 0) then redis.call('pexpire', KEYS[1], ARGV[2]); return 0; else redis.call('del', KEYS[1]); redis.call('publish', KEYS[2], ARGV[1]); return 1; end; return nil;], slots=[], reply=[<nil>]
panic: redisWriter received error. error=[EOF], argv=[script load if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('hincrby', KEYS[1], ARGV[3], -1); if (counter > 0) then redis.call('pexpire', KEYS[1], ARGV[2]); return 0; else redis.call('del', KEYS[1]); redis.call('publish', KEYS[2], ARGV[1]); return 1; end; return nil;], slots=[], reply=[<nil>]

goroutine 20 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc0001fa000, 0x0})
github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc000090900, {0xc0001fa000, 0x186})
github.com/rs/zerolog@v1.27.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc000090900, {0x7b742a, 0x40c0ca}, {0xc000043f78, 0x745ea0, 0x407001})
        github.com/alibaba/RedisShake/internal/log/func.go:77 +0x53
github.com/alibaba/RedisShake/internal/log.Panicf({0x7b742a, 0x45}, {0xc000043f78, 0x4, 0x4})
github.com/alibaba/RedisShake/internal/log/func.go:27 +0x57
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc000098100)
github.com/alibaba/RedisShake/internal/writer/redis.go:75 +0x3bd
created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter
github.com/alibaba/RedisShake/internal/writer/redis.go:35 +0x19c

**Comment by wavelet123** [comment]
> @wavelet123 然后 shake 日志发全量的 redis-shake.log，源端和目的端 redis 日志发启动 shake 这一时刻之后的。

真的比较紧急，麻烦尽快看下

**Comment by suxb201** [comment]
@wavelet123 需要 目的端 日志

**Comment by wavelet123** [comment]
> @wavelet123 需要 目的端 日志

48854:S 16 Dec 2022 16:01:11.780 * Non blocking connect for SYNC fired the event.
48854:S 16 Dec 2022 16:01:11.781 * Master replied to PING, replication can continue...
48854:S 16 Dec 2022 16:01:11.782 * Trying a partial resynchronization (request 05878ded52ad65edc9429752c9aab926167e40cd:1).
48854:S 16 Dec 2022 16:01:11.783 * Full resync from master: 1299899fe3d02266a70998ec4b0bdfe5c49cc2d0:0
48854:S 16 Dec 2022 16:01:11.783 * Discarding previously cached master state.
48854:S 16 Dec 2022 16:01:11.803 * MASTER <-> REPLICA sync: receiving 175 bytes from master to disk
48854:S 16 Dec 2022 16:01:11.803 * MASTER <-> REPLICA sync: Flushing old data
48854:S 16 Dec 2022 16:01:11.803 * MASTER <-> REPLICA sync: Loading DB in memory
48854:S 16 Dec 2022 16:01:11.804 * Loading RDB produced by version 6.2.6
48854:S 16 Dec 2022 16:01:11.804 * RDB age 0 seconds
48854:S 16 Dec 2022 16:01:11.804 * RDB memory usage when created 9.63 Mb
48854:S 16 Dec 2022 16:01:11.804 # Done loading RDB, keys loaded: 0, keys expired: 0.
48854:S 16 Dec 2022 16:01:11.804 * MASTER <-> REPLICA sync: Finished with success
48854:S 16 Dec 2022 16:01:47.490 * Marking node bd983fe5ec8f3042e0453faecbc381ddd4dad55b as failing (quorum reached).
48854:S 16 Dec 2022 16:01:47.490 * Marking node b7d2ef2821ef5407c192d61948859e1e1a333972 as failing (quorum reached).
48854:S 16 Dec 2022 16:02:29.685 * Marking node c7d97d377513598a8c739e88acc84f7da30016e6 as failing (quorum reached).
48854:S 16 Dec 2022 16:02:37.003 * Marking node d76ecb14e8ab832a95ca6115f7fcce787f1b556a as failing (quorum reached).
48854:S 16 Dec 2022 16:02:37.003 * Marking node 936d8dd49672df893fd11f596198b05c67cbff99 as failing (quorum reached).
48854:S 16 Dec 2022 16:02:43.864 * Clear FAIL state for node c7d97d377513598a8c739e88acc84f7da30016e6: master without slots is reachable again.
48854:S 16 Dec 2022 16:02:49.937 * Clear FAIL state for node bd983fe5ec8f3042e0453faecbc381ddd4dad55b: is reachable again and nobody is serving its slots after some time.
48854:S 16 Dec 2022 16:02:53.786 * Clear FAIL state for node b7d2ef2821ef5407c192d61948859e1e1a333972: is reachable again and nobody is serving its slots after some time.
48854:S 16 Dec 2022 16:03:14.382 # Cluster state changed: ok
48854:S 16 Dec 2022 16:03:15.227 * Clear FAIL state for node 936d8dd49672df893fd11f596198b05c67cbff99: master without slots is reachable again.
48854:S 16 Dec 2022 16:03:22.256 * Clear FAIL state for node d76ecb14e8ab832a95ca6115f7fcce787f1b556a: master without slots is reachable again.
48854:S 16 Dec 2022 16:06:57.786 # Forced failover user request accepted.
48854:S 16 Dec 2022 16:06:57.830 # Start of election delayed for 0 milliseconds (rank #0, offset 476).
48854:S 16 Dec 2022 16:06:57.830 # Starting a failover election for epoch 37.
48854:S 16 Dec 2022 16:06:57.831 # Currently unable to failover: Waiting for votes, but majority still not reached.
48854:S 16 Dec 2022 16:06:57.831 # Failover election won: I'm the new master.
48854:S 16 Dec 2022 16:06:57.831 # configEpoch set to 37 after successful failover
48854:M 16 Dec 2022 16:06:57.831 # Connection with master lost.
48854:M 16 Dec 2022 16:06:57.831 * Caching the disconnected master state.
48854:M 16 Dec 2022 16:06:57.831 * Discarding previously cached master state.
48854:M 16 Dec 2022 16:06:57.831 # Setting secondary replication ID to 1299899fe3d02266a70998ec4b0bdfe5c49cc2d0, valid up to offset: 477. New replication ID is b4b3845df5ab4326c4b42a1a9c3f5ba45ffac1a1
48854:M 16 Dec 2022 16:06:57.836 * Replica 192.168.254.2:6690 asks for synchronization
48854:M 16 Dec 2022 16:06:57.836 * Partial resynchronization request from 192.168.254.2:6690 accepted. Sending 0 bytes of backlog starting from offset 477.
48854:M 16 Dec 2022 16:07:40.759 # Failover auth granted to 5a6580c0f2702efe21165c295595b0a28e4a7692 for epoch 38

**Comment by wavelet123** [comment]
我用redisshake2 同步完成了，虽然比较惊险，主要client_output_buffer设大之后，内存不够了

**Comment by suxb201** [comment]
> > @wavelet123 需要 目的端 日志
> 
> 48854:S 16 Dec 2022 16:01:11.780 * Non blocking connect for SYNC fired the event. 48854:S 16 Dec 2022 16:01:11.781 * Master replied to PING, replication can continue... 48854:S 16 Dec 2022 16:01:11.782 * Trying a partial resynchronization (request 05878ded52ad65edc9429752c9aab926167e40cd:1). 48854:S 16 Dec 2022 16:01:11.783 * Full resync from master: 1299899fe3d02266a70998ec4b0bdfe5c49cc2d0:0 48854:S 16 Dec 2022 16:01:11.783 * Discarding previously cached master state. 48854:S 16 Dec 2022 16:01:11.803 * MASTER <-> REPLICA sync: receiving 175 bytes from master to disk 48854:S 16 Dec 2022 16:01:11.803 * MASTER <-> REPLICA sync: Flushing old data 48854:S 16 Dec 2022 16:01:11.803 * MASTER <-> REPLICA sync: Loading DB in memory 48854:S 16 Dec 2022 16:01:11.804 * Loading RDB produced by version 6.2.6 48854:S 16 Dec 2022 16:01:11.804 * RDB age 0 seconds 48854:S 16 Dec 2022 16:01:11.804 * RDB memory usage when created 9.63 Mb 48854:S 16 Dec 2022 16:01:11.804 # Done loading RDB, keys loaded: 0, keys expired: 0. 48854:S 16 Dec 2022 16:01:11.804 * MASTER <-> REPLICA sync: Finished with success 48854:S 16 Dec 2022 16:01:47.490 * Marking node bd983fe5ec8f3042e0453faecbc381ddd4dad55b as failing (quorum reached). 48854:S 16 Dec 2022 16:01:47.490 * Marking node b7d2ef2821ef5407c192d61948859e1e1a333972 as failing (quorum reached). 48854:S 16 Dec 2022 16:02:29.685 * Marking node c7d97d377513598a8c739e88acc84f7da30016e6 as failing (quorum reached). 48854:S 16 Dec 2022 16:02:37.003 * Marking node d76ecb14e8ab832a95ca6115f7fcce787f1b556a as failing (quorum reached). 48854:S 16 Dec 2022 16:02:37.003 * Marking node 936d8dd49672df893fd11f596198b05c67cbff99 as failing (quorum reached). 48854:S 16 Dec 2022 16:02:43.864 * Clear FAIL state for node c7d97d377513598a8c739e88acc84f7da30016e6: master without slots is reachable again. 48854:S 16 Dec 2022 16:02:49.937 * Clear FAIL state for node bd983fe5ec8f3042e0453faecbc381ddd4dad55b: is reachable again and nobody is serving its slots after some time. 48854:S 16 Dec 2022 16:02:53.786 * Clear FAIL state for node b7d2ef2821ef5407c192d61948859e1e1a333972: is reachable again and nobody is serving its slots after some time. 48854:S 16 Dec 2022 16:03:14.382 # Cluster state changed: ok 48854:S 16 Dec 2022 16:03:15.227 * Clear FAIL state for node 936d8dd49672df893fd11f596198b05c67cbff99: master without slots is reachable again. 48854:S 16 Dec 2022 16:03:22.256 * Clear FAIL state for node d76ecb14e8ab832a95ca6115f7fcce787f1b556a: master without slots is reachable again. 48854:S 16 Dec 2022 16:06:57.786 # Forced failover user request accepted. 48854:S 16 Dec 2022 16:06:57.830 # Start of election delayed for 0 milliseconds (rank #0, offset 476). 48854:S 16 Dec 2022 16:06:57.830 # Starting a failover election for epoch 37. 48854:S 16 Dec 2022 16:06:57.831 # Currently unable to failover: Waiting for votes, but majority still not reached. 48854:S 16 Dec 2022 16:06:57.831 # Failover election won: I'm the new master. 48854:S 16 Dec 2022 16:06:57.831 # configEpoch set to 37 after successful failover 48854:M 16 Dec 2022 16:06:57.831 # Connection with master lost. 48854:M 16 Dec 2022 16:06:57.831 * Caching the disconnected master state. 48854:M 16 Dec 2022 16:06:57.831 * Discarding previously cached master state. 48854:M 16 Dec 2022 16:06:57.831 # Setting secondary replication ID to 1299899fe3d02266a70998ec4b0bdfe5c49cc2d0, valid up to offset: 477. New replication ID is b4b3845df5ab4326c4b42a1a9c3f5ba45ffac1a1 48854:M 16 Dec 2022 16:06:57.836 * Replica 192.168.254.2:6690 asks for synchronization 48854:M 16 Dec 2022 16:06:57.836 * Partial resynchronization request from 192.168.254.2:6690 accepted. Sending 0 bytes of backlog starting from offset 477. 48854:M 16 Dec 2022 16:07:40.759 # Failover auth granted to 5a6580c0f2702efe21165c295595b0a28e4a7692 for epoch 38

时间对不上。 不过你既然成功了就先这样吧。

**Comment by wavelet123** [comment]
redisshake2同步成功
