### ISSUE TITLE
关于启动redis-shake报错

### ISSUE THREAD

**Issue by tangwenjie-123** [aliyun/redis-shake#554]
我使用3主3从的redis集群，源集群和目标集群的redis版本都是6.2.8，下面是配置下：
#cat sync.toml 
type = "sync"

[source]
version = 6.0 # redis version, such as 2.8, 4.0, 5.0, 6.0, 6.2, 7.0, ...
address = "182.10.10.21:7001"
password = "123456" # keep empty if no authentication is required

[target]
type = "cluster" # "standalone" or "cluster"
version = 6.0 # redis version, such as 2.8, 4.0, 5.0, 6.0, 6.2, 7.0, ...
address = "182.10.10.11:7001"
password = "123456" # keep empty if no authentication is required

以下为执行命令：
python3 cluster_helper.py ../redis-shake ../sync.toml
对应报错信息：
redis-shake path: ../redis-shake
redis-shake abs path: /root/redis-shake/redis-shake
{'type': 'sync', 'source': {'version': 6.0, 'address': '182.10.10.21:7001', 'username': '', 'password': '123456', 'tls': False, 'elasticache_psync': ''}, 'target': {'type': 'cluster', 'version': 6.0, 'address': '182.10.10.11:7001', 'username': '', 'password': '123456', 'tls': False}, 'advanced': {'dir': 'data', 'ncpu': 4, 'pprof_port': 0, 'metrics_port': 0, 'log_file': 'redis-shake.log', 'log_level': 'debug', 'log_interval': 5, 'rdb_restore_command_behavior': 'rewrite', 'pipeline_count_limit': 1024, 'target_redis_client_max_querybuf_len': 1024000000, 'target_redis_proto_max_bulk_len': 512000000}}
host: 182.10.10.21, port: 7001, username: , password: 123456, tls: False
cluster nodes: {'182.10.10.23:7002': {'node_id': 'a5d020b22593986591180abbe3093abfa7ebdd6c', 'flags': 'slave', 'master_id': '1d21fc980721efe1a34e80421999093353ef68c4', 'last_ping_sent': '0', 'last_pong_rcvd': '1672366218000', 'epoch': '3', 'slots': [], 'migrations': [], 'connected': True}, '182.10.10.21:7001': {'node_id': 'cc593181a220491ffedc657e8b530d6e0179ebe1', 'flags': 'myself,master', 'master_id': '-', 'last_ping_sent': '0', 'last_pong_rcvd': '1672366218000', 'epoch': '1', 'slots': [['0', '5460']], 'migrations': [], 'connected': True}, '182.10.10.22:7002': {'node_id': '8cede6434b66e3bbe240ef883616767f7a487790', 'flags': 'slave', 'master_id': 'cc593181a220491ffedc657e8b530d6e0179ebe1', 'last_ping_sent': '0', 'last_pong_rcvd': '1672366219000', 'epoch': '1', 'slots': [], 'migrations': [], 'connected': True}, '182.10.10.22:7001': {'node_id': '1d21fc980721efe1a34e80421999093353ef68c4', 'flags': 'master', 'master_id': '-', 'last_ping_sent': '0', 'last_pong_rcvd': '1672366219994', 'epoch': '3', 'slots': [['5461', '10922']], 'migrations': [], 'connected': True}, '182.10.10.23:7001': {'node_id': 'df0b1bd0ed9ed31e97a915f389a4b99bb389f58e', 'flags': 'slave', 'master_id': 'f3fc0980d6ebde792212985cdb0fa5a39596affc', 'last_ping_sent': '0', 'last_pong_rcvd': '1672366221002', 'epoch': '7', 'slots': [], 'migrations': [], 'connected': True}, '182.10.10.21:7002': {'node_id': 'f3fc0980d6ebde792212985cdb0fa5a39596affc', 'flags': 'master', 'master_id': '-', 'last_ping_sent': '0', 'last_pong_rcvd': '1672366219000', 'epoch': '7', 'slots': [['10923', '16383']], 'migrations': [], 'connected': True}}
addresses:
182.10.10.21:7001
182.10.10.22:7001
182.10.10.21:7002
start syncing...
sleep 3 seconds to wait redis-shake start
================ 2022-12-30 10:10:24 ================
get metrics from [182.10.10.21:7001] failed: HTTPConnectionPool(host='localhost', port=11008): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe61af1520>: Failed to establish a new connection: [Errno 111] Connection refused'))
get metrics from [182.10.10.22:7001] failed: HTTPConnectionPool(host='localhost', port=11009): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe61af1dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
get metrics from [182.10.10.21:7002] failed: HTTPConnectionPool(host='localhost', port=11010): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe61ac0610>: Failed to establish a new connection: [Errno 111] Connection refused'))
no redis-shake is running
Waiting for process 7177 to exit...
process 7177 exited.
Waiting for process 7178 to exit...
process 7178 exited.
Waiting for process 7179 to exit...
process 7179 exited.

单独启动一个redis-shake也同样报错：
#./redis-shake sync.toml 
./redis-shake: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./redis-shake)
./redis-shake: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./redis-shake)

**Comment by suxb201** [comment]
@tangwenjie-123  依赖有问题，clone 下仓库自己编译就行

**Comment by tangwenjie-123** [comment]
果然是依赖问题，我配置go环境自己用源码编译就ok了，直接下载编译好的包是有问题的。感谢大佬
