### ISSUE TITLE
“/usr/lib64/libc.so.6: version `GLIBC_2.32' not found”的报错

### ISSUE THREAD

**Issue by v587xpt** [aliyun/redis-shake#556]
请问使用的时候出现过这个问题吗？是我缺失了什么环境么？
![image](https://user-images.githubusercontent.com/37898515/213096058-5ef2719b-d595-4b50-8830-c815dbabe570.png)
我查到可能是因为 glibc 版本低，可以在升级glibc过程中遇到了一连串的问题，各种的包都要升级.....

**Comment by suxb201** [comment]
可以下载源码自己编译，注意要有较新的 go 环境。
```
sh build.sh
```
