### ISSUE TITLE
[PANIC] restore command error key:task:user:6464009835423744:day:20230227:movie:time err:Do failed[EOF]

### ISSUE THREAD

**Issue by 0521ak47** [aliyun/redis-shake#565]
- [ ] 请确保已经看过 wiki：https://github.com/alibaba/RedisShake/wiki
- [ ] 请确保已经学习过 Markdown 语法，良好的排版有助于维护人员了解你的问题
- [ ] 请在此提供足够的信息供社区维护人员排查问题
- [ ] 请在提交 issue 前删除此模板中多余的文字，包括这几句话

**问题描述**
redis-shakev2.0.3 通过rdb文件恢复到目的redis-cluster集群过程中报一下错误
[PANIC] restore command error key:task:user:6464009835423744:day:20230227:movie:time err:Do failed[EOF]
这里描述你的问题。

redis-shake 的日志：
shake 的日志贴在这里
```
[PANIC] restore command error key:task:user:6464009835423744:day:20230227:movie:time err:Do failed[EOF]
---

**源端 Redis**
版本：6.0，集群自建
日志：
```
[PANIC] restore command error key:task:user:6464009835423744:day:20230227:movie:time err:Do failed[EOF]
```

---

**目的端 Redis**
版本：6.0，集群 自建
日志：
```
[PANIC] restore command error key:task:user:6464009835423744:day:20230227:movie:time err:Do failed[EOF]
```

**Comment by suxb201** [comment]
试下 3.x 版本的 redis-shake：https://github.com/alibaba/RedisShake/releases

**Comment by 0521ak47** [comment]
> 试下 3.x 版本的 redis-shake：https://github.com/alibaba/RedisShake/releases
如何离线迁移？源集群与目标集群网络不通，我想通过备份rdb后，拷贝到目标集群迁移，我暂时找不到3.x版本有关离线迁移的文档，都是2.x的文档才有离线迁移的

**Comment by suxb201** [comment]
https://github.com/alibaba/RedisShake/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B%EF%BC%9A%E4%BB%8E-dump.rdb-%E6%81%A2%E5%A4%8D%E6%95%B0%E6%8D%AE

**Comment by 0521ak47** [comment]
> https://github.com/alibaba/RedisShake/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B%EF%BC%9A%E4%BB%8E-dump.rdb-%E6%81%A2%E5%A4%8D%E6%95%B0%E6%8D%AE

此文档只是介绍单机到单机，单机到集群的方式。集群到集群的方式没有，是否从源集群每个master节点拷贝dump.rdb，然后怎么导入？

**Comment by suxb201** [comment]
@0521ak47 是，分别导入。

**Comment by 0521ak47** [comment]
是集群A每个master节点对应集群B每个master节点导入？，那要执行三次？

**Comment by 0521ak47** [comment]
> @0521ak47 是，分别导入。


是集群A每个master节点对应集群B每个master节点导入？，那要执行三次？
但是我看官方文档只是需要填写目标其中1个master节点？

**Comment by suxb201** [comment]
rdb 对集群这样导入。因为你有三个 rdb，所以要执行三次。
