### ISSUE TITLE
自建redis同步数据失败

### ISSUE THREAD

**Issue by zzkkll99** [aliyun/redis-shake#574]
**问题描述**
自检redis 单机到单机同步数据，上下游版本一致（2.8 版本merge高版本特性）；sync模式同步数据失败

redis-shake 的日志：
```
2023-03-10 16:59:57 PNC redisWriter received error. error=[ERR wrong number of arguments for 'restore' command], argv=[restore hotcontent:lowScore:toutiao_7206314578790154790 103303584 0.8852223753929138
           F�RG� replace], slots=[10191], reply=[<nil>]
panic: redisWriter received error. error=[ERR wrong number of arguments for 'restore' command], argv=[restore hotcontent:lowScore:toutiao_7206314578790154790 103303584 0.8852223753929138
                                                          F�RG�
```

---

redis日志无异常

**Comment by zzkkll99** [comment]
# log
log_file = "redis-shake.log"
log_level = "info" # debug, info or warn
log_interval = 5 # in seconds
rdb_restore_command_behavior = "rewrite"

**Comment by zzkkll99** [comment]
配置信息如下：
# log
log_file = "redis-shake.log"
log_level = "info" # debug, info or warn
log_interval = 5 # in seconds
rdb_restore_command_behavior = "rewrite"

**Comment by suxb201** [comment]
是目的版本不支持 restore 的一些参数
<img width="691" alt="image" src="https://user-images.githubusercontent.com/16659368/224277514-c236fdb4-2617-4807-9932-37ff90559fd6.png">

请准确填写配置文件中的 version 字段

**Comment by zzkkll99** [comment]
确认下当前 redis版本支持  RESTORE 命令；

**Comment by zzkkll99** [comment]
redis 版本配置为2.8 后
2023-03-10 17:58:27 INF RDB version: 6
2023-03-10 17:58:27 PNC RDB restore command behavior is rewrite, but target redis version is 2.800000, not support REPLACE modifier
panic: RDB restore command behavior is rewrite, but target redis version is 2.800000, not support REPLACE modifier

**Comment by suxb201** [comment]
改下这个参数
```toml
# redis-shake gets key and value from rdb file, and uses RESTORE command to
# create the key in target redis. Redis RESTORE will return a "Target key name
# is busy" error when key already exists. You can use this configuration item
# to change the default behavior of restore:
# panic:   redis-shake will stop when meet "Target key name is busy" error.
# rewrite: redis-shake will replace the key with new value.
# ignore:  redis-shake will skip restore the key when meet "Target key name is busy" error.
rdb_restore_command_behavior = "rewrite" # panic, rewrite or skip
```

**Comment by suxb201** [comment]
[rdb_restore_command_behavior](https://github.com/alibaba/RedisShake/wiki/%E5%B8%B8%E8%A7%81%E6%8A%A5%E9%94%99#err-wrong-number-of-arguments-for-restore-command)

**Comment by zzkkll99** [comment]
rdb_restore_command_behavior 尝试改为 panic 或 skip后 会报如下错误：

**Comment by zzkkll99** [comment]
rdb_restore_command_behavior 参数尝试改为 skip 或 panic会报以下错误：
{"level":"info","time":"2023-03-10T19:26:32+08:00","message":"syncing rdb. percent=[36.13]%, allowOps=[19374.00], disallowOps=[0.00], entryId=[410535], InQueue
EntriesCount=[0], unansweredBytesCount=[0]bytes, rdbFileSize=[1.278]G, rdbSendSize=[0.462]G"}
{"level":"panic","time":"2023-03-10T19:26:34+08:00","message":"redisWriter received error. error=[ERR Target key name is busy.], argv=[restore redismon 0 \u000
0\ufffd\u0001\u0006\u0000\ufffd\ufffd\ufffd6$T-o], slots=[3041], reply=[<nil>]"}

**Comment by zzkkll99** [comment]
配置截图如下:
<img width="833" alt="image" src="https://user-images.githubusercontent.com/46043574/225196029-ebb052ff-bdaf-4bf3-aba8-5f96b9ec733b.png">

**Comment by suxb201** [comment]
是 BUG，没有针对 2.8 测过这个特性，2.8 的报错与其他版本不一样，你可以改改这部分代码测试下：
```diff
--- a/internal/writer/redis.go
+++ b/internal/writer/redis.go
@@ -65,7 +65,8 @@ func (w *redisWriter) flushInterval() {
                if err == proto.Nil {
                        log.Warnf("redisWriter receive nil reply. argv=%v", e.Argv)
                } else if err != nil {
-                       if err.Error() == "BUSYKEY Target key name already exists." {
+                       if err.Error() == "BUSYKEY Target key name already exists." || // others
+                               err.Error() == "ERR Target key name is busy." { // Redis 2.8
                                if config.Config.Advanced.RDBRestoreCommandBehavior == "skip" {
                                        log.Warnf("redisWriter received BUSYKEY reply. argv=%v", e.Argv)
                                } else if config.Config.Advanced.RDBRestoreCommandBehavior == "panic" {
```

改动后：
```golang
func (w *redisWriter) flushInterval() {
	for e := range w.chWaitReply {
		reply, err := w.client.Receive()
		if err == proto.Nil {
			log.Warnf("redisWriter receive nil reply. argv=%v", e.Argv)
		} else if err != nil {
			if err.Error() == "BUSYKEY Target key name already exists." || // others
				err.Error() == "ERR Target key name is busy." { // Redis 2.8
				if config.Config.Advanced.RDBRestoreCommandBehavior == "skip" {
					log.Warnf("redisWriter received BUSYKEY reply. argv=%v", e.Argv)
				} else if config.Config.Advanced.RDBRestoreCommandBehavior == "panic" {
					log.Panicf("redisWriter received BUSYKEY reply. argv=%v", e.Argv)
				}
			} else {
				log.Panicf("redisWriter received error. error=[%v], argv=%v, slots=%v, reply=[%v]", err, e.Argv, e.Slots, reply)
			}
		}
		atomic.AddUint64(&w.UpdateUnansweredBytesCount, ^(e.EncodedSize - 1))
		statistics.UpdateAOFAppliedOffset(uint64(e.Offset))
		statistics.UpdateUnansweredBytesCount(atomic.LoadUint64(&w.UpdateUnansweredBytesCount))
	}
	w.chWg.Done()
}

```

**Comment by zzkkll99** [comment]
<img width="1911" alt="image" src="https://user-images.githubusercontent.com/46043574/225506049-5e01e287-e2cc-4119-aa16-895be7716dc2.png">
大佬， 根据提示修改后全量同步完成 增量同步失败又失败了， 辛苦看下报错

**Comment by suxb201** [comment]
@zzkkll99 麻烦发下带栈的日志

**Comment by zzkkll99** [comment]
2023-03-16 11:19:06 PNC redis: can't parse bool reply: "#1678936629"
2023-03-16 11:19:06 INF AOFReader close file. aof_filename=[3937871805.aof]
panic: redis: can't parse bool reply: "#1678936629"

goroutine 23 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc00fae7a40?, 0x0?})
	/Users/leezhe/Desktop/gosrc/pkg/mod/github.com/rs/zerolog@v1.28.0/log.go:375 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc000204060, {0xc00fae7a40, 0x2c})
	/Users/leezhe/Desktop/gosrc/pkg/mod/github.com/rs/zerolog@v1.28.0/event.go:156 +0x2a5
github.com/rs/zerolog.(*Event).Msgf(0xc000204060, {0xc00fae7a10?, 0x461?}, {0x0?, 0x7c4926?, 0x3?})
	/Users/leezhe/Desktop/gosrc/pkg/mod/github.com/rs/zerolog@v1.28.0/event.go:129 +0x4e
github.com/alibaba/RedisShake/internal/log.Panicf({0xc00fae7a10, 0x2c}, {0x0, 0x0, 0x0})
	/Users/leezhe/Desktop/gosrc/src/RedisShake/internal/log/func.go:32 +0xef
github.com/alibaba/RedisShake/internal/log.PanicError({0x863980?, 0xc00faf0700?})
	/Users/leezhe/Desktop/gosrc/src/RedisShake/internal/log/func.go:36 +0x33
github.com/alibaba/RedisShake/internal/client.ArrayString({0x75f680?, 0xa42620}, {0x863980?, 0xc00faf0700?})
	/Users/leezhe/Desktop/gosrc/src/RedisShake/internal/client/reply.go:7 +0x46
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).sendAOF(0xc0000fa230, 0xc0002c2060?)
	/Users/leezhe/Desktop/gosrc/src/RedisShake/internal/reader/psync.go:223 +0x23e
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1()
	/Users/leezhe/Desktop/gosrc/src/RedisShake/internal/reader/psync.go:51 +0x114
created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead
	/Users/leezhe/Desktop/gosrc/src/RedisShake/internal/reader/psync.go:43 +0x8d

**Comment by suxb201** [comment]
你 merge 了什么高版本特性？Redis 2.8 发给 slave 的内容不规范。

**Comment by zzkkll99** [comment]
4.0版本的 内存回收等； 我看了下aof文件内容  没什么区别
<img width="777" alt="image" src="https://user-images.githubusercontent.com/46043574/225510234-00d4c2b3-97ab-4de7-a1a0-841271aec880.png">

**Comment by zzkkll99** [comment]
<img width="950" alt="image" src="https://user-images.githubusercontent.com/46043574/225548412-ad2d1a90-0424-4fbe-befd-6e90ee0d1ac1.png">
大佬， 是不是这一类内容导致解析失败了？ 
<img width="1894" alt="image" src="https://user-images.githubusercontent.com/46043574/225548768-1619f921-1d6e-4fcd-a89a-473f5aa25e98.png">
我debug了下， 前面正常可以解析到一部分aof的内容

**Comment by suxb201** [comment]
和 AOF 文件没关系，报错是 shake 收到主发过来的包，发现没法解析，就报错了。确认没有修改 redis 的主从复制的话，建议：
1. 重新尝试下
2. 使用 Wireshark 抓包看看

**Comment by suxb201** [comment]
@zzkkll99 请问知道原因了吗？

**Comment by boomballa** [comment]
@zzkkll99 和您遇到一样的问题，请问解决了不？

**Comment by zzkkll99** [comment]
> @zzkkll99 请问知道原因了吗？
魔改内核的时候复制日志中增加了时间戳，针对这部分工具做了下兼容
