### ISSUE TITLE
Redisshake全量同步可以限速吗？

### ISSUE THREAD

**Issue by niheartent** [aliyun/redis-shake#577]
请问Redisshake全量同步可以限速吗？

另外我对配置文件中的一些参数不太理解，请问以下参数如何对Redisshake产生影响？
pipeline_count_limit
target_redis_client_max_querybuf_len
target_redis_proto_max_bulk_len

**Comment by suxb201** [comment]
不支持限速。
配置文件中有参数说明，没出问题的情况下不需要动这些参数。

**Comment by niheartent** [comment]
这三个应该是等效为redis conf文件中配置？请问这里配置最后这三个参数的目的是什么，可以讲解一下吗？

**Comment by suxb201** [comment]
* pipeline_count_limit 可以理解为 RedisShake 的发送 buffer 大小
* 后两个与 Redis 实现强相关，没遇到问题就不需要了解，想解释清楚要讲一大堆才行。可以去搜 Redis conf 中类似字段。

**Comment by niheartent** [comment]
> * pipeline_count_limit 可以理解为 RedisShake 的发送 buffer 大小
> * 后两个与 Redis 实现强相关，没遇到问题就不需要了解，想解释清楚要讲一大堆才行。可以去搜 Redis conf 中类似字段。

感谢
