### ISSUE TITLE
全量同步之后，增量出现报错

### ISSUE THREAD

**Issue by fg1813042793** [aliyun/redis-shake#578]
- [x] 请确保已经看过 wiki：https://github.com/alibaba/RedisShake/wiki
- [x] 请确保已经学习过 Markdown 语法，良好的排版有助于维护人员了解你的问题
- [x] 请在此提供足够的信息供社区维护人员排查问题
- [x] 请在提交 issue 前删除此模板中多余的文字，包括这几句话

**问题描述**

同步任务是自建的standalone 4.0到阿里云社区版cluster 6.0；全量之后增量出现mset 报错

redis-shake 的日志：
```
shake 的日志贴在这里
```
"level":"panic","time":"2023-03-19T01:35:18+08:00","message":"CROSSSLOT Keys in request don't hash to the same slot. argv=[MSET LIKE_COUNT_301995 438 LIKE_COUNT_301997
---

**源端 Redis**
版本 4.0，自建
日志：
```
日志贴在这里
```

---

**目的端 Redis**
版本：6.0，阿里云社区版
日志：
```
日志贴在这里
```

**Comment by suxb201** [comment]
1. 请整理提问格式：https://markdown.com.cn/basic-syntax/
2. 这是 Redis 常见报错，不要在集群模式下使用跨 slot 命令：https://stackoverflow.com/questions/38042629/redis-cross-slot-error
