### ISSUE TITLE
不懂就问

### ISSUE THREAD

**Issue by matrixoom** [aliyun/redis-shake#581]
**问题描述**
你好，初识redis-shake，感谢分享。有几点疑问：
1. 看v3版本说的是欢迎非生产环境试用，本来打算在生产环境使用，看到这个有点顾虑了，v3在版本现在不稳定吗，不推荐在线上使用吗？
2. v3版本的参数少很多，个别参数还看不明白事什么意思，比如下面这三个，似懂非懂的，能否解释下作用。 v2中很多参数都没有了，是都不支持了吗？还能或者需要配置吗？
 # pipeline
pipeline_count_limit = 1024

# Client query buffers accumulate new commands. They are limited to a fixed
# amount by default. This amount is normally 1gb.
target_redis_client_max_querybuf_len = 1024_000_000

# In the Redis protocol, bulk requests, that are, elements representing single
# strings, are normally limited to 512 mb.
target_redis_proto_max_bulk_len = 512_000_000

**Comment by suxb201** [comment]
1. v3 可以在生产环境使用
2. 关于你咨询的参数：https://github.com/alibaba/RedisShake/issues/577
3. 相对于 v2 缺失的参数主要是过滤项，这部分功能由 lua 脚本承接：https://github.com/alibaba/RedisShake/wiki/%E4%BD%BF%E7%94%A8-filters-%E5%81%9A%E6%95%B0%E6%8D%AE%E6%B8%85%E6%B4%97

**Comment by matrixoom** [comment]
您好，您的来信我已收到，谢谢。

**Comment by matrixoom** [comment]
多谢~
