### ISSUE TITLE
sync同步问题询问

### ISSUE THREAD

**Issue by haiqishiwo** [aliyun/redis-shake#582]
**问题描述**

你好，初识redis-shake，感谢分享。有两点疑问(基于最新版本)：
1.在sync模式下,因为其是先全量再增量同步，且是自动进入增量同步,那我怎么能知道我目的端什么时候全量同步结束进入增量同步的，有日志或者其他什么手段知道吗？

我目前的需求为:
 不停机同步redis单点数据到redis cluster集群中,且需要将新增到redis cluster中的某些key按一定规则转换为新key,我转换程序已经有了,
但是我并不想在我使用转换程序的时候还在同步数据到目的端，所以:

2.是否有方法能暂停数据同步到目的端,等我处理完之前的数据后，再恢复同步，继续同步到目的端

---

**源端 Redis**
版本：5.0  单点

---

**目的端 Redis**
版本： 5.0 集群

**Comment by suxb201** [comment]
1. 日志中有字段可以判断的，可以对比下日志
2. 目前没办法暂停，只能通过停止向源端写入实现。但是对于按 key 转化的需求，这里有一个 PR 说不定有帮助：https://github.com/alibaba/RedisShake/pull/555

**Comment by suxb201** [comment]
@haiqishiwo 现在 shake 原生支持 key 的转换了，参考：https://tair-opensource.github.io/RedisShake/zh/function/best_practices.html
