### ISSUE TITLE
请问是否可以在redis-shark启动的时候设置同步开始的offset

### ISSUE THREAD

**Issue by letianyuweng** [aliyun/redis-shake#584]
请问是否可以在redis-shark启动的时候设置同步开始的offset

**Comment by suxb201** [comment]
不支持，是想触发增量同步吗？

理论上可以，但是 Redis 的增量同步握手成功率不高，暂时不打算搞。

**Comment by letianyuweng** [comment]
> 不支持，是想触发增量同步吗？
> 
> 理论上可以，但是 Redis 的增量同步握手成功率不高，暂时不打算搞。

是的

**Comment by letianyuweng** [comment]
> 不支持，是想触发增量同步吗？
> 
> 理论上可以，但是 Redis 的增量同步握手成功率不高，暂时不打算搞。

你好，看了V3的文档。v3文档上写的是测试了5.0，6.0。我们目前测试下来3系列迁移到6是没有问题的。请问下是否可能有潜藏的问题，或者从逻辑上来说是兼容的

**Comment by suxb201** [comment]
@letianyuweng 目前没有已知问题；如果使用了module 需要保证 module 内单 key 的大小不能超过 500MB

**Comment by letianyuweng** [comment]
已解决
