### ISSUE TITLE
AWS Elasticache 数据迁移时 BytesUsedForCache 暴涨

### ISSUE THREAD

**Issue by niheartent** [aliyun/redis-shake#585]
**问题描述**

Redis 4.0->7.0数据迁移，源集群52GB可用内存，原内存使用量40%，当开启增量同步时BytesUsedForCache 暴涨，导致数据库内存使用量暴涨，请问这是为什么？
请问源集群的BytesUsedForCache和什么有关？
请问增量同步阶段如果没有切换业务访问连接，原集群的BytesUsedForCache会一直涨吗
![image](https://user-images.githubusercontent.com/57069100/230260886-53484615-88e3-48c0-bf44-6b302919e754.png)
![image](https://user-images.githubusercontent.com/57069100/230260932-009ad6ae-a502-4981-91e9-d3baaf0b7117.png)

redis-shake 的日志：
```
增量同步阶段报WARN 
{"level":"info","time":"2023-03-28T08:53:51Z","message":"send RDB finished. address=[pet-redis-aps1.dlalsm.ng.0001.apse1.cache.amazonaws.com:6379], repl-stream-db=[0]"}
{"level":"info","time":"2023-03-28T08:53:52Z","message":"AOFReader open file. aof_filename=[8524366045542.aof]"}
{"level":"warn","time":"2023-03-28T08:53:52Z","message":"redisWriter receive nil reply. argv=[EVAL redis.call(...)]"}
{"level":"warn","time":"2023-03-28T08:53:52Z","message":"redisWriter receive nil reply. argv=[EVAL redis.call(...)]"}
{"level":"warn","time":"2023-03-28T08:53:52Z","message":"redisWriter receive nil reply. argv=[EVAL redis.call(...)]"}
...
```
```
ubuntu@ip-10-123-0-89:~$ curl localhost:1024
{"address":"*","entry_id":24962998,"allow_entries_count":7323871,"disallow_entries_count":17639128,"is_doing_bgsave":false,"rdb_file_size":8174081883,"rdb_received_size":8174081883,"rdb_send_size":8174081883,"aof_received_offset":309710726346220,"aof_applied_offset":309710726280683,"in_queue_entries_count":0,"unanswered_bytes_count":0,"scan_db_id":0,"scan_cursor":0,"msg":"syncing aof. allowOps=[5583.80], disallowOps=[3763.80], entryId=[24947665], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[81920], aofReceivedOffset=[309710714222060], aofAppliedOffset=[309710714140140]"}
```
---

**源端 Redis**
版本：aws elasticache 4.0

**目的端 Redis**
版本：aws elasticache 7.0

**Comment by suxb201** [comment]
原因：源端节点做快照导致的，猜测开启 AOF 或者减少源端写流量会好些
会一直涨吗：不会，理论上较坏情况内存会上涨一倍，这也是为什么 EC 会建议你预留内存。进入增量同步阶段后内存应该会下降不少。

**Comment by niheartent** [comment]
> 原因：源端节点做快照导致的，猜测开启 AOF 或者减少源端写流量会好些 会一直涨吗：不会，理论上较坏情况内存会上涨一倍，这也是为什么 EC 会建议你预留内存。进入增量同步阶段后内存应该会下降不少。
![image](https://user-images.githubusercontent.com/57069100/230303114-2987798e-85ed-4d1e-86ea-f0f98dff40fb.png)

看指标确实在增量同步节点，斜率减少，10:07时全量同步结束，此时内存增长量为rdb文件大小，但是增量同步阶段看起来内存使用率会无限增长？增量同步阶段的bytesforcache会有增长尽头吗？

**Comment by suxb201** [comment]
@niheartent 不符合预期，可以咨询下 EC 支持
