### ISSUE TITLE
增量同步过程中遇到Lua script attempted to access a non local key in a cluster node导致同步中断

### ISSUE THREAD

**Issue by Dankeee** [aliyun/redis-shake#597]
**问题描述**
cluster到cluster同步，源和目标版本都是4.0，分片数量都是4个，但是刚开启增量同步，其中一个redis-shake子任务就会中断，尝试过单独启动同步失败节点的redis-shake任务，也会复现该问题

redis-shake 的日志：
```
PNC redisWriter received error. error=[ERR Error running script (call to f_8edf47511368bee7537a65ab07d869a8e29c6161): @user_script:1: @user_script: 1: Lua script attempted to access a non local key in a cluster node ]
```

---

**源端 Redis**
版本：4.0.14，自建

---

**目的端 Redis**
版本：4.0.9，6.0.14都试过，自建集群模式

**Comment by Dankeee** [comment]
异常日志和服务端抓包看到redis.call 操作的key都是同一个

panic: redisWriter received error. error=[ERR Error running script (call to f_8edf47511368bee7537a65ab07d869a8e29c6161): @user_script:1: @user_script: 1: Lua script attempted to access a non local key in a cluster node ], argv=[EVAL redis.call('del', 'u_bg_i_01')  redis.call('hset', 'u_bg_i_01', '605092589', '[{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/24918334918/b8cc/2023115194348/11qe.jpg","id":49003,"imageType":0,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/24918295000/263f/2023115194158/318tian.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/24918085854/6e44/2023115193239/suoluo.png"},{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/24917969588/56f6/202311519273/1124.jpg","id":45004,"imageType":0,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/24917968273/8e1f/2023115192658/318.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/24917965331/d5de/2023115192650/suoluo.png"},{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/12755578843/1d44/202201920926/mpw.mp4","id":23001,"imageType":1,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/12755632233/f56d/202201920127/0220119201154.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/12755112242/b71c/2022019194255/obj_w5nDksOAwrHCnTvDjcOj_12272196056_db1f_20211124145925_mTex.png"}]')  redis.call('hset', 'u_bg_i_01', '1291139907', '[{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/24719772550/4371/20231914222/12.jpg","id":49002,"imageType":0,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/24719774150/9789/20231914225/13.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/24719769104/fc28/202319142152/suluo.png"},{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/24063164808/ceff/2023016203839/tunian.jpg","id":45003,"imageType":0,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/24063164193/b179/2023016203835/tunian111.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/24063160413/c782/2023016203829/3444.png"},{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/23634797840/2354/20221130112626/3.jpg","id":48001,"imageType":1,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/23634797440/d8aa/20221130112622/2.png","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/23634796852/88a2/20221130112619/1.png"},{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/12755578843/1d44/202201920926/mpw.mp4","id":23001,"imageType":1,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/12755632233/f56d/202201920127/0220119201154.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/12755112242/b71c/2022019194255/obj_w5nDksOAwrHCnTvDjcOj_12272196056_db1f_20211124145925_mTex.png"},{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/12254150638/2b81/20211123155535/1124-2000.jpg","id":12002,"imageType":1,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/12254150362/22be/20211123155531/318-444.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/12254144784/5034/20211123155523/mTex.png"}]')  redis.call('hset', 'u_bg_i_01', '360276649', '[{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/14676803050/459d/2022425175316/1124.jpg","id":41004,"imageType":1,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/14676799773/9c98/2022425175312/318.png","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/14676798227/373e/202242517534/mTex.jpg"}]')  redis.call('hset', 'u_bg_i_01', '412727529', '[{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/14676803050/459d/2022425175316/1124.jpg","id":41004,"imageType":1,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/14676799773/9c98/2022425175312/318.png","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/14676798227/373e/202242517534/mTex.jpg"},{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726331354/a854/2022231143151/1124.jpg","id":42002,"imageType":1,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726328113/e388/2022231143137/318.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726321774/6fbc/2022231143122/512.jpg"}]')  redis.call('hset', 'u_bg_i_01', '491087044', '[{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726331354/a854/2022231143151/1124.jpg","id":42002,"imageType":1,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726328113/e388/2022231143137/318.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726321774/6fbc/2022231143122/512.jpg"}]')  redis.call('hset', 'u_bg_i_01', '1607419073', '[{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726331354/a854/2022231143151/1124.jpg","id":42002,"imageType":1,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726328113/e388/2022231143137/318.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726321774/6fbc/2022231143122/512.jpg"}]')  redis.call('hset', 'u_bg_i_01', '286574320', '[{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726331354/a854/2022231143151/1124.jpg","id":42002,"imageType":1,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726328113/e388/2022231143137/318.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726321774/6fbc/2022231143122/512.jpg"}]')  redis.call('hset', 'u_bg_i_01', '1481887940', '[{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726331354/a854/2022231143151/1124.jpg","id":42002,"imageType":1,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726328113/e388/2022231143137/318.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726321774/6fbc/2022231143122/512.jpg"}]')  redis.call('hset', 'u_bg_i_01', '1960790238', '[{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726331354/a854/2022231143151/1124.jpg","id":42002,"imageType":1,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726328113/e388/2022231143137/318.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/13726321774/6fbc/2022231143122/512.jpg"}]')  redis.call('hset', 'u_bg_i_01', '516696120', '[{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/12254150638/2b81/20211123155535/1124-2000.jpg","id":12002,"imageType":1,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/12254150362/22be/20211123155531/318-444.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/12254144784/5034/20211123155523/mTex.png"}]')  redis.call('hset', 'u_bg_i_01', '121866148', '[{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/12254150638/2b81/20211123155535/1124-2000.jpg","id":12002,"imageType":1,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/12254150362/22be/20211123155531/318-444.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/12254144784/5034/20211123155523/mTex.png"}]')  redis.call('hset', 'u_bg_i_01', '373622634', '[{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/11986377647/9a15/2021118145529/zuixin.jpg","id":6001,"imageType":0,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/11983554267/c16b/2021118104111/yulan.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/11983552336/9f93/202111810416/suolue.png"}]')  redis.call('hset', 'u_bg_i_01', '494189492', '[{"bgImageKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/11986377647/9a15/2021118145529/zuixin.jpg","id":6001,"imageType":0,"previewImgKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/11983554267/c16b/2021118104111/yulan.jpg","thumbnailKey":"yyimgs/obj/w5nDksOAwrHCnTvDjcOj/11983552336/9f93/202111810416/suolue.png"}]')  0], slots=[], reply=[<nil>]

**Comment by suxb201** [comment]
lua 脚本问题，自己检查下吧。搜这个报错能搜出很多回答：`Lua script attempted to access a non local key in a cluster node`

**Comment by Dankeee** [comment]
redis-shake3.x 能否跟2.x一样配置不让lua脚本通过呢

**Comment by suxb201** [comment]
可以的：https://github.com/tair-opensource/RedisShake/wiki/%E4%BD%BF%E7%94%A8-filters-%E5%81%9A%E6%95%B0%E6%8D%AE%E6%B8%85%E6%B4%97#skip_scriptslua-%E8%B7%B3%E8%BF%87%E6%89%80%E6%9C%89-scripting-%E5%91%BD%E4%BB%A4
