### ISSUE TITLE
Does v3 will support redis module?

### ISSUE THREAD

**Issue by ghost** [aliyun/redis-shake#599]
RedisShake 团队：
你好。之前v2版支持阿里自研的redis tair模块迁移，请问v3版是否会支持？
谢谢

**Comment by suxb201** [comment]
@ZengyiZhao 云上还是云下，云上走 DTS 可以支持，云下 Shake 考虑支持下 TairHash、TairZset、TairString。

**Comment by suxb201** [comment]
对了，其实大多数情况下现在也是可以迁移的，只有 key 特别大的情况（单 key 超过 500M）需要特殊适配。

**Comment by suxb201** [comment]
@ZengyiZhao 目前已经支持了 TairHash、TairZset、TairString。
