### ISSUE TITLE
请问一下，最新版v3支持下面这些特性吗？

### ISSUE THREAD

**Issue by zhanghaiyang9999** [aliyun/redis-shake#600]
1.断点续传，比如网络断开或者程序异常退出，重新启动情况。
2.传输过程中（比如从master接收数据，发送数据到目标端等）有压缩或者加密功能吗？
3.支持插件吗？比如全量同步进度或者全量同步结束通知等。

多谢！！！

**Comment by suxb201** [comment]
1. 不支持，无法实现
2. 不支持，没有必要
3. 这些可以从日志或者监控获取
