### ISSUE TITLE
源端存在使用MULTI指令时panic退出

### ISSUE THREAD

**Issue by wxjackie** [aliyun/redis-shake#605]
- [ ] 请确保已经看过 wiki：https://github.com/alibaba/RedisShake/wiki
- [ ] 请确保已经学习过 Markdown 语法，良好的排版有助于维护人员了解你的问题
- [ ] 请在此提供足够的信息供社区维护人员排查问题
- [ ] 请在提交 issue 前删除此模板中多余的文字，包括这几句话

**问题描述**

使用redis shake v3进行同步时，panic退出

redis-shake 的日志：
```
(panic: rediswriter received error. error=[invalid request], argv=[MUlLTI], slots=[], reply=[<nil>]])
```

---

**源端 Redis**
版本：自建，6.2.7
日志：
```
暂无
```

---

**目的端 Redis**
版本：自建6.2.7
日志：
```
暂无
```

如果有默认不支持的Redis原生命令，是否可以内部直接跳过？

**Comment by wxjackie** [comment]
补充2个问题：
1.RedisShakeV3目前有哪些命令是不支持会Panic退出的呢？
2.Shake V3运行期间的内存占用有估算方式吗，比如源集群为5分片的RedisCluster，每个分片RDB文件3GB左右。

**Comment by suxb201** [comment]
MUlLTI 这是 multi 敲错了吗？
可以使用 filter 来过滤。
内存占用取决于最大的 key。

**Comment by wxjackie** [comment]
好的，如果我想过滤所有的事务命令，filter脚本应该如何写呢，事务命令有统一的group吗，像示例的skip_scripts.lua那样的。

**Comment by suxb201** [comment]
事务只有 multi 和 exec 按命令过滤即可

**Comment by wxjackie** [comment]
> MUlLTI 这是 multi 敲错了吗？ 可以使用 filter 来过滤。 内存占用取决于最大的 key。

请问redis-shake进程的内存占用与源端Redis的dump.rdb大小有关吗，实际使用中频繁出现read dump.rdb: cannot allocate memory的panic问题

**Comment by suxb201** [comment]
补充了下 wiki：https://github.com/tair-opensource/RedisShake/wiki#%E5%86%85%E5%AD%98%E5%8D%A0%E7%94%A8

**Comment by wxjackie** [comment]
> 补充了下 wiki：https://github.com/tair-opensource/RedisShake/wiki#%E5%86%85%E5%AD%98%E5%8D%A0%E7%94%A8

感谢。wiki中说到shake是逐个key解析发送的，所以 redis-shake 的峰值内存由源端 Redis 源端的体积较大的 key 决定。
1.那么shake在获取到源端的dump.rdb后，是解析dump.rdb，然后逐个key向目标端写入，之后对于源端就相当于是一个增量同步的slave客户端，我描述的准确吗？
2.我们碰到一个奇怪的问题，源端存在一个大key大约500MB，没有额外写入。每次在sync rdb到一定百分比时，shake进程就会断掉，没有ERROR日志但是INFO中间有一点特殊，怀疑是被源端kill掉了，原因不明，理论上如果大key没有额外写入，应该会在全量的rdb中，不会因为同步大key导致超出client-output-limit-buffer，有其他可能的原因和排查思路吗？
<img width="1005" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/17384960/3dc1f8d2-4069-486d-8f7c-7e66b2bbccb2">

**Comment by suxb201** [comment]
1. 是的
2. 看起来是出错 panic 了。可以发下中间出问题的完整 info 看下

**Comment by wxjackie** [comment]
> 1. 是的
> 2. 看起来是出错 panic 了。可以发下中间出问题的完整 info 看下

环境特殊，无法复制文本，前置的正常INFO日志如图
<img width="1219" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/17384960/d9c8ac68-bbc4-4e57-adfd-5cf84db09bb0">

第一张截图已包含PANIC，并且是日志的结尾。

**Comment by suxb201** [comment]
后面应该有类似报错：
```
redisWriter received error. error=
```

**Comment by wxjackie** [comment]
> 后面应该有类似报错：
> 
> ```
> redisWriter received error. error=
> ```

后续日志确实为空的，之后我再使用debug日志级别重试一次后再回复，多谢。
