### ISSUE TITLE
create cluster connection error

### ISSUE THREAD

**Issue by a0a0996** [aliyun/redis-shake#607]
I am getting the below connection error while taking azure redis as the source, what is the workaround, though I am able to connect via redis-cli with same hostname and port

Error:-
2023/05/16 07:56:28 [PANIC] create cluster connection error[NewCluster: no valid node in [10.34.176.58:6379 10.34.176.73:6379 10.34.176.71:6379], error list: [node[10.34.176.58:6379] update failed[unexpected type string for Values: ECONNTIMEOUT: read tcp 10.85.213.168:60843->10.34.176.58:6379: read: connection reset by peer] node[10.34.176.73:6379] update failed[unexpected type string for Values: ECONNTIMEOUT: read tcp 10.85.213.168:60844->10.34.176.73:6379: read: connection reset by peer] node[10.34.176.71:6379] update failed[unexpected type string for Values: ECONNTIMEOUT: read tcp 10.85.213.168:60847->10.34.176.71:6379: read: connection reset by peer]]]
[stack]: 
    3   github.com/alibaba/RedisShake/redis-shake/common/utils.go:57
            github.com/alibaba/RedisShake/redis-shake/common.OpenRedisConnWithTimeout
    2   github.com/alibaba/RedisShake/redis-shake/common/utils.go:38
            github.com/alibaba/RedisShake/redis-shake/common.OpenRedisConn
    1   github.com/alibaba/RedisShake/redis-shake/rump.go:132
            github.com/alibaba/RedisShake/redis-shake.(*dbRumper).run
    0   github.com/alibaba/RedisShake/redis-shake/rump.go:64
            github.com/alibaba/RedisShake/redis-shake.(*CmdRump).Main.func1
        ... ...

**Comment by suxb201** [comment]
Please use redis-shake 3.x as the 2.x version is no longer maintained：https://github.com/tair-opensource/RedisShake/wiki

**Comment by a0a0996** [comment]
With 3.x I am facing issue with PSYNC, since I am using azure redis as source so not able to run the PSYNC, thus using 2.x

**Comment by suxb201** [comment]
@a0a0996 Try the [scan mode](https://github.com/tair-opensource/RedisShake/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B%EF%BC%9A%E6%95%B0%E6%8D%AE%E8%BF%81%E7%A7%BB%EF%BC%88%E4%BD%BF%E7%94%A8-scan-%E6%A8%A1%E5%BC%8F%EF%BC%89) and [restore mode](https://github.com/tair-opensource/RedisShake/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B%EF%BC%9A%E4%BB%8E-dump.rdb-%E6%81%A2%E5%A4%8D%E6%95%B0%E6%8D%AE).

**Comment by a0a0996** [comment]
Yes, I tried scan mode, but it doesn't support incremental migration/live migration, which can be only supported by sync mode, any ways to support live migration with 3.x for azure clouds?

**Comment by a0a0996** [comment]
One more question: Is there any limit on no of keys which can be migrated or we can migrate unlimited keys via RedisShake?

**Comment by suxb201** [comment]
1. Without the permission to use `Sync/PSync`, it is not possible to support incremental data migration. We recommend that you submit a ticket to Azure and try to obtain the PSync permission.
2. No limit on no of keys.
