### ISSUE TITLE
redis sentinel 集群 sync 同步问题

### ISSUE THREAD

**Issue by jusl-song** [aliyun/redis-shake#610]
**问题描述**

使用sync模式同步数据，目标端 redis   type = "standalone"

启动同步后，目标集群会切主到源集群，两个sentinel集群 变成了1个

这个是我的用法问题吗？

现在我是先不启动目标集群sentinel服务，等数据同步完成后，再启动目标集群的sentinel服务

---

**源端 Redis**
版本：3.0.4 自建  mode: sentinel 

---

**目的端 Redis**
版本：3.0.4 自建 mode: sentinel

**Comment by suxb201** [comment]
对于源端 sentinel 不要挂载到主节点上，要挂到备节点上。 至于“两个sentinel集群 变成了1个”没有听明白。

**Comment by jusl-song** [comment]
同步源端写的是slave节点

问题现象是：
比如源端集群为
10.0.0.1（master）、1.0.0.2、10.0.0.3

目标端集群为
10.0.1.1(master)、10.0.1.2、10.0.1.3

开启sync之后
目标端集群会被加入到源端集群变为  10.0.0.1 的 slave节点

**Comment by jusl-song** [comment]
发现了，两组sentinel的 master name 是一样的
我把新sentinle集群的master name 改成其他的了，当前没有问题，多谢
