### ISSUE TITLE
哨兵之间同步会发生主备倒换

### ISSUE THREAD

**Issue by xingqi8** [aliyun/redis-shake#614]
- [X] 请确保已经看过 wiki：https://github.com/alibaba/RedisShake/wiki
- [X] 请确保已经学习过 Markdown 语法，良好的排版有助于维护人员了解你的问题
- [X] 请在此提供足够的信息供社区维护人员排查问题
- [X] 请在提交 issue 前删除此模板中多余的文字，包括这几句话

**问题描述**

这里描述你的问题。
需求是同城两地的一主两从三哨兵的A地给B地同步数据，sync模式配置了A地三台中的从机为源，B地三台中的主为目标，启动后会发生主备倒换，整个6台机器都会组成哨兵模式。

**Comment by suxb201** [comment]
“启动后会发生主备倒换” 是主库出现故障 failover 了吗？

**Comment by xingqi8** [comment]
主库没有故障failover，我把redis-shake部署到了一台新的机器，算上这台机器总共7台机器，哨兵把redis-shake也会当从节点纳入监控，然后会重新投票选出主机倒换，也就是会导致两个独立的均是一主二从三哨兵组成一个一主六从的整体。

**Comment by suxb201** [comment]
我理解 redis-shake 配置文件中的源端设置的是从节点的话，不应该被哨兵算入吧。

**Comment by xingqi8** [comment]
实测算，redis版本7.0.5，测了两次，两次都算了，并且都发生主备倒换了。就我描述的那种情况。

**Comment by yhxjack** [comment]
我这边也测试了，就算源端设置的是从节点，也会被哨兵算入

**Comment by suxb201** [comment]
@xingqi8 @yhxjack 已经修复这个问题，参考：https://github.com/tair-opensource/RedisShake/issues/656
