### ISSUE TITLE
Is this a big Bug !?

### ISSUE THREAD

**Issue by FrancoZhangVip** [aliyun/redis-shake#617]
![image](https://github.com/tair-opensource/RedisShake/assets/80463983/3e178392-ba26-410e-903d-1f9c1b4c2666)

I got this situation:
if the cmd is: select db and set key value
you read reply from chWaitReply channel
![image](https://github.com/tair-opensource/RedisShake/assets/80463983/7fd3f6a1-81af-48f8-8d79-cdc256aefc62)
but, the first reply is select db cmd; not set key value cmd

so, if there are so many select db, you will not read reply corresponding to the correct write cmd, you read many select db reply !!! 
@suxb201

**Comment by baronwangr** [comment]
why there's so many select db regarding of a normal case?

**Comment by FrancoZhangVip** [comment]
> 

one select db is enough, it will never receive the latest reply, did you get what i mean ?

**Comment by suxb201** [comment]
感谢反馈，已经修复：https://github.com/tair-opensource/RedisShake/pull/619

**Comment by FrancoZhangVip** [comment]
well done
