### ISSUE TITLE
redis源如果是cluster，支持数据在节点之间切换吗？

### ISSUE THREAD

**Issue by zhanghaiyang9999** [aliyun/redis-shake#620]
这里描述你的问题。
咨询一下，这种情况，目前支持吗？谢谢！
源是cluster，如果数据在不同的节点之间发生了切换，比如有一些数据原来属于节点1，后来切换到节点2了，相当于这个数据从节点1中被删除了，节点2中添加了这个数据，这种情况下redisShake能够正常处理吗？谢谢！

**Comment by suxb201** [comment]
怎么切换的，源节点调用命令 del ，目的节点 set 吗？这样的话是可以的。

**Comment by zhanghaiyang9999** [comment]
> 怎么切换的，源节点调用命令 del ，目的节点 set 吗？这样的话是可以的。

https://github.com/redis/redis/issues/10546
像这个issue上面描述的这种情况能支持吗？

**Comment by suxb201** [comment]
1. 如果集群-shake-集群/主从，源端集群发生 slot 迁移，shake 能正常工作
2. 至于原 issue 提到的想区分用户写入命令与 slot 迁移命令，这个利用 shake 也做不到

**Comment by zhanghaiyang9999** [comment]
> 1. 如果集群-shake-集群/主从，源端集群发生 slot 迁移，shake 能正常工作
> 2. 至于原 issue 提到的想区分用户写入命令与 slot 迁移命令，这个利用 shake 也做不到

感谢！！
