### ISSUE TITLE
如何在toml文件中指定database id？

### ISSUE THREAD

**Issue by zjfmail** [aliyun/redis-shake#621]
- [ ] 请确保已经看过 wiki：https://github.com/alibaba/RedisShake/wiki
- [ ] 请确保已经学习过 Markdown 语法，良好的排版有助于维护人员了解你的问题
- [ ] 请在此提供足够的信息供社区维护人员排查问题
- [ ] 请在提交 issue 前删除此模板中多余的文字，包括这几句话

**问题描述**
由于云服务的权限限制，只能使用一个database，如何在toml中指定database id？

这里描述你的问题。

redis-shake 的日志：
```
shake 的日志贴在这里
```

---

**源端 Redis**
版本：版本号，自建还是云厂商？
日志：
```
日志贴在这里
```

---

**目的端 Redis**
版本：版本号，是否是集群？自建还是云厂商？
日志：
```
日志贴在这里
```

**Comment by suxb201** [comment]
在 lua 中指定，参考：https://github.com/tair-opensource/RedisShake/wiki/%E4%BD%BF%E7%94%A8-filters-%E5%81%9A%E6%95%B0%E6%8D%AE%E6%B8%85%E6%B4%97#swap_dblua-%E4%BA%A4%E6%8D%A2-db
