### ISSUE TITLE
有没有可能自动决定是sync模式还是scan模式

### ISSUE THREAD

**Issue by zhanghaiyang9999** [aliyun/redis-shake#627]
有的redis服务器可以用sync模式，有的只能用scan模式，有没有办法能够自动判断出该使用sync模式还是该使用scan模式（比如服务器禁用了sync）？谢谢！

**Comment by suxb201** [comment]
很好区分，自建 Redis 都支持 sync，只有少数云厂商才会不支持。

**Comment by zhanghaiyang9999** [comment]
> 很好区分，自建 Redis 都支持 sync，只有少数云厂商才会不支持。

有没有相关的命令，可以从程序的角度来判断，不是通过人工的方式？

**Comment by suxb201** [comment]
@zhanghaiyang9999 哈哈，你们需求是啥，是多云场景吗？

**Comment by zhanghaiyang9999** [comment]
> @zhanghaiyang9999 哈哈，你们需求是啥，是多云场景吗？
想支持本地的同步，也能支持云端的同步，就可以不用手动去改配置文件了

**Comment by suxb201** [comment]
从 RedisShake 角度是不会做相关检测的。你应该有很多方法可以做到。至于判断是否支持 sync 可以通过判断是否支持 replconf 命令，一般支持 replconf 命令都会支持 sync 模式。

**Comment by zhanghaiyang9999** [comment]
> 从 RedisShake 角度是不会做相关检测的。你应该有很多方法可以做到。至于判断是否支持 sync 可以通过判断是否支持 replconf 命令，一般支持 replconf 命令都会支持 sync 模式。

好的，多谢！

**Comment by feiazifeiazi** [comment]
> > 很好区分，自建 Redis 都支持 sync，只有少数云厂商才会不支持。
> 
> 有没有相关的命令，可以从程序的角度来判断，不是通过人工的方式？

少数云厂商：华为云Redis禁用了SYNC和PSYNC命令。
