### ISSUE TITLE
[CRASH] error=[ERR Bad data format]

### ISSUE THREAD

**Issue by thdwldud** [aliyun/redis-shake#631]
**源端 Redis**
版本：7.0.7 

**目的端 Redis**
版本：6.0.2

panic: redisWriter received error. error=[ERR Bad data format] 

我在github上发现了相同的issue，用相应的方法解决了问题。 (#479)
替换为 `target_redis_proto_max_bulk_len= 0 `。

虽然在其"issue"上也留下了comment，但有一个疑问，所以重新写issue。

将 `target_redis_proto_max_bulk_len` 更改为零，可以知道为什么它运行吗？

我提前为我的中文不太好道歉。

**Comment by suxb201** [comment]
redis-shake 默认使用 `restore` 命令，直接将源端数据发送给目的端。Redis 7 使用了新的编码结构，Redis 6 无法识别对应编码的数据。

将 target_redis_proto_max_bulk_len 更改为零，会迫使 redis-shake 放弃使用 `restore` 命令，转而使用 `set`、`zadd`、`lpush` 等命令，Redis 6 支持这些命令。

**Comment by thdwldud** [comment]
@suxb201 
`target_redis_revis_max_revis_len`
- 0:不要使用 restore 命令（使用 set、zadd、lpush 代替）
- 1 ~ n:对最大为 n 的单个元素使用 restore 命令

设置 `target_redis_report_max_len=0` 来强制数据同步到redis版本6。

如上所述，我理解。 是吗？

**Comment by suxb201** [comment]
正确

**Comment by thdwldud** [comment]
@suxb201 
感谢您快速、亲切的答复。:)
