### ISSUE TITLE
MSET ABC1 value ABC2 value 这种命令，需要在 lua 中额外判断。

### ISSUE THREAD

**Issue by l36t** [aliyun/redis-shake#632]
在看key_prefix.lua 脚本的时候，有一句“注意对于增量的 MSET ABC1 value ABC2 value 这种命令，需要在 lua 中额外判断。”不太理解，请问如果想过滤mset类型的需要做哪些额外判断呢，有没有示例，谢谢

**Comment by suxb201** [comment]
```lua
    if string.sub(keys[1], 0, 3) == "ABC" then  -- 因为类似命令有多个 key，所以这里需要变为循环
    return 1, db_id -- disallow
    end
```
而且 mset k1 v1 k2 v2，假如你想过滤 k1，不想过滤 k2，此时需要自己考虑了，因为 shake 目前只支持全部过滤或者全部不过滤。

**Comment by l36t** [comment]
明白了，感谢

**Comment by dou1984** [comment]
可否将keys中的元素删除，达到过滤的目的呢？

**Comment by suxb201** [comment]
@dou1984 过滤的话直接 return 1 就好了，请问是不满足要求吗？是想保留 abc1 过滤 abc2？

**Comment by suxb201** [comment]
> 可否将keys中的元素删除，达到过滤的目的呢？

目前支持了。
