### ISSUE TITLE
how to detect REAL EOF in function [func (r *AOFReader) Read] ?

### ISSUE THREAD

**Issue by zhanghaiyang9999** [aliyun/redis-shake#633]
If the source redis network is broken, the function [func (r *AOFReader) Read] will never return as the code for err == io.EOF always is true.

How can get to return if the network is broken?

func (r *AOFReader) Read(buf []byte) (n int, err error) {
	n, err = r.file.Read(buf)
	filename := fmt.Sprintf("%s/%d.aof", r.folder, r.offset)
	for err == io.EOF {
		if r.filename != filename {
			r.readNextFile(r.offset)
		}
		time.Sleep(time.Millisecond * 10)
		_, err = r.file.Seek(0, 1)
		if err != nil {
			log.PanicError(err)
		}
		n, err = r.file.Read(buf)z
	}
	if err != nil {
		log.PanicError(err)
	}
	r.offset += int64(n)
	r.pos += int64(n)
	return n, nil
}

**Comment by suxb201** [comment]
没理解你的意思。

**Comment by zhanghaiyang9999** [comment]
> 没理解你的意思。

抱歉，就是说，如果是网络断开了，n, err = r.file.Read(buf)这个函数返回的也是EOF，不能确定是真的EOF还是网络断了的原因，并且会导致一直不能退出循环，即使后来又连上了，就会死循环在那里了，不能退出。

**Comment by suxb201** [comment]
不会有重连的。
