### ISSUE TITLE
序列化的疑问

### ISSUE THREAD

**Issue by wujincheng2333** [aliyun/redis-shake#634]
看了下代码，为啥所有值最终都会序列化成string，像jdk序列化那种，序列化为简单的string，反序列化不会出问题吗

**Comment by suxb201** [comment]
RESP 有长度字段，是二进制安全的

**Comment by wujincheng2333** [comment]
> RESP 有长度字段，是二进制安全的

我看到v2是二进制的，v3是字符串，jdk序列化直接转字符串是乱码的，反序列应该是错误的

**Comment by wujincheng2333** [comment]
> RESP 有长度字段，是二进制安全的

<img width="752" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/39256897/f509b2a0-b213-41c0-992c-0396874f3b0f">

**Comment by suxb201** [comment]
golang 中的 string 是 utf-8 编码的，所以可以认为其就是 byte 数组。
```golang
func main() {
	s := "你好"
	fmt.Printf("[]byte: %v\n", []byte(s))
	println("size", len(s))
}
```

输出
```bash
[]byte: [228 189 160 229 165 189]
size 6
```

**Comment by wujincheng2333** [comment]
> golang 中的 string 是 utf-8 编码的，所以可以认为其就是 byte 数组。
> 
> ```go
> func main() {
> 	s := "你好"
> 	fmt.Printf("[]byte: %v\n", []byte(s))
> 	println("size", len(s))
> }
> ```
> 
> 输出
> 
> ```shell
> []byte: [228 189 160 229 165 189]
> size 6
> ```

好的，谢谢。就是说只影响打印吗，不兼容直接写文本。写文本就变 ？号了，不过数据是文本写文本才有意义。
