### ISSUE TITLE
关于启动后确认是否全部同步状态的问题

### ISSUE THREAD

**Issue by 101536363** [aliyun/redis-shake#642]
- [ x ] 请确保已经看过 wiki：https://github.com/alibaba/RedisShake/wiki
- [ x ] 请确保已经学习过 Markdown 语法，良好的排版有助于维护人员了解你的问题

**问题描述**
您好，目前我这边情况是我已经正常启动了redis-shake(sync)，日志正常输出，我在看wiki的时候看到同步完成的条件是allowOps=[0]，目前线上的服务一直处于有数据是写入的状态，我看到allowOps一直不为0。想咨询一下是不是我只要不停止这个服务， 服务会一直将增量数据写入，首次同步会同步所有数据然后进入增量阶段吗？ 谢谢！
<img width="1365" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/72073965/c3fb3d13-eabe-442f-ba43-9702e03428b1">

**Comment by 101536363** [comment]
然后再追加个问题 在进行另一台服务同步的时候出现一直source db is doing bgsave的状态这个是前期的一个准备状态吗？
<img width="820" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/72073965/7dfb99cf-d18a-4984-aecb-2c894c84a374">

**Comment by suxb201** [comment]
正常状态，应该是源端 db 的内存用量比较高（应该用了 10G 以上吧），所以 bgsave 耗时较久。

**Comment by 101536363** [comment]
嗯 确实是 准！！！ 同步那里是 我想的那样 开启后同步全部数据 只要不关闭会一直同步增量数据吗？

**Comment by suxb201** [comment]
对的，同步完全量会同步增量的

**Comment by 101536363** [comment]
好的 感谢哈！

**Comment by suxb201** [comment]
4.0 现在有一个标志位（consistent） 来辅助判断是否一致，但也是仅供参考，因为数据一直是源源不断过来的，很难有一个准确的一致状态。
