### ISSUE TITLE
metrics_port = 0 仍然会开启端口 

### ISSUE THREAD

**Issue by EvanMatlon** [aliyun/redis-shake#647]
- [x] 请确保已经看过 wiki：https://github.com/alibaba/RedisShake/wiki
- [x] 请确保已经学习过 Markdown 语法，良好的排版有助于维护人员了解你的问题
- [x] 请在此提供足够的信息供社区维护人员排查问题
- [x] 请在提交 issue 前删除此模板中多余的文字，包括这几句话

**问题描述**

   在配置文件中设置metrics_port = 0 不开启metrics后，执行cluster_helper.py后，仍然会在各节点的子配置文件中开启metrics_port，端口从11007开始,因本地未开通此范围端口，会报如下错误

redis-shake 的日志：
```
failed: HTTPConnectionPool(host='localhost', port=11008): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8a8a6bc2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

---

**源端 Redis**
版本：6.2.5
日志：
```

```
---

**目的端 Redis**
版本：6.2.5
日志：
```
日志贴在这里
```

**Comment by ElvisWai** [comment]
#648
