### ISSUE TITLE
如何终止 PSYNC 命令？

### ISSUE THREAD

**Issue by zhanghaiyang9999** [aliyun/redis-shake#650]
当执行PSYNC命令后，如下面代码：
// send psync
	argv = []string{"PSYNC", "?", "-1"}
	if r.elastiCachePSync != "" {
		argv = []string{r.elastiCachePSync, "?", "-1"}
	}
	r.client.Send(argv...)
	log.Infof("send %v", argv)
	// format: \n\n\n$<reply>\r\n
	for true {
......
这个时候redis服务端会生成一个.rdb临时文件，后续如果程序出错了或者直接退出函数，那个临时rdb文件不会被删除，还会一直保留在redis服务器 端。有没有命令来终止此次PSYNC以便redis服务器能够自动删除刚才产生的临时rdb文件，如果不能终止的话，次数多了，就会产生很多垃圾文件占满磁盘空间。

**Comment by suxb201** [comment]
Redis 的问题，和 RedisShake 无关。
