### ISSUE TITLE
scan 复制，进度卡在92.29%

### ISSUE THREAD

**Issue by coderrrr** [aliyun/redis-shake#651]
scan 模式的复制，源库和目标库都是 AWS ElastiCache for Redis，版本 6.0，都是同一内网，都是 standalone 模式，数据大约有 29GB，尝试了几次都停留在 92.29%。
[redis-shake.log](https://github.com/tair-opensource/RedisShake/files/12365043/redis-shake.log)

**Comment by coderrrr** [comment]
[scan.toml.txt](https://github.com/tair-opensource/RedisShake/files/12365111/scan.toml.txt)
toml 文件如下。

**Comment by suxb201** [comment]
target_redis_client_max_querybuf_len 这个参数改到非常大试试

**Comment by coderrrr** [comment]
您好，又尝试了 【target_redis_client_max_querybuf_len】改为 4096_000_000，还是在接近的地方出错，但错误有所不同（write: broken pipe），已和默认值 1024_000_000 做了对比，请看附件，感谢。
![2023-08-18 13 45 43](https://github.com/tair-opensource/RedisShake/assets/3182137/db1dcc49-6757-4fdf-a938-e676448faf88)

**Comment by suxb201** [comment]
符合预期，有某些 key 非常大，没办法直接 restore 到目的端。有两个解决方案选择：
1. 修改目的端 Redis 的 redis_client_mac_querybuf_len 和 redis_proto_max_bulk_len 参数，改到非常大。
2. 改用 sync 模式或者 restore 模式。

**Comment by sitoc** [comment]
![image](https://github.com/tair-opensource/RedisShake/assets/17570029/c4a85882-939e-45d5-a9f5-3d548c1be471)
源端：RedisCluster 4.0，目的端：RedisCluster 4.0，两边都是测试环境，key非常少，但是也报错误，帮忙看看，谢谢

**Comment by suxb201** [comment]
@sitoc 看看 ip 对应的 Redis 的日志

**Comment by suxb201** [comment]
参考文档：https://tair-opensource.github.io/RedisShake/zh/reader/scan_reader.html
