### ISSUE TITLE
AWS ElasticCache不支持psync命令

### ISSUE THREAD

**Issue by ShineBlake1996** [aliyun/redis-shake#653]
AWS ElasticCache的命令受限，不支持psync，有其他办法吗？
reply=[ERR unknown command `PSYNC`, with args beginning with: `?`, `-1`,]  panic: psync error.

https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/RestrictedCommands.html

**Comment by suxb201** [comment]
提工单，要求其开放 psync。

**Comment by huangfxx** [comment]
aws elasticcache提工单让开放psync，他们支持吗？

**Comment by suxb201** [comment]
@huangfxx 支持的
