### ISSUE TITLE
增量同步的原理和主从同步sentinel粘连问题

### ISSUE THREAD

**Issue by yhxjack** [aliyun/redis-shake#656]
- [ ] 请确保已经看过 wiki：https://github.com/alibaba/RedisShake/wiki
- [ ] 请确保已经学习过 Markdown 语法，良好的排版有助于维护人员了解你的问题
- [ ] 请在此提供足够的信息供社区维护人员排查问题
- [ ] 请在提交 issue 前删除此模板中多余的文字，包括这几句话

**问题描述**

这里描述你的问题。
两个问题：
1、增量同步的原理是啥？
2、我们使用3.x以上的版本做生产主从模式的迁移，源集群是idc的，目标集群是容器集群，迁移之前idc和容器集群各自有3个sentinel监听，从idc迁移到容器集群后，redis的sentinel变成了6个，推测是增量同步过程中有什么机制将idc的sentinel信息同步给了容器集群。

---

**源端 Redis**
版本：4.0，自建

---

**目的端 Redis**
版本：4.0，自建(容器集群)

**Comment by suxb201** [comment]
shake 应该连接到 sentinel 的备库，不要连主库。

**Comment by yhxjack** [comment]
> 

你这里sentinel的备库指的是连接源集群的时候吗？因为目标集群肯定是要连接主节点做写入动作

**Comment by suxb201** [comment]
对的

**Comment by yhxjack** [comment]
> 对的
试过了，不行的，目标库里的主从集群的sentinel个数翻倍了，依然携带了idc的sentinel信息，大佬还有其他的解决办法吗

**Comment by suxb201** [comment]
目标库翻倍了？
源端 A->B，目的端 C->D，你是 B->shake->C 对吗？然后 C 的 sentinel 个数翻倍了吗？

**Comment by yhxjack** [comment]
> 目标库翻倍了？ 源端 A->B，目的端 C->D，你是 B->shake->C 对吗？然后 C 的 sentinel 个数翻倍了吗？

对的，去c的sentinel上查c的sentinel，数量是6个，是其他集群的2倍。
迁移之前：
![image](https://github.com/tair-opensource/RedisShake/assets/28732417/5c9a652d-1a47-4d6f-8281-3e358340f874)
迁移之后：
<img width="746" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/28732417/4825ece4-84e0-4b0c-b0ed-f9ccb87b1a92">

**Comment by shamil** [comment]
We also experience same problem

**Comment by suxb201** [comment]
@yhxjack @shamil Redis Sentinel 使用 Pub/Sub 来记录一些信息，RedisShake 将这些信息传递给过去了，从而导致出现上述问题。并不影响数据一致性。在 RedisShake 传输完成后调用一下 sentinel reset * 可以恢复。
后面 RedisShake 会修复一下这个问题，过滤掉 __sentinel__:hello 命令。

**Comment by suxb201** [comment]
修复了此问题，可以再试试。
