### ISSUE TITLE
 rdb_restore_command_behavior. failed

### ISSUE THREAD

**Issue by ykwang20200** [aliyun/redis-shake#663]
rdb_restore_command_behavior 我设置成skip或者ignore， redis 依然会对重复的key进行覆盖，

**Comment by ykwang20200** [comment]
type = "sync"

[source]
version = 5.0 # redis version, such as 2.8, 4.0, 5.0, 6.0, 6.2, 7.0, ...
address = "SOURCE_IP:16379"
username = "" # keep empty if not using ACL
password = "passwd!" # keep empty if no authentication is required
tls = false
elasticache_psync = "" # using when source is ElastiCache. ref: https://github.com/alibaba/RedisShake/issues/373

[target]
type = "standalone" # "standalone" or "cluster"
version = 5.0 # redis version, such as 2.8, 4.0, 5.0, 6.0, 6.2, 7.0, ...
# When the target is a cluster, write the address of one of the nodes.
# redis-shake will obtain other nodes through the `cluster nodes` command.
address = "TARGET_IP:16379"
username = "" # keep empty if not using ACL
password = "passwd!" # keep empty if no authentication is required
tls = false

[advanced]
dir = "data"

# runtime.GOMAXPROCS, 0 means use runtime.NumCPU() cpu cores
ncpu = 4

# pprof port, 0 means disable
pprof_port = 0

# metric port, 0 means disable
metrics_port = 0

# log
log_file = "./redis-shake.log"
log_level = "info" # debug, info or warn
log_interval = 5 # in seconds

# redis-shake gets key and value from rdb file, and uses RESTORE command to
# create the key in target redis. Redis RESTORE will return a "Target key name
# is busy" error when key already exists. You can use this configuration item
# to change the default behavior of restore:
# panic:   redis-shake will stop when meet "Target key name is busy" error.
# rewrite: redis-shake will replace the key with new value.
# ignore:  redis-shake will skip restore the key when meet "Target key name is busy" error.
rdb_restore_command_behavior = "ignore" # panic, rewrite or skip

# pipeline
pipeline_count_limit = 1024

# Client query buffers accumulate new commands. They are limited to a fixed
# amount by default. This amount is normally 1gb.
target_redis_client_max_querybuf_len = 1024_000_000

# In the Redis protocol, bulk requests, that are, elements representing single
# strings, are normally limited to 512 mb.
target_redis_proto_max_bulk_len = 512_000_000

这是我的配置文件

**Comment by suxb201** [comment]
rdb_restore_command_behavior 只影响全量同步阶段，增量同步阶段依旧能修改目的端。

**Comment by ykwang20200** [comment]
额。。。这个就没办法避免呗，或者配置成以最新时间戳为准的也行，

**Comment by suxb201** [comment]
自己写脚本把 key 过滤掉
