### ISSUE TITLE
怎么配置源端和目标端的tls证书

### ISSUE THREAD

**Issue by wangshuang0220** [aliyun/redis-shake#666]
- [x] 请确保已经看过 wiki：https://RedisShake/wiki
- [x] 请确保已经学习过 Markdown 语法，良好的排版有助于维护人员了解你的问题
- [x] 请在此提供足够的信息供社区维护人员排查问题
- [x] 请在提交 issue 前删除此模板中多余的文字，包括这几句话

**问题描述**

这里描述你的问题。
redis6.0+开启tls之后，怎么在redis-shake中配置源端和目的端的tls相关的证书。

redis-shake 的日志：
```
shake 的日志贴在这里
```

---

**源端 Redis**
版本：redis6.0+
日志：
```
日志贴在这里
```

---

**目的端 Redis**
版本：redis6.0+
日志：
```
日志贴在这里
```

**Comment by suxb201** [comment]
不需要配置证书，shake 不校验服务端证书。
