### ISSUE TITLE
如何只做全量迁移，不做增量迁移

### ISSUE THREAD

**Issue by wangshuang0220** [aliyun/redis-shake#671]
### 问题描述（Issue Description）

如何只做全量迁移，不做增量迁移

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：4.0
- Redis 源端版本（Redis Source Version）：redis6.0+
- Redis 目的端版本（Redis Destination Version）：redis6.0+
- Redis 部署方式（standalone/cluster/sentinel）：standalone
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：

**Comment by suxb201** [comment]
发现到增量迁移的时候停止就好。

**Comment by wangshuang0220** [comment]
> 

嗯，好的。就是不能直接全量迁移完自动退出是吧，。只能人工介入了

**Comment by suxb201** [comment]
@wangshuang0220 目前不支持的

**Comment by suxb201** [comment]
已经支持了。
```
sync_rdb = true # set to false if you don't want to sync rdb
sync_aof = true # set to false if you don't want to sync aof
```
