### ISSUE TITLE
能否支持布隆过滤器

### ISSUE THREAD

**Issue by mohism1530978667** [aliyun/redis-shake#673]
我有一个使用了布隆过滤器的redis集群，想把数据导入一个新建的redis集群（也使用了布隆过滤器）里。

使用了Sync Reader和rdb_reader的方式都报错：unsupported module type: MBbloom

我使用的redis-shake版本是v4.0

**Comment by suxb201** [comment]
暂无计划，欢迎提交 PR。

**Comment by suxb201** [comment]
添加 Module 的教程：https://tair-opensource.github.io/RedisShake/zh/others/modules.html
