### ISSUE TITLE
本地自建redis 同步到阿里云redis报错

### ISSUE THREAD

**Issue by huwenkai26** [aliyun/redis-shake#675]
### 问题描述  receive reply failed. cmd=[SET mykj:wallpaper:text_to_image_lock:5277929 1694425862363 PXAT 1694425922363], error=[ERR syntax error]

、
### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：最新release版本
- Redis 源端版本（Redis Source Version）：7.0版本
- Redis 目的端版本（Redis Destination Version）：6.0版本
- Redis 部署方式（standalone/cluster/sentinel）：standalone
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：Redis 目的是

**Comment by suxb201** [comment]
不要降级，命令不兼容。
