### ISSUE TITLE
redis-shake 4.0支持部分key 迁移吗？

### ISSUE THREAD

**Issue by Dayro-9** [aliyun/redis-shake#676]
### 问题描述（Issue Description）

现有A、B两个阿里云4.0集群版实例，想从A实例将某个前缀的key迁移到B实例，可以使用redis-shake 4.0 function功能实现吗？

**Comment by suxb201** [comment]
可以实现：https://tair-opensource.github.io/RedisShake/zh/function/introduction.html

**Comment by Dayro-9** [comment]
> 可以实现：https://tair-opensource.github.io/RedisShake/zh/function/introduction.html
function = """
shake.log(DB)
shake.call(keys,"prefile*")
"""

**Comment by Dayro-9** [comment]
> 可以实现：https://tair-opensource.github.io/RedisShake/zh/function/introduction.html

应该怎么编写这个lua脚本？

**Comment by Dayro-9** [comment]
> 可以实现：https://tair-opensource.github.io/RedisShake/zh/function/introduction.html
在shake.toml这样写function吗?
![image](https://github.com/tair-opensource/RedisShake/assets/59091691/7231e23a-5e20-4077-95c6-c5f899f3dd4f)
可以给一个示例不？

**Comment by sitoc** [comment]
我也正在使用redis-shake4.x版本，但是官网的文档不太清晰，没看明白怎么写function函数，我也想过滤部分前缀的key，麻烦回复一下

**Comment by sitoc** [comment]
> > 可以实现：https://tair-opensource.github.io/RedisShake/zh/function/introduction.html
> > 在shake.toml这样写function吗?
> > ![image](https://user-images.githubusercontent.com/59091691/267596660-7231e23a-5e20-4077-95c6-c5f899f3dd4f.png)
> > 可以给一个示例不？

你写出来了吗？

**Comment by Dayro-9** [comment]
> > > 可以实现：https://tair-opensource.github.io/RedisShake/zh/function/introduction.html
> > > 在shake.toml这样写function吗?
> > > ![image](https://user-images.githubusercontent.com/59091691/267596660-7231e23a-5e20-4077-95c6-c5f899f3dd4f.png)
> > > 可以给一个示例不？
> 
> 你写出来了吗？

没有，这种写法不可以，我也没有看懂这个https://tair-opensource.github.io/RedisShake/zh/function/introduction.html

**Comment by sitoc** [comment]
我是这么写的，增量阶段的同步可以过滤 只同步abc前缀的key，
`function = """
shake.log(KEYS)
if string.find(KEYS[1],'abc') == 1
then
   shake.call(DB, ARGV)
   for k,v in ipairs(ARGV)
   do
      print(k,v)
   end
end
"""
`

**Comment by sitoc** [comment]
我是这么写的，过滤只同步abc前缀的key
function = """
shake.log(KEYS)
if string.find(KEYS[1],'abc') == 1
then
   shake.call(DB, ARGV)
   for k,v in ipairs(ARGV)
   do
      print(k,v)
   end
end
"""
![image](https://github.com/tair-opensource/RedisShake/assets/17570029/969453e1-16bf-484f-88b0-8f252fc5dbbc)

**Comment by Dayro-9** [comment]
> 我是这么写的，过滤只同步abc前缀的key function = """ shake.log(KEYS) if string.find(KEYS[1],'abc') == 1 then shake.call(DB, ARGV) for k,v in ipairs(ARGV) do print(k,v) end end """ ![image](https://user-images.githubusercontent.com/17570029/267672572-969453e1-16bf-484f-88b0-8f252fc5dbbc.png)

感谢大佬，用这个迁移abc浅醉的key成功了

**Comment by sitoc** [comment]
但是KEYS官网文档说是 table类型，即{‘abc_1’,'kk_1','abc_2'}这样的，而我的判断只是通过KEYS[1]，即只判断了第一个KEY的前缀，如果多个KEY怎么判断？

**Comment by suxb201** [comment]
@sitoc @Dayro-9 多个 key 需要写循环，自己拆分。
比如 mset k1 v1 k2 v2，这种就需要自己拆分成 set k1 v1，set k2 v2。
如果 k1 满足规则就 shake call set k1 v1
如果 k2 满足规则就 shake call set k2 v2

还是根据业务来，如果业务没有 mset 等命令就不用这么麻烦了。而且 mset 等命令只会出现在增量阶段，如果不想要增量也不用这么麻烦。

**Comment by sitoc** [comment]
那就是我还需要判断命令是否为mset，如果为mset的话，我就转为多个set来进行，是吗？
我看官方的源码里有这样写的，你帮看看是否可行：
 opts["function"] = """
        shake.log(KEYS)
        if CMD == "MSET"
        then
            for i = 2, #ARGV, 2 -- MSET k1 v1 k2 v2 k3 v3 ...
            do
                shake.call(1, {"SET", ARGV[i], ARGV[i+1]}) -- move to db 1
            end
        end
    """

**Comment by Dayro-9** [comment]
> 但是KEYS官网文档说是 table类型，即{‘abc_1’,'kk_1','abc_2'}这样的，而我

> 我是这么写的，过滤只同步abc前缀的key function = """ shake.log(KEYS) if string.find(KEYS[1],'abc') == 1 then shake.call(DB, ARGV) for k,v in ipairs(ARGV) do print(k,v) end end """ ![image](https://user-images.githubusercontent.com/17570029/267672572-969453e1-16bf-484f-88b0-8f252fc5dbbc.png)

我后面再测了一下这个function，一直在报错，重新写了一下，也可以迁移某个前缀的key
`function = """
shake.log(KEYS)
for k,v in ipairs(KEYS) do
    if string.find(v,"HOME:CART:USER_SKU:*") == 1
    then
        shake.call(DB, ARGV)
        print(k,v)
    end
end
"""`

**Comment by Dayro-9** [comment]
> 但是KEYS官网文档说是 table类型，即{‘abc_1’,'kk_1','abc_2'}这样的，而我的判断只是通过KEYS[1]，即只判断了第一个KEY的前缀，如果多个KEY怎么判断？

后面再测试了一下，一直在报错，改写了一下这个function，可以迁移abc前缀的key
function = """ shake.log(KEYS) for k,v in ipairs(KEYS) do if string.find(v,"abc*") == 1 then shake.call(DB, ARGV) print(k,v) end end """

**Comment by TT-EL** [comment]
我也正在解决这个问题，感谢大佬提供的案例和思路 @Dayro-9 ☕☕☕

**Comment by suxb201** [comment]
@Dayro-9 @sitoc @TT-EL 哈喽，我写了几个场景的实现，欢迎参考下：[过滤 Key
](https://tair-opensource.github.io/RedisShake/zh/function/best_practices.html#%E4%BF%AE%E6%94%B9-key-%E7%9A%84%E5%89%8D%E7%BC%80)

我猜测误解最多的地方是这里：
> 因为有些命令中含有多个 key，比如 mset 等命令。所以，KEYS、KEY_INDEXES、SLOTS 这三个变量都是数组类型。如果确认命令只有一个 key，可以直接使用 KEYS[1]、KEY_INDEXES[1]、SLOTS[1]。

**Comment by sitoc** [comment]
我又基于场景重新写了一遍Lua代码，如下，主要分两种情况，白名单和黑名单过滤

![Lua白名单key过滤](https://github.com/tair-opensource/RedisShake/assets/17570029/9ebbfc18-93cc-4e78-a48e-dd08b393cdca)
对应代码：
---白名单过滤key的前缀字符MSETNX
function = """
    local prefix_arr = {"ab","ef"}
    shake.log(KEYS)
    if CMD == "MSET" or CMD == "MSETNX"
    then
        if string.sub(CMD, -2) == "NX"
        then
            CMD_SUB = "SETNX"
        else
            CMD_SUB = "SET"
        end
        shake.log(ARGV)
        for i = 2, #ARGV, 2
        do
            for k, prefix in ipairs(prefix_arr) do
                if string.match(ARGV[i], "^"..prefix)
                then
                    shake.log(ARGV[i])
                    shake.call(0, {CMD_SUB, ARGV[i], ARGV[i+1]}) 
                end
            end
        end
    else
        for i, prefix in ipairs(prefix_arr) do
            if string.match(KEYS[1], "^"..prefix)
            then
                shake.call(DB, ARGV)
            end
        end
    end
"""

黑名单key过滤：
![Lua黑名单key过滤](https://github.com/tair-opensource/RedisShake/assets/17570029/49d4b468-ff6d-48df-8ac2-a33201488b67)

---黑名单key过滤前缀字符
function = """
    local prefix_arr = {"ab","ef"}
    local prefix_len = #prefix_arr
    shake.log(KEYS)
    if CMD == "MSET" or CMD == "MSETNX"
    then
        if string.sub(CMD, -2) == "NX"
        then
            CMD_SUB = "SETNX"
        else
            CMD_SUB = "SET"
        end
        shake.log(ARGV)
        for i = 2, #ARGV, 2
        do
            for k, prefix in ipairs(prefix_arr) do
                if string.match(ARGV[i], "^"..prefix)
                then
                    break
                else
                    if k == prefix_len
                    then
                        shake.log(ARGV[i])
                        shake.call(0, {CMD_SUB, ARGV[i], ARGV[i+1]}) 
                    end
                end
            end
        end
    else
        for i, prefix in ipairs(prefix_arr) do
            if string.match(KEYS[1], "^"..prefix)
            then
                return
            end
        end
        shake.call(DB, ARGV)
    end
"""
