### ISSUE TITLE
实时同步异常

### ISSUE THREAD

**Issue by PeikunChen** [aliyun/redis-shake#677]
### 问题描述（Issue Description）

redis 4.0.1集群使用sync增量同步模式，大概10来个小时，出现日志打印diff不断增大，实际数据已经不再实时同步。任务还在正常打印日志，但是实际实时同步已经不正常了。

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：3.1.10
- Redis 源端版本（Redis Source Version）：4.0.1 
- Redis 目的端版本（Redis Destination Version）：4.0.1
- Redis 部署方式（standalone/cluster/sentinel）：3主3从集群
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：否

### 日志信息（Logs）

{"level":"info","time":"2023-08-29T10:41:01+08:00","message":"AOFWriter close file. filename=[1213143674232.aof], filesize=[1073742512]"}
{"level":"info","time":"2023-08-29T10:41:01+08:00","message":"AOFWriter open file. filename=[1214217416744.aof]"}
{"level":"info","time":"2023-08-29T10:41:04+08:00","message":"syncing aof. allowOps=[0.00], disallowOps=[0.00], entryId=[19469065], InQueueEntriesCount=[2], unansweredBytesCount=[68001]bytes, diff=[2640379352], aofReceivedOffset=[1214217699853], aofAppliedOffset=[1211577320501]"}
{"level":"info","time":"2023-08-29T10:41:09+08:00","message":"syncing aof. allowOps=[0.00], disallowOps=[0.00], entryId=[19469065], InQueueEntriesCount=[2], unansweredBytesCount=[68001]bytes, diff=[2640683123], aofReceivedOffset=[1214218003624], aofAppliedOffset=[1211577320501]"}
{"level":"info","time":"2023-08-29T10:41:14+08:00","message":"syncing aof. allowOps=[0.00], disallowOps=[0.00], entryId=[19469065], InQueueEntriesCount=[2], unansweredBytesCount=[68001]bytes, diff=[2640958712], aofReceivedOffset=[1214218279213], aofAppliedOffset=[1211577320501]"}

**Comment by suxb201** [comment]
3.x 版本的问题不再细究了，尝试下 4.x 有问题我再看下。
