### ISSUE TITLE
read: connection reset by peer

### ISSUE THREAD

**Issue by hengyumo** [aliyun/redis-shake#680]
### 问题描述（Issue Description）
 
redis-shake 突然中断，报错是 `read: connection reset by peer`，可以确定的是，远端没有设置最大超时时间，也没有达到最大连接数量。

The redis-shake suddenly breaks with the error 'read: connection reset by peer'. I can confirm that the maximum timeout time is not set on the remote end and the maximum number of connections is not reached.

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：v3.1.11
- Redis 源端版本（Redis Source Version）：6.2
- Redis 目的端版本（Redis Destination Version）：6.2
- Redis 部署方式（standalone/cluster/sentinel）：cluster
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：否 no

### 日志信息（Logs）

{"level":"info","time":"2023-09-16T05:29:00+08:00","message":"syncing aof. allowOps=[0.00], disallowOps=[0.00], entryId=[55619062], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[234292], aofReceivedOffset=[30257040269], aofAppliedOffset=[30256805977]"}
{"level":"info","time":"2023-09-16T05:29:04+08:00","message":"goroutine 21 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0x7b2790, 0x45}, {0xc0000c5f78, 0x4, 0x4})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc00030a300)]<-github.com/alibaba/RedisShake/internal/writer/redis.go:80 +0x369  [created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter]<-github.com/alibaba/RedisShake/internal/writer/redis.go:36 +0x19c  ["}
{"level":"panic","time":"2023-09-16T05:29:04+08:00","message":"redisWriter received error. error=[read tcp xx.xx.xx.xx:53550->xx.xx.xx:6379: read: connection reset by peer], argv=[MULTI], slots=[], reply=[<nil>]"}

**Comment by hengyumo** [comment]
https://github.com/tair-opensource/RedisShake/issues/360

I found the issue, but I'm not sure if v3 still has the `keep_alive = 1` parameter

**Comment by suxb201** [comment]
一直在使用 ping 命令保活，所以没有 keep_alive 的问题。你观察下 qps 偶尔会有点的。

**Comment by hengyumo** [comment]
那请教下，会是什么原因导致远端断开连接呢

**Comment by suxb201** [comment]
远端有断开日志吗

**Comment by hengyumo** [comment]
运维没有看到远端日志，暂时还不确定是什么原因。
