### ISSUE TITLE
target为redis cluster时节点解析失败

### ISSUE THREAD

**Issue by jijijijijichild** [aliyun/redis-shake#681]
对于没有持有slots的master节点，这里会panic
`{"level":"panic","time":"2023-09-18T15:50:59+08:00","message":"invalid cluster nodes line: 12ec4d92275eda9a60649622b3c5a722f78922a8 127.0.0.1:7040@17040 myself,master - 0 1695023455000 1 connected"}`

https://github.com/tair-opensource/RedisShake/blob/6cfb386eca76cfbd8ba857f296c5276259b5b589/internal/utils/cluster_nodes.go#L23

**Comment by suxb201** [comment]
感谢反馈，此前没有考虑这个问题，请问是否愿意帮忙修下。

**Comment by suxb201** [comment]
修了，可以再试试。
