### ISSUE TITLE
v4 版本在同步的时候报warning

### ISSUE THREAD

**Issue by ntuwang** [aliyun/redis-shake#682]
### 问题描述（Issue Description）

v4 版本在同步的时候报warning

### 环境信息（Environment）
 WRN [writer_10.199.132.64_6379] receive nil reply. cmd=[EVAL if (redis.call('exists', KEYS[1]) == 0) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis....]
- RedisShake 版本 4.0.0
- Redis 源端版本 4.0.12
- Redis 目的端版本4.0.12
- Redis 部署方式（standalone/cluster/sentinel）：cluster

### 日志信息（Logs）
![image](https://github.com/tair-opensource/RedisShake/assets/11935122/f43c4b49-f1aa-4360-af82-2ae564868527)

请问下 这段lua脚本具体功能是啥？ 此warn有没有实质影响？

**Comment by suxb201** [comment]
无影响。
