### ISSUE TITLE
Redis-shake4.0没有写入Target集群就结束了

### ISSUE THREAD

**Issue by AtomTu** [aliyun/redis-shake#689]
问题描述：只运行了，把rdb拉取到本地，日志就提示all done,没有把数据写目的集群，什么问题？

toml文件如下：

```function = ""

[sync_reader]
cluster = true            # set to true if source is a redis cluster
address = "100.30.6.160:6379" # when cluster is true, set address to one of the cluster node
username = ""              # keep empty if not using ACL
password = ""              # keep empty if no authentication is required
tls = false
sync_rdb = true # set to false if you don't want to sync rdb
sync_aof = true # set to false if you don't want to sync aof

[redis_writer]
cluster = true            # set to true if target is a redis cluster
address = "100.30.12.195:6379" # when cluster is true, set address to one of the cluster node
username = ""              # keep empty if not using ACL
password = ""              # keep empty if no authentication is required
tls = false

[advanced]
dir = "data"
ncpu = 0        # runtime.GOMAXPROCS, 0 means use runtime.NumCPU() cpu cores
#pprof_port = 0  # pprof port, 0 means disable
#status_port = 0 # status port, 0 means disable

# log
log_file = "shake.log"
log_level = "debug"     # debug, info or warn
log_interval = 5       # in seconds

rdb_restore_command_behavior = "rewrite" # panic, rewrite or skip

pipeline_count_limit = 1024

target_redis_client_max_querybuf_len = 4096_000_000

target_redis_proto_max_bulk_len = 4096_000_000`
```
日志如下：
```
{"level":"info","time":"2023-10-10T15:10:11+08:00","message":"start syncing..."}
{"level":"debug","time":"2023-10-10T15:10:11+08:00","message":"[reader_100.30.6.163_6379] source db is doing bgsave."}
{"level":"debug","time":"2023-10-10T15:10:11+08:00","message":"[reader_100.30.6.164_6379] source db is doing bgsave."}
{"level":"debug","time":"2023-10-10T15:10:11+08:00","message":"[reader_100.30.6.160_6379] source db is doing bgsave."}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.163_6379] source db bgsave finished. timeUsed=[2.13]s"}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.163_6379] rdb file size: [35 MiB]"}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.163_6379] start receiving RDB. path=[/data/redis-shake/data/reader_100.30.6.163_6379/dump.rdb]"}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.163_6379] save RDB finished. timeUsed=[0.05]s"}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.163_6379] start receiving aof data, and save to file"}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.163_6379] open file for write. filename=[/data/redis-shake/data/reader_100.30.6.163_6379/0.aof]"}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.160_6379] source db bgsave finished. timeUsed=[2.21]s"}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.160_6379] rdb file size: [35 MiB]"}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.160_6379] start receiving RDB. path=[/data/redis-shake/data/reader_100.30.6.160_6379/dump.rdb]"}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.160_6379] save RDB finished. timeUsed=[0.05]s"}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.160_6379] start receiving aof data, and save to file"}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.160_6379] open file for write. filename=[/data/redis-shake/data/reader_100.30.6.160_6379/0.aof]"}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.164_6379] source db bgsave finished. timeUsed=[2.30]s"}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.164_6379] rdb file size: [35 MiB]"}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.164_6379] start receiving RDB. path=[/data/redis-shake/data/reader_100.30.6.164_6379/dump.rdb]"}
{"level":"debug","time":"2023-10-10T15:10:13+08:00","message":"[reader_100.30.6.164_6379] save RDB finished. timeUsed=[0.06]s"}
{"level":"info","time":"2023-10-10T15:10:13+08:00","message":"all done"}
```

**Comment by suxb201** [comment]
没有复现，用的 shake 版本是哪个？终端有报错吗？

**Comment by AtomTu** [comment]
4.0 就是最新版
shake日志没有错误

**Comment by AtomTu** [comment]
目标集群redis日志：
26411:M 09 Oct 2023 16:35:54.914 * Replica 10.3.10.194:<unknown-replica-port> asks for synchronization
26411:M 09 Oct 2023 16:35:57.329 * Synchronization with replica 10.3.10.194:<unknown-replica-port> succeeded
26411:M 09 Oct 2023 16:35:57.346 # Connection with replica 10.3.10.194:<unknown-replica-port> lost.
26411:M 09 Oct 2023 16:35:54.914 * Full resync requested by replica 10.3.10.194:<unknown-replica-port>
26411:M 09 Oct 2023 16:35:14.492 * Synchronization with replica 10.3.10.194:<unknown-replica-port> succeeded
26411:M 09 Oct 2023 16:35:15.691 # Connection with replica 10.3.10.194:<unknown-replica-port> lost.
26411:M 09 Oct 2023 16:35:12.132 * Full resync requested by replica 10.3.10.194:<unknown-replica-port>
26411:M 09 Oct 2023 16:35:12.132 * Replica 10.3.10.194:<unknown-replica-port> asks for synchronization

**Comment by AtomTu** [comment]
<img width="474" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/147486646/504fb5e3-4ff8-45ed-b316-9e1e63ad327e">

**Comment by suxb201** [comment]
@AtomTu 看 Redis 日志是没有问题的，日志表示有 RedisShake 连接来，过了一段时间断开了。
对于 issue 的问题：
1. 你可以稳定复现吗？
2. 确认你提供的配置文件是你正在使用的，尤其是这两项：sync_rdb、sync_aof
3. Redis 的版本是什么？
4. 确认版本是 redis-shake-v4.0.1 对吧，不是 4.0.0

**Comment by AtomTu** [comment]
1、每次必现
2、redis版本5.0.7
3、确认版本是 redis-shake-v4.0.1 

4、配置文件截图如下：
<img width="804" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/147486646/9d0f6f30-2623-4c83-afc5-40e5f5b9edc1">
<img width="792" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/147486646/cd9a4c86-6636-40b3-8c76-dd0a6ef53505">

**Comment by suxb201** [comment]
@AtomTu 试试新包，4.0.1 的包打的好像有问题：https://github.com/tair-opensource/RedisShake/releases/tag/v4.0.2

**Comment by AtomTu** [comment]
issue解决了，请问下最大支持多少个redi实例的集群迁移？

**Comment by suxb201** [comment]
@AtomTu 没有测过，实践过几十个分片的集群没核心啥问题，已知问题：
1. 还是一个线程发会慢一些
2. 长时间运行后 diff 的统计会出错

**Comment by AtomTu** [comment]
100个分片，1个分片10g,有什么建议吗

**Comment by suxb201** [comment]
@AtomTu 感觉问题不大，你可以先试试，反正不会有什么很坏的副作用。

**Comment by AtomTu** [comment]
rdb的时候是所有redis实例同时做，还是什么并发策略

**Comment by suxb201** [comment]
同时做

**Comment by AtomTu** [comment]
ERR redisClusterWriter: slot 8543 already occupied.   遇到这个错误了，该咋解决啊

**Comment by lbgATts** [comment]
@suxb201 现在这个redis-shake 能不能 做合并操作，比如 从 A实例的 (0~15) 这16个db，合并到 B实例的 db0？

**Comment by suxb201** [comment]
@lbgATts 可以的，使用这个能力：https://tair-opensource.github.io/RedisShake/zh/filter/function.html
重写 db 这个参数

**Comment by lbgATts** [comment]
> [@lbgATts](https://github.com/lbgATts) 可以的，使用这个能力：https://tair-opensource.github.io/RedisShake/zh/filter/function.html 重写 db 这个参数

看了下 短时间内 我怕是搞不定了，我这个需求是因为你这个工具没办法 从 A实例的 (0~15) 这16个db 迁移到集群里(集群默认是0)，会报错 说 不能执行 SELECT 操作(类似这种)，所以我想到曲线救过，先合并到中间实例，然后从中间实例的db0 迁移到集群的db0，，，，所以说短时间内，大佬能不能帮个忙看看 有没啥好的快速的办法

**Comment by lbgATts** [comment]
@suxb201  我用了下filter和function 功能，基本是达到了需求，但是看起来数量对不上

<img width="1618" height="1374" alt="Image" src="https://github.com/user-attachments/assets/baa4f65f-1697-4ddc-a69a-054cc2d0a927" />

看起来也没啥工具可以比对

**Comment by suxb201** [comment]
@lbgATts 就差 10 个，还好，是不是有重名 key 或者过期 key 之类的

**Comment by lbgATts** [comment]
> [@lbgATts](https://github.com/lbgATts) 就差 10 个，还好，是不是有重名 key 或者过期 key 之类的

我仔细看了下 不太对，源头的 过期的数据  为什么在新库不存在 老库还存在呢，这显然不合理

第二 这些差值 有什么工具能diff不？ 暂时搞不清楚 这diff是哪些，为什么会不一样，这些丢失的key是不是重要的缓存 不能丢失

**Comment by suxb201** [comment]
@lbgATts 
1. 源头过期不一定及时
2. 一共 3000 个 key，写个脚本对源目都 scan 一遍来对比呗
