### ISSUE TITLE
如何只扫描指定DB库

### ISSUE THREAD

**Issue by ywxc1997** [aliyun/redis-shake#695]
使用Scan方式从哨兵迁移至集群，由于需要分批迁移，每次只需要某个DB下的数据。
使用function可以实现将DB9的数据迁移，但过程会扫描所有的DB，迁移时间太长。
是否可以指定扫描的DB库，跳过全库扫描？

**Comment by suxb201** [comment]
合理需求，确实会比较慢。
没时间做，你可以自己改下代码，很好改的，将这里写成你想同步的 db 就行：
https://github.com/tair-opensource/RedisShake/blob/8d239aeebcbd478d6671f9275b9963d6f1b29496/internal/reader/scan_standalone_reader.go#L55

如果可以的话也欢迎添加配置文件与文档说明，提交个 PR。

**Comment by ywxc1997** [comment]
> 合理需求，确实会比较慢。 没时间做，你可以自己改下代码，很好改的，将这里写成你想同步的 db 就行：
> 
> https://github.com/tair-opensource/RedisShake/blob/8d239aeebcbd478d6671f9275b9963d6f1b29496/internal/reader/scan_standalone_reader.go#L55
> 
> 如果可以的话也欢迎添加配置文件与文档说明，提交个 PR。

好的，我会尝试去提交一个PR
