### ISSUE TITLE
能否做高版redis6本向低版本redis5迁移

### ISSUE THREAD

**Issue by wangshuang0220** [aliyun/redis-shake#699]
### 问题描述（Issue Description）
能否使用redis-shake 做redis高版本到低版本的迁移，比如redis6迁移到redis5，或者redis7迁移到redis6
请在这里简要描述你遇到的问题。

Please provide a brief description of the issue you encountered.

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：v4.0.2
- Redis 源端版本（Redis Source Version）：v6.0
- Redis 目的端版本（Redis Destination Version）： v5.0
- Redis 部署方式（standalone/cluster/sentinel）： standlone
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：no

### 日志信息（Logs）

如果有错误日志或其他相关日志，请在这里提供。

If there are any error logs or other relevant logs, please provide them here.

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

Please provide any additional information, such as configuration files, error messages, or screenshots.

**Comment by suxb201** [comment]
理论上可以实现，需要做很多工作。
1. 配置 target_redis_proto_max_bulk_len 为 0，强制将 restore 命令转化为普通 redis 命令
2. 自己排查没有不兼容的命令调用，比如调用 xadd 命令，Redis 4.0 肯定是不支持的。如果无法避免不兼容的命令调用，可以使用 function 过滤掉。
