### ISSUE TITLE
当目的端为集群时，应保证源端发过来的命令满足 Key 的哈希值属于同一个 slot。

### ISSUE THREAD

**Issue by wangshuang0220** [aliyun/redis-shake#701]
### 问题描述（Issue Description）
目标是集群，源端是单机版，存在这个问题吗？redis-shake应该会根据key算出slot，再根据slot所在的节点去写入数据，或者redis-shake会处理服务端的moved操作吗？然后路由到slot所在的节点去写数据？
https://tair-opensource.github.io/RedisShake/zh/writer/redis_writer.html
请在这里简要描述你遇到的问题。

Please provide a brief description of the issue you encountered.

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：v4.0.2
- Redis 源端版本（Redis Source Version）：v6.0 standalone
- Redis 目的端版本（Redis Destination Version）：v6.0 cluster
- Redis 部署方式（standalone/cluster/sentinel）：
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：

### 日志信息（Logs）

如果有错误日志或其他相关日志，请在这里提供。

If there are any error logs or other relevant logs, please provide them here.

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

Please provide any additional information, such as configuration files, error messages, or screenshots.

**Comment by suxb201** [comment]
会根据key算出slot，再根据slot所在的节点去写入数据
