### ISSUE TITLE
集群向单机版迁移数据时是否只能迁移到单机版的db0，可否指定db进行迁移

### ISSUE THREAD

**Issue by wangshuang0220** [aliyun/redis-shake#702]
### 问题描述（Issue Description）
集群向单机版迁移数据时是否只能迁移到db0，可否指定db迁移. 如果不能的话就需要迁移之后根据需要用redis的SWAPDB 命令实现了
请在这里简要描述你遇到的问题。

Please provide a brief description of the issue you encountered.

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：v4.0.2
- Redis 源端版本（Redis Source Version）：v6.0
- Redis 目的端版本（Redis Destination Version）：v6.0
- Redis 部署方式（standalone/cluster/sentinel）：
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：

### 日志信息（Logs）

如果有错误日志或其他相关日志，请在这里提供。

If there are any error logs or other relevant logs, please provide them here.

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

Please provide any additional information, such as configuration files, error messages, or screenshots.

**Comment by suxb201** [comment]
https://tair-opensource.github.io/RedisShake/zh/function/best_practices.html#%E8%BF%87%E6%BB%A4-db
