### ISSUE TITLE
redis6+ acl迁移账号的最小权限是什么？没在文档中找到说明

### ISSUE THREAD

**Issue by wangshuang0220** [aliyun/redis-shake#703]
### 问题描述（Issue Description）
redis6+ acl迁移账号的最小权限是什么？没在文档中找到说明
自己测试这些权限即可：+psync +replconf +restore +ping +cluster+@write
请在这里简要描述你遇到的问题。

Please provide a brief description of the issue you encountered.

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：v4.0.2
- Redis 源端版本（Redis Source Version）：v6.0
- Redis 目的端版本（Redis Destination Version）：v6.0
- Redis 部署方式（standalone/cluster/sentinel）：cluster
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：

### 日志信息（Logs）

如果有错误日志或其他相关日志，请在这里提供。

If there are any error logs or other relevant logs, please provide them here.

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

Please provide any additional information, such as configuration files, error messages, or screenshots.

**Comment by suxb201** [comment]
源端还是目的端？
源端就几个命令，目的端需要所有写权限。
文档中确实没提到这点，如果愿意的话欢迎帮忙更新下文档。

**Comment by wangshuang0220** [comment]
> 源端还是目的端？ 源端就几个命令，目的端需要所有写权限。 文档中确实没提到这点，如果愿意的话欢迎帮忙更新下文档。

好的

**Comment by maoliugang** [comment]
redisshake 源集群为cluster模式是，执行完成后会自动停止进程，非cluster不会自动停止，请问有什么配置可以让redis-shake迁移完数据后不自动停止呢？

**Comment by wangshuang0220** [comment]
> redisshake 源集群为cluster模式是，执行完成后会自动停止进程，非cluster不会自动停止，请问有什么配置可以让redis-shake迁移完数据后不自动停止呢？

迁移完自动停止即不同步aof，需要修改如下参数
[sync_reader]
sync_rdb = true # set to false if you don't want to sync rdb
sync_aof = false # set to false if you don't want to sync aof

**Comment by maoliugang** [comment]
sync_aof 设置为true和false刚刚测试了都会停止（测试为4.0版本），请问可能还会有什么原因呢？

**Comment by suxb201** [comment]
@maoliugang 请新开 issue，附带日志。
