### ISSUE TITLE
standalone->cluster迁移时报错

### ISSUE THREAD

**Issue by wangshuang0220** [aliyun/redis-shake#704]
### 问题描述（Issue Description）
standalone->cluster迁移时报错

standalone有两个db，db0和db1。如果只有db0的时候不会报错，有多个db的时候会报错。如果源端有多个db需要用function处理吗？

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：v4.0.2
- Redis 源端版本（Redis Source Version）：v6
- Redis 目的端版本（Redis Destination Version）：v6
- Redis 部署方式（standalone/cluster/sentinel）：源端standlone，目的端cluster
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：

### 日志信息（Logs）

![image](https://github.com/tair-opensource/RedisShake/assets/8791900/096d7988-b3fd-4de6-b2c7-95be5053150b)

If there are any error logs or other relevant logs, please provide them here.

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

Please provide any additional information, such as configuration files, error messages, or screenshots.

**Comment by suxb201** [comment]
“如果源端有多个db需要用function处理吗？” 是的

**Comment by rainy0714** [comment]
function = """
local db1 = 5
local db2 = 0

if DB == db1 then
  DB = db2
end
shake.call(DB, ARGV)
"""
源redis是单机的，且数据库放在5，目标redis是集群的，数据库只能放在0，上面是我在shake.toml中加的
