### ISSUE TITLE
redis shake 4.0.2版本restore模式多数据源疑惑

### ISSUE THREAD

**Issue by PPeng2015** [aliyun/redis-shake#705]
1、rdb reader 是否支持多个rdb文件源？
2、aof reader 是否支持多个aof文件源？
3、同时配置rdb reader、aof reader会同时导入配置的rdb、aof文件么？

感谢！

**Comment by suxb201** [comment]
1. 不支持
2. 不支持
3. 不会

**Comment by PPeng2015** [comment]
刚使用aof reader，启动时返回：

**Comment by PPeng2015** [comment]
使用[aof_reader]模式，启动脚本，返回：ERR no reader config entry found，请问现在还不支持仅仅导入aof文件么？
