### ISSUE TITLE
redis-shake restore异常 len out of range

### ISSUE THREAD

**Issue by YunCheng-Dylan** [aliyun/redis-shake#710]
背景rdb to cluster ；
restore时len out of range；
期待您打答复

**Comment by YunCheng-Dylan** [comment]
![Uploading 6241700192728_.pic_hd.jpg…]()

**Comment by YunCheng-Dylan** [comment]
问题描述（Issue Description）


环境信息（Environment）
RedisShake 版本（RedisShake Version）：4.0.1
Redis 源端版本（Redis Source Version）：6.2.6
Redis 目的端版本（Redis Destination Version）：6.2.6
Redis 部署方式（standalone/cluster/sentinel）: cluster
是否在云服务商实例上部署（Deployed on Cloud Provider）：否

**Comment by suxb201** [comment]
图片没上传成功。

**Comment by YunCheng-Dylan** [comment]
![Uploading 6241700192728_.pic_hd.jpg…]()

**Comment by YunCheng-Dylan** [comment]
附件有问题我邮件发您邮箱

**Comment by YunCheng-Dylan** [comment]
[rdb reader] start read
panic: runtime error: makeslice: len out of range
goroutine 12 [running]:
RedisShake/internal/rdb/structure.ReadBytes((0x4c0348,0x4000062a20},0x400003€4682)
RedisShake/internal/rdb/structure/byte.go:14+0x34
RedisShake/internal/rdb/structure.ReadString((0x4c0348,0x4000062a20})
RedisShake/internal/rdb/structure/string.go:42+0xlb8
RedisShake/internal/rdb. (*Loader) .parseRDBEntry (0x40000d6510, 0x4000062a20)
RedisShake/internal/rdb/rdb.go:156+0×634
RedisShake/internal/rdb. (*Loader) .ParseRDB(0x40000d6510)
RedisShake/internal/rdb/rdb.go:91+0x358
RedisShake/internal/reader. (*rdbReader) .StartRead.func2 ()
RedisShake/internal/reader/rdb reader.go:54 +0x28
created by Redisshake/internal/reader. (*rdbReader) .StartRead
ADX
RedisShake/internal/reader/rdb reader.go:53 +0xlf0

**Comment by YunCheng-Dylan** [comment]
rdb 模式还原 len out of range
sync 模式存在同样的问题
read count=[0], read ops=[0.00], write count=[0], write ops=[6.00], src-0, receiving rdb
镇发 新建文件夹配区 panic: runtime error: makeslice: len out of range
黑…
通基线 新建XLSX
普数…
工作表ssx
larm
23RM038...
nuriw运维服务管，
goroutine 27 [running]:
RedisShake/internal/rdb/structure.ReadBytes((0x4c0348,0x4000064180}.0x400008dbf8?)
RedisShake/internal/rdb/structure/byte.go:14+0x34
RedisShake/internal/rdb/structure.ReadString({0x4c0348,0x4000064180})
RedisShake/internal/rdb/structure/string.go:42+0xlbs
RedisShake/internal/rdb. (*Loader) .parseRDBEntry(0x40001c1b0, 0x4000064180)
RedisShake/internal/rdb/rdb.go:156+0x634
RedisShake/internal/rdb.(*Loader).ParseRDB(0x400011c1b0)
RedisShake/internal/rdb/rdb.go:91+0x358
RedisShake/internal/reader.(*syncStandaloneReader).sendRDB(0x400017a000)
RedisShake/internal/reader/sync standalone reader.go:247 +0x1a0
RedisShake/internal/reader. (*syncStandaToneReader) .StartRead. func1()
RedisShake/internal/reader/sync standalone reader.go:99 +0x110
created by RedisShake/internal/reader.(#syncStandaToneReader).StartRead
RedisShake/internal/reader/sync standalone reader.go:91 +0x98
[bcsappadminesit-0001 bin]$

**Comment by YunCheng-Dylan** [comment]
rdb 模式还原 len out of range
sync 模式存在同样的问题


read count=[0], read ops=[0.00], write count=[0], write ops=[6.00], src-0, receiving rdb
panic: runtime error: makeslice: len out of range
goroutine 27 [running]:
RedisShake/internal/rdb/structure.ReadBytes((0x4c0348,0x4000064180}.0x400008dbf8?)
RedisShake/internal/rdb/structure/byte.go:14+0x34
RedisShake/internal/rdb/structure.ReadString({0x4c0348,0x4000064180})
RedisShake/internal/rdb/structure/string.go:42+0xlbs
RedisShake/internal/rdb. (*Loader) .parseRDBEntry(0x40001c1b0, 0x4000064180)
RedisShake/internal/rdb/rdb.go:156+0x634
RedisShake/internal/rdb.(*Loader).ParseRDB(0x400011c1b0)
RedisShake/internal/rdb/rdb.go:91+0x358
RedisShake/internal/reader.(*syncStandaloneReader).sendRDB(0x400017a000)
RedisShake/internal/reader/sync standalone reader.go:247 +0x1a0
RedisShake/internal/reader. (*syncStandaToneReader) .StartRead. func1()
RedisShake/internal/reader/sync standalone reader.go:99 +0x110
created by RedisShake/internal/reader.(#syncStandaToneReader).StartRead
RedisShake/internal/reader/sync standalone reader.go:91 +0x98
[bcsappadminesit-0001 bin]$

**Comment by suxb201** [comment]
@YunCheng-Dylan 可以 RDB 发我供分析下吗？

**Comment by YunCheng-Dylan** [comment]
应该是旧环境的老数据用到了RediSearch和RedisJson模块，但是新环境不需要加载这两个模块。想问一下这种有解决方案吗。

**Comment by suxb201** [comment]
@YunCheng-Dylan 旧环境删掉这两个 module 的数据
