### ISSUE TITLE
redisshake能否自主选择搭在源端主节点或者从节点

### ISSUE THREAD

**Issue by ntuwang** [aliyun/redis-shake#713]
我在同步数据的时候(集群-->集群)， 发现 redisshake默认选择了源端主节点作为数据源，这样对于源端集群会有一定的性能损耗，且占用master的缓冲区可能导致其他问题，我想问下 是否可以配置选择成从节点同步数据

**Comment by suxb201** [comment]
有道理，目前不支持。可以添加一个配置，然后解析路由表的时候自动选择 slave，暂时没开发规划，欢迎提交 PR。
