### ISSUE TITLE
使用V4版本进行sync同步时，当源数据量过大时，repl_ack_time无法及时更新，会导致超时断联

### ISSUE THREAD

**Issue by zgg2001** [aliyun/redis-shake#714]
### 问题描述（Issue Description）

背景：
使用V4版本进行sync同步
源集群数据量较大时且源集群不存在写操作

问题表现：
一定时间(repl-timeout)后出现 ERR: EOF 报错

问题原因：
repl_ack_time无法及时更新，会导致超时断联。

个人解决方案：
在StartRead()中定时发送命令更新repl_ack_time
`go func() {
        for range time.Tick(time.Second * 5) {
               r.client.SendBytes([]byte("\n"))
	}
}()`

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：v4
- Redis 源端版本（Redis Source Version）：6.x
- Redis 目的端版本（Redis Destination Version）：4.x
- Redis 部署方式（standalone/cluster/sentinel）：集群

### 补充

定时发送命令后，此问题不再出现，但是我怕会有隐藏问题，所以烦请再次看下这个问题。

**Comment by SKYNE0** [comment]
@zgg2001 遇到了相似的问题，可以帮忙补充点代码改动的部分吗

**Comment by suxb201** [comment]
是源端集群单个分片比较大吗。
一般 EOF 是源端 buffer 爆掉，杀 shake 连接了。

**Comment by zgg2001** [comment]
> @zgg2001 遇到了相似的问题，可以帮忙补充点代码改动的部分吗

我这边的最终方案如下：
`internal/reader/sync_standalone_reader.go +297` 后新增
```go
if r.stat.Status != kHandShake && r.stat.Status != kWaitBgsave && time.Now().Second()%10 == 0 {
	r.client.SendBytes([]byte("\n"))
}
```

**Comment by zgg2001** [comment]
> 是源端集群单个分片比较大吗。 一般 EOF 是源端 buffer 爆掉，杀 shake 连接了。

应该不是
我这边看源端log里有 `Disconnecting timedout replica (streaming sync): %s`
看源码应该是 `slave->repl_ack_time` 没更新导致的

**Comment by SKYNE0** [comment]
好的，谢谢
