### ISSUE TITLE
ERR unknown type byte:20

### ISSUE THREAD

**Issue by ScorpioAeolus** [aliyun/redis-shake#715]
### 问题描述（Issue Description）

redis:7.2.1同步到redis:7.2.1报错

Please provide a brief description of the issue you encountered.

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：V4.0.2(其他版本也试过)
- Redis 源端版本（Redis Source Version）：7.2.1
- Redis 目的端版本（Redis Destination Version）：7.2.1
- Redis 部署方式（standalone/cluster/sentinel）：docker standalone
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：

### 日志信息（Logs）

{"level":"info","time":"2023-11-27T09:05:59Z","message":"create RedisStandaloneWriter: 127.0.0.1:6379"}
{"level":"info","time":"2023-11-27T09:05:59Z","message":"not set status port"}
{"level":"info","time":"2023-11-27T09:05:59Z","message":"start syncing..."}
{"level":"error","time":"2023-11-27T09:06:03Z","message":"unknown type byte: 20"}

### 其他信息（Additional Information）

<img width="714" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/23074759/12a6b7e2-836a-44e9-8a20-5560f253c589">

**Comment by suxb201** [comment]
需要支持这两项的解析：https://github.com/redis/redis/blob/a1c5171c1deab0c39efe517218f24eb5ca915fd5/src/rdb.h#L98-L99

**Comment by ScorpioAeolus** [comment]
> 需要支持这两项的解析：https://github.com/redis/redis/blob/a1c5171c1deab0c39efe517218f24eb5ca915fd5/src/rdb.h#L98-L99

现在有新版本包打出来了吗？还是说要自己拉源码打包

**Comment by suxb201** [comment]
https://github.com/tair-opensource/RedisShake/commit/e8d2881a72327c6d2c50b4b3ece704a673378546
@ScorpioAeolus
自己拉源码，然后编译下吧。

**Comment by ScorpioAeolus** [comment]
> [e8d2881](https://github.com/tair-opensource/RedisShake/commit/e8d2881a72327c6d2c50b4b3ece704a673378546) @ScorpioAeolus 自己拉源码，然后编译下吧。

ok
