### ISSUE TITLE
error=[CROSSSLOT Keys in request don't hash to the same slot]

### ISSUE THREAD

**Issue by dba3306** [aliyun/redis-shake#717]
### 问题描述（Issue Description）

实时同步，rdb阶段快结束的时候，报error=[CROSSSLOT Keys in request don't hash to the same slot]

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：4.0.2
- Redis 源端版本（Redis Source Version）：7.0.9
- Redis 目的端版本（Redis Destination Version）：7.0.9
- Redis 部署方式（standalone/cluster/sentinel）：集群

### 日志信息（Logs）
2023-12-02 11:45:38 ERR [writer_10.1.x.x_6380] receive reply failed. cmd=[EXEC], error=[CROSSSLOT Keys in request don't hash to the same slot]

**Comment by yasiping** [comment]
我也碰到了这个问题，主和备都是集群

**Comment by suxb201** [comment]
是的，这是 shake 的 bug，shake 需要过滤掉 multi 和 exec 命令才行。

**Comment by yasiping** [comment]
> 我也碰到了这个问题，主和备都是集群

问题找到了，是源和目标端的槽分配不一样，源端的每个节点的槽都是不连续的，都是几千个不连续的槽，目标端刚创建的集群都是平均连续分配的，这样源端多key操作，有可能多个key 是move到一台节点上，到源端就可能在不同节点上了。

**Comment by suxb201** [comment]
@yasiping 不影响，这是 shake 的 bug

**Comment by hanxinhisen** [comment]
@suxb201 请问有这个报错，如何干预一下呢

**Comment by suxb201** [comment]
@hanxinhisen @yasiping @dba3306 https://github.com/tair-opensource/RedisShake/pull/786

**Comment by hanxinhisen** [comment]
@suxb201 这响应速度太快了，已完美解决问题。非常感谢。

**Comment by bennypea** [comment]
We are encountering this issue when trying to migrate a cluster to another cluster. Was this only fixed for stand alone instances? I am using v4.1.0

**Comment by suxb201** [comment]
@hanxinhisen The issue you're encountering might not be the same, please open a new issue with detailed description.
