### ISSUE TITLE
单机redis数据库迁移至集群redis scan_reader方式不同步增量数据

### ISSUE THREAD

**Issue by Gary2Luke** [aliyun/redis-shake#723]
问题描述（Issue Description）

场景：单机redis数据库迁移至集群redis

问题：scan_reader方式同步时，同步完全量数据后迁移进程停止；请问下如何处理成：同步完全量数据后进程不停止，等待迁移增量数据

环境信息（Environment）

RedisShake 版本（RedisShake Version）：v4.0.2

Redis 源端版本（Redis Source Version）：5.0

Redis 目的端版本（Redis Destination Version）：5.0

Redis 部署方式（standalone/cluster/sentinel）：源redis是standalone，目标redis是cluster

日志：
scanStandaloneReader fetch finished.
all done

**Comment by suxb201** [comment]
scan_reader 在开启 ksn 配置后才会同步增量数据：https://tair-opensource.github.io/RedisShake/zh/reader/scan_reader.html
