### ISSUE TITLE
优先选择从节点执行任务

### ISSUE THREAD

**Issue by jjz921024** [aliyun/redis-shake#724]
当前scan_reader和sync_reader都是选择主节点进行连接，
为了避免主节点负载太高，在有从节点的情况下，优先选择从节点进行同步和迁移工作

1. 在scan_reader和sync_reader下增加 `perfer_replica` 属性，表示优先选择从节点
2. 修改 cluster_nodes.go 中的 `GetRedisClusterNodes()` 函数，根据配置选择主从节点，若某个主节点没有从节点，则还是连接主节点

**Comment by suxb201** [comment]
感觉配置文件直接写从节点就可以，RedisShake 不做决策，可以尽量保持简单。

**Comment by jjz921024** [comment]
目前的实现中，即使配置文件中指定了从节点， `GetRedisClusterNodes()` 通过`cluster node`命令拿到集群的拓扑信息后，还是会连到主节点上

https://github.com/tair-opensource/RedisShake/blob/aa047467192bb3f431d924451daed3e839bb85e6/internal/utils/cluster_nodes.go#L20

**Comment by suxb201** [comment]
明白了，Cluster 模式下确实有这样的问题。

**Comment by Zheaoli** [comment]
这里的设计我有点纠结，我自己测试下来后，我倾向于 scan 可以连接到从节点，sync 还是链接到主节点比较好？

**Comment by suxb201** [comment]
@Zheaoli  sync 也是会增加主节点负载的。Redis 是单线程架构，处理用户命令和给 salve 节点发送数据交替进行。

**Comment by jjz921024** [comment]
@suxb201 @Zheaoli hi，这个功能感觉还是有挺多需求的，生产环境上都不想加重主节点的负载，这种同步的功能都可以移到从节点做。能麻烦看看 #725 这个pr的实现是否有问题吗
