### ISSUE TITLE
连接源实例的vip，vip发生切换时迁移任务就失败了

### ISSUE THREAD

**Issue by wangshuang0220** [aliyun/redis-shake#729]
### 问题描述（Issue Description）

源实例是哨兵集群，通过vip的方式连接主节点，vip始终绑定在主节点上，当源实例发生failover时，vip会漂移到新主节点上，发生failover时redis-shake就报错了

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：4.0.2
- Redis 源端版本（Redis Source Version）：redis6
- Redis 目的端版本（Redis Destination Version）：redis6
- Redis 部署方式（standalone/cluster/sentinel）：3 个sentinel ，1 master，1 replica
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：

### 日志信息（Logs）

![微信截图_20231215103306](https://github.com/tair-opensource/RedisShake/assets/8791900/b9c9719f-5a61-46d0-8f3d-d9c7df726bbb)

**Comment by suxb201** [comment]
vip 的换绑会导致 tcp 断连，目前版本的 RedisShake 不支持断点续传。
