### ISSUE TITLE
v4.0.2 语法报错strconv.Atoi: parsing

### ISSUE THREAD

**Issue by hophiya** [aliyun/redis-shake#730]
在使用redis-shake工具过程中，发现报错：
`{"level":"error","time":"2023-12-15T11:06:27+08:00","message":"strconv.Atoi: parsing \"[0\": invalid syntax"}`

Redis源端版本：6.2.6， Redis目标端版本 ：6.2.6，工具版本：4.0.2

执行迁移时报错：
`{"level":"info","time":"2023-12-15T11:06:27+08:00","message":"redisClusterWriter load cluster nodes. line=c5076e7b3229ee9c553d6a30a714511c4eee2d9e 192.168.8.42:7000@17000 myself,master - 0 1702609585000 2 connected 5461-10922 [0-<-16e920108c3e17d48ba509275345f70913fe45d9] [1-<-16e920108c3e17d48ba509275345f70913fe45d9] [2-<-16e920108c3e17d48ba509275345f70913fe45d9] [3-<-16e920108c3e17d48ba509275345f70913fe45d9]...... [5459-<-16e920108c3e17d48ba509275345f70913fe45d9] [5460-<-16e920108c3e17d48ba509275345f70913fe45d9]"}
......
{"level":"error","time":"2023-12-15T11:06:27+08:00","message":"strconv.Atoi: parsing \"[0\": invalid syntax"}`

发现在解析节点时将[0-<-16e920108c3e17d48ba509275345f70913fe45d9] 大量带中括号数据插入到结果行中，导致解析报错

![image](https://github.com/tair-opensource/RedisShake/assets/120696271/c35268e7-7ecc-4145-a013-c813db2830f6)

经查看源码，打入日志排查，发现只是在write阶段格式有问题
对应源码位置：internal/utils/cluster_nodes.go
无法深究，修改源码，处理掉，用正则表达，将带中括号的数据替换为空
import (
        "RedisShake/internal/client"
        "RedisShake/internal/log"
        "fmt"
        "strconv"
        "strings"
        "**regexp**"
)

func GetRedisClusterNodes(address string, username string, password string, Tls bool) (addresses []string, slots [][]int) {
        c := client.NewRedisClient(address, username, password, Tls)
        reply := c.DoWithStringReply("cluster", "nodes")
        reply = strings.TrimSpace(reply)
        slotsCount := 0
        **re := regexp.MustCompile(`\[[^\[\]]*\]`)**
        for _, line := range strings.Split(reply, "\n") {
                **line = re.ReplaceAllString(line,"")**
                line = strings.TrimSpace(line)
                words := strings.Split(line, " ")
                log.Infof("addbyxfdba: %s", line)
                log.Infof("addbyxfdba: %s", words)
                if !strings.Contains(words[2], "master") {
                        continue
                }

编译后运行能正常迁移
更优方案应该是前置就处理掉，但比较复杂，调用关系：writer/redis_cluster_writer.go->utils/cluster_nodes.go->client/redis.go->client/proto/writer.go

**Comment by suxb201** [comment]
是 Redis Cluster 迁移数据时会在 `cluster nodes` 命令的返回结果插入上述字段，我修下。
