### ISSUE TITLE
redisShake 目标端写入的连接是不是没有保活

### ISSUE THREAD

**Issue by ntuwang** [aliyun/redis-shake#758]
### 问题描述（Issue Description）

在rdb全量阶段，如果耗时很长，超过了目前端集群的timeout 链接会被kill掉，所以问下是不是没有做目标端的keepalive？

### 环境信息（Environment）

- RedisShake 版本4.0.2
- Redis 源端版本 4.0.14
- Redis 目的端版本（4.0.14
- Redis 部署方式cluster

**Comment by suxb201** [comment]
是的

**Comment by ntuwang** [comment]
![image](https://github.com/tair-opensource/RedisShake/assets/11935122/464f87bc-e02b-4a76-aaa2-8fe786c77fc5)
目前我是在NewRedisClusterWriter，新起一个协程去处理，麻烦大佬帮忙看看这样是不是对的，或者有没有什么潜在的坑

**Comment by suxb201** [comment]
@ntuwang 有竞争。简单改的话可以 Write 里面加一个锁。

**Comment by ntuwang** [comment]
OK 谢大佬
