### ISSUE TITLE
redisshake处理zset数据消耗大量内存，触发oom

### ISSUE THREAD

**Issue by Suarez1024** [aliyun/redis-shake#761]
### 问题描述（Issue Description）

在源库采用 bgsave 获取 rdb文件，大小为18G，采用 redisshake restore 模式加载到目标库，运行 redisshake 的机器（8c64g）触发oom。

排查后发现源库中有一个 zset，里面有超过1亿行数据，每行数据有几十个字符。redisshake 读取 zset 的时候是一次性全部读入内存的，64g都不够用，扩容机器到128G才加载成功。

建议修改读取 zset 的方式。

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：4.0.3
- Redis 源端版本（Redis Source Version）：7.0
- Redis 目的端版本（Redis Destination Version）：7.0
- Redis 部署方式（standalone/cluster/sentinel）：standalone
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：是

### 日志信息（Logs）

<img width="1439" alt="企业微信截图_a2ac992c-e22b-4818-8b27-a9b211031442" src="https://github.com/tair-opensource/RedisShake/assets/53106388/9a75bb90-fa2b-4624-8d47-5ee415c785bd">

percent=[28.57]% 时开始读取zset oom后直接退出进程，没有报错信息

**Comment by suxb201** [comment]
是这样的，很有道理。

**Comment by UFOXD** [comment]
我这边也遇到类似问题了，不知道有没有修复计划

**Comment by Suarez1024** [comment]
请问这个有修复计划吗？

**Comment by vczyh** [comment]
现在是将所有 element 放到数组中，应该可以改成放到 channel 中

**Comment by suxb201** [comment]
@vczyh 有道理，但是暂时没时间改。欢迎 PR！

**Comment by vczyh** [comment]
> @vczyh 有道理，但是暂时没时间改。欢迎 PR！

看了下现在的逻辑，感觉不太好改，现在的接口是：

```go
// RedisObject is interface for a redis object
type RedisObject interface {
	LoadFromBuffer(rd io.Reader, key string, typeByte byte)
	Rewrite() []RedisCmd
}
````

LoadFromBuffer 现在是全部解析：

```go
type SetObject struct {
	key      string
	elements []string
}
```

我的想法是把 RedisObject 改成类似这样，还是 Set 为例：

```go
type SetObject struct {
	key      string
        r io      Reader
}

func (o *SetObject) Rewrite() chan RedisCmd {
	cmds := make(chan RedisCmd, 100)
	go func() {
		// parse set element
		element := "set element"
		cmd := RedisCmd{"sadd", o.key, element}
		cmds <- cmd
	}()
	return cmds
}
```

根据命令恢复：

```go
o := types.ParseObject(anotherReader, typeByte, key)
for cmd range o.Rewrite() {
    // send to entry channel
}
```

因为需要支持 restore 命令恢复，可以在 RedisObject 添加 dump 方法，现在接口变成这样：

```go
type RedisObject interface {
	LoadFromBuffer(rd io.Reader, key string, typeByte byte)
	Rewrite() chan RedisCmd
        DumpTo(w io.Writer) error 
}
```

**Comment by suxb201** [comment]
@vczyh 酷，我认为这是比较优雅的改法。
有两点需要提醒下：
1. go func() 中需要 close channel，这样外面的 for 循环才可以停止。
2. 我没明白 `DumpTo` 的用途，对于从 dump.rdb 中加载出来数据，如果需要解析才走 Rewrite()，否则直接封装为 restore 命令发送至目的端。没有必要解析-编码-封装为 restore 命令。实际上对于多数命令都是不需要解析的，可以直接封装为 restore 命令发送至目的端。只有对于体积很大的 key，一条 restore 命令无法承载，才需要解析，然后重写为 Redis 命令发送。

**Comment by vczyh** [comment]
> @vczyh 酷，我认为这是比较优雅的改法。 有两点需要提醒下：
> 
> 1. go func() 中需要 close channel，这样外面的 for 循环才可以停止。
> 2. 我没明白 `DumpTo` 的用途，对于从 dump.rdb 中加载出来数据，如果需要解析才走 Rewrite()，否则直接封装为 restore 命令发送至目的端。没有必要解析-编码-封装为 restore 命令。实际上对于多数命令都是不需要解析的，可以直接封装为 restore 命令发送至目的端。只有对于体积很大的 key，一条 restore 命令无法承载，才需要解析，然后重写为 Redis 命令发送。

1. 感谢提醒。
2. `DumpTo` 的作用就是 restore 内容，类似这个：https://github.com/tair-opensource/RedisShake/blob/c5ff14cad77d1502154a51069e56f07dcf60d4b9/internal/rdb/rdb.go#L210-L219

RedisObject 持有 `io.Reader` 引用，调用 `Rewrite` 会解析成具体 cmd，调用  `DumpTo` 会直接拼接内容生成 restore 内容。

**Comment by suxb201** [comment]
@vczyh 意思是把 createValueDump 方法搬到 RedisObject 内部吗？这样会不会一样的方法要实现多遍。

**Comment by vczyh** [comment]
> @vczyh 意思是把 createValueDump 方法搬到 RedisObject 内部吗？这样会不会一样的方法要实现多遍。

有道理，那就还是放在外部，就像现在一样：https://github.com/tair-opensource/RedisShake/blob/c5ff14cad77d1502154a51069e56f07dcf60d4b9/internal/rdb/rdb.go#L160-L162

看看还有什么其他问题没？

**Comment by suxb201** [comment]
@vczyh 没有了。有些不好改的结构也可以保留原有的 rewrite 方式，虽然方法是返回 chan，但是内部可以一次性做完。

**Comment by vczyh** [comment]
> @vczyh 没有了。有些不好改的结构也可以保留原有的 rewrite 方式，虽然方法是返回 chan，但是内部可以一次性做完。

好的，我有时间改一下～

**Comment by vczyh** [comment]
@suxb201 遇到一个问题，虽然现在 `o.Rewrite()` 返回的是 channel，实现了同时解析和发送，但是 `value` 字段仍然会存着所有的 RedisObject 数据，仍然占大量内存，这块逻辑怎么优化？最好是直接写入到目标 socket writer。

```go
key := structure.ReadString(rd)
var value bytes.Buffer
anotherReader := io.TeeReader(rd, &value)
o := types.ParseObject(anotherReader, typeByte, key)
if uint64(value.Len()) > config.Opt.Adv anced.TargetRedisProtoMaxBulkLen {
	cmdC := o.Rewrite()
	for cmd := range cmdC {
		e := entry.NewEntry()
		e.DbId = ld.nowDBId
		e.Argv = cmd
		ld.ch <- e
	}
	if ld.expireMs != 0 {
		e := entry.NewEntry()
		e.DbId = ld.nowDBId
		e.Argv = []string{"PEXPIRE", key, strconv.FormatInt(ld.expireMs, 10)}
		ld.ch <- e
	}
}
```

**Comment by suxb201** [comment]
我没有想到好的解决方案。
推荐：去掉 `TargetRedisProtoMaxBulkLen` 配置，无论什么类型统一 `Rewrite()`，这样可以去掉 `TeeReader`。可以先这样试着能不能写出来。

**Comment by vczyh** [comment]
@suxb201  Review code please.
