### ISSUE TITLE
redisStandaloneWriter received BUSYKEY reply

### ISSUE THREAD

**Issue by jasonchen0524** [aliyun/redis-shake#767]
### 问题描述（Issue Description）

请在这里简要描述你遇到的问题。

从redis哨兵模式其中一个slave节点数据迁移到新集群报错 redisStandaloneWriter received BUSYKEY reply

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：4.0.3
- Redis 源端版本（Redis Source Version）：6.2.4
- Redis 目的端版本（Redis Destination Version）：6.2.10
- Redis 部署方式（standalone/cluster/sentinel）：cluster
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：no

### 日志信息（Logs）
<img width="1125" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/141199900/a5770b1c-c2a4-4506-8880-c8dc57848e56">

如果有错误日志或其他相关日志，请在这里提供。

2504 10.188.220.78:32504]
2024-01-31 16:30:09 INF create RedisClusterWriter: 10.188.220.79:32504
2024-01-31 16:30:09 INF not set status port
2024-01-31 16:30:09 INF start syncing...
2024-01-31 16:30:10 ERR [writer_10.188.220.79_32504] redisStandaloneWriter received BUSYKEY reply. cmd=[restore reorder2_b9b6068f56efa8426c90c539584028a9_1_S2 0 �@�@�"1210301112734123035,12208 

9293218...]
                        RedisShake/internal/writer/redis_standalone_writer.go:108 -> (*redisStandaloneWriter).processReply()
                        runtime/asm_amd64.s:1598 -> goexit()

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。
function = ""

[sync_reader]
cluster = false            # set to true if source is a redis cluster
address = "127.0.0.1:5379" # when cluster is true, set address to one of the cluster node
username = ""              # keep empty if not using ACL
password = "xxxxx"              # keep empty if no authentication is required
tls = false
sync_rdb = true # set to false if you don't want to sync rdb
sync_aof = true # set to false if you don't want to sync aof
prefer_replica = true # set to true if you want to sync from replica node

[redis_writer]
cluster = true            # set to true if target is a redis cluster
address = "10.188.220.79:32504" # when cluster is true, set address to one of the cluster node
username = ""              # keep empty if not using ACL
password = "xxxxx"              # keep empty if no authentication is required
tls = false
off_reply = false       # ture off the server reply

**Comment by vczyh** [comment]
Key 已经存在了，参考 advance section 中的 `rdb_restore_command_behavior` 配置项。

```toml
# redis-shake gets key and value from rdb file, and uses RESTORE command to
# create the key in target redis. Redis RESTORE will return a "Target key name
# is busy" error when key already exists. You can use this configuration item
# to change the default behavior of restore:
# panic:   redis-shake will stop when meet "Target key name is busy" error.
# rewrite: redis-shake will replace the key with new value.
# ignore:  redis-shake will skip restore the key when meet "Target key name is busy" error.
rdb_restore_command_behavior = "rewrite" # panic, rewrite or skip
```
