### ISSUE TITLE
loacl cursor=‘0’  redis.call('SCAN')

### ISSUE THREAD

**Issue by yuekk1** [aliyun/redis-shake#778]
### 问题描述（Issue Description）
同步数据报错

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：4.2
- Redis 源端版本（Redis Source Version）：5.05
- Redis 目的端版本（Redis Destination Version）：东方通RDS
- Redis 部署方式（standalone/cluster/sentinel）：cluster
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：
- 服务器：arm64

### 日志信息（Logs）
![bda9ea438676d57e8dd114fa3eaf304](https://github.com/tair-opensource/RedisShake/assets/162561307/32cc2e37-6fbe-4ebc-813c-e380ea9200e0)

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

Please provide any additional information, such as configuration files, error messages, or screenshots.

**Comment by suxb201** [comment]
日志拍全
