### ISSUE TITLE
源集群节点版本不一致报错

### ISSUE THREAD

**Issue by drowsyBruin** [aliyun/redis-shake#779]
### 问题描述（Issue Description）

使用redis-shake迁移redis集群，源集群节点版本不一致，能否支持？

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：v2.1.2
- Redis 源端版本（Redis Source Version）：5.0.4、5.0.3
- Redis 目的端版本（Redis Destination Version）：
- Redis 部署方式（standalone/cluster/sentinel）：cluser
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：否

### 日志信息（Logs）

![企业微信截图_16996077836615](https://github.com/tair-opensource/RedisShake/assets/17338350/a4903162-e7de-4cb3-b7e4-ce5d118a009a)

If there are any error logs or other relevant logs, please provide them here.

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

Please provide any additional information, such as configuration files, error messages, or screenshots.

**Comment by suxb201** [comment]
不提供 2.x 版本的答疑，使用最新版本尝试。
