### ISSUE TITLE
同步数据太慢

### ISSUE THREAD

**Issue by 0521ak47** [aliyun/redis-shake#783]
### 问题描述（Issue Description）

每个master节点key数量大概1120万，同步了快7个小时，还在同步完，两个集群不同内网，外网带宽200Mbp

Please provide a brief description of the issue you encountered.

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：v3.1.11
- Redis 源端版本（Redis Source Version）：6.0
- Redis 目的端版本（Redis Destination Version）：6.0
- Redis 部署方式（standalone/cluster/sentinel）：cluster
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：否

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。
![123456](https://github.com/tair-opensource/RedisShake/assets/32762041/bb810933-495d-4cf1-9200-465c8de360d9)

**Comment by suxb201** [comment]
v3.1.11 版本不提供答疑，使用新版本试试。

**Comment by 0521ak47** [comment]
那4.x 源是cluster集群，目的也是cluster集群，同步是否只需开启一个redis-shake？填写源集群其中1个master节点，目的其中1个master节点，开始同步？

**Comment by suxb201** [comment]
是的，请查看文档：https://tair-opensource.github.io/RedisShake/zh/reader/sync_reader.html
