### ISSUE TITLE
Overwriting Keys Issue

### ISSUE THREAD

**Issue by aliemregursu** [aliyun/redis-shake#784]
### 问题描述（Issue Description）

请在这里简要描述你遇到的问题。

Please provide a brief description of the issue you encountered.
When I try to restore using rdb reader and rediswriter the keys are overwrited regardless of the configuration option rdb_restore_command_behavior. 
I tried panic, ignore,skip all and tried also deleting the key to use the default version but always it overrides the key value. 

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）： v4.0.5 (https://github.com/tair-opensource/RedisShake/releases/download/v4.0.5/redis-shake-linux-arm64.tar.gz)
- Redis 源端版本（Redis Source Version）： 7.0.5
- Redis 目的端版本（Redis Destination Version）： 7.0.5
- Redis 部署方式（standalone/cluster/sentinel）：standalone
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：on prem

### 日志信息（Logs）

如果有错误日志或其他相关日志，请在这里提供。

If there are any error logs or other relevant logs, please provide them here.
There are not any error logs
### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

Please provide any additional information, such as configuration files, error messages, or screenshots.
[rdb_reader]
filepath = "/home/aeg/Desktop/dump_new.rdb"

[redis_writer]
cluster = false            # set to true if target is a redis cluster
address = "127.0.0.1:6379" # when cluster is true, set address to one of the cluster node
username = ""              # keep empty if not using ACL
password = "samplepass"              # keep empty if no authentication is required
tls = false
off_reply = false       # ture off the server reply

[advanced]
dir = "data"
ncpu = 0
pprof_port = 0
status_port = 0
log_file = "shake.log"
log_level = "info"
log_interval = 15
rdb_restore_command_behavior = "panic"
pipeline_count_limit = 1024

![image](https://github.com/tair-opensource/RedisShake/assets/17311850/179acb14-8a90-43b8-8c90-ae757c42955a)

{"level":"info","time":"2024-03-20T15:54:10+03:00","message":"log_level: [info], log_file: [/home/aeg/Desktop/data/shake.log]"}
{"level":"info","time":"2024-03-20T15:54:10+03:00","message":"changed work dir. dir=[/home/aeg/Desktop/data]"}
{"level":"info","time":"2024-03-20T15:54:10+03:00","message":"GOMAXPROCS defaults to the value of runtime.NumCPU [4]"}
{"level":"info","time":"2024-03-20T15:54:10+03:00","message":"not set pprof port"}
{"level":"info","time":"2024-03-20T15:54:10+03:00","message":"create RdbReader: /home/aeg/Desktop/dump_new.rdb"}
{"level":"info","time":"2024-03-20T15:54:10+03:00","message":"create RedisStandaloneWriter: 127.0.0.1:6379"}
{"level":"info","time":"2024-03-20T15:54:10+03:00","message":"not set status port"}
{"level":"info","time":"2024-03-20T15:54:10+03:00","message":"start syncing..."}
{"level":"info","time":"2024-03-20T15:54:10+03:00","message":"[rdb_reader] start read"}
{"level":"info","time":"2024-03-20T15:54:25+03:00","message":"read_count=[396829], read_ops=[27602.02], write_count=[396828], write_ops=[27602.02], [rdb_reader] rdb file synced: 50.32%"}
{"level":"info","time":"2024-03-20T15:54:40+03:00","message":"read_count=[802114], read_ops=[26785.49], write_count=[802113], write_ops=[26785.49], [rdb_reader] rdb file synced: 50.32%"}
{"level":"info","time":"2024-03-20T15:54:46+03:00","message":"[rdb_reader] rdb file parse done"}
{"level":"info","time":"2024-03-20T15:54:47+03:00","message":"all done"}

**Comment by suxb201** [comment]
问题是没有出现 100% 吗，可能只是日志间隙没有打印到。

**Comment by guoard** [comment]
> 问题是没有出现 100% 吗，可能只是日志间隙没有打印到。

No, this is not about a log gap!  
When you restore the same RDB file with `rdb_restore_command_behavior` set to `panic`, you would expect the operation to stop. However, it continues instead, behaving as if the setting were `rewrite`.

cc @EquentR

**Comment by EquentR** [comment]
The `rdb_restore_command_behavior` configuration options, *skip* and *panic*, take effect only in the `redis_writer` when a key is simultaneously modified by RedisShake and another client, resulting in a conflict. For example, if the following two write operations occur simultaneously:  
- RedisShake: `SET key value`  
- Another Redis client: `SET key value2`  

In this case, RedisShake provides the *skip* and *panic* options to handle this error.  

As for *rewrite*, this option applies to the `scan_reader` during source-side Redis scanning. If the key already exists in the target Redis during the full synchronization, this option determines whether the new value for this key should overwrite the target Redis data.  

Admittedly, this configuration can be a bit confusing. 😢

**Comment by guoard** [comment]
@EquentR Thank you for your response!

What if we want to set `skip` for `redis_writer` and `rewrite` for `scan_reader`? It seems these options can be configured under the advanced section. Could you please clarify how to achieve this?

**Comment by EquentR** [comment]
@guoard 
I’m not very clear on the original design logic of this feature either. In fact, if you set `rewrite`, it will only take effect in the `scan_reader`. In this case, the logic in the `redis_writer` defaults to `skip`, and no `panic` situation will occur.

**Comment by suxb201** [comment]
The `rdb_restore_command_behavior` option will apply to `scan_reader`, `rdb_reader` and the RDB stage of `sync_reader`, as these stages generate [restore](https://redis.io/docs/latest/commands/restore/) commands.
