### ISSUE TITLE
数据传输过程中，报[ERR MULTI calls can not be nested]

### ISSUE THREAD

**Issue by Jingunwoo** [aliyun/redis-shake#789]
### 问题描述（Issue Description）

数据传输过程中，报[ERR MULTI calls can not be nested]，并导致数据传输中断

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：4.0.5
- Redis 源端版本（Redis Source Version）：5.0.7
- Redis 目的端版本（Redis Destination Version）：5.0
- Redis 部署方式（standalone/cluster/sentinel）：源端：集群3主3从；目的端：主从
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：
阿里私有云
<img width="701" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/31399739/d4ca7226-4b3f-407d-8078-280586887fe4">

### 日志信息（Logs）

<img width="2541" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/31399739/c5f0d335-feae-4427-a78d-d82bc0214343">

### 其他信息（Additional Information）

redis-shake同步配置
<img width="727" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/31399739/10f8f4f1-8d7b-4fbf-8b6f-baacc674d523">

**Comment by suxb201** [comment]
我修了，还没发版本。git clone 最新的代码，然后编译运行。

**Comment by Jingunwoo** [comment]
下载了最新代码编译运行后，可以运行了，非常感谢！
