### ISSUE TITLE
运行过程中大概有5分钟的时间，read_ops/write_ops都是0，最后任务失败退出

### ISSUE THREAD

**Issue by mulihong** [aliyun/redis-shake#793]
### 问题描述（Issue Description）
- 工具同步数据过程中速度太慢
- 运行过程中有5分钟时间，read_ops/write_ops都是0、无数据写入目标集群

Please provide a brief description of the issue you encountered.

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：
  - [redis-shake-v4.0.5](https://github.com/tair-opensource/RedisShake/releases/tag/v4.0.5)
- Redis 源端版本（Redis Source Version）：
  - Redis server v=4.0.10
- Redis 目的端版本（Redis Destination Version）：
  - Redis server v=4.0.10
- Redis 部署方式（standalone/cluster/sentinel）：
  - redis cluster
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：
  - 否
### 日志信息（Logs）
{"level":"info","time":"2024-05-06T15:10:51+08:00","message":"read_count=[704822], read_ops=[0.00], write_count=[704821], write_ops=[0.00], src-0, syncing rdb, size=[58MiB/286 MiB]"}
{"level":"info","time":"2024-05-06T15:10:56+08:00","message":"read_count=[704822], read_ops=[0.00], write_count=[704821], write_ops=[0.00], src-1, syncing rdb, size=[9.8 MiB/338 MiB]"}
{"level":"info","time":"2024-05-06T15:11:01+08:00","message":"read_count=[704822], read_ops=[0.00], write_count=[704821], write_ops=[0.00], src-2, syncing rdb, size=[15MiB/367 MiB]"}
{"level":"info","time":"2024-05-06T15:11:06+08:00","message":"read_count=[704822], read_ops=[0.00], write_count=[704821], write_ops=[0.00], src-0, syncing rdb, size=[58MiB/286 MiB]"}
{"level":"info","time":"2024-05-06T15:11:11+08:00","message":"read_count=[704822], read_ops=[0.00], write_count=[704821], write_ops=[0.00], src-1, syncing rdb, size=[9.8 MiB/338 MiB]"}
{"level":"info","time":"2024-05-06T15:11:16+08:00","message":"read_count=[704822], read_ops=[0.00], write_count=[704821], write_ops=[0.00], src-2, syncing rdb, size=[15MiB/367 MiB]"}
{"level":"info","time":"2024-05-06T15:11:21+08:00","message":"read_count=[704822], read_ops=[0.00], write_count=[704821], write_ops=[0.00], src-0, syncing rdb, size=[58MiB/286 MiB]"}
{"level":"info","time":"2024-05-06T15:11:26+08:00","message":"read_count=[704822], read_ops=[0.00], write_count=[704821], write_ops=[0.00], src-1, syncing rdb, size=[9.8 MiB/338 MiB]"}
{"level":"info","time":"2024-05-06T15:11:31+08:00","message":"read_count=[704822], read_ops=[0.00], write_count=[704821], write_ops=[0.00], src-2, syncing rdb, size=[15MiB/367 MiB]"}
{"level":"info","time":"2024-05-06T15:11:36+08:00","message":"read_count=[707790], read_ops=[2678.38], write_count=[707789], write_ops=[2678.38], src-0, syncing rdb, size=[58 MiB/286 MiB]"}
{"level":"info","time":"2024-05-06T15:11:41+08:00","message":"read_count=[707790], read_ops=[0.00], write_count=[707789], write_ops=[0.00], src-1, syncing rdb, size=[9.8 MiB/338 MiB]"}
{"level":"info","time":"2024-05-06T15:11:46+08:00","message":"read_count=[969912], read_ops=[56398.56], write_count=[969911], write_ops=[56398.56], src-2, syncing rdb, size=[20 MiB/367 MiB]"}
{"level":"info","time":"2024-05-06T15:11:51+08:00","message":"read_count=[976518], read_ops=[0.00], write_count=[976517], write_ops=[0.00], src-0, syncing rdb, size=[68MiB/286 MiB]"}
{"level":"info","time":"2024-05-06T15:11:56+08:00","message":"read_count=[977545], read_ops=[0.00], write_count=[977544], write_ops=[0.00], src-1, syncing rdb, size=[21MiB/338 MiB]"}
{"level":"info","time":"2024-05-06T15:12:01+08:00","message":"read_count=[984466], read_ops=[3174.75], write_count=[984465], write_ops=[3174.75], src-2, syncing rdb, size=[26 MiB/367 MiB]"}
{"level":"info","time":"2024-05-06T15:12:06+08:00","message":"read_count=[1068594], read_ops=[17527.76], write_count=[1068593], write_ops=[17527.76], src-0, syncing rdb, size=[70 MiB/286 MiB]"}
{"level":"info","time":"2024-05-06T15:12:11+08:00","message":"read_count=[1159504], read_ops=[18860.14], write_count=[1159503], write_ops=[18860.14], src-1, syncing rdb, size=[25 MiB/338 MiB]"}

如果有错误日志或其他相关日志，请在这里提供。

If there are any error logs or other relevant logs, please provide them here.
### 其他信息（Additional Information）

Please provide any additional information, such as configuration files, error messages, or screenshots.
![企业微信截图_17149798032422](https://github.com/tair-opensource/RedisShake/assets/11975922/68fcf473-d702-44bb-9b98-8557fadb2d7f)

![企业微信截图_17149792695750](https://github.com/tair-opensource/RedisShake/assets/11975922/eab70d8b-f9ee-4a2f-81b4-6c1dbc0ecb3d)

**Comment by mulihong** [comment]
错误日志:
{"level":"error","time":"2024-05-06T15:23:24+08:00","message":"[writer_10.204.210.52_8080] receive reply failed. cmd=[EVAL if redis.call('setnx', KEYS[6], ARGV[4]) == 0then return -1;end;redis.call('expire', KEYS[6], ...], error=[ERR Error running script (call to f_3eac13e5e38d0467336564b28d5ee65efaeb0d8a): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) ]\n\t\t\tRedisShake/internal/writer/redis_standalone_writer.go:112 -> (*redisStandaloneWriter).processReply()\n\t\t\truntime/asm_amd64.s:1598 -> goexit()"}

**Comment by suxb201** [comment]
看着是 LUA 脚本的问题，自行检查一下脚本。
