### ISSUE TITLE
自建Redis与云Redis同步异常

### ISSUE THREAD

**Issue by 1260328762** [aliyun/redis-shake#794]
### 问题描述（Issue Description）

请在这里简要描述你遇到的问题。
Redis源版本和目的地版本不一致，导致同步过程中报错

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：4.0.5
- Redis 源端版本（Redis Source Version）：7.0.5
- Redis 目的端版本（Redis Destination Version）：4.0.11
- Redis 部署方式（standalone/cluster/sentinel）：standalone
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：源Redis为自建，目的Redis为政务云

### 日志信息（Logs）

如果有错误日志或其他相关日志，请在这里提供。
![image](https://github.com/tair-opensource/RedisShake/assets/42630066/b4021ba7-262f-4a88-a92e-5c2bc4035fcd)

If there are any error logs or other relevant logs, please provide them here.

### 其他信息（Additional Information）
配置文件如下
![image](https://github.com/tair-opensource/RedisShake/assets/42630066/35a6ad3a-e163-40ad-b4e3-df3b7d257c87)

![image](https://github.com/tair-opensource/RedisShake/assets/42630066/fa4e63a6-61fc-4d5b-9657-72d9a262a8ee)

**Comment by suxb201** [comment]
降低版本是会有这种问题，没法避免。

**Comment by suxb201** [comment]
补充文档说明
