### ISSUE TITLE
RedisShake 3.1.11 从4.0.11同步到6.0.14，key数量对不上

### ISSUE THREAD

**Issue by robert1070** [aliyun/redis-shake#795]
### 问题描述（Issue Description）

请在这里简要描述你遇到的问题。

Please provide a brief description of the issue you encountered.

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：3.1.11
- Redis 源端版本（Redis Source Version）：4.0.11
- Redis 目的端版本（Redis Destination Version）：6.0.14
- Redis 部署方式（standalone/cluster/sentinel）：cluster
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：否

### 详细及日志
**同步方式为：单机 ---> 集群**

- 源集群中某一个节点：
<img width="992" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/27329773/92513a2e-e3f5-4028-a372-0ba8be183c85">

- 目标集群中某一节点：
<img width="986" alt="image" src="https://github.com/tair-opensource/RedisShake/assets/27329773/05da1db8-0fec-493c-aea6-0851cbac682b">

**Comment by suxb201** [comment]
可能是存在过期数据，导致数据过期

**Comment by suxb201** [comment]
提供文档说明。
