### ISSUE TITLE
RedisShake 4.x支持断点续传吗

### ISSUE THREAD

**Issue by 52hzbobo** [aliyun/redis-shake#796]
### 问题描述（Issue Description）
现在有一个需求场景
需要从Redis单机迁移到RedisCluster集群
翻了官方文档没找到4.x支持断点的配置

**Comment by 52hzbobo** [comment]
找到解决方案了：

redis shake 第一次进行同步时候 
shake.toml 配置
[sync_reader]
...
sync_rdb = true  # 全量同步开启
sync_aof = true  # 增量同步开启
同步完成后设置(shake关闭或者异常终止)
sync_rdb = false  # 全量同步关闭 不然会重新全量覆盖到目标库(目标在使用情况下同样key会被旧来源数据覆盖) 
sync_aof = true   # 增量同步开启

**Comment by suxb201** [comment]
不支持断点续传
