### ISSUE TITLE
通过nat转换进行同步报 i/o timeout

### ISSUE THREAD

**Issue by nvll2x** [aliyun/redis-shake#800]
### 问题描述（Issue Description）

请在这里简要描述你遇到的问题。

Please provide a brief description of the issue you encountered.

在做跨云同步时，进行nat转换，日志里面识别出来的是连接原IP，报i/o timeout

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：[v4.0.5]
- Redis 源端版本（Redis Source Version）：5
- Redis 目的端版本（Redis Destination Version）：5
- Redis 部署方式（standalone/cluster/sentinel）：cluster
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：是

### 日志信息（Logs）

如果有错误日志或其他相关日志，请在这里提供。

If there are any error logs or other relevant logs, please provide them here.

### 其他信息（Additional Information）
![image](https://github.com/tair-opensource/RedisShake/assets/84450520/98174d64-883d-494c-a91a-008041b6e4e8)

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

Please provide any additional information, such as configuration files, error messages, or screenshots.

**Comment by suxb201** [comment]
源端 redis -> nat -> shake
因为源端 redis 不知道 nat 的存在，其返回的分片信息的 ip 都是内网 ip。所以这种场景不能依赖 redis 返回的分片信息，需要为每个分片单独配置 shake，配置为 nat 的 ip。
