### ISSUE TITLE
can_reader模式同步过程中报：ERR unexpected EOF 

### ISSUE THREAD

**Issue by xcjing** [aliyun/redis-shake#802]
### 问题描述（Issue Description）
在采用scan_reader模式从AWS的Elasticache同步到自建的redis 集群的时候，有时候会报下面的错误，是什么原因？

2024-05-18 14:37:55 ERR unexpected EOF 			RedisShake/internal/reader/scan_standalone_reader.go:102 -> (*scanStandaloneReader).subscript.func1() 			runtime/asm_amd64.s:1598 -> goexit()

Please provide a brief description of the issue you encountered.

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：4.0.5
- Redis 源端版本（Redis Source Version）：7.07
- Redis 目的端版本（Redis Destination Version）：7.07
- Redis 部署方式（standalone/cluster/sentinel）：cluster
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：是

### 日志信息（Logs）

如果有错误日志或其他相关日志，请在这里提供。

If there are any error logs or other relevant logs, please provide them here.

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

Please provide any additional information, such as configuration files, error messages, or screenshots.

**Comment by suxb201** [comment]
可能是 `client-output-buffer-limit pubsub` 超限，然后被杀掉了。本质还是同步太慢，导致数据堆积。
