### ISSUE TITLE
sync_rdb设为false之后依然拉取全量rdb文件发给slave

### ISSUE THREAD

**Issue by githahaha** [aliyun/redis-shake#815]
### 问题描述（Issue Description）

sync_rdb设为false之后依然拉取全量rdb文件发给slave

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：v4.0.3
- Redis 源端版本（Redis Source Version）：6.2.4
- Redis 目的端版本（Redis Destination Version）：6.2.4
- Redis 部署方式（standalone/cluster/sentinel）： cluster
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：否

### 日志信息（Logs）

<img width="1776" alt="WechatIMG355" src="https://github.com/tair-opensource/RedisShake/assets/15137659/68cfa8e7-7899-4610-b557-cf7fd7a9753c">

**Comment by suxb201** [comment]
sync_rdb设为false之后依然拉取全量rdb文件 -- 正确
sync_rdb设为false之后依然拉取全量rdb文件**发给slave** -- 错误

**Comment by githahaha** [comment]
非常谢谢您的回复, 意思是即使sync_rdb设置为false之后redis-shake还是会把源库的rdb拉取到shake本地但不会发给目标slave是吗?  源库单个rdb文件大概在4.2GB左右, 拉取rdb文件的过程会受client-output-buffer-limit的大小限制么?

**Comment by suxb201** [comment]
是的；会，一遍需要改大些。

**Comment by githahaha** [comment]
又发现一个问题, 我们生产环境redis cluster是5主5从的配置, 刚开始redis-shake放在一台4核的机器上跑只会同步5个主节点中其中1个节点数据, 后面放到一台8核的机器上跑他只会同步5个主节点中其中2个节点的数据,  难道同步5个节点的数据我需要给一台20核的服务器么? ncpu设置的0.
