### ISSUE TITLE
请问如何配置ssh方式连接redis

### ISSUE THREAD

**Issue by zhangys529** [aliyun/redis-shake#829]
### 问题描述（Issue Description）

我们是在aws两个不同账号之间做elasticache迁移，但是不支持公网访问，目前想到的是在各自账号下开一台ec2，然后redisshake工具通过这两台ec2来访问redis，但是没找到如何配置

**Comment by suxb201** [comment]
ec2 上自建代理，把 elasticache 暴露出去。

**Comment by zhangys529** [comment]
恩目前已经代理好了，现在有另外一个问题就是aws的elasticache不支持psync，已经提了工单等回复
