### ISSUE TITLE
Valkey support

### ISSUE THREAD

**Issue by VincentWang1024** [aliyun/redis-shake#840]
### 问题描述（Issue Description）
 redis shake 对Valkey的支持
请在这里简要描述你遇到的问题。

我们团队使用的IBM redis未来可能迁移到Valkey，想了解redis shake 对其的支持程度。
### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：v4
- Redis 源端版本（Redis Source Version）：6.2
- Redis 目的端版本（Redis Destination Version）：6.2
- Redis 部署方式（standalone/cluster/sentinel）：IBM cloud cluster
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：是

**Comment by suxb201** [comment]
完全支持源端和目的端为 Valkey。
