### ISSUE TITLE
当前的V4版本是否还支持 filter.key.whitelist 配置呢

### ISSUE THREAD

**Issue by ztommyc** [aliyun/redis-shake#856]
### 问题描述（Issue Description）

当前的V4版本是否还支持 filter.key.whitelist 配置呢, 我看配置文件里面没有该项

**Comment by suxb201** [comment]
都可以通过 https://tair-opensource.github.io/RedisShake/zh/function/introduction.html 来实现

**Comment by ztommyc** [comment]
tks
