### ISSUE TITLE
psync同步模式下，RedisShake目录中的aof文件重做问题

### ISSUE THREAD

**Issue by strongworker** [aliyun/redis-shake#865]
### 问题描述（Issue Description）
场景：通过psync模式发起数据同步，aof同步期间，RedisShake会持续写入命令到本地的0.aof文件下；
问题：源Redis触发自动的 bgrewriteaof时（非手动），重做源端aof文件；但是RedisShake目录下的0.aof在附近时间点也发生重做，查看0.aof并未发现bgrewriteaof相应命令；请问下这是什么原因呢？查看Redis相应文档也未查到。

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：4.1.1
- Redis 源端版本（Redis Source Version）：6.x
- Redis 目的端版本（Redis Destination Version）：6.x
- Redis 部署方式（standalone/cluster/sentinel）：standalone
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：

### 日志信息（Logs）

如果有错误日志或其他相关日志，请在这里提供。

If there are any error logs or other relevant logs, please provide them here.

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

Please provide any additional information, such as configuration files, error messages, or screenshots.

**Comment by suxb201** [comment]
源端 Redis 的 aof rewrite 和 RedisShake 数据同步保存的临时 aof 没有一点关系。

**Comment by strongworker** [comment]
> 源端 Redis 的 aof rewrite 和 RedisShake 数据同步保存的临时 aof 没有一点关系。

我也理解没关系，但是为什么临时的aof也会在相近时间点发生重做呢？

**Comment by suxb201** [comment]
临时的 aof 只会在达到一定容量后轮转，不会 rewrite

**Comment by dev-lake** [comment]
请教“达到一定容量后轮转”是什么意思

**Comment by suxb201** [comment]
@dev-lake 就是单文件过大（超过1G）之后切个新文件，旧文件还留着。
