### ISSUE TITLE
unknown rdb value type byte. key=[]

### ISSUE THREAD

**Issue by lqwsss12** [aliyun/redis-shake#880]
### 问题描述（Issue Description）

请在这里简要描述你遇到的问题。

Please provide a brief description of the issue you encountered.

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：4.20
- Redis 源端版本（Redis Source Version）：7.4
- Redis 目的端版本（Redis Destination Version）：7.4
- Redis 部署方式（standalone/cluster/sentinel）：集群
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：否

### 日志信息（Logs）

如果有错误日志或其他相关日志，请在这里提供。

{"level":"info","time":"2024-11-13T12:16:47+08:00","message":"log_level: [info], log_file: [/apprun/redis-shake-v4.2.0/data/shake.log]"}
{"level":"info","time":"2024-11-13T12:16:47+08:00","message":"changed work dir. dir=[/apprun/redis-shake-v4.2.0/data]"}
{"level":"info","time":"2024-11-13T12:16:47+08:00","message":"GOMAXPROCS defaults to the value of runtime.NumCPU [2]"}
{"level":"info","time":"2024-11-13T12:16:47+08:00","message":"not set pprof port"}
{"level":"info","time":"2024-11-13T12:16:47+08:00","message":"address=172.28.47.131:6379, reply=31a4a801fcadd90cd0eb44b645c04a3d308762b8 172.28.47.176:6379@16379 slave be996687d4107127139216bd51b6c392e6218b94 0 1731471407603 14 connected\nbebe35d85f5a0d16ee9bff4bc179c9631bb63c1d 172.28.47.142:6379@16379 slave 31d27246c9a54b6aaabf436401cf6cad26696699 0 1731471405590 12 connected\n47fc294b17d417ee1ed3260146a3b9b3476a2112 172.28.47.28:6379@16379 master - 0 1731471406596 13 connected 0-5460\nbe996687d4107127139216bd51b6c392e6218b94 172.28.47.209:6379@16379 master - 0 1731471405000 14 connected 10923-16383\n31d27246c9a54b6aaabf436401cf6cad26696699 172.28.47.53:6379@16379 master - 0 1731471406000 12 connected 5461-10922\n8f2dbb567926bbb8ded77468d7744d511b6ab8dd 172.28.47.131:6379@16379 myself,slave 47fc294b17d417ee1ed3260146a3b9b3476a2112 0 1728984692920 13 connected"}
{"level":"info","time":"2024-11-13T12:16:47+08:00","message":"create SyncClusterReader: 172.28.47.131:6379"}
{"level":"info","time":"2024-11-13T12:16:47+08:00","message":"address=172.20.181.16:6379, reply=41308fad319a2ba754c8a6d889e81360911f307f 172.20.181.16:6379@16379 myself,master - 0 1729560030443 15 connected 10923-16383\nce59ecebb5c2fcf1d250db50b85f507adae5c05b 172.20.181.195:6379@16379 master - 0 1731471407756 13 connected 0-5460\nddcbe987e31fde61d5ba0c639968b3863067d2ba 172.20.181.217:6379@16379 slave ce59ecebb5c2fcf1d250db50b85f507adae5c05b 0 1731471405745 13 connected\n6fbc497df616c2d5ab6f786f2c904c93b712f4a0 172.20.181.72:6379@16379 master - 0 1731471405000 14 connected 5461-10922\n50199221ddc09f5270a51f93e9b84cf7013f0f0d 172.20.181.37:6379@16379 slave 6fbc497df616c2d5ab6f786f2c904c93b712f4a0 0 1731471406000 14 connected\n72f70ccf8bcdb1bb82d7a42274d8b9a89ff7c94a 172.20.181.36:6379@16379 slave 41308fad319a2ba754c8a6d889e81360911f307f 0 1731471406751 15 connected"}
{"level":"info","time":"2024-11-13T12:16:47+08:00","message":"redisClusterWriter connected to redis cluster successful. addresses=[172.20.181.16:6379 172.20.181.195:6379 172.20.181.72:6379]"}
{"level":"info","time":"2024-11-13T12:16:47+08:00","message":"create RedisClusterWriter: 172.20.181.16:6379"}
{"level":"info","time":"2024-11-13T12:16:47+08:00","message":"not set status port"}
{"level":"info","time":"2024-11-13T12:16:47+08:00","message":"start syncing..."}
{"level":"error","time":"2024-11-13T12:16:50+08:00","message":"unknown rdb value type byte. key=[], type=[244]\n\t\t\tRedisShake/internal/rdb/types/interface.go:100 -> ParseObject()\n\t\t\tRedisShake/internal/rdb/rdb.go:191 -> (*Loader).parseRDBEntry()\n\t\t\tRedisShake/internal/rdb/rdb.go:101 -> (*Loader).ParseRDB()\n\t\t\tRedisShake/internal/reader/sync_standalone_reader.go:265 -> (*syncStandaloneReader).sendRDB()\n\t\t\tRedisShake/internal/reader/sync_standalone_reader.go:105 -> (*syncStandaloneReader).StartRead.func1()\n\t\t\truntime/asm_amd64.s:1598 -> goexit()"}

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

Please provide any additional information, such as configuration files, error messages, or screenshots.

**Comment by suxb201** [comment]
试一下： #881

**Comment by ouchuji** [comment]
@suxb201  这个PR大概什么时候可以发版呢？
