### ISSUE TITLE
能否支持FalkorDB图数据库同步

### ISSUE THREAD

**Issue by EquentR** [aliyun/redis-shake#884]
现在有个叫做FalkorDB的图数据库，底层是基于Redis的，但是在使用sync时，似乎有很多命令不支持？scan模式怕丢数据，有考虑过支持这种数据格式吗？
![aaa](https://github.com/user-attachments/assets/ed7ef2d1-81f7-4faf-b286-2c854ffc244d)

**Comment by suxb201** [comment]
支持不了，FalkorDB  的前身是 RedisGragh，非常复杂的数据结构。每个 Module 都需要适配如何解析，然后转成命令发送至目的端，我没有精力去适配它。你可以咨询下 FalkorDB 是否有意愿支持贡献解析代码，或者官方是否提供其他迁移方案。

Scan 模式是可以的，你可以尝试一下。

**Comment by EquentR** [comment]
> 支持不了，FalkorDB 的前身是 RedisGragh，非常复杂的数据结构。每个 Module 都需要适配如何解析，然后转成命令发送至目的端，我没有精力去适配它。你可以咨询下 FalkorDB 是否有意愿支持贡献解析代码，或者官方是否提供其他迁移方案。
> 
> Scan 模式是可以的，你可以尝试一下。

好吧，感觉也是个大工程😂😂😂
