### ISSUE TITLE
从单机redis同步数据到哨兵集群出现报错

### ISSUE THREAD

**Issue by surel9** [aliyun/redis-shake#887]
### 问题描述（Issue Description）

请在这里简要描述你遇到的问题。

想从一台单机 redis 同步数据到 哨兵集群

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：v4.2.2
- Redis 源端版本（Redis Source Version）：v6.0.5
- Redis 目的端版本（Redis Destination Version）：v6.0.5
- Redis 部署方式（standalone/cluster/sentinel）：源端：standalone；目的端：sentinel
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：否

### 日志信息（Logs）

如果有错误日志或其他相关日志，请在这里提供。

{"level":"info","time":"2024-11-25T10:50:07+08:00","message":"log_level: [info], log_file: [/opt/redis-shake/data/shake.log]"}
{"level":"info","time":"2024-11-25T10:50:07+08:00","message":"changed work dir. dir=[/opt/redis-shake/data]"}
{"level":"info","time":"2024-11-25T10:50:07+08:00","message":"GOMAXPROCS defaults to the value of runtime.NumCPU [2]"}
{"level":"info","time":"2024-11-25T10:50:07+08:00","message":"not set pprof port"}
{"level":"info","time":"2024-11-25T10:50:07+08:00","message":"create SyncStandaloneReader: 192.168.101.24:6480"}
{"level":"error","time":"2024-11-25T10:50:07+08:00","message":"dial failed. address=[], tls=[false], err=[dial tcp: missing address]\n\t\t\tRedisShake/internal/client/redis.go:49 -> NewRedisClient()\n\t\t\tRedisShake/internal/client/redis.go:26 -> NewSentinelMasterClient()\n\t\t\tRedisShake/internal/writer/redis_sentinel_writer.go:11 -> NewRedisSentinelWriter()\n\t\t\tRedisShake/cmd/redis-shake/main.go:105 -> main()\n\t\t\truntime/proc.go:267 -> main()\n\t\t\truntime/asm_amd64.s:1650 -> goexit()"}

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

[sync_reader]
cluster = false            # set to true if source is a redis cluster
address = "192.168.101.24:6480" # when cluster is true, set address to one of the cluster node
username = ""              # keep empty if not using ACL
password = "xxxxxxxxxxxxxx"              # keep empty if no authentication is required
tls = false                #
sync_rdb = true            # set to false if you don't want to sync rdb
sync_aof = true            # set to false if you don't want to sync aof
prefer_replica = false     # set to true if you want to sync from replica node
try_diskless = false       # set to true if you want to sync by socket and source repl-diskless-sync=yes

[redis_writer]
cluster = false            # set to true if target is a redis cluster
sentinel = true           # set to true if target is a redis sentinel
master = "192.168.2.103:6480"                # set to master name if target is a redis sentinel
address = "" # when cluster is true, set address to one of the cluster node
username = ""              # keep empty if not using ACL
password = "xxxxxxxxxx"              # keep empty if no authentication is required
tls = false
off_reply = false          # turn off the server reply

[filter]
allow_key_prefix = []
allow_key_suffix = []
block_key_prefix = []
block_key_suffix = []
allow_db = []
block_db = []
allow_command = [] 
block_command = [] 
allow_command_group = [] 
block_command_group = [] 
function = ""

[advanced]
dir = "data"
ncpu = 0        # runtime.GOMAXPROCS, 0 means use runtime.NumCPU() cpu cores
pprof_port = 0  # pprof port, 0 means disable
status_port = 0 # status port, 0 means disable
log_file = "shake.log"
log_level = "info"     # debug, info or warn
log_interval = 5       # in seconds
rdb_restore_command_behavior = "panic" # panic, rewrite or skip
pipeline_count_limit = 1024
target_redis_client_max_querybuf_len = 1073741824  # 1GB in bytes
target_redis_proto_max_bulk_len = 512_000_000
aws_psync = "" # example: aws_psync = "10.0.0.1:6379@nmfu2sl5osync,10.0.0.1:6379@xhma21xfkssync"
empty_db_before_sync = false

[module]
target_mbbloom_version = 20603

**Comment by suxb201** [comment]
redis_writer 里 master 留空，地址 port 写到 address 里

**Comment by surel9** [comment]
然后查看日志又出现了这个错误：
{"level":"info","time":"2024-11-25T11:02:50+08:00","message":"log_level: [info], log_file: [/opt/redis-shake/data/shake.log]"}
{"level":"info","time":"2024-11-25T11:02:50+08:00","message":"changed work dir. dir=[/opt/redis-shake/data]"}
{"level":"info","time":"2024-11-25T11:02:50+08:00","message":"GOMAXPROCS defaults to the value of runtime.NumCPU [2]"}
{"level":"info","time":"2024-11-25T11:02:50+08:00","message":"not set pprof port"}
{"level":"info","time":"2024-11-25T11:02:50+08:00","message":"create SyncStandaloneReader: 192.168.101.24:6480"}
{"level":"error","time":"2024-11-25T11:02:50+08:00","message":"ERR unknown command `SENTINEL`, with args beginning with: `GET-MASTER-ADDR-BY-NAME`, ``, \n\t\t\tRedisShake/internal/writer/redis_sentinel_writer.go:15 -> NewRedisSentinelWriter()\n\t\t\tRedisShake/cmd/redis-shake/main.go:105 -> main()\n\t\t\truntime/proc.go:267 -> main()\n\t\t\truntime/asm_amd64.s:1650 -> goexit()"}

配置文件内容为：
[sync_reader]
cluster = false            # set to true if source is a redis cluster
address = "192.168.101.24:6480" # when cluster is true, set address to one of the cluster node
username = ""              # keep empty if not using ACL
password = "xxxxxxx"  # keep empty if no authentication is required
tls = false                #
sync_rdb = true            # set to false if you don't want to sync rdb
sync_aof = true            # set to false if you don't want to sync aof
prefer_replica = false     # set to true if you want to sync from replica node
try_diskless = false       # set to true if you want to sync by socket and source repl-diskless-sync=yes

[redis_writer]
cluster = false            # set to true if target is a redis cluster
sentinel = true           # set to true if target is a redis sentinel
master = ""                # set to master name if target is a redis sentinel
address = "192.168.2.103:6480" # when cluster is true, set address to one of the cluster node
username = ""              # keep empty if not using ACL
password = "xxxxxxxxxx"              # keep empty if no authentication is required
tls = false
off_reply = false          # turn off the server reply

[filter]
allow_key_prefix = []
allow_key_suffix = []
block_key_prefix = []
block_key_suffix = []
allow_db = []
block_db = []
allow_command = [] 
block_command = [] 
allow_command_group = [] 
block_command_group = [] 
function = ""

[advanced]
dir = "data"
ncpu = 0        # runtime.GOMAXPROCS, 0 means use runtime.NumCPU() cpu cores
pprof_port = 0  # pprof port, 0 means disable
status_port = 0 # status port, 0 means disable
log_file = "shake.log"
log_level = "info"     # debug, info or warn
log_interval = 5       # in seconds
rdb_restore_command_behavior = "panic" # panic, rewrite or skip
pipeline_count_limit = 1024
target_redis_client_max_querybuf_len = 1073741824  # 1GB in bytes
target_redis_proto_max_bulk_len = 512_000_000
aws_psync = "" # example: aws_psync = "10.0.0.1:6379@nmfu2sl5osync,10.0.0.1:6379@xhma21xfkssync"
empty_db_before_sync = false

[module]
target_mbbloom_version = 20603

**Comment by suxb201** [comment]
<img width="686" alt="image" src="https://github.com/user-attachments/assets/6f416099-20bb-4ec3-9fd2-991fc37591f4">
看起来你需要在 master 里写你的 db 的这个名字....

**Comment by surel9** [comment]
通过目的端的 redis 哨兵集群可以得知：
![微信截图_20241125111408](https://github.com/user-attachments/assets/8fc2f937-f091-4eb1-97fc-c68f001386ce)

shake.toml配置修改如下：
![123](https://github.com/user-attachments/assets/ffd00475-236d-4d83-ac37-ade2d0a1c460)

报错内容如下：
![45](https://github.com/user-attachments/assets/389af41e-f76b-45bf-abf3-68f9a6b159c0)

**Comment by suxb201** [comment]
192.168.2.103:6480 不是 sentinel 的地址。所以你这里不需要专门设置 sentinel，改成：
* sentinel = false
* master = “”
* address = “192.168.2.103:6480“

**Comment by surel9** [comment]
昂，原来如此，我以为 sentinel 代表的意思为：是否为 sentinel 集群？
