### ISSUE TITLE
源端大量写入时，shake所在机器硬盘使用率一直在90%+

### ISSUE THREAD

**Issue by EquentR** [aliyun/redis-shake#890]
### 问题描述（Issue Description）

源端大量写入时，shake所在机器硬盘使用率一直在90%+，shake运行所在硬盘为机械硬盘，看硬盘的写入速度只有几MiB/s，占用率却很高

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：4.2.2
- Redis 源端版本（Redis Source Version）：7.2.3
- Redis 目的端版本（Redis Destination Version）：7.2.3
- Redis 部署方式（standalone/cluster/sentinel）：standalone
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：否

### 日志信息（Logs）

无错误日志，增量阶段同步速度远远赶不上redis源端的写入速度，看diff没有堆积，盲猜是硬盘占用过高导致接收aof速度太慢？实际在redis侧堆积aof了？PS：此处使用redis-benchmark模拟极端源端写入，目前有业务确实能打满redis，此写入速度应该不算夸张
![image](https://github.com/user-attachments/assets/f7645146-3c95-4c28-a93a-5d1ba70ff7a8)

看diff很有规律是在16k左右
![image](https://github.com/user-attachments/assets/ec0e322f-02c1-4b6a-a836-75b48d8af097)

### 其他信息（Additional Information）
Win下任务管理器截图，实测在linux中也是类似的情况，iostat %util占用90+
![image](https://github.com/user-attachments/assets/9c014803-1bed-43cb-9498-d2c8ae09cab0)

**Comment by suxb201** [comment]
是的，shake 会先将 aof 写到盘上，然后再消费。这样可以利用硬盘作为缓冲区，避免内存占用过高。
高流量下对硬盘压力很大，文档中有[测试结果](https://tair-opensource.github.io/RedisShake/zh/guide/architecture.html#%E6%80%A7%E8%83%BD%E5%92%8C%E8%B5%84%E6%BA%90%E5%8D%A0%E7%94%A8)，或许新增一种模式可以纯走内存。

**Comment by EquentR** [comment]
看了一下pprof，这里每读取16k就往硬盘写，写完就刷sync。大量时间耗费在这里了。以前写过一些大文件写入类的程序，都没用过这种手动刷盘的方式，文件也能正常落盘，这里能不能交由操作系统自行管理？感觉应该可行？
![image](https://github.com/user-attachments/assets/a266ebe0-a9e7-433f-be69-3b910e9d3ead)
![image](https://github.com/user-attachments/assets/ee14d83a-f396-41c8-bfec-40789b0f4c61)
![image](https://github.com/user-attachments/assets/fa506a69-509f-4668-8b58-6571a0da7626)

**Comment by suxb201** [comment]
👍 合理的，频繁 sync 性能影响很大。

**Comment by EquentR** [comment]
刚才试了一下删除sync，aof_reader能正常读，硬盘压力小了很多（30%左右），应该问题不大，同步速度能达到源端压力速度了。

对于内存的方式来说，我很久之前尝试自己撸了一个环形缓冲区，固定大小不增长的那种，基于这个重写了一个aof_reader和writer。速度是快起来了，但发现有概率出现命令解析出错的情况，看diff感觉缓冲区没满（分配了2GB），不知道是不是循环覆盖超读了导致的，我自己的win机器上复现不了，在服务器上有较高概率出现。感觉内存的方案也没那么简单，要考虑的太多了🤣
![image](https://github.com/user-attachments/assets/17bc9703-33d2-493d-8684-d207db145d9a)
下面这张图的log中，key不全，前面丢失了几个字符
![image](https://github.com/user-attachments/assets/bfc5782e-c6cf-481a-9460-c81659b31fa8)

附：环形缓冲区代码。大佬有空看下？
```go
// CircularBuffer 基础环形缓冲区
type CircularBuffer struct {
	buffer   []byte
	size     int
	readPos  int
	writePos int
	mu       sync.Mutex
}

// NewCircularBuffer 创建一个固定大小的环形缓冲区
func NewCircularBuffer(capacity int) *CircularBuffer {
	return &CircularBuffer{
		buffer: make([]byte, capacity),
	}
}

// Write 写入数据
func (cb *CircularBuffer) Write(p []byte) (int, error) {
	cb.mu.Lock()
	defer cb.mu.Unlock()

	n := len(p)
	if n > len(cb.buffer)-cb.size {
		return 0, errors.New("buffer is full")
	}

	for i := 0; i < n; i++ {
		cb.buffer[cb.writePos] = p[i]
		cb.writePos = (cb.writePos + 1) % len(cb.buffer)
	}
	cb.size += n
	return n, nil
}

// Read 读取数据
func (cb *CircularBuffer) Read(p []byte) (int, error) {
	cb.mu.Lock()
	defer cb.mu.Unlock()

	if cb.size == 0 {
		return 0, io.EOF
	}

	n := len(p)
	if n > cb.size {
		n = cb.size
	}

	for i := 0; i < n; i++ {
		p[i] = cb.buffer[cb.readPos]
		cb.readPos = (cb.readPos + 1) % len(cb.buffer)
	}
	cb.size -= n
	return n, nil
}
```
