### ISSUE TITLE
sentinel_password

### ISSUE THREAD

**Issue by wHoareYouY** [aliyun/redis-shake#891]
### 问题描述（Issue Description）

请在这里简要描述你遇到的问题。
  大佬好，麻烦问下。
  源standlaone，目标是哨兵，哨兵本身没有密码，哨兵监听的redis服务有密码，配置文件如何配置呢？看代码有一个sentinel_username和sentinel_password的配置，但是配置之后没有生效,，配置文件如下

  
![1732687130368](https://github.com/user-attachments/assets/66ac6335-5401-4035-aef7-fcebd29ff5cd)

Please provide a brief description of the issue you encountered.

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：v4.2.2
- Redis 源端版本（Redis Source Version）：6.2.3
- Redis 目的端版本（Redis Destination Version）：6.2.3
- Redis 部署方式（standalone/cluster/sentinel）：目标是哨兵
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：否

### 日志信息（Logs）

如果有错误日志或其他相关日志，请在这里提供。
![1732686798753](https://github.com/user-attachments/assets/16bd6151-de17-4fa9-bb09-3170e3a90c8d)

If there are any error logs or other relevant logs, please provide them here.

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

Please provide any additional information, such as configuration files, error messages, or screenshots.

**Comment by EquentR** [comment]
现在最新的代码已经解决了这个问题，你可以看最新的提交，自己编译一份最新的来用，我也不太清楚管理员什么时候发版新的😂
提交：https://github.com/tair-opensource/RedisShake/commit/d621053eaf8316d902bfab24e251f04630dc5518
PR：https://github.com/tair-opensource/RedisShake/pull/888

**Comment by wHoareYouY** [comment]
奥奥 好滴好滴 谢谢~
