### ISSUE TITLE
redis-shake-v4.2.2 遇到特殊字符提示密码不对

### ISSUE THREAD

**Issue by niuniu2005** [aliyun/redis-shake#892]
### 问题描述（Issue Description）

请在这里简要描述你遇到的问题。

Please provide a brief description of the issue you encountered.

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：redis-shake-v4.2.2
- Redis 源端版本（Redis Source Version）：redis-shake-v4.2.2
- Redis 目的端版本（Redis Destination Version）：redis-5.0.4
- Redis 部署方式（standalone/cluster/sentinel）：redis-5.0.4
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：否

### 日志信息（Logs）
[root@client-01 redis-shavev4.2]# ./redis-shake  shake.toml
2024-11-27 10:04:37 INF load config from file: shake.toml
2024-11-27 10:04:37 INF log_level: [info], log_file: [/opt/soft/redis-shavev4.2/data/shake.log]
2024-11-27 10:04:37 INF changed work dir. dir=[/opt/soft/redis-shavev4.2/data]
2024-11-27 10:04:37 INF GOMAXPROCS defaults to the value of runtime.NumCPU [1]
2024-11-27 10:04:37 INF not set pprof port
2024-11-27 10:04:37 ERR ERR invalid password
                        RedisShake/internal/client/redis.go:152 -> (*Redis).DoWithStringReply()
                        RedisShake/internal/client/redis.go:64 -> NewRedisClient()
                        RedisShake/internal/reader/sync_standalone_reader.go:89 -> NewSyncStandaloneReader()
                        RedisShake/cmd/redis-shake/main.go:50 -> main()
                        runtime/proc.go:267 -> main()
                        runtime/asm_amd64.s:1650 -> goexit()

如果有错误日志或其他相关日志，请在这里提供。
密码的后面两位为：$R，提示密码不对，但我通过此密码无论是客户端还是从节点都可以成功登录的。 如果把密码换成其他的则可以成功完成数据同步
If there are any error logs or other relevant logs, please provide them here.

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

Please provide any additional information, such as configuration files, error messages, or screenshots.

**Comment by EquentR** [comment]
看了一下，这个提交https://github.com/tair-opensource/RedisShake/commit/48314cffd37c3a9e94b4f495f68dc2ddaf7e561b 前的代码是正常的，应该是增加了docker支持后配置文件解析方式发生了变更，导致$后被解析为环境变量赋值了。
可以先用着4.1.1版本或者编译这个提交前的代码使用

@suxb201
